-- PIPELINE (Sauces): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('DmBio', 'Tomatensoße Klassik', 'dm'),
    ('Hengstenberg', 'Tomaten stückig mit Kräutern', 'REWE'),
    ('Bautz''ner', 'Fix Tomatensoße', 'Lidl'),
    ('DmBio', 'Tomatensoße Arrabbiata', 'dm'),
    ('InnFood Organic', 'Bio-Tomatensauce - Gemüse und Parmesan', 'Aldi'),
    ('ORO di Parma', 'Stückige Tomaten scharf', 'Edeka'),
    ('ORO di Parma', 'Stückige Tomaten scharf', 'Real'),
    ('Aldi', 'ALDI GUT BIO GEMÜSE Passata Rustica 680g 1.69€ 1kg 2.49€', 'Aldi'),
    ('Riesa', 'Nudelsauce mit Gemüse', 'REWE'),
    ('Oro di Parma', 'Sugo - Gemüse', 'Aldi'),
    ('Oro di Parma', 'Sugo - Gemüse', 'Kaufland'),
    ('Uncle Ben''s', 'Süß-Sauer extra Gemüse Sauce', 'Netto'),
    ('Oro d''Italia', 'Tomatensugo Kräuter', 'REWE'),
    ('DmBio', 'Tomatensoße Ricotta Percorino', 'dm'),
    ('Aldi', 'Currywurstsauce gewürzt', 'Aldi'),
    ('Aldi', 'Passierte Tomaten', 'Aldi'),
    ('DmBio', 'Tomatensauce - Ricotta Pecorino', 'dm'),
    ('King''s Crown', 'Passata', 'Aldi'),
    ('Oro Di Parma', 'Pizzasauce Oregano', 'REWE'),
    ('InnFood Organic', 'Bio-Tomatensauce - Basilikum', 'Aldi'),
    ('DmBio', 'Tomatensauce - gegrillte Paprika', 'dm'),
    ('InnFood Organic', 'Bio-Tomatensauce - Arrabiata', 'Aldi'),
    ('Clama', 'Tomate Frito', 'Aldi'),
    ('Cucina', 'Pasta-Sauce Arrabbiata', 'Aldi'),
    ('Mars', 'Pastasauce Miracoli Klassiker', 'REWE'),
    ('Alnatura', 'Passata', 'Edeka'),
    ('Oro', 'Pastasauce Classico', 'Kaufland'),
    ('Cucina', 'Pasta-Sauce - Napoletana', 'Aldi'),
    ('Cucina', 'Passata rustica', 'Aldi'),
    ('K Classic', 'Passierte Tomaten', 'Kaufland'),
    ('Aldi', 'Pastasauce - Bolognese', 'Aldi'),
    ('Cucina Nobile', 'Pastasauce - Napoletana', 'Aldi'),
    ('Hengstenberg', 'Tomaten passiert', 'Edeka'),
    ('Oro Di Parma', 'Tomatensauce - Sugo Tradizionale', 'Edeka'),
    ('Clama', 'Sizilianische Kirschtomaten-Sauce - Arrabiata', 'Aldi'),
    ('DmBio', 'Sos bolognese vegan eco', 'dm'),
    ('Cucina', 'Passata Rustica Basilikum', 'Aldi'),
    ('K-Classic', 'Tomaten Passierte Tomaten', 'Kaufland'),
    ('Bertolli', 'Arrabbiata', 'Lidl'),
    ('Bertolli', 'Arrabbiata', 'REWE'),
    ('Bio Zentrale', 'Vegane Bolognese', 'Edeka'),
    ('Gut bio', 'Tomatensauce Kinder', 'Aldi'),
    ('DmBio', 'Tomatensauce Krauter', 'dm'),
    ('DmBio', 'Passata Natur', 'dm'),
    ('Grillmeister', 'Steak House Style Sauce', 'Lidl'),
    ('Bernbacher', 'Al''Arrabbiata Sauce', 'Edeka'),
    ('Bernbacher', 'Al''Arrabbiata Sauce', 'REWE'),
    ('REWE Bio', 'Tomatensauce Kräuter', 'REWE'),
    ('Barilla', 'Toscana Kräuter', 'Lidl'),
    ('Barilla', 'Toscana Kräuter', 'REWE'),
    ('REWE Beste Wahl', 'Stückige Tomaten', 'REWE'),
    ('Rewe', 'Kräuter Knoblauch Saucenbasis', 'REWE'),
    ('Heinz', 'Tomato stückig', 'REWE'),
    ('Rewe', 'Kräuter Saucenbasis', 'REWE'),
    ('Rewe', 'Tomatensauce - Geheim Zutat 3 Stückige Tomatensoße', 'REWE'),
    ('Rewe', 'Pasta Sauce Kräuter', 'REWE'),
    ('Unknown', 'Tomatensauce Bolognese Bio Aldi', 'Aldi'),
    ('Barilla', 'Basilico 400g eu', 'Aldi'),
    ('Barilla', 'Basilico 400g eu', 'Lidl'),
    ('Baresa', 'Tomatenmark', 'Lidl'),
    ('Baresa', 'Passierte Tomate', 'Lidl'),
    ('Gut & Günstig', 'Passierte Tomaten', 'Edeka'),
    ('Mutti', 'Triplo concentrato di pomodoro', 'REWE'),
    ('Mutti', 'Triplo concentrato di pomodoro', 'Tegut'),
    ('Barilla', 'Arrabbiata', 'Lidl'),
    ('EDEKA Bio', 'Passata, passierte Tomaten - Bio', 'Edeka'),
    ('Ppura', 'Vegane Bolognese', 'REWE'),
    ('Barilla', 'Napoletana', 'Lidl'),
    ('Barilla', 'Ricotta', 'Edeka'),
    ('Combino', 'Bolognese', 'Lidl'),
    ('Baresa', 'Passierte Tomaten', 'Lidl'),
    ('Ja!', 'Tomatensauce mit Basilikum', 'REWE'),
    ('Mutti', 'Pizzasauce Aromatica', 'REWE'),
    ('Combino', 'Arrabbiata', 'Lidl'),
    ('Rewe Bio', 'Passata Tomaten', 'REWE'),
    ('Barilla', 'Verdure mediterranee 400g eu cross', 'REWE'),
    ('REWE Bio', 'Tomatensauce Ricotta', 'REWE'),
    ('Alnatura', 'Tomatensauce Toscana', 'Edeka'),
    ('Rewe', 'Tomate Ricotta mit Basilikum', 'REWE'),
    ('Alnatura', 'Alnatura Pesto Arrabbiata', 'Edeka'),
    ('Mutti', 'Pastasaus m/Basilikum', 'Edeka'),
    ('BioBio', 'Tomaten-Sahne-Sauce', 'Netto'),
    ('Alnatura', 'Arrabbiata', 'Edeka'),
    ('REWE Bio', 'Tomatensauce Arrabiata', 'REWE'),
    ('Heinz', 'Tomato passiert', 'REWE'),
    ('Barilla', 'Bolognese Soja Vegan', 'Edeka'),
    ('Pomito', 'Pizza und Pastasauce', 'REWE'),
    ('La Doria', 'Basilico Tomatensauce', 'REWE'),
    ('RBW', 'All Arrabiata', 'REWE'),
    ('Edeka Bio', 'Tomatensauce Arrabbiata', 'Edeka'),
    ('Rewe beste Wahl', 'REWE Beste Wahl Tomate Basilikum Saucenbasis', 'REWE'),
    ('EDEKA Bio', 'Tomatensauce Arrabiata mit Chili', 'Edeka'),
    ('Mutti', 'Le verdurine, salsa di pomodoro e verdurine', 'Kaufland'),
    ('Naturgut', 'Bio Tomatensauce', 'Penny'),
    ('Ener BIO', 'Rajčatová omáčka se zeleninou', 'Rossmann'),
    ('Ppura', 'Pizza Sauce mit Oregano', 'dm'),
    ('Rewe', 'Tomatensauce - Geheim Zutat 4 Rauchige Tomatensauce', 'REWE'),
    ('Alnatura', 'Passata Fein Passiert Natur', 'Edeka'),
    ('Alnatura', 'Passata Fein Passiert Natur', 'dm'),
    ('MONDO Italiano (NETTO)', 'Nudelsauce Arrabbiata', 'Netto'),
    ('Italiamo', 'Cherry tomaten saus', 'Lidl'),
    ('Combino', 'Sauce Tomate Napolitaine', 'Lidl'),
    ('PPura', 'Passata', 'REWE'),
    ('PPura', 'Passata', 'dm'),
    ('PennySan Fabio', 'Arrabiata Pasta Sauce', 'Penny'),
    ('Italiamo', 'Polpa di pomodoro all''arrabiata', 'Lidl'),
    ('Saclà', 'Sauce Getrocknete Tomaten und Rucola', 'Kaufland'),
    ('Rewe', 'Tomatensauce - Geheim Zutat 2 Passierte Tomaten', 'REWE'),
    ('A. Petti fu Pasquale', 'Passierte Tomaten (Bio)', 'REWE'),
    ('A. Petti fu Pasquale', 'Passierte Tomaten (Bio)', 'Tegut'),
    ('BioBio', 'Passierte Bio-Tomaten/ Pack.', 'Netto'),
    ('Edeka', 'Tomatensauce Klassik', 'Edeka'),
    ('K-Classic', 'Passierte Tomaten', 'Kaufland'),
    ('Ja!', 'Tomate-Basilikum Pasta-Sauce', 'REWE'),
    ('San Fabio', 'Tomatensauce mit Basilikum', 'Penny'),
    ('REWE Beste Wahl', 'Tomaten-Ricotta Pasta Sauce', 'REWE'),
    ('K-Classic', 'Passata rustica Tomaten', 'Kaufland'),
    ('Italiamo', 'Sauce tomate Toscane', 'Lidl'),
    ('Knorr', 'Tomato al Gusto Tomaten-Bolognese', 'Edeka'),
    ('Pomito', 'Tomaten passiert', 'Edeka'),
    ('Penny', 'San Fabio Arrabbiata', 'Penny'),
    ('Belbake', 'Tomaten gehackt', 'Lidl'),
    ('REWE Beste Wahl', 'Arrabiata 4388860679106', 'REWE'),
    ('Rossmann', 'Klassik Tomatensauce', 'Rossmann'),
    ('Ja!', 'Arrabiata Sauce', 'REWE'),
    ('Rewe Feine Welt', 'Sugo Tradizionale Tomaten & Parmesan', 'REWE'),
    ('Rewe Beste Wahl', 'Butter Chicken - Sauce indische Art', 'REWE'),
    ('Rewe', 'Tomaten Sahne Pasta Sauce', 'REWE'),
    ('REWE Bio', 'Tomatensauce Arrabbiata', 'REWE'),
    ('BioBio', 'Tomaten Basilikum Sauce', 'Netto'),
    ('La campagna', 'Pasta Sauce', 'Netto'),
    ('Gut & Günstig', 'Pastasauce Arrabiata', 'Edeka'),
    ('REWE Bio', 'Pasta Sauce Arrabbiata', 'REWE'),
    ('Netto', 'Passata Rustica', 'Netto')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Sauces' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
