-- PIPELINE (Frozen & Prepared): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Dobra kaloria', 'Roślinna kaszanka', 'Lidl'),
    ('Koral', 'Lody śmietankowe - kostka śnieżna', 'Biedronka'),
    ('Bracia Koral', 'Lody śmietankowe z ciasteczkami', 'Lewiatan'),
    ('Biedronka', 'Rożek z czekoladą', 'Biedronka'),
    ('Gotszlik', 'Rożek Dolce Giacomo', 'Kaufland'),
    ('Marletto', 'Lody o smaku śmietankowym', 'Biedronka'),
    ('Marletto', 'Orzech Włoski', 'Biedronka'),
    ('Marinero', 'Krewetki vannamei białe', 'Biedronka'),
    ('Bracia Koral', 'Lody Jak Dawniej Rożek Bakaliowy', 'Żabka'),
    ('Bracia Koral', 'Lody śmietankowe z truskawkami.', 'Dino'),
    ('Nestlé', 'Kaktus 8+1', 'Biedronka'),
    ('Marletto', 'Marletto White Almond', 'Biedronka'),
    ('Kilargo', 'Marletto Almond', 'Biedronka'),
    ('Kilargo', 'Marletto Salted Caramel Lava', 'Biedronka'),
    ('Grycan', 'Lody waniliowe', 'Auchan'),
    ('Grycan', 'Lody truskawkowe', 'Auchan'),
    ('Zielona Budka', 'Lody Truskawkowe', 'Auchan'),
    ('Marletto', 'Lody kawowe', 'Biedronka'),
    ('Lewiatan', 'Pizza z Pieczarkami', 'Lewiatan'),
    ('Augusto', 'Bambo Cream & Nuts', 'Netto'),
    ('Gelato classico', 'Gelato Classico Classic', 'Netto'),
    ('Milka', 'Milka Crunchy Chocolate', 'Żabka'),
    ('Marletto', 'Lody o smaku czekoladowym', 'Biedronka'),
    ('Gourmet', 'Girane Sübe Eishörnchen', 'Kaufland'),
    ('Nestlé', 'Kaktus BOOM', 'Żabka'),
    ('Marinero', 'Atlantic salmon', 'Biedronka'),
    ('Nestlé', 'Kaktus shake', 'Lidl'),
    ('Koral', 'Ice Coffee Americano', 'Tesco'),
    ('Grand', 'Grand Orzech', 'Tesco'),
    ('Koral', 'Grand Gold Blueberry', 'Tesco'),
    ('Nestlé', 'Mini ice cream adventure', 'Carrefour'),
    ('Carrefour', 'Lody waniliowo-czekoladowe', 'Carrefour'),
    ('Algida', 'Bigmilk smak śmietankowo czekoladowy', 'Carrefour'),
    ('Ballino', 'Śmietanka z bakaliami', 'Lidl'),
    ('Algida', 'Bigmilk smak śmietankowo truskawkowy', 'Carrefour'),
    ('Ballino', 'Śmietanka z truskawką', 'Lidl'),
    ('Lidl', 'Śmietanka z czekoladą', 'Lidl'),
    ('Ballino', 'Ballino Almond Lody Śmietankowe', 'Lidl'),
    ('Marletto', 'Marletto Słony Karmel', 'Biedronka'),
    ('Kaufland', 'Frytki z batatów z piekarnika', 'Kaufland'),
    ('Lidl', 'Panierowane Krążki Cebulowe', 'Lidl'),
    ('Marletto', 'Lody Czekoladowe', 'Biedronka'),
    ('Marletto', 'Lody Waniliowe', 'Biedronka'),
    ('Algida', 'Bigmilk smak śmietankowo waniliowy', 'Carrefour'),
    ('Algida', 'Bigmilk ze śmiezym mlekiem', 'Carrefour'),
    ('Bon Gelati', 'Stracciatella Premium Eis', 'Lidl'),
    ('Bon Gelati', 'Premium Bourbon - Dairy ice cream', 'Lidl'),
    ('Carte d''Or', 'Pistachio Delight', 'Carrefour'),
    ('Carte D''or', 'Lody waniliowe', 'Biedronka'),
    ('Gelatelli', 'High Protein Salted Caramel Ice Cream', 'Lidl'),
    ('Bon Gelati', 'Walnut Bon Gelati', 'Lidl'),
    ('Gelatelli', 'Mixed berries with a fruity sauce', 'Lidl'),
    ('Gelatelli', 'Gelatelli Chocolate', 'Lidl'),
    ('Gelatelli', 'Almond', 'Lidl'),
    ('Magnum', 'Magnum Crème Glacée en Pot Amande 440ml', 'Żabka'),
    ('Gelatelli', 'High protein cookies & cream', 'Lidl'),
    ('Bon Gelati', 'Bon Gelati Eiscreme mit Schlagsahne', 'Lidl'),
    ('Snickers', 'Snickers Ice Cream', 'Biedronka'),
    ('Nixe', 'Weisser Thunfish Alalunga', 'Lidl'),
    ('Harvest Basket', 'Frytki', 'Lidl'),
    ('Kaufland', 'Veganes Stieleis Mandel', 'Kaufland'),
    ('Bon Gelati', 'Glace Erdbeer Strawberry ice cream premium', 'Lidl'),
    ('Gelatelli', 'Glace café (noblissima) 1litre', 'Lidl'),
    ('Bon Gelati', 'Salted caramel premium ice cream', 'Lidl'),
    ('Gelatelli', 'Creme al pistacchio', 'Lidl'),
    ('Gelatelli', 'Dairy Ice Cream', 'Lidl'),
    ('Mars', 'Snickers ice cream', 'Żabka'),
    ('Marletto', 'Marletto Belgijska Czekolada', 'Biedronka'),
    ('Carrefour', 'Cheeseburgers', 'Carrefour'),
    ('Carrefour', 'Cônes PARFUM CHOCOLAT Pistache', 'Carrefour'),
    ('Carrefour', 'Bâtonnets géants CHOCOLAT BLANC', 'Carrefour'),
    ('Carrefour', 'Pain au Chocolat', 'Carrefour'),
    ('Carrefour', 'Frites', 'Carrefour'),
    ('Simpl', 'Tranches de filets de Colin d''Alaska', 'Carrefour'),
    ('Carrefour', 'Filets de Colin Alaska', 'Carrefour'),
    ('Carrefour', 'Frites Allumettes pour friteuse', 'Carrefour'),
    ('Carrefour', 'Pavés de SAUMON kéta du Pacifique', 'Carrefour'),
    ('Carrefour', 'Haché au boeuf', 'Carrefour'),
    ('Carrefour', 'Glace PARFUM VANILLE', 'Carrefour'),
    ('Magnum', 'Magnum Praliné Noisette', 'Lidl'),
    ('Magnum', 'Mini Batonnet Double Chocolat', 'Carrefour'),
    ('Carrefour', 'Pommes rissolées', 'Carrefour'),
    ('Carrefour', 'Mochi vanilla', 'Carrefour'),
    ('Carrefour', 'Mochi Coconut', 'Carrefour'),
    ('Carrefour', 'Mochi Chocolate', 'Carrefour'),
    ('Bon Gelati', 'Chocolate crisp', 'Lidl'),
    ('Harrys', 'Brioche Tranchée Noix de Coco, Chocolat au Lait', 'Carrefour'),
    ('Carrefour', 'Mochi Salted Caramel', 'Carrefour'),
    ('Ferrero', 'Raffaello', 'Carrefour'),
    ('Carrefour', 'Mochi pistachio', 'Carrefour'),
    ('Carrefour', 'Mochi black sesame', 'Carrefour'),
    ('Carrefour', 'Cônes parfum vanille', 'Carrefour'),
    ('Carrefour', '16 Bâtonnets GLACÉS', 'Carrefour'),
    ('Carte d''or', 'Lemon pie', 'Biedronka'),
    ('Carrefour', 'Croquettes de pommes de terre', 'Carrefour'),
    ('Algida', 'Lody Czekoladowe', 'Carrefour'),
    ('Algida', 'Big milk smak bakalia', 'Carrefour'),
    ('Algida', 'Bigmilk ze swiezym mlekiem', 'Carrefour'),
    ('Algida', 'Bigmilk smak ciasteczko', 'Carrefour'),
    ('Ikea', 'Vegetable balls', 'Ikea')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'PL' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Frozen & Prepared' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'PL' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
