-- PIPELINE (Oils & Vinegars): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Carrefour', 'Oliwa z oliwek najwyższej jakości z pierwszego tłoczenia', 'B'),
    ('Biedronka', 'Wyborny olej słonecznikowy', 'C'),
    ('Wielkopolski', 'Wielkopolski olej słonecznikowy rafinowany', 'C'),
    ('OEL Polska', 'Wielkopolski olej rzepakowy tłoczony tylko raz, rafinowany.', 'B'),
    ('House of Asia', 'Ocet ryżowy', 'NOT-APPLICABLE'),
    ('ZT Kruszwica', 'Bartek olej słonecznikowy', 'C'),
    ('Kujawski', 'Olej rzepakowy z pierwszego tłoczenia, filtrowany', 'B'),
    ('Kujawski', 'Olej rzepakowy z pierwszego tłoczenia', 'B'),
    ('Oliwa kaszubska', 'Olej rzepakowy tłoczony na zimno', 'B'),
    ('Vifon', 'Ocet ryżowy', 'NOT-APPLICABLE'),
    ('Asia Kitchen', 'Ocet ryżowy', 'NOT-APPLICABLE'),
    ('Mi''Ra', 'Olej z ryżu', 'C'),
    ('Slonecznikowy', 'Olej wyborny', 'C'),
    ('Komagra', 'Polski olej rzepakowy', 'B'),
    ('Wyborny Olej', 'Wyborny olej rzepakowy', 'UNKNOWN'),
    ('Kujawski', 'Olej rzepakowy pomidor czosnek bazylia', 'B'),
    ('Wyborny', 'Olej rzepakowy', 'B'),
    ('Unknown', 'Olej wyborny rzepakowy', 'B'),
    ('Auchan', 'Rafinowany olej rzepakowy', 'B'),
    ('Vitanella', 'Olej kokosowy, bezzapachowy', 'E'),
    ('House of Asia', 'Olej z prażonego sezamu', 'UNKNOWN'),
    ('Bunge', 'Optima Cardio', 'D'),
    ('Intenson', 'Olej kokosowy rafinowany', 'E'),
    ('Look Food', 'Olej lniany ekologiczny', 'C'),
    ('Lewiatan', 'Olej kokosowy', 'E'),
    ('Coosur', 'Oliwa z oliwek najwyższej jakości z pierwszego tłoczenia', 'B'),
    ('Lidl Primadonna', 'Bio Hiszpańska oliwa z oliwek.', 'B'),
    ('Bielmar', 'Sonnenblumen Öl', 'B'),
    ('Oleo', 'Olej rzepakowy', 'B'),
    ('Semco', 'Olej rzepakowy', 'B'),
    ('Culineo', 'Ocet spirytusowy 10%', 'NOT-APPLICABLE'),
    ('GustoBello', 'Krem z octem balsamicznym', 'NOT-APPLICABLE'),
    ('Pegaz', 'Ocet spirytusowy 10%', 'NOT-APPLICABLE'),
    ('Kujawski', 'Olej 3 ziarna', 'B'),
    ('Kujawski', 'Kujawski czosnek bazylia', 'B'),
    ('Biedronka', 'Olej z awokado z pierwszego tłoczenia', 'B'),
    ('Oliver', 'Olej', 'B'),
    ('EkoWital', 'Ekologiczny Olej Kokosowy', 'E'),
    ('Felix', 'Orzeszki z pieca', 'C'),
    ('LenVitol', 'Olej lniany', 'B'),
    ('Olejowy Raj', 'Olej kokosowy', 'E'),
    ('Unknown', 'Wyborny Delio', 'B'),
    ('Oleofarm', 'Olej z pestek dyni', 'C'),
    ('Semco', 'Oil', 'B'),
    ('Premium Gold Master', 'Olej kokosowy', 'E'),
    ('Olejarnia Świecie', 'Naturalny olej konopny', 'C'),
    ('Radix-Bis', 'Olej kokosowy rafinowany', 'E'),
    ('Go Bio', 'Olej Kokosowy', 'E'),
    ('Vita Natura', 'Olej kokosowy Bio', 'E'),
    ('Unknown', 'Olej kokosowy bezzapachowy rafinowany', 'E'),
    ('Unknown', 'Olej z czarnuszki', 'C'),
    ('Nestlé', 'Przyprawa Maggi', 'E'),
    ('Iorgos', 'Olive Oil', 'B'),
    ('PPHU &quot;OLMAJ&quot; Sławomir Majewski', 'Olej rzepakowy zwyczajny', 'B'),
    ('Lyrakis Family', 'Oliwa z oliwek z pierwszego tłoczenia', 'B'),
    ('Suriny', 'Olej z ryżu 100%', 'C'),
    ('Basso', 'Olej z ryżu', 'C'),
    ('Pudliszki', 'Pudliszki', 'UNKNOWN'),
    ('Primadonna', 'Extra Virgin Olive Oil', 'B'),
    ('Casa de Azeite', 'Oliwa z oliwek', 'B'),
    ('Carrefour BIO', 'Huile d''olive vierge extra', 'B'),
    ('Casa de Azeite', 'Casa de Azeite', 'B'),
    ('Auchan', 'Auchan huile d''olive extra vierge verre 0.75l pack b', 'B'),
    ('Vita D''or', 'Sonnenblumenöl', 'C'),
    ('Vita D´or', 'Sonnenblumenöl', 'UNKNOWN'),
    ('Carrefour', 'Huile De Tournesol', 'C'),
    ('Vita d''Or', 'Rapsöl', 'B'),
    ('Vita D''or', 'Olej rzepakowy', 'B'),
    ('Kaufland', 'Rapsöl', 'UNKNOWN'),
    ('SimplCarrefour', 'Huile de Colza', 'B'),
    ('Złote Łany', 'Olej rzepakowy', 'B'),
    ('Vitasia', 'Vinagre de arroz', 'NOT-APPLICABLE'),
    ('Lidl', 'Olej kokosowy', 'E'),
    ('Carrefour', 'Huile pour friture', 'D'),
    ('Monini', 'Oliwa z oliwek', 'B'),
    ('Gallo', 'Olive Oil', 'B'),
    ('Lidl', 'Huile d''olive vierge extra origine Espagne extraite à froid bio', 'B'),
    ('K-Classic', 'Extra virgin olive oil', 'B'),
    ('Unknown', 'Olio Extre Vergine Do Oliva Grecale', 'B'),
    ('Lyttos', 'Greek Olive Oil', 'D'),
    ('Eridanous', 'Öl - Griechisches natives Olivenöl Extra', 'B'),
    ('Basso', 'Olio extravergine di oliva', 'B'),
    ('La PEDRIZA', 'Aceite de Olive Virgen Extra', 'B'),
    ('Basso', 'Oliwa z wytloczyn z oliwek', 'B'),
    ('Goccia d''oro', 'Olio di Sansa di Oliva', 'B'),
    ('Neféli', 'Extra Virgin Olive Oil', 'B'),
    ('Kaufland', 'Bio oliwa z oliwek', 'B'),
    ('Salvadori', 'Olio Di Sansa Di Oliva Salvadori', 'B'),
    ('Font Oliva', 'Olive Oil', 'B'),
    ('Unknown', 'Pedriza extra virgin olive oil', 'B'),
    ('Basso', 'Oliwa z oliwek extra vergine al basilico', 'B'),
    ('Basso', 'Oliwa z oliwek extra vergine al rosmarino', 'B'),
    ('Ollineo', 'Ollineo Öl', 'B'),
    ('Monini', 'Aceto di vino blanco 7,1 %', 'NOT-APPLICABLE'),
    ('JCCoinbra II', 'Olej z pestek winogron. Rafinowany', 'C'),
    ('Basso', 'Peanut oil', 'C'),
    ('Sottile Gusto', 'Olej z pestek winogron', 'C'),
    ('Bio Planete', 'Olej Kokosowy ekologiczny', 'E'),
    ('Bio planete', 'Ekologiczny Olej kokosowy virgin', 'E'),
    ('Foodbroker as', 'Olej z pestek winogron', 'C'),
    ('Vilgain', 'Avocado oil spray', 'UNKNOWN'),
    ('Basso', 'Olej z pestek winogron', 'C'),
    ('Unknown', 'Oliwa z Oliwek', 'B'),
    ('La Espanola', 'Oliwa Z Oliwek', 'UNKNOWN'),
    ('Agrelos', 'Extra Virgin Olive Oil', 'UNKNOWN'),
    ('Unknown', 'Aceite de oliva virgen extra', 'B'),
    ('Unknown', 'Orazio''s olive oil', 'B'),
    ('Unknown', 'Extra Virgin Olive Oil', 'B'),
    ('Unknown', 'Huile de coco', 'E')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Carrefour', 'Oliwa z oliwek najwyższej jakości z pierwszego tłoczenia', '2'),
    ('Biedronka', 'Wyborny olej słonecznikowy', '2'),
    ('Wielkopolski', 'Wielkopolski olej słonecznikowy rafinowany', '2'),
    ('OEL Polska', 'Wielkopolski olej rzepakowy tłoczony tylko raz, rafinowany.', '2'),
    ('House of Asia', 'Ocet ryżowy', '2'),
    ('ZT Kruszwica', 'Bartek olej słonecznikowy', '2'),
    ('Kujawski', 'Olej rzepakowy z pierwszego tłoczenia, filtrowany', '4'),
    ('Kujawski', 'Olej rzepakowy z pierwszego tłoczenia', '4'),
    ('Oliwa kaszubska', 'Olej rzepakowy tłoczony na zimno', '2'),
    ('Vifon', 'Ocet ryżowy', '2'),
    ('Asia Kitchen', 'Ocet ryżowy', '2'),
    ('Mi''Ra', 'Olej z ryżu', '4'),
    ('Slonecznikowy', 'Olej wyborny', '2'),
    ('Komagra', 'Polski olej rzepakowy', '2'),
    ('Wyborny Olej', 'Wyborny olej rzepakowy', '2'),
    ('Kujawski', 'Olej rzepakowy pomidor czosnek bazylia', '4'),
    ('Wyborny', 'Olej rzepakowy', '2'),
    ('Unknown', 'Olej wyborny rzepakowy', '2'),
    ('Auchan', 'Rafinowany olej rzepakowy', '2'),
    ('Vitanella', 'Olej kokosowy, bezzapachowy', '2'),
    ('House of Asia', 'Olej z prażonego sezamu', '2'),
    ('Bunge', 'Optima Cardio', '4'),
    ('Intenson', 'Olej kokosowy rafinowany', '2'),
    ('Look Food', 'Olej lniany ekologiczny', '2'),
    ('Lewiatan', 'Olej kokosowy', '2'),
    ('Coosur', 'Oliwa z oliwek najwyższej jakości z pierwszego tłoczenia', '4'),
    ('Lidl Primadonna', 'Bio Hiszpańska oliwa z oliwek.', '2'),
    ('Bielmar', 'Sonnenblumen Öl', '2'),
    ('Oleo', 'Olej rzepakowy', '2'),
    ('Semco', 'Olej rzepakowy', '2'),
    ('Culineo', 'Ocet spirytusowy 10%', '2'),
    ('GustoBello', 'Krem z octem balsamicznym', '4'),
    ('Pegaz', 'Ocet spirytusowy 10%', '2'),
    ('Kujawski', 'Olej 3 ziarna', '2'),
    ('Kujawski', 'Kujawski czosnek bazylia', '2'),
    ('Biedronka', 'Olej z awokado z pierwszego tłoczenia', '4'),
    ('Oliver', 'Olej', '2'),
    ('EkoWital', 'Ekologiczny Olej Kokosowy', '2'),
    ('Felix', 'Orzeszki z pieca', '4'),
    ('LenVitol', 'Olej lniany', '4'),
    ('Olejowy Raj', 'Olej kokosowy', '2'),
    ('Unknown', 'Wyborny Delio', '2'),
    ('Oleofarm', 'Olej z pestek dyni', '2'),
    ('Semco', 'Oil', '4'),
    ('Premium Gold Master', 'Olej kokosowy', '2'),
    ('Olejarnia Świecie', 'Naturalny olej konopny', '4'),
    ('Radix-Bis', 'Olej kokosowy rafinowany', '2'),
    ('Go Bio', 'Olej Kokosowy', '4'),
    ('Vita Natura', 'Olej kokosowy Bio', '2'),
    ('Unknown', 'Olej kokosowy bezzapachowy rafinowany', '2'),
    ('Unknown', 'Olej z czarnuszki', '4'),
    ('Nestlé', 'Przyprawa Maggi', '4'),
    ('Iorgos', 'Olive Oil', '2'),
    ('PPHU &quot;OLMAJ&quot; Sławomir Majewski', 'Olej rzepakowy zwyczajny', '2'),
    ('Lyrakis Family', 'Oliwa z oliwek z pierwszego tłoczenia', '2'),
    ('Suriny', 'Olej z ryżu 100%', '4'),
    ('Basso', 'Olej z ryżu', '2'),
    ('Pudliszki', 'Pudliszki', '4'),
    ('Primadonna', 'Extra Virgin Olive Oil', '2'),
    ('Casa de Azeite', 'Oliwa z oliwek', '2'),
    ('Carrefour BIO', 'Huile d''olive vierge extra', '2'),
    ('Casa de Azeite', 'Casa de Azeite', '2'),
    ('Auchan', 'Auchan huile d''olive extra vierge verre 0.75l pack b', '2'),
    ('Vita D''or', 'Sonnenblumenöl', '4'),
    ('Vita D´or', 'Sonnenblumenöl', '2'),
    ('Carrefour', 'Huile De Tournesol', '2'),
    ('Vita d''Or', 'Rapsöl', '4'),
    ('Vita D''or', 'Olej rzepakowy', '2'),
    ('Kaufland', 'Rapsöl', '2'),
    ('SimplCarrefour', 'Huile de Colza', '2'),
    ('Złote Łany', 'Olej rzepakowy', '2'),
    ('Vitasia', 'Vinagre de arroz', '2'),
    ('Lidl', 'Olej kokosowy', '2'),
    ('Carrefour', 'Huile pour friture', '2'),
    ('Monini', 'Oliwa z oliwek', '2'),
    ('Gallo', 'Olive Oil', '2'),
    ('Lidl', 'Huile d''olive vierge extra origine Espagne extraite à froid bio', '2'),
    ('K-Classic', 'Extra virgin olive oil', '2'),
    ('Unknown', 'Olio Extre Vergine Do Oliva Grecale', '2'),
    ('Lyttos', 'Greek Olive Oil', '4'),
    ('Eridanous', 'Öl - Griechisches natives Olivenöl Extra', '4'),
    ('Basso', 'Olio extravergine di oliva', '2'),
    ('La PEDRIZA', 'Aceite de Olive Virgen Extra', '2'),
    ('Basso', 'Oliwa z wytloczyn z oliwek', '2'),
    ('Goccia d''oro', 'Olio di Sansa di Oliva', '4'),
    ('Neféli', 'Extra Virgin Olive Oil', '2'),
    ('Kaufland', 'Bio oliwa z oliwek', '2'),
    ('Salvadori', 'Olio Di Sansa Di Oliva Salvadori', '4'),
    ('Font Oliva', 'Olive Oil', '2'),
    ('Unknown', 'Pedriza extra virgin olive oil', '2'),
    ('Basso', 'Oliwa z oliwek extra vergine al basilico', '2'),
    ('Basso', 'Oliwa z oliwek extra vergine al rosmarino', '2'),
    ('Ollineo', 'Ollineo Öl', '2'),
    ('Monini', 'Aceto di vino blanco 7,1 %', '2'),
    ('JCCoinbra II', 'Olej z pestek winogron. Rafinowany', '2'),
    ('Basso', 'Peanut oil', '2'),
    ('Sottile Gusto', 'Olej z pestek winogron', '2'),
    ('Bio Planete', 'Olej Kokosowy ekologiczny', '2'),
    ('Bio planete', 'Ekologiczny Olej kokosowy virgin', '2'),
    ('Foodbroker as', 'Olej z pestek winogron', '2'),
    ('Vilgain', 'Avocado oil spray', '2'),
    ('Basso', 'Olej z pestek winogron', '4'),
    ('Unknown', 'Oliwa z Oliwek', '2'),
    ('La Espanola', 'Oliwa Z Oliwek', '2'),
    ('Agrelos', 'Extra Virgin Olive Oil', '2'),
    ('Unknown', 'Aceite de oliva virgen extra', '2'),
    ('Unknown', 'Orazio''s olive oil', '2'),
    ('Unknown', 'Extra Virgin Olive Oil', '2'),
    ('Unknown', 'Huile de coco', '2')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Oils & Vinegars', 100, 'PL');
