-- PIPELINE (Frozen & Prepared): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('FRoSTA', 'Fischstäbchen ( Frosta)', 'Edeka'),
    ('FRoSTA', 'Fischstäbchen ( Frosta)', 'Kaufland'),
    ('Speisezeit', 'Süßkartoffel-Pommes', 'Aldi'),
    ('Original Wagner', 'Piccolinis Drei-Käse Pizza', 'REWE'),
    ('Nur Nur Natur', 'Bio-Dinkel-Steinofenpizza - Grillgemüse', 'Aldi'),
    ('Mucci', 'Milchmäuse Eis am Stiel - Haselnuss', 'Aldi'),
    ('Schne-frost', 'Mikrowellen-Pommes - Extra dünn', 'Netto'),
    ('Aldi', 'Backfisch-Stäbchen (15 Stück)', 'Aldi'),
    ('Mövenpick', 'Schwarzwälder Kirsch', 'REWE'),
    ('Aldi', 'Bratkartoffel-Pfanne mit Hähnchen', 'Aldi'),
    ('Ocean Sea', 'Fischstäbchen', 'Lidl'),
    ('Speise Zeit', 'Wellenschnitt Pommes', 'Aldi'),
    ('Dr. Oetker', 'Pizza Traditionale Verdure Grigliate', 'Edeka'),
    ('Nur Nur Natur', 'Bio-Eiscreme - Vanille', 'Aldi'),
    ('Aldi', 'Pommes Frites', 'Aldi'),
    ('Mucci', 'Eiskalte Kiste', 'Aldi'),
    ('Golden Seafood', 'Fisch Schlemmer-Filet à la Bordelaise classic', 'Aldi'),
    ('Bon Gelati', 'Mini Almond', 'Lidl'),
    ('Bon Gelati', 'Eis Mandel', 'Lidl'),
    ('Original Wagner', 'Piccolinis Tomate Mozzarella', 'REWE'),
    ('Mucci', 'Selection Bourbon-Vanilleeis', 'Aldi'),
    ('Harvest Basket', 'Wellenschnitt Pommes Frites', 'Lidl'),
    ('Aldi', 'Less & Tasty - Vanille', 'Aldi'),
    ('Nestlé', 'Salted Caramel Eis', 'REWE'),
    ('Nur Nur Natur', 'Bio-Eiscreme Schokolade', 'Aldi'),
    ('Aldi', 'Mediterrane Kartoffel-Wedges offen', 'Aldi'),
    ('La Finesse', 'Curly Fries', 'Aldi'),
    ('ABLIG Feinfrost GmbH', 'Softeis Hexenbecher Schoko-Vanille', 'Norma'),
    ('Nestlé', 'Eis Cappuccino', 'REWE'),
    ('Femeg', 'Wildlachsfilets handfiletiert', 'Edeka'),
    ('Gelatelli', 'Bourbon vanilla & blueberry ice cream', 'Lidl'),
    ('Mucci', 'Less & Tasty - Vanille-Walnuss', 'Aldi'),
    ('Aldi', 'Pommes frites, angebrochen XXL', 'Aldi'),
    ('Mövenpick', 'Cookie Dough', 'Edeka'),
    ('Mövenpick', 'Cookie Dough', 'Kaufland'),
    ('DMK Eis', 'Eisschale Tricolor - Pistazie-Vanille-Nougat', 'Aldi'),
    ('Aldi', 'Nuss-Nougat-Eis', 'Aldi'),
    ('Boujee', 'Dubai Chocolate Style', 'Lidl'),
    ('Boujee', 'Dubai Chocolate Style', 'Netto'),
    ('Lidl', 'Italienisches Premium Eis aus Sizilien', 'Lidl'),
    ('Original Wagner', 'Piccolinis Wednesday - Bloody Margherita', 'Edeka'),
    ('Lidl Harvest Basket', 'Kroketten', 'Lidl'),
    ('Aldi', 'Less & Tasty - Salted Caramel', 'Aldi'),
    ('Harvest Basket', 'Pommes extra dünn', 'Lidl'),
    ('Cremissimo', 'Cremissimo Schwarzwälder Kirsch', 'Aldi'),
    ('Cremissimo', 'Cremissimo Schwarzwälder Kirsch', 'Edeka'),
    ('Cremissimo', 'Cremissimo Schwarzwälder Kirsch', 'REWE'),
    ('Cremissimo', 'Cremissimo Schwarzwälder Kirsch', 'Netto'),
    ('Fertigessen', 'Rösti Ecken', 'REWE'),
    ('Iglo', 'TK Fischstäbchen Omega 3', 'Aldi'),
    ('Iglo', 'TK Fischstäbchen Omega 3', 'Edeka'),
    ('Iglo', 'TK Fischstäbchen Omega 3', 'REWE'),
    ('Confiserie Firenze', 'Mini Windbeutel mit Sahnecreme-Füllung', 'Lidl'),
    ('Mövenpick', 'Mango 7613036211802 Mangoeis mit Fruchtzubereitung mit Mangostückchen', 'REWE'),
    ('Iglo', 'Schlemmer Filet Grüner Spargel', 'REWE'),
    ('Bon Gelati', 'Erdbeer-Vanille Hörnchen', 'Lidl'),
    ('REWE Beste Wahl', 'Hähnchen Gärtnerin', 'REWE'),
    ('Mövenpick', 'Bourbon-Vanille-Eis', 'REWE'),
    ('Cremissimo', 'Bourbon Vanille Eis vegan', 'Edeka'),
    ('Cremissimo', 'Bourbon Vanille Eis vegan', 'REWE'),
    ('Ben & Jerry''s', 'Cookie Dough', 'Edeka'),
    ('Vemondo', 'Frozen Smoothie Stick', 'Lidl'),
    ('Cremissimo', 'Cremissimo Schokolade', 'REWE'),
    ('McCain', 'Chef Frites', 'Aldi'),
    ('McCain', 'Chef Frites', 'Edeka'),
    ('McCain', 'Chef Frites', 'REWE'),
    ('Cremissimo', 'Bourbon Vanille', 'REWE'),
    ('McCain', 'Smiles Pommesgesichter', 'REWE'),
    ('Nutella', 'Glace au Nutella', 'REWE'),
    ('Magnum', 'Magnum Glace Bâtonnet Classic 6x100ml', 'REWE'),
    ('Fisch', 'Ofen-Backfisch', 'Netto'),
    ('Alnatura', 'Reiswaffeln mit Salz', 'Edeka'),
    ('REWE Beste Wahl', 'Bourbon Vanille Vegan', 'REWE'),
    ('Milka', 'Vannilla Chocolate Swirl', 'Kaufland'),
    ('Nestlé', 'Eis Chocolate Chips', 'REWE'),
    ('Eisbär Eis', 'High Protein Eis Double Chocolate', 'REWE'),
    ('Eisbär Eis', 'High Protein Eis Cookies & Cream', 'REWE'),
    ('Rewe Bio', 'Pommes Frites', 'REWE'),
    ('Magnum', 'Magnum Mini Almond', 'REWE'),
    ('Ocean Sea', 'Pavés de saumon Rose du Pacifique', 'Lidl'),
    ('Ocean Sea', 'Schlemmerfilet', 'Lidl'),
    ('Nestlé', 'Magnum Double Gold Caramel Billionaire', 'REWE'),
    ('Ola', 'Nogger', 'Lidl'),
    ('K-Classic', 'Pommes', 'Kaufland'),
    ('Langnese', 'Cuja Mara Split', 'Aldi'),
    ('Langnese', 'Cuja Mara Split', 'Edeka'),
    ('Langnese', 'Cuja Mara Split', 'REWE'),
    ('Edeka', 'Edeka Bio Rahm-Blattspinat', 'Edeka'),
    ('Cremissimo', 'Cremissimo Walnuss', 'Aldi'),
    ('Cremissimo', 'Cremissimo Walnuss', 'Edeka'),
    ('Cremissimo', 'Cremissimo Walnuss', 'REWE'),
    ('Cremissimo', 'Cremissimo Walnuss', 'Netto'),
    ('Nestlé', 'Maple Walnuts Eis', 'Aldi'),
    ('Nestlé', 'Maple Walnuts Eis', 'REWE'),
    ('McCain', 'Pommes', 'Tegut'),
    ('Ben & Jerry''s', 'Chocolate Fudge Brownie', 'REWE'),
    ('Ben & Jerry''s', 'Ben & Jerry''s Glace en Pot Peanut Butter Cup 465ml', 'Edeka'),
    ('Ice Fantasy', 'Big Choc - Mandel', 'Netto'),
    ('REWE Beste Wahl', 'Steakhouse Fries', 'REWE'),
    ('Nestlé', 'Bum Bum', 'REWE'),
    ('Eisbär Eis', 'Vanille Eiscreme', 'REWE'),
    ('Ben & Jerry''s', 'Sundae Dulce De-lish', 'REWE'),
    ('Cremissimo', 'Cremissimo Solero', 'Aldi'),
    ('Cremissimo', 'Cremissimo Solero', 'Edeka'),
    ('Cremissimo', 'Cremissimo Solero', 'REWE'),
    ('Cremissimo', 'Cremissimo Solero', 'Netto'),
    ('Magnum', 'Vegan Almond', 'Edeka'),
    ('Eisbär Eis', 'High Protein Eis Vanille Salted Caramel', 'REWE'),
    ('Edeka', 'Eiscreme Bourbon-Vanille', 'Edeka'),
    ('McCain', 'Air Fryer Frites', 'Edeka'),
    ('Kinder', 'Kinder Chocolate Ice Cream', 'Netto'),
    ('Kinder', 'Kinder Chocolate Ice Cream', 'Kaufland'),
    ('Cremissimo', 'Cremissimo Nogger Choc', 'Aldi'),
    ('Cremissimo', 'Cremissimo Nogger Choc', 'Edeka'),
    ('Cremissimo', 'Cremissimo Nogger Choc', 'REWE'),
    ('Cremissimo', 'Cremissimo Nogger Choc', 'Netto'),
    ('REWE Beste Wahl', 'Cookie Dough', 'REWE'),
    ('Ja', 'Jumbo Fries', 'REWE'),
    ('Cremissimo', 'Cremissimo Erdbeer Joghurt', 'REWE'),
    ('Cremissimo', 'Eis Heidelbeer Vanille', 'Edeka'),
    ('REWE Beste Wahl', 'Tempura shrimp in batter', 'REWE'),
    ('Raffaello', 'Raffaello Peach Dream 3er-Pack', 'Edeka'),
    ('Raffaello', 'Raffaello Peach Dream 3er-Pack', 'REWE'),
    ('Raffaello', 'Raffaello Peach Dream 3er-Pack', 'Netto'),
    ('Original Wagner', 'Steinofen-Pizza Vegetaria', 'Edeka'),
    ('Freshona', 'Seasoned mixed vegetables - Italian style', 'Lidl'),
    ('Bon Gelati', 'Vanille Eis', 'Lidl'),
    ('Edeka', 'Mini Kartoffeltaschen', 'Edeka'),
    ('Ben & Jerry''s', 'Cookie Dough S''Wich Up', 'Edeka'),
    ('Cremissimo', 'Eis Peanut Banane', 'Kaufland'),
    ('REWE Beste Wahl', 'Apfel-Rotkohl', 'REWE'),
    ('McCain', 'Pommes ''Golden Longs'' (mit Knuspermantel)', 'Aldi'),
    ('Rewe', 'Vanille Eiscreme', 'REWE'),
    ('Cremissimo', 'Schokolade Haselnuss Vegan', 'REWE'),
    ('Eisbär Eis', 'Peanut Butter chunks', 'REWE'),
    ('Magnum', 'Magnum Glace Bâtonnet Mini Classique, Amande & Chocolat Blanc 6x55ml', 'REWE'),
    ('Harvest Basket', 'Backofen Wellenschnitt Pommes', 'Lidl'),
    ('Ja!', 'Eiskonfekt', 'REWE'),
    ('Rewe', 'Fischburger', 'REWE'),
    ('Magnum', 'Magnum vegan chill blueberry cookie', 'REWE'),
    ('Ben & Jerry''s', 'Bohemian Raspberry Vegan', 'REWE'),
    ('Galileo Lebensmittel', 'Mini-Pizza Pomodoro Vegan', 'REWE'),
    ('Mövenpick', 'Eis - Vanilla Chocolate', 'REWE'),
    ('Magnum', 'MAGNUM Glace Bâtonnet Chocolat Blanc & Cookies 4x90ml', 'Lidl'),
    ('REWE Feine Welt', 'Schokoladen Eiscreme', 'REWE')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Frozen & Prepared' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
