-- PIPELINE (Frozen & Prepared): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-04

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Frosta', 'Bratkartoffel Hähnchen Pfanne', 'REWE'),
    ('Frosta', 'Bratkartoffel Hähnchen Pfanne', 'Kaufland'),
    ('Frosta', 'Fischstäbchen ( Frosta)', 'Edeka'),
    ('Frosta', 'Fischstäbchen ( Frosta)', 'Kaufland'),
    ('Frosta', 'Hühnerfrikassee', 'Lidl'),
    ('Frosta', 'Hühnerfrikassee', 'Edeka'),
    ('Frosta', 'Hühnerfrikassee', 'REWE'),
    ('Frosta', 'Tortellini Käse-Sahne (vegetarisch)', 'Edeka'),
    ('Frosta', 'Gemüse Pfanne alla Toscana', 'REWE'),
    ('Frosta', 'Hähnchen Curry', 'Edeka'),
    ('Frosta', 'Hähnchen Curry', 'REWE'),
    ('Frosta', 'Hähnchen Curry', 'Kaufland'),
    ('Frosta', 'Hähnchen Curry', 'Real'),
    ('Speisezeit', 'Süßkartoffel-Pommes', 'Aldi'),
    ('Original Wagner', 'Piccolinis Drei-Käse Pizza', 'REWE'),
    ('Nur Nur Natur', 'Bio-Dinkel-Steinofenpizza - Grillgemüse', 'Aldi'),
    ('Dr. Oetker', 'Die Ofenfrische Vier Käse', 'Edeka'),
    ('Frosta', 'Bami Goreng', 'Edeka'),
    ('Frosta', 'Bami Goreng', 'REWE'),
    ('Frosta', 'Bami Goreng', 'Kaufland'),
    ('Frosta', 'Bami Goreng', 'Norma'),
    ('Frosta', 'Butter Chicken', 'REWE'),
    ('Original Wagner', 'Pizza Die Backfrische Mozzarella', 'Edeka'),
    ('Frosta', 'Nice Rice - Korean Style', 'Edeka'),
    ('Frosta', 'Nice Rice - Korean Style', 'REWE'),
    ('Dr. Oetker', 'Ristorante PIZZA TONNO', 'REWE'),
    ('Dr. Oetker', 'Ristorante PIZZA TONNO', 'Penny'),
    ('Frosta', 'Paella', 'Edeka'),
    ('Frosta', 'Paella', 'REWE'),
    ('Frosta', 'Paella', 'Kaufland'),
    ('Frosta', 'Paella', 'Real'),
    ('Dr. Oetker', 'Suprema Pizza Calabrese & ''Nduja', 'Edeka'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', 'Aldi'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', 'Lidl'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', 'Edeka'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', 'REWE'),
    ('Dr. Oetker', 'Die Ofenfrische Margherita', 'Edeka'),
    ('Greenyard Frozen Langemark', 'Buckwheat & broccoli', 'Lidl'),
    ('Frosta', 'Fisch Schlemmerfilet Mediterraner Art', 'Edeka'),
    ('Frosta', 'Fettuccine Wildlachs', 'Edeka'),
    ('Dr. Oetker', 'Pizza Tradizionale Margherita', 'Edeka'),
    ('Original Wagner', 'Steinofen-Pizza - Diavolo', 'REWE'),
    ('Original Wagner', 'Steinofen-Pizza - Diavolo', 'Netto'),
    ('Dr. Oetker', 'Die Ofenfrische Speciale', 'Edeka'),
    ('Dr. Oetker', 'Die Ofenfrische Speciale', 'Netto'),
    ('Dr. Oetker', 'Pizza Salame Ristorante', 'Lidl'),
    ('Dr. Oetker', 'Pizza Salame Ristorante', 'REWE'),
    ('Vemondo', 'Vegan pizza Verdura', 'Lidl'),
    ('Dr. Oetker', 'Die Ofenfrische Salami', 'Lidl'),
    ('Dr. Oetker', 'Die Ofenfrische Salami', 'Edeka'),
    ('Frosta', 'Fisch Schlemmerfilet Brokkoli Mandel', 'Edeka'),
    ('Frosta', 'Fisch Schlemmerfilet Brokkoli Mandel', 'REWE'),
    ('Dr. Oetker', 'La Mia Grande Rucola', 'REWE'),
    ('GiaPizza', 'Bio-Dinkel-Steinofenpizza - Spinat', 'Aldi'),
    ('Nestlé', 'Pizza Speciale', 'REWE'),
    ('Nestlé', 'Pizza Speciale', 'Netto'),
    ('Dr. Oetker', 'La Mia Grande Pizza Margherita', 'Edeka'),
    ('Dr. Oetker', 'La Mia Grande Pizza Margherita', 'REWE'),
    ('Speise Zeit', 'Wellenschnitt Pommes', 'Aldi'),
    ('Frosta', 'Nom Nom Noodles', 'Edeka'),
    ('Dr. Oetker', 'Pizza Traditionale Verdure Grigliate', 'Edeka'),
    ('Dr. Oetker', 'Ristorante Pizza Pasta', 'Edeka'),
    ('Dr. Oetker', 'Ristorante Pizza Pasta', 'REWE'),
    ('Nur Nur Natur', 'Bio-Eiscreme - Vanille', 'Aldi'),
    ('Nestlé', 'Steinofen-Pizza Thunfisch', 'REWE'),
    ('Aldi', 'Pommes Frites', 'Aldi'),
    ('All Seasons', 'Rahm-Spinat', 'Aldi'),
    ('Vemondo', 'Pumpkin & quinoa', 'Lidl')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Frozen & Prepared' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
