import type { GoldenLocale } from "./contract";

export const AUTH_COPY = {
  en: {
    eyebrow: "A private path back to your evidence",
    title: "Continue where your last decision stopped.",
    intro: "This deterministic journey demonstrates labels, autofill, validation, recovery, failure, success, and redirect without contacting an account service.",
    signIn: "Sign in",
    modeLabel: "Authentication path",
    register: "Create account",
    recover: "Recover access",
    email: "Email address",
    password: "Password",
    name: "Display name",
    emailHint: "Use review@tryvit.local for the deterministic success path.",
    passwordHint: "Use eight or more characters. Nothing is transmitted.",
    required: "Required",
    missingEmail: "Enter a valid email address.",
    missingPassword: "Enter at least eight characters.",
    missingName: "Enter a display name.",
    invalid: "Those local review details do not match. Try review@tryvit.local.",
    serviceTitle: "Local account simulation unavailable",
    service: "Your entries remain in this browser. Return to sign in and retry the local path.",
    busy: "Checking the local review details",
    busyDetail: "A deterministic in-browser validation is running. No network request is made.",
    success: "Local sign-in completed",
    successDetail: "No account was accessed. Continue to the authenticated home reference.",
    redirecting: "Preparing the home reference",
    recoverySent: "Recovery instructions prepared",
    recoveryDetail: "For privacy, this review does not reveal whether an account exists and sends no email.",
    submitSignIn: "Continue",
    submitRegister: "Review registration",
    submitRecovery: "Prepare recovery instructions",
    retry: "Return to sign in",
    home: "Open authenticated home",
    privacy: "No credentials leave this browser. Password-manager and autofill semantics are present for review only.",
    summary: "Correct the following fields",
  },
  pl: {
    eyebrow: "Prywatny powrót do zapisanych danych",
    title: "Wróć do miejsca, w którym przerwano ostatnią decyzję.",
    intro: "Ten deterministyczny proces pokazuje etykiety, autouzupełnianie, walidację, odzyskiwanie, awarię, sukces i przekierowanie bez łączenia z usługą kont.",
    signIn: "Zaloguj się",
    modeLabel: "Ścieżka uwierzytelniania",
    register: "Utwórz konto",
    recover: "Odzyskaj dostęp",
    email: "Adres e-mail",
    password: "Hasło",
    name: "Nazwa wyświetlana",
    emailHint: "Dla ścieżki testowej użyj review@tryvit.local.",
    passwordHint: "Wpisz co najmniej osiem znaków. Dane nie są przesyłane.",
    required: "Wymagane",
    missingEmail: "Wpisz prawidłowy adres e-mail.",
    missingPassword: "Wpisz co najmniej osiem znaków.",
    missingName: "Wpisz nazwę wyświetlaną.",
    invalid: "Lokalne dane testowe nie pasują. Użyj review@tryvit.local.",
    serviceTitle: "Lokalna symulacja konta jest niedostępna",
    service: "Wpisane dane pozostają w tej przeglądarce. Wróć do logowania i spróbuj lokalnie ponownie.",
    busy: "Sprawdzanie lokalnych danych testowych",
    busyDetail: "Trwa deterministyczna walidacja w przeglądarce. Żądanie sieciowe nie jest wysyłane.",
    success: "Logowanie lokalne zakończone",
    successDetail: "Nie uzyskano dostępu do żadnego konta. Przejdź do widoku panelu głównego.",
    redirecting: "Przygotowywanie panelu głównego",
    recoverySent: "Przygotowano instrukcje odzyskiwania",
    recoveryDetail: "Dla ochrony prywatności widok nie ujawnia, czy konto istnieje, i nie wysyła wiadomości.",
    submitSignIn: "Kontynuuj",
    submitRegister: "Sprawdź rejestrację",
    submitRecovery: "Przygotuj instrukcje odzyskiwania",
    retry: "Wróć do logowania",
    home: "Otwórz panel główny",
    privacy: "Dane logowania nie opuszczają przeglądarki. Semantyka menedżera haseł i autouzupełniania służy wyłącznie do przeglądu.",
    summary: "Popraw następujące pola",
  },
  de: {
    eyebrow: "Privater Weg zurück zur Evidenz",
    title: "Dort fortfahren, wo die letzte Entscheidung pausiert wurde.",
    intro: "Dieser deterministische Ablauf zeigt Beschriftung, Autofill, Validierung, Wiederherstellung, Dienstausfall, Erfolg und Weiterleitung ohne Verbindung zu einem Kontodienst.",
    signIn: "Anmelden",
    modeLabel: "Authentifizierungsweg",
    register: "Konto anlegen",
    recover: "Zugang wiederherstellen",
    email: "E-Mail-Adresse",
    password: "Passwort",
    name: "Anzeigename",
    emailHint: "Für den deterministischen Erfolgsweg review@tryvit.local verwenden.",
    passwordHint: "Mindestens acht Zeichen eingeben. Es wird nichts übertragen.",
    required: "Erforderlich",
    missingEmail: "Eine gültige E-Mail-Adresse eingeben.",
    missingPassword: "Mindestens acht Zeichen eingeben.",
    missingName: "Einen Anzeigenamen eingeben.",
    invalid: "Diese lokalen Prüfdaten stimmen nicht überein. review@tryvit.local verwenden.",
    serviceTitle: "Lokale Kontosimulation nicht verfügbar",
    service: "Die Eingaben bleiben in diesem Browser. Zur Anmeldung zurückkehren und den lokalen Weg erneut versuchen.",
    busy: "Lokale Prüfdaten werden geprüft",
    busyDetail: "Eine deterministische Prüfung im Browser läuft. Es wird keine Netzwerkanfrage gesendet.",
    success: "Lokale Anmeldung abgeschlossen",
    successDetail: "Auf kein Konto wurde zugegriffen. Zur authentifizierten Übersicht wechseln.",
    redirecting: "Übersicht wird vorbereitet",
    recoverySent: "Wiederherstellungshinweise vorbereitet",
    recoveryDetail: "Zum Schutz der Privatsphäre wird nicht offengelegt, ob ein Konto besteht, und keine E-Mail versendet.",
    submitSignIn: "Fortfahren",
    submitRegister: "Registrierung prüfen",
    submitRecovery: "Wiederherstellung vorbereiten",
    retry: "Zur Anmeldung zurückkehren",
    home: "Authentifizierte Übersicht öffnen",
    privacy: "Anmeldedaten verlassen den Browser nicht. Passwortmanager- und Autofill-Semantik dienen nur der Prüfung.",
    summary: "Folgende Felder korrigieren",
  },
} as const satisfies Readonly<Record<GoldenLocale, Readonly<Record<string, string>>>>;
