import type { GoldenLocale } from "./contract";

export const SCANNER_COPY = {
  en: {
    eyebrow: "Signature scanner · deterministic simulation",
    title: "Frame the code. Keep every uncertain step visible.",
    intro: "No camera or product service is active. Recognition, lookup, partial matches, interruption, and recovery are explicit local states.",
    noCamera: "Camera inactive",
    statusEyebrow: "Simulation status",
    manual: "Enter barcode manually",
    request: "Review permission request",
    allow: "Allow simulation",
    deny: "Deny",
    cancel: "Cancel",
    continue: "Continue acquisition",
    recognize: "Recognize synthetic barcode",
    process: "Build evidence result",
    retry: "Retry this stage",
    resume: "Resume interrupted scan",
    contribute: "Contribute missing record",
    rescan: "Start another simulated scan",
    manualLabel: "EAN-13 barcode",
    manualHint: "Use the fixed review barcode 5901234123457.",
    manualSubmit: "Check local barcode",
    invalid: "Enter the 13-digit synthetic review barcode.",
    contributionLabel: "Product name on the package",
    contributionHint: "Local review only; nothing is uploaded.",
    contributionSubmit: "Prepare local contribution",
    permissionTitle: "Camera access would be requested now",
    permissionBody: "A real product would explain why access is needed at this moment. This review never invokes a browser permission.",
    progress: "Local lookup simulation · step 3 of 4",
    resultDecision: "Review before deciding",
    resultReason: "A synthetic product matched, but processing remains unassessed.",
    stateLabel: {
      "not-requested": "Permission has not been requested. Manual entry is available.",
      "permission-request": "Permission rationale is shown. No browser prompt is open.",
      "permission-denied": "Permission was declined in the simulation. Manual entry remains available.",
      "camera-unavailable": "Camera capability is unavailable. No access was attempted.",
      ready: "Scanner simulation ready. Align the synthetic barcode within the frame.",
      "acquisition-assist": "Move the package closer and keep the full barcode inside the frame.",
      recognized: "Barcode 5901234123457 recognized. Product identity is not matched yet.",
      processing: "Barcode decoded. Local product lookup is in progress.",
      matched: "North Grain Oat Drink matched with moderate data confidence.",
      "partial-match": "Partial match. Brand and barcode agree; processing evidence is missing.",
      "uncertain-match": "Two synthetic records could match. No score is shown until identity is confirmed.",
      "not-found": "The barcode is valid but no synthetic product record was found.",
      offline: "Optical recognition may continue, but product lookup is unavailable offline.",
      interrupted: "The local scan was interrupted before lookup completed.",
      resumed: "Interrupted recognition resumed without duplicating the lookup.",
      "manual-entry": "Manual barcode entry is active.",
      "invalid-barcode": "The manual barcode is invalid.",
      "contribution-entry": "Prepare a local contribution for a missing product record.",
    },
  },
  pl: {
    eyebrow: "Charakterystyczny skaner · deterministyczna symulacja",
    title: "Ustaw kod w kadrze. Zachowaj widoczność każdego niepewnego etapu.",
    intro: "Aparat i usługa produktów są nieaktywne. Rozpoznanie, wyszukiwanie, częściowe dopasowanie, przerwanie i odzyskanie to jawne stany lokalne.",
    noCamera: "Aparat nieaktywny",
    statusEyebrow: "Stan symulacji",
    manual: "Wpisz kod ręcznie",
    request: "Sprawdź prośbę o dostęp",
    allow: "Zezwól na symulację",
    deny: "Odmów",
    cancel: "Anuluj",
    continue: "Kontynuuj pozyskiwanie",
    recognize: "Rozpoznaj kod syntetyczny",
    process: "Zbuduj wynik danych",
    retry: "Ponów ten etap",
    resume: "Wznów przerwany skan",
    contribute: "Dodaj brakujący rekord",
    rescan: "Rozpocznij kolejną symulację",
    manualLabel: "Kod kreskowy EAN-13",
    manualHint: "Użyj stałego kodu testowego 5901234123457.",
    manualSubmit: "Sprawdź kod lokalnie",
    invalid: "Wpisz 13-cyfrowy syntetyczny kod testowy.",
    contributionLabel: "Nazwa produktu na opakowaniu",
    contributionHint: "Wyłącznie lokalny przegląd; nic nie jest przesyłane.",
    contributionSubmit: "Przygotuj lokalny wkład",
    permissionTitle: "W tym momencie pojawiłaby się prośba o dostęp do aparatu",
    permissionBody: "Prawdziwy produkt wyjaśniłby teraz potrzebę dostępu. Ten przegląd nigdy nie wywołuje uprawnienia przeglądarki.",
    progress: "Lokalna symulacja wyszukiwania · krok 3 z 4",
    resultDecision: "Sprawdź przed decyzją",
    resultReason: "Dopasowano produkt syntetyczny, ale przetworzenia nie oceniono.",
    stateLabel: {
      "not-requested": "Nie poproszono o dostęp. Możesz wpisać kod ręcznie.",
      "permission-request": "Wyświetlono uzasadnienie dostępu. Okno przeglądarki nie jest otwarte.",
      "permission-denied": "W symulacji odmówiono dostępu. Ręczne wpisanie kodu jest dostępne.",
      "camera-unavailable": "Aparat jest niedostępny. Nie próbowano uzyskać dostępu.",
      ready: "Symulowany skaner jest gotowy. Umieść syntetyczny kod w kadrze.",
      "acquisition-assist": "Przybliż opakowanie i zachowaj cały kod w kadrze.",
      recognized: "Rozpoznano kod 5901234123457. Produkt nie został jeszcze dopasowany.",
      processing: "Kod odczytano. Trwa lokalne wyszukiwanie produktu.",
      matched: "Dopasowano napój owsiany North Grain z umiarkowaną wiarygodnością danych.",
      "partial-match": "Częściowe dopasowanie. Marka i kod pasują; brakuje danych o przetworzeniu.",
      "uncertain-match": "Mogą pasować dwa rekordy syntetyczne. Wynik nie jest wyświetlany do potwierdzenia tożsamości.",
      "not-found": "Kod jest prawidłowy, ale nie znaleziono syntetycznego rekordu produktu.",
      offline: "Rozpoznanie kodu może działać, ale wyszukiwanie produktu offline jest niedostępne.",
      interrupted: "Lokalny skan przerwano przed zakończeniem wyszukiwania.",
      resumed: "Wznowiono rozpoznawanie bez powielania wyszukiwania.",
      "manual-entry": "Ręczne wpisywanie kodu jest aktywne.",
      "invalid-barcode": "Ręczny kod jest nieprawidłowy.",
      "contribution-entry": "Przygotuj lokalny wkład dla brakującego rekordu produktu.",
    },
  },
  de: {
    eyebrow: "Signatur-Scanner · deterministische Simulation",
    title: "Code ausrichten. Jeden unsicheren Schritt sichtbar halten.",
    intro: "Kamera und Produktdienst sind nicht aktiv. Erkennung, Suche, Teiltreffer, Unterbrechung und Wiederaufnahme sind ausdrückliche lokale Zustände.",
    noCamera: "Kamera inaktiv",
    statusEyebrow: "Simulationsstatus",
    manual: "Strichcode manuell eingeben",
    request: "Berechtigungsanfrage prüfen",
    allow: "Simulation zulassen",
    deny: "Ablehnen",
    cancel: "Abbrechen",
    continue: "Erfassung fortsetzen",
    recognize: "Synthetischen Strichcode erkennen",
    process: "Evidenzergebnis aufbauen",
    retry: "Diese Stufe wiederholen",
    resume: "Unterbrochenen Scan fortsetzen",
    contribute: "Fehlenden Datensatz beitragen",
    rescan: "Weitere Simulation beginnen",
    manualLabel: "EAN-13-Strichcode",
    manualHint: "Festgelegten Prüfcode 5901234123457 verwenden.",
    manualSubmit: "Code lokal prüfen",
    invalid: "Den 13-stelligen synthetischen Prüfcode eingeben.",
    contributionLabel: "Produktname auf der Verpackung",
    contributionHint: "Nur lokale Prüfung; nichts wird hochgeladen.",
    contributionSubmit: "Lokalen Beitrag vorbereiten",
    permissionTitle: "Jetzt würde Kamerazugriff angefragt",
    permissionBody: "Ein reales Produkt würde an dieser Stelle den Bedarf erklären. Diese Prüfung ruft niemals eine Browserberechtigung auf.",
    progress: "Lokale Suchsimulation · Schritt 3 von 4",
    resultDecision: "Vor der Entscheidung prüfen",
    resultReason: "Ein synthetisches Produkt wurde gefunden, die Verarbeitung ist jedoch nicht bewertet.",
    stateLabel: {
      "not-requested": "Keine Berechtigung angefragt. Manuelle Eingabe ist verfügbar.",
      "permission-request": "Die Begründung wird gezeigt. Kein Browserdialog ist geöffnet.",
      "permission-denied": "Die Berechtigung wurde in der Simulation abgelehnt. Manuelle Eingabe bleibt verfügbar.",
      "camera-unavailable": "Kamerafunktion ist nicht verfügbar. Es wurde kein Zugriff versucht.",
      ready: "Scanner-Simulation bereit. Den synthetischen Strichcode im Rahmen ausrichten.",
      "acquisition-assist": "Verpackung näher bewegen und den vollständigen Code im Rahmen halten.",
      recognized: "Strichcode 5901234123457 erkannt. Produktidentität noch nicht zugeordnet.",
      processing: "Strichcode dekodiert. Die lokale Produktsuche läuft.",
      matched: "North Grain Hafergetränk mit mittlerer Datenverlässlichkeit gefunden.",
      "partial-match": "Teiltreffer. Marke und Strichcode stimmen; Verarbeitungsevidenz fehlt.",
      "uncertain-match": "Zwei synthetische Datensätze könnten passen. Bis zur Bestätigung wird kein Wert gezeigt.",
      "not-found": "Der Strichcode ist gültig, aber kein synthetischer Produktdatensatz wurde gefunden.",
      offline: "Optische Erkennung kann fortfahren, die Produktsuche ist offline jedoch nicht verfügbar.",
      interrupted: "Der lokale Scan wurde vor Abschluss der Suche unterbrochen.",
      resumed: "Die Erkennung wurde ohne doppelte Suche fortgesetzt.",
      "manual-entry": "Manuelle Strichcodeeingabe ist aktiv.",
      "invalid-barcode": "Der manuelle Strichcode ist ungültig.",
      "contribution-entry": "Einen lokalen Beitrag für einen fehlenden Produktdatensatz vorbereiten.",
    },
  },
} as const satisfies Readonly<Record<GoldenLocale, Readonly<Record<string, unknown>>>>;

export type ScannerCopy = (typeof SCANNER_COPY)[GoldenLocale];
