import type { GoldenLocale } from "./contract";

export const SEARCH_COPY = {
  en: {
    label: "Search synthetic products",
    hint: "Try oat, North Grain, or the review EAN 5901234123457.",
    placeholder: "Product name or barcode",
    submit: "Search",
    filter: "Filters",
    close: "Close filters",
    apply: "Apply filters",
    clear: "Clear filters",
    partialFilter: "Include partial records",
    unknownFilter: "Include records without a score",
    summary: "Active filters",
    allRecords: "All three synthetic records",
    withPartial: "Partial evidence included",
    withUnknown: "Score-unavailable records included",
    noQuery: "Start with a product or barcode",
    noQueryDetail: "Recent review searches: oat drink, 5901234123457. No external product service is queried.",
    loading: "Calculating the local result set",
    results: "3 synthetic records in this fixture; 1 has no comparable score.",
    empty: "No synthetic record matches this query",
    emptyDetail: "Clear the query or filters, or continue to the deterministic scanner.",
    error: "The local search simulation stopped",
    errorDetail: "Retry the failed stage. No hosted fallback was attempted.",
    degraded: "One source is stale",
    degradedDetail: "Retained results remain visible with their recorded dates; count coverage is incomplete.",
    offline: "Showing retained offline fixtures",
    offlineDetail: "Fresh lookup is unavailable. Dates and unknown fields remain visible.",
    resultDecision: "Review",
    scoreUnavailable: "Score unavailable",
    open: "Inspect evidence",
    recent: "Recent searches",
    suggestion: "Suggested synthetic query",
    typingTitle: "Query in progress",
    typingDetail: "Submit the current query or choose a deterministic suggestion after it is prepared.",
    records: {
      "north-grain-oat-drink": { name: "North Grain Oat Drink — synthetic review record", confidence: "Moderate", confidenceReason: "One package transcription; zero independent checks.", mainReason: "Sugars are available, while processing classification is not assessed." },
      "polny-owies": { name: "Polny Owies Oat Drink — synthetic review record", confidence: "Limited", confidenceReason: "The nutrition table is available; ingredient percentages are incomplete.", mainReason: "Comparable nutrition is available, but ingredient detail is partial." },
      "lange-haferquelle": { name: "Haferquelle Original — synthetic review record", confidence: "Unavailable", confidenceReason: "A required score input is unavailable.", mainReason: "No score is shown because the record cannot be compared safely." },
    },
  },
  pl: {
    label: "Wyszukaj produkty syntetyczne",
    hint: "Wpisz owies, North Grain albo testowy EAN 5901234123457.",
    placeholder: "Nazwa produktu lub kod kreskowy",
    submit: "Szukaj",
    filter: "Filtry",
    close: "Zamknij filtry",
    apply: "Zastosuj filtry",
    clear: "Wyczyść filtry",
    partialFilter: "Uwzględnij niepełne rekordy",
    unknownFilter: "Uwzględnij rekordy bez wyniku",
    summary: "Aktywne filtry",
    allRecords: "Wszystkie trzy rekordy syntetyczne",
    withPartial: "Uwzględniono niepełne dane",
    withUnknown: "Uwzględniono rekordy bez wyniku",
    noQuery: "Zacznij od produktu lub kodu",
    noQueryDetail: "Ostatnie wyszukiwania testowe: napój owsiany, 5901234123457. Usługa zewnętrzna nie jest używana.",
    loading: "Obliczanie lokalnego zestawu wyników",
    results: "3 rekordy syntetyczne w materiale; 1 nie ma porównywalnego wyniku.",
    empty: "Brak pasującego rekordu syntetycznego",
    emptyDetail: "Wyczyść zapytanie lub filtry albo przejdź do deterministycznego skanera.",
    error: "Lokalna symulacja wyszukiwania została przerwana",
    errorDetail: "Ponów tylko przerwany etap. Nie użyto zewnętrznej usługi awaryjnej.",
    degraded: "Jedno źródło jest nieaktualne",
    degradedDetail: "Zachowane wyniki są widoczne razem z datami; zakres licznika jest niepełny.",
    offline: "Wyświetlanie zachowanych materiałów offline",
    offlineDetail: "Nowe wyszukiwanie jest niedostępne. Daty i nieznane pola pozostają widoczne.",
    resultDecision: "Sprawdź",
    scoreUnavailable: "Wynik niedostępny",
    open: "Przejrzyj dane",
    recent: "Ostatnie wyszukiwania",
    suggestion: "Sugerowane zapytanie syntetyczne",
    typingTitle: "Wpisywanie zapytania",
    typingDetail: "Wyślij bieżące zapytanie albo wybierz deterministyczną sugestię po jej przygotowaniu.",
    records: {
      "north-grain-oat-drink": { name: "Napój owsiany North Grain — materiał testowy", confidence: "Umiarkowana", confidenceReason: "Jeden zapis z opakowania; bez niezależnej weryfikacji.", mainReason: "Dane o cukrach są dostępne, ale klasyfikacji przetworzenia nie oceniono." },
      "polny-owies": { name: "Napój owsiany Polny Owies — materiał testowy", confidence: "Ograniczona", confidenceReason: "Tabela żywieniowa jest dostępna; procenty składników są niepełne.", mainReason: "Dane żywieniowe są porównywalne, ale szczegóły składników są niepełne." },
      "lange-haferquelle": { name: "Napój owsiany Haferquelle Original — materiał testowy", confidence: "Niedostępna", confidenceReason: "Brakuje danej wymaganej do wyliczenia wyniku.", mainReason: "Wynik nie jest wyświetlany, ponieważ rekordu nie można bezpiecznie porównać." },
    },
  },
  de: {
    label: "Synthetische Produkte suchen",
    hint: "Hafer, North Grain oder Prüf-EAN 5901234123457 eingeben.",
    placeholder: "Produktname oder Strichcode",
    submit: "Suchen",
    filter: "Filter",
    close: "Filter schließen",
    apply: "Filter anwenden",
    clear: "Filter löschen",
    partialFilter: "Unvollständige Datensätze einbeziehen",
    unknownFilter: "Datensätze ohne Wert einbeziehen",
    summary: "Aktive Filter",
    allRecords: "Alle drei synthetischen Datensätze",
    withPartial: "Teilweise Evidenz einbezogen",
    withUnknown: "Datensätze ohne Wert einbezogen",
    noQuery: "Mit Produkt oder Strichcode beginnen",
    noQueryDetail: "Letzte Prüfsuchen: Hafergetränk, 5901234123457. Kein externer Produktdienst wird abgefragt.",
    loading: "Lokale Ergebnismenge wird berechnet",
    results: "3 synthetische Datensätze in diesem Prüfsatz; 1 hat keinen vergleichbaren Wert.",
    empty: "Kein synthetischer Datensatz passt",
    emptyDetail: "Suchbegriff oder Filter löschen oder zum deterministischen Scanner wechseln.",
    error: "Die lokale Suchsimulation wurde unterbrochen",
    errorDetail: "Nur die fehlgeschlagene Stufe erneut versuchen. Kein gehosteter Ausweichdienst wurde verwendet.",
    degraded: "Eine Quelle ist veraltet",
    degradedDetail: "Gespeicherte Ergebnisse bleiben mit Datum sichtbar; die Abdeckung der Anzahl ist unvollständig.",
    offline: "Gespeicherte Offline-Prüfdaten werden gezeigt",
    offlineDetail: "Eine aktuelle Suche ist nicht verfügbar. Daten und unbekannte Felder bleiben sichtbar.",
    resultDecision: "Prüfen",
    scoreUnavailable: "Wert nicht verfügbar",
    open: "Evidenz prüfen",
    recent: "Letzte Suchen",
    suggestion: "Vorgeschlagene synthetische Suche",
    typingTitle: "Suchbegriff wird eingegeben",
    typingDetail: "Die aktuelle Suche absenden oder nach der Vorbereitung einen deterministischen Vorschlag wählen.",
    records: {
      "north-grain-oat-drink": { name: "North Grain Hafergetränk — synthetischer Prüfsatz", confidence: "Mittel", confidenceReason: "Eine Verpackungsabschrift; keine unabhängige Prüfung.", mainReason: "Zuckerangaben sind verfügbar; die Verarbeitungsklassifikation ist nicht bewertet." },
      "polny-owies": { name: "Polny Owies Hafergetränk — synthetischer Prüfsatz", confidence: "Begrenzt", confidenceReason: "Die Nährwerttabelle ist verfügbar; Zutatenanteile sind unvollständig.", mainReason: "Vergleichbare Nährwerte sind verfügbar, die Zutatenangaben jedoch nur teilweise." },
      "lange-haferquelle": { name: "Haferquelle Original — synthetischer Prüfsatz", confidence: "Nicht verfügbar", confidenceReason: "Eine erforderliche Eingabe für den Wert fehlt.", mainReason: "Es wird kein Wert gezeigt, weil der Datensatz nicht sicher vergleichbar ist." },
    },
  },
} as const satisfies Readonly<Record<GoldenLocale, Readonly<Record<string, unknown>>>>;

export type SearchCopy = (typeof SEARCH_COPY)[GoldenLocale];
