-- PIPELINE (Breakfast & Grain-Based): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi oraz kandyzowanymi owocami', 'Biedronka'),
    ('Vitanella', 'Granola z kawałkami czekolady, prażonymi orzeszkami ziemnymi ilaskowymi', 'Biedronka'),
    ('Vitanella', 'Musli prażone z suszoną, słodzoną żurawiną.', 'Biedronka'),
    ('Biedronka', 'Vitanella Granola z czekoladą', 'Biedronka'),
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi owocami oraz kawałkami prażonych orzeszków laskowych', 'Biedronka'),
    ('Biedronka', 'Mieszanka płatków zbożowych z rodzynkami i orzechami laskowymi', 'Biedronka'),
    ('Bakalland', 'Musli chrupkie klasyczne z dodatkiem wiórków kokosowych', 'Biedronka'),
    ('Vitanella', 'Płatki zbożowe z suszonymi i kandyzowanymi owocami.', 'Biedronka'),
    ('Melvit', 'CRISPY PIECZYWO CHRUPKIE z serem i cebulką', 'Lidl'),
    ('Łowicz', 'Dżem truskawkowy', 'Stokrotka'),
    ('Łowicz', 'Dżem Porzeczka', 'Lidl'),
    ('Herbapol', 'Powidła wegierkowe', 'Auchan'),
    ('Rapsodia', 'Dżem czarna porzeczka', 'Biedronka'),
    ('Rapsodia', 'Produkt owocowy z brzoskwiń.', 'Biedronka'),
    ('Rapsodia', 'Dżem wiśniowy', 'Biedronka'),
    ('Rapsodia', 'Powidła węgierkowe', 'Biedronka'),
    ('Herbapol', 'Konfitura z malin ekstra o obniżonej zawartości cukru', 'Auchan'),
    ('Herbapol', 'Konfitura ekstra z truskawek o obniżonej zawartości cukru.', 'Auchan'),
    ('Raspodia', 'Dżem wiśniowy', 'Biedronka'),
    ('Herbapol', 'Dżem z Czarnych Porzeczek', 'Kaufland'),
    ('Dawtona', 'Powidła śliwkowe', 'Dino'),
    ('Famil-Jada', 'Dżem z czarnej porzeczki niskosłodzony', 'Dino'),
    ('Łowicz', 'Dżem truskawkowy niskosłodzony.', 'Biedronka'),
    ('Miedzychód', 'Powidła śliwkowe', 'Biedronka'),
    ('Biedronka', 'Dżem z pomarańczy', 'Biedronka'),
    ('Dawtona', 'Dżem Brzoskwiniowy niskosłodzony', 'Dino'),
    ('Łowicz', 'Dżem z truskawek i limonki niskosłodzony.', 'Dino'),
    ('Rapsodia', 'Dżem z czarnego bzu', 'Biedronka'),
    ('Krokus', 'Powidła śliwkowe', 'Biedronka'),
    ('Łaciate', 'Łaciaty serek śmietankowy', 'Żabka'),
    ('Łaciate', 'Łaciaty serek śmietankowy', 'Stokrotka'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Biedronka'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Lidl'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Żabka'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Auchan'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Carrefour'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'Stokrotka'),
    ('Piątnica', 'Serek Wiejski że szczypiorkiem', 'Żabka'),
    ('Go Vege', 'Krem z orzeszków ziemnych z kawałkami', 'Biedronka'),
    ('Biedronka', 'Serek śmietankowy ze szczypiorkiem', 'Biedronka'),
    ('Kruszwica', 'Smakowita maślany smak', 'Tesco'),
    ('Sante', 'Masło orzechowe', 'Kaufland'),
    ('Mlekpol', 'Łaciaty z czosnkiem', 'Auchan'),
    ('Go Vege', 'Paprykarz warzywny z kaszą jaglaną', 'Biedronka'),
    ('ZT Bielmar', 'Margaryna półtłusta 40 %. Do smarowania.', 'Biedronka'),
    ('Salato', 'Sałatka warzywna z jajkiem', 'Biedronka'),
    ('Go Vege', 'Pasta warzywna - biała fasola, siemię lniane', 'Biedronka'),
    ('Go vege', 'Pasta słonecznikowa z pomidorami', 'Biedronka'),
    ('Mlekpol', 'Mlemix Zambrowski mix tłuszczowy do smarowania 68% tłuszczu', 'Auchan'),
    ('Vitanella', 'Muesli z owocami i siemieniem lnianym', 'Biedronka'),
    ('Vitanella', 'Banana Chocolate musli', 'Biedronka'),
    ('One day more', 'Muesli Protein', 'Lidl'),
    ('Vitanella', 'Musli premium', 'Biedronka'),
    ('Inna Bajka', 'Owsianka Mango i Jagody Goji', 'Żabka'),
    ('Inna Bajka', 'Owsianka Mango i Jagody Goji', 'Carrefour'),
    ('Vitanella', 'Musli z owocami i orzechami', 'Biedronka'),
    ('Bell''s', 'Owsianka owoce i orzechy', 'Netto'),
    ('Inna Bajka', 'Musli Marakuja i Pitaja', 'Biedronka'),
    ('Dawtona', 'Eperdzsem', 'Dino'),
    ('Piątnica', 'Serek Wiejski', 'Biedronka'),
    ('Piątnica', 'Serek Wiejski', 'Żabka'),
    ('Piątnica', 'Serek Wiejski', 'Auchan'),
    ('Go On', 'Peanut Butter Smooth', 'Lidl'),
    ('Piątnica', 'Low Fat Cottage Cheese', 'Żabka'),
    ('Piątnica', 'Cottage Cheese With Strawberry', 'Biedronka'),
    ('Go Active', 'Almond butter', 'Biedronka'),
    ('Go Active', 'Cashew butter', 'Biedronka'),
    ('Sante', 'Pasztet z pomidorami sojowy', 'Żabka'),
    ('Sante', 'Pasztet z pomidorami sojowy', 'Lewiatan'),
    ('Nuss milki', 'Krem orzechowo-kakaowy bez cukru i oleju palmowego', 'Biedronka'),
    ('Primavika', 'Tahini', 'Carrefour'),
    ('Lisner', 'Boczniaki w sosie musztardowym', 'Biedronka'),
    ('Tesco', 'Musli prażone z kawałkami suszonych i kandyzowanych owoców.', 'Tesco'),
    ('Wasa', 'Pieczywo z pełnoziarnistej mąki żytniej', 'Biedronka'),
    ('Wasa', 'Wasa Pieczywo chrupkie z błonnikiem', 'Stokrotka'),
    ('Maribel - Lidl', 'Dżem z czarnej porzeczki', 'Lidl'),
    ('Maribel', 'Dżem wiśniowy o obniżonej zawartości cukrów', 'Lidl'),
    ('Unknown', 'Masło orzechowe crunchy', 'Biedronka'),
    ('Kasia', 'Kasia - Najlepsza do pieczenia i smażenia', 'Biedronka'),
    ('Lunter', 'Smalczyk roślinny z tofu z cebulką', 'Kaufland'),
    ('Salato', 'Pasta z tuńczykiem', 'Biedronka')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'PL' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Breakfast & Grain-Based' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'PL' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
