-- PIPELINE (Breakfast & Grain-Based): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi oraz kandyzowanymi owocami', 'C'),
    ('Vitanella', 'Granola z kawałkami czekolady, prażonymi orzeszkami ziemnymi ilaskowymi', 'D'),
    ('Vitanella', 'Musli prażone z suszoną, słodzoną żurawiną.', 'C'),
    ('Biedronka', 'Vitanella Granola z czekoladą', 'D'),
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi owocami oraz kawałkami prażonych orzeszków laskowych', 'B'),
    ('Biedronka', 'Mieszanka płatków zbożowych z rodzynkami i orzechami laskowymi', 'A'),
    ('Bakalland', 'Musli chrupkie klasyczne z dodatkiem wiórków kokosowych', 'D'),
    ('Vitanella', 'Płatki zbożowe z suszonymi i kandyzowanymi owocami.', 'C'),
    ('Melvit', 'CRISPY PIECZYWO CHRUPKIE z serem i cebulką', 'C'),
    ('Łowicz', 'Dżem truskawkowy', 'D'),
    ('Łowicz', 'Dżem Porzeczka', 'UNKNOWN'),
    ('Herbapol', 'Powidła wegierkowe', 'D'),
    ('Rapsodia', 'Dżem czarna porzeczka', 'UNKNOWN'),
    ('Rapsodia', 'Produkt owocowy z brzoskwiń.', 'C'),
    ('Rapsodia', 'Dżem wiśniowy', 'C'),
    ('Rapsodia', 'Powidła węgierkowe', 'D'),
    ('Herbapol', 'Konfitura z malin ekstra o obniżonej zawartości cukru', 'C'),
    ('Herbapol', 'Konfitura ekstra z truskawek o obniżonej zawartości cukru.', 'D'),
    ('Raspodia', 'Dżem wiśniowy', 'C'),
    ('Herbapol', 'Dżem z Czarnych Porzeczek', 'UNKNOWN'),
    ('Dawtona', 'Powidła śliwkowe', 'D'),
    ('Famil-Jada', 'Dżem z czarnej porzeczki niskosłodzony', 'C'),
    ('Łowicz', 'Dżem truskawkowy niskosłodzony.', 'D'),
    ('Miedzychód', 'Powidła śliwkowe', 'D'),
    ('Biedronka', 'Dżem z pomarańczy', 'D'),
    ('Dawtona', 'Dżem Brzoskwiniowy niskosłodzony', 'C'),
    ('Łowicz', 'Dżem z truskawek i limonki niskosłodzony.', 'C'),
    ('Rapsodia', 'Dżem z czarnego bzu', 'C'),
    ('Krokus', 'Powidła śliwkowe', 'C'),
    ('Łaciate', 'Łaciaty serek śmietankowy', 'D'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', 'A'),
    ('Piątnica', 'Serek Wiejski że szczypiorkiem', 'C'),
    ('Go Vege', 'Krem z orzeszków ziemnych z kawałkami', 'A'),
    ('Biedronka', 'Serek śmietankowy ze szczypiorkiem', 'D'),
    ('Kruszwica', 'Smakowita maślany smak', 'C'),
    ('Sante', 'Masło orzechowe', 'C'),
    ('Mlekpol', 'Łaciaty z czosnkiem', 'D'),
    ('Go Vege', 'Paprykarz warzywny z kaszą jaglaną', 'C'),
    ('ZT Bielmar', 'Margaryna półtłusta 40 %. Do smarowania.', 'D'),
    ('Salato', 'Sałatka warzywna z jajkiem', 'C'),
    ('Go Vege', 'Pasta warzywna - biała fasola, siemię lniane', 'C'),
    ('Go vege', 'Pasta słonecznikowa z pomidorami', 'C'),
    ('Mlekpol', 'Mlemix Zambrowski mix tłuszczowy do smarowania 68% tłuszczu', 'D'),
    ('Vitanella', 'Musli 5 zbóż', 'A'),
    ('Fitella', 'Musli chrupkie bananowe z kawałkami czekolady', 'D'),
    ('Kupiec', 'Coś na ząb owsianka z jabłkiem i bananem', 'A'),
    ('Biedronka', 'Vitanella Owsianka - śliwka, migdał, żurawina', 'UNKNOWN'),
    ('Go Active', 'Musli wyobiałkowe', 'C'),
    ('Kupiec', 'Owsianka z jabłkiem i cynamonem', 'A'),
    ('Vivi Polska', 'Musli owocowe pożywne śniadanie.', 'B'),
    ('Go Bio', 'Musli z czekoladą i orzechami', 'C'),
    ('Kupiec', 'Coś na Ząb', 'A'),
    ('One Day More', 'Musli z suszonymi figami i prażonymi orzeszkami ziemnymi.', 'A'),
    ('Brüggen', 'Płatki owsiane z suszonymi owocami i orzechami', 'A'),
    ('Brüggen', 'Płatki owsiane z mlekiem w proszku odtłuszczonym, kawałkami białej czekolady i liofilizowanych malin.', 'C'),
    ('OneDayMore', 'Musli z malinami i jeżynami', 'A'),
    ('Promienie Słońca', 'Promienie Słońca Słoneczna granola z orzechami i miodem', 'C'),
    ('OneDayMore', 'Musli z truskawkami, czerwonymi porzeczkami i czekoladą mleczna', 'C'),
    ('Pano', 'Pieczywo żytnie chrupkie', 'UNKNOWN'),
    ('Łowicz', 'Dżem czarna i czerwoną porzeczka', 'UNKNOWN'),
    ('Lidl', 'Dżem truskawkowy Rapsodia', 'UNKNOWN'),
    ('Łowicz', 'Łowicz - Dżem Wiśniowy', 'D'),
    ('Łowicz', 'Extra konfitura z wiśni', 'D'),
    ('Łowicz', 'Dżem 100% z owoców wiśnia', 'C'),
    ('Rapsodia', 'Dżem truskawkowy', 'UNKNOWN'),
    ('Rapsodia', 'Dżem malinowy', 'UNKNOWN'),
    ('Łowicz', 'Dżem Dobry! Truskawa z czerwoną porzeczką', 'C'),
    ('Herbapol', 'Dżem truskawkowy', 'C'),
    ('Łowicz', 'Konfitura z żółtych owoców', 'D'),
    ('Łowicz', 'Dżem brzoskwiniowy super gładki', 'C'),
    ('Łowicz', 'Dżem Malinowy', 'C'),
    ('Łowicz', 'Dżem brzoskwiniowy', 'UNKNOWN'),
    ('Materne', 'Konfitura truskawkowa niskosłodzona', 'C'),
    ('Międzychód', 'Dżem malinowy', 'D'),
    ('Unknown', 'Konfitura z czarnych owoców', 'D'),
    ('Dobra Nasza!', 'Dżem malinowy niskosłodzony', 'C'),
    ('Dobra Nasza!', 'Dżem wiśniowy o obniżonej zawartości cukrów', 'C'),
    ('Stovit', 'Marmolada o smaku różanym', 'D'),
    ('Mirella', 'Powidła śliwkowe', 'D'),
    ('Łowicz', 'Dżem malinowy z czerwoną porzeczką', 'C'),
    ('Łowicz', 'Dżem z wiśni', 'C'),
    ('Międzychód', 'Dżem z czarnych porzeczek', 'D'),
    ('Laciaty', 'Serek puszysty naturalny Łaciaty', 'D'),
    ('Wawrzyniec', 'Pasta warzywna z suszonymi pomidorami i żurawiną', 'C'),
    ('Dega', 'Paprykarz z łososia', 'C'),
    ('Mlekpol', 'Miks tłuszczowy do smarowania 68%.', 'D'),
    ('Lisner', 'Pastella - pasta z łososia', 'E'),
    ('Wawrzyniec', 'Wawrzyniec ze słodką cebulką i suszonymi pomidorami', 'C'),
    ('Bielmar', 'Beskidzki miks o zmniejszonej zawartości tłuszczu', 'D'),
    ('Kruszwica', 'Wawrzyniec - Pasta warzywna z ciecierzycą, pieprzem i czarnuszką', 'C'),
    ('Łowicz', 'Pasta warzywna bakłażan & suszone pomidory', 'C'),
    ('Go vege', 'Pasta słonecznikowa z papryką', 'C'),
    ('Łowicz', 'ONEPLAN FROGS ast masła! Smaruj zamiast maslo! 100', 'A'),
    ('Wawrzyniec', 'Pasztet z fasoli z cebulą, pieprzem i czarnuszką', 'A'),
    ('Auchan', 'Pasta z prażonych orzechów nerkowca', 'B'),
    ('Go Active/Sante', 'Peanut Butter wysokobiałkowy', 'A'),
    ('Smakowita', 'Margaryna półtłusta 39%', 'C'),
    ('Lovege', 'Paprykarz z kaszą jaglaną', 'C'),
    ('Sante', 'FILETY ŚLEDZIOWE Lisner Sante Pasztet Sonda 554, 0', 'C'),
    ('Masmix', 'Masmix klasyczny z masłem', 'UNKNOWN'),
    ('Lovege', 'Pasztet z soczewicą', 'B'),
    ('Smakowita', 'Pasta z ziaren fasoli z czerwoną papryką', 'A'),
    ('Sante', 'Pasztet z papryką sojowy', 'C'),
    ('Sante', 'Pasta warzywna meksykańska', 'C'),
    ('Vitanella', 'Muesli z owocami i siemieniem lnianym', 'C'),
    ('Vitanella', 'Granola z czekoladą i orzechami', 'C'),
    ('Vitanella', 'Banana Chocolate musli', 'D'),
    ('One day more', 'Muesli Protein', 'C'),
    ('Vitanella', 'Musli premium', 'D'),
    ('Inna Bajka', 'Owsianka Mango i Jagody Goji', 'B'),
    ('Vitanella', 'Musli z owocami i orzechami', 'D'),
    ('Bell''s', 'Owsianka owoce i orzechy', 'A'),
    ('Inna Bajka', 'Musli Marakuja i Pitaja', 'UNKNOWN'),
    ('Dobra Kaloria', 'Owsianka królewska z jabłkiem', 'UNKNOWN'),
    ('Rapsodia', 'Dżem wiśniowy o obniżonej zawartości cukru', 'C'),
    ('Łowicz', 'Dżem z agrestu i kiwi', 'UNKNOWN'),
    ('Rolnik', 'Borówka cala', 'C'),
    ('Rapsodia', 'Konfitura ekstra wiśniowa słodzona miodem', 'UNKNOWN'),
    ('Rapsodia', 'Dżem brzoskwiniowy', 'UNKNOWN'),
    ('Dawtona', 'Eperdzsem', 'C'),
    ('Rapsodia', 'Konfitura ekstra truskawkowa słodzona miodem', 'C'),
    ('Piątnica', 'Serek Wiejski', 'C'),
    ('Go On', 'Peanut Butter Smooth', 'A'),
    ('Piątnica', 'Low Fat Cottage Cheese', 'B'),
    ('Piątnica', 'Cottage Cheese With Strawberry', 'C'),
    ('Go Active', 'Almond butter', 'A'),
    ('Go Active', 'Cashew butter', 'A'),
    ('Sante', 'Pasztet z pomidorami sojowy', 'C'),
    ('Nuss milki', 'Krem orzechowo-kakaowy bez cukru i oleju palmowego', 'D'),
    ('Primavika', 'Tahini', 'D'),
    ('Lisner', 'Boczniaki w sosie musztardowym', 'D'),
    ('Sante', 'Granola chocolate / pieces of chocolate', 'D'),
    ('Vitanella', 'Granola z kakao i orzechami', 'A'),
    ('Vitanella', 'Owsianka z owocami bez dodatku curku', 'C'),
    ('One Day More', 'Muesli chocolat', 'C'),
    ('Vitanella', 'Owsianka ananas, kokos', 'D'),
    ('Sante', 'Granola Nut / peanuts & peanut butter', 'D'),
    ('One Day More', 'Meusli Fruits et Chocolat Blanc', 'C'),
    ('Vitanella', 'Muesli z owocami i orzechami', 'UNKNOWN'),
    ('Sante', 'Sante fit granola strawberry and cherry', 'B'),
    ('Santé', 'Sante Crunchy Crispy Muesli Banana With Chocolate 350G', 'D'),
    ('Nestlé', 'Musli tropical', 'C'),
    ('Bell''s', 'Crunchy', 'C'),
    ('One Day More', 'Porridge Orange', 'A'),
    ('BakallanD', 'Granola klasyczna z kokosem', 'C'),
    ('Biedronka', 'Granola', 'C'),
    ('One Day More', 'Muesli for focused ones', 'A'),
    ('Kupiec', 'Cosnazab', 'A'),
    ('Promienie słońca', 'Baton musli z owocami', 'B'),
    ('Promienie słońca', 'Baton musli z orzechami i miodem', 'B'),
    ('Purella', 'Purella Super Musli Proteinowe', 'C'),
    ('Purella Superfoods', 'Purella superfoods granola', 'A'),
    ('One Day More', 'Granola with salty caramel and white chocolate', 'C'),
    ('Go on', 'Protein granola', 'A'),
    ('Nestlé', 'Musli classic', 'C'),
    ('Kupiec', 'Cos na Zab', 'A'),
    ('Sante', 'Musli Lo z owocami', 'C'),
    ('Bell''s', 'Owsianka', 'A'),
    ('Go On', 'Protein Granola Go On', 'A'),
    ('Vivi', 'Musli owocowe: polskie owoce', 'C'),
    ('OneDayMore', 'Musli Keto Choco', 'C'),
    ('Tesco', 'Musli prażone z kawałkami suszonych i kandyzowanych owoców.', 'E'),
    ('One day more', 'Fruit Granola', 'A'),
    ('Bifood', 'Muesli crunchy', 'D'),
    ('Wasa', 'Pieczywo z pełnoziarnistej mąki żytniej', 'A'),
    ('Wasa', 'Wasa Pieczywo chrupkie z błonnikiem', 'A'),
    ('Lestello', 'Chickpea cakes', 'B'),
    ('Melvit', 'Pieczywo chrupkie', 'E'),
    ('Yeemy', 'Pancakes z sosem malinowym', 'C'),
    ('Dr. Oetker', 'Protein Pancakes', 'UNKNOWN'),
    ('Łowicz', 'Strawberry Jam', 'C'),
    ('Maribel - Lidl', 'Dżem z czarnej porzeczki', 'C'),
    ('Allnutrition', 'Frulove strawberry & raspberry with chia', 'A'),
    ('Łowicz', 'Blackcurrant jam', 'C'),
    ('Łowicz', 'Dzem z czarnych porzeczek', 'C'),
    ('Łowicz', 'Confiture from blackcurrant', 'C'),
    ('Maribel', 'Dżem wiśniowy o obniżonej zawartości cukrów', 'C'),
    ('Pięć Przemian', 'Konfitura jagodowa', 'B'),
    ('Łowicz', 'Extra confiture', 'C'),
    ('Go On', 'Peanut Butter Crunchy', 'A'),
    ('GoVege', 'Peanut Butter', 'A'),
    ('Unknown', 'Masło orzechowe crunchy', 'C'),
    ('Kasia', 'Kasia - Najlepsza do pieczenia i smażenia', 'D'),
    ('Dobra Kaloria', 'Pasztet z pomidorami pieczony', 'D'),
    ('Lunter', 'Smalczyk roślinny z tofu z cebulką', 'C'),
    ('Nutrition', 'Peanut butter', 'UNKNOWN'),
    ('Felix', 'Crunchy peanut butter', 'A'),
    ('Felix', 'Creamy Peanut Butter', 'A'),
    ('Alpi', 'Basia Basia Pistacjolada', 'B'),
    ('Go On', 'PROTEIN peanut butter - salted caramel flavour', 'B'),
    ('Polonaise', 'Polonaise Chrzan Tarty', 'C'),
    ('Go On', 'Go On peanut butter', 'A'),
    ('Salato', 'Pasta z tuńczykiem', 'UNKNOWN'),
    ('Auchan', 'Peanut Paste Crunchy', 'A'),
    ('I love vege', 'Paprykarz warzywny', 'C'),
    ('Go on', 'Protein white cream and peanut butter', 'UNKNOWN'),
    ('Społem Kielce', 'Chrzan luksusowy', 'D'),
    ('CD miody & kremy', 'Kokosowe Love', 'E'),
    ('Prymat', 'Chrzan tarty', 'C'),
    ('Lumiko', 'Butter with 3/4 fat content', 'E')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi oraz kandyzowanymi owocami', '4'),
    ('Vitanella', 'Granola z kawałkami czekolady, prażonymi orzeszkami ziemnymi ilaskowymi', '4'),
    ('Vitanella', 'Musli prażone z suszoną, słodzoną żurawiną.', '4'),
    ('Biedronka', 'Vitanella Granola z czekoladą', '4'),
    ('Vitanella', 'Mieszanka płatków zbożowych z suszonymi owocami oraz kawałkami prażonych orzeszków laskowych', '4'),
    ('Biedronka', 'Mieszanka płatków zbożowych z rodzynkami i orzechami laskowymi', '4'),
    ('Bakalland', 'Musli chrupkie klasyczne z dodatkiem wiórków kokosowych', '4'),
    ('Vitanella', 'Płatki zbożowe z suszonymi i kandyzowanymi owocami.', '4'),
    ('Melvit', 'CRISPY PIECZYWO CHRUPKIE z serem i cebulką', '4'),
    ('Łowicz', 'Dżem truskawkowy', '4'),
    ('Łowicz', 'Dżem Porzeczka', '4'),
    ('Herbapol', 'Powidła wegierkowe', '3'),
    ('Rapsodia', 'Dżem czarna porzeczka', '4'),
    ('Rapsodia', 'Produkt owocowy z brzoskwiń.', '4'),
    ('Rapsodia', 'Dżem wiśniowy', '4'),
    ('Rapsodia', 'Powidła węgierkowe', '4'),
    ('Herbapol', 'Konfitura z malin ekstra o obniżonej zawartości cukru', '4'),
    ('Herbapol', 'Konfitura ekstra z truskawek o obniżonej zawartości cukru.', '4'),
    ('Raspodia', 'Dżem wiśniowy', '4'),
    ('Herbapol', 'Dżem z Czarnych Porzeczek', '4'),
    ('Dawtona', 'Powidła śliwkowe', '4'),
    ('Famil-Jada', 'Dżem z czarnej porzeczki niskosłodzony', '4'),
    ('Łowicz', 'Dżem truskawkowy niskosłodzony.', '4'),
    ('Miedzychód', 'Powidła śliwkowe', '3'),
    ('Biedronka', 'Dżem z pomarańczy', '4'),
    ('Dawtona', 'Dżem Brzoskwiniowy niskosłodzony', '4'),
    ('Łowicz', 'Dżem z truskawek i limonki niskosłodzony.', '4'),
    ('Rapsodia', 'Dżem z czarnego bzu', '4'),
    ('Krokus', 'Powidła śliwkowe', '4'),
    ('Łaciate', 'Łaciaty serek śmietankowy', '4'),
    ('Piatnica', 'Serek Wiejski wysokobiałkowy', '4'),
    ('Piątnica', 'Serek Wiejski że szczypiorkiem', '4'),
    ('Go Vege', 'Krem z orzeszków ziemnych z kawałkami', '1'),
    ('Biedronka', 'Serek śmietankowy ze szczypiorkiem', '4'),
    ('Kruszwica', 'Smakowita maślany smak', '4'),
    ('Sante', 'Masło orzechowe', '4'),
    ('Mlekpol', 'Łaciaty z czosnkiem', '4'),
    ('Go Vege', 'Paprykarz warzywny z kaszą jaglaną', '4'),
    ('ZT Bielmar', 'Margaryna półtłusta 40 %. Do smarowania.', '4'),
    ('Salato', 'Sałatka warzywna z jajkiem', '3'),
    ('Go Vege', 'Pasta warzywna - biała fasola, siemię lniane', '3'),
    ('Go vege', 'Pasta słonecznikowa z pomidorami', '3'),
    ('Mlekpol', 'Mlemix Zambrowski mix tłuszczowy do smarowania 68% tłuszczu', '4'),
    ('Vitanella', 'Musli 5 zbóż', '1'),
    ('Fitella', 'Musli chrupkie bananowe z kawałkami czekolady', '4'),
    ('Kupiec', 'Coś na ząb owsianka z jabłkiem i bananem', '4'),
    ('Biedronka', 'Vitanella Owsianka - śliwka, migdał, żurawina', '1'),
    ('Go Active', 'Musli wyobiałkowe', '4'),
    ('Kupiec', 'Owsianka z jabłkiem i cynamonem', '4'),
    ('Vivi Polska', 'Musli owocowe pożywne śniadanie.', '1'),
    ('Go Bio', 'Musli z czekoladą i orzechami', '3'),
    ('Kupiec', 'Coś na Ząb', '4'),
    ('One Day More', 'Musli z suszonymi figami i prażonymi orzeszkami ziemnymi.', '3'),
    ('Brüggen', 'Płatki owsiane z suszonymi owocami i orzechami', '1'),
    ('Brüggen', 'Płatki owsiane z mlekiem w proszku odtłuszczonym, kawałkami białej czekolady i liofilizowanych malin.', '4'),
    ('OneDayMore', 'Musli z malinami i jeżynami', '3'),
    ('Promienie Słońca', 'Promienie Słońca Słoneczna granola z orzechami i miodem', '4'),
    ('OneDayMore', 'Musli z truskawkami, czerwonymi porzeczkami i czekoladą mleczna', '3'),
    ('Pano', 'Pieczywo żytnie chrupkie', '3'),
    ('Łowicz', 'Dżem czarna i czerwoną porzeczka', '4'),
    ('Lidl', 'Dżem truskawkowy Rapsodia', '4'),
    ('Łowicz', 'Łowicz - Dżem Wiśniowy', '4'),
    ('Łowicz', 'Extra konfitura z wiśni', '4'),
    ('Łowicz', 'Dżem 100% z owoców wiśnia', '4'),
    ('Rapsodia', 'Dżem truskawkowy', '4'),
    ('Rapsodia', 'Dżem malinowy', '4'),
    ('Łowicz', 'Dżem Dobry! Truskawa z czerwoną porzeczką', '4'),
    ('Herbapol', 'Dżem truskawkowy', '4'),
    ('Łowicz', 'Konfitura z żółtych owoców', '4'),
    ('Łowicz', 'Dżem brzoskwiniowy super gładki', '4'),
    ('Łowicz', 'Dżem Malinowy', '4'),
    ('Łowicz', 'Dżem brzoskwiniowy', '4'),
    ('Materne', 'Konfitura truskawkowa niskosłodzona', '4'),
    ('Międzychód', 'Dżem malinowy', '4'),
    ('Unknown', 'Konfitura z czarnych owoców', '4'),
    ('Dobra Nasza!', 'Dżem malinowy niskosłodzony', '4'),
    ('Dobra Nasza!', 'Dżem wiśniowy o obniżonej zawartości cukrów', '4'),
    ('Stovit', 'Marmolada o smaku różanym', '3'),
    ('Mirella', 'Powidła śliwkowe', '4'),
    ('Łowicz', 'Dżem malinowy z czerwoną porzeczką', '4'),
    ('Łowicz', 'Dżem z wiśni', '4'),
    ('Międzychód', 'Dżem z czarnych porzeczek', '4'),
    ('Laciaty', 'Serek puszysty naturalny Łaciaty', '4'),
    ('Wawrzyniec', 'Pasta warzywna z suszonymi pomidorami i żurawiną', '3'),
    ('Dega', 'Paprykarz z łososia', '4'),
    ('Mlekpol', 'Miks tłuszczowy do smarowania 68%.', '4'),
    ('Lisner', 'Pastella - pasta z łososia', '4'),
    ('Wawrzyniec', 'Wawrzyniec ze słodką cebulką i suszonymi pomidorami', '3'),
    ('Bielmar', 'Beskidzki miks o zmniejszonej zawartości tłuszczu', '4'),
    ('Kruszwica', 'Wawrzyniec - Pasta warzywna z ciecierzycą, pieprzem i czarnuszką', '3'),
    ('Łowicz', 'Pasta warzywna bakłażan & suszone pomidory', '3'),
    ('Go vege', 'Pasta słonecznikowa z papryką', '3'),
    ('Łowicz', 'ONEPLAN FROGS ast masła! Smaruj zamiast maslo! 100', '3'),
    ('Wawrzyniec', 'Pasztet z fasoli z cebulą, pieprzem i czarnuszką', '3'),
    ('Auchan', 'Pasta z prażonych orzechów nerkowca', '1'),
    ('Go Active/Sante', 'Peanut Butter wysokobiałkowy', '4'),
    ('Smakowita', 'Margaryna półtłusta 39%', '4'),
    ('Lovege', 'Paprykarz z kaszą jaglaną', '4'),
    ('Sante', 'FILETY ŚLEDZIOWE Lisner Sante Pasztet Sonda 554, 0', '4'),
    ('Masmix', 'Masmix klasyczny z masłem', '4'),
    ('Lovege', 'Pasztet z soczewicą', '4'),
    ('Smakowita', 'Pasta z ziaren fasoli z czerwoną papryką', '3'),
    ('Sante', 'Pasztet z papryką sojowy', '4'),
    ('Sante', 'Pasta warzywna meksykańska', '4'),
    ('Vitanella', 'Muesli z owocami i siemieniem lnianym', '3'),
    ('Vitanella', 'Granola z czekoladą i orzechami', '4'),
    ('Vitanella', 'Banana Chocolate musli', '4'),
    ('One day more', 'Muesli Protein', '3'),
    ('Vitanella', 'Musli premium', '3'),
    ('Inna Bajka', 'Owsianka Mango i Jagody Goji', '3'),
    ('Vitanella', 'Musli z owocami i orzechami', '4'),
    ('Bell''s', 'Owsianka owoce i orzechy', '1'),
    ('Inna Bajka', 'Musli Marakuja i Pitaja', '1'),
    ('Dobra Kaloria', 'Owsianka królewska z jabłkiem', '4'),
    ('Rapsodia', 'Dżem wiśniowy o obniżonej zawartości cukru', '4'),
    ('Łowicz', 'Dżem z agrestu i kiwi', '4'),
    ('Rolnik', 'Borówka cala', '4'),
    ('Rapsodia', 'Konfitura ekstra wiśniowa słodzona miodem', '4'),
    ('Rapsodia', 'Dżem brzoskwiniowy', '4'),
    ('Dawtona', 'Eperdzsem', '4'),
    ('Rapsodia', 'Konfitura ekstra truskawkowa słodzona miodem', '4'),
    ('Piątnica', 'Serek Wiejski', '3'),
    ('Go On', 'Peanut Butter Smooth', '1'),
    ('Piątnica', 'Low Fat Cottage Cheese', '4'),
    ('Piątnica', 'Cottage Cheese With Strawberry', '4'),
    ('Go Active', 'Almond butter', '1'),
    ('Go Active', 'Cashew butter', '1'),
    ('Sante', 'Pasztet z pomidorami sojowy', '4'),
    ('Nuss milki', 'Krem orzechowo-kakaowy bez cukru i oleju palmowego', '4'),
    ('Primavika', 'Tahini', '1'),
    ('Lisner', 'Boczniaki w sosie musztardowym', '4'),
    ('Sante', 'Granola chocolate / pieces of chocolate', '4'),
    ('Vitanella', 'Granola z kakao i orzechami', '4'),
    ('Vitanella', 'Owsianka z owocami bez dodatku curku', '4'),
    ('One Day More', 'Muesli chocolat', '4'),
    ('Vitanella', 'Owsianka ananas, kokos', '3'),
    ('Sante', 'Granola Nut / peanuts & peanut butter', '4'),
    ('One Day More', 'Meusli Fruits et Chocolat Blanc', '4'),
    ('Vitanella', 'Muesli z owocami i orzechami', '4'),
    ('Sante', 'Sante fit granola strawberry and cherry', '4'),
    ('Santé', 'Sante Crunchy Crispy Muesli Banana With Chocolate 350G', '4'),
    ('Nestlé', 'Musli tropical', '4'),
    ('Bell''s', 'Crunchy', '4'),
    ('One Day More', 'Porridge Orange', '4'),
    ('BakallanD', 'Granola klasyczna z kokosem', '3'),
    ('Biedronka', 'Granola', '4'),
    ('One Day More', 'Muesli for focused ones', '4'),
    ('Kupiec', 'Cosnazab', '4'),
    ('Promienie słońca', 'Baton musli z owocami', '4'),
    ('Promienie słońca', 'Baton musli z orzechami i miodem', '4'),
    ('Purella', 'Purella Super Musli Proteinowe', '4'),
    ('Purella Superfoods', 'Purella superfoods granola', '4'),
    ('One Day More', 'Granola with salty caramel and white chocolate', '4'),
    ('Go on', 'Protein granola', '4'),
    ('Nestlé', 'Musli classic', '4'),
    ('Kupiec', 'Cos na Zab', '4'),
    ('Sante', 'Musli Lo z owocami', '4'),
    ('Bell''s', 'Owsianka', '4'),
    ('Go On', 'Protein Granola Go On', '4'),
    ('Vivi', 'Musli owocowe: polskie owoce', '1'),
    ('OneDayMore', 'Musli Keto Choco', '4'),
    ('Tesco', 'Musli prażone z kawałkami suszonych i kandyzowanych owoców.', '4'),
    ('One day more', 'Fruit Granola', '1'),
    ('Bifood', 'Muesli crunchy', '4'),
    ('Wasa', 'Pieczywo z pełnoziarnistej mąki żytniej', '1'),
    ('Wasa', 'Wasa Pieczywo chrupkie z błonnikiem', '3'),
    ('Lestello', 'Chickpea cakes', '3'),
    ('Melvit', 'Pieczywo chrupkie', '4'),
    ('Yeemy', 'Pancakes z sosem malinowym', '4'),
    ('Dr. Oetker', 'Protein Pancakes', '4'),
    ('Łowicz', 'Strawberry Jam', '4'),
    ('Maribel - Lidl', 'Dżem z czarnej porzeczki', '4'),
    ('Allnutrition', 'Frulove strawberry & raspberry with chia', '4'),
    ('Łowicz', 'Blackcurrant jam', '4'),
    ('Łowicz', 'Dzem z czarnych porzeczek', '4'),
    ('Łowicz', 'Confiture from blackcurrant', '4'),
    ('Maribel', 'Dżem wiśniowy o obniżonej zawartości cukrów', '4'),
    ('Pięć Przemian', 'Konfitura jagodowa', '4'),
    ('Łowicz', 'Extra confiture', '4'),
    ('Go On', 'Peanut Butter Crunchy', '1'),
    ('GoVege', 'Peanut Butter', '1'),
    ('Unknown', 'Masło orzechowe crunchy', '4'),
    ('Kasia', 'Kasia - Najlepsza do pieczenia i smażenia', '4'),
    ('Dobra Kaloria', 'Pasztet z pomidorami pieczony', '4'),
    ('Lunter', 'Smalczyk roślinny z tofu z cebulką', '4'),
    ('Nutrition', 'Peanut butter', '4'),
    ('Felix', 'Crunchy peanut butter', '3'),
    ('Felix', 'Creamy Peanut Butter', '3'),
    ('Alpi', 'Basia Basia Pistacjolada', '3'),
    ('Go On', 'PROTEIN peanut butter - salted caramel flavour', '4'),
    ('Polonaise', 'Polonaise Chrzan Tarty', '3'),
    ('Go On', 'Go On peanut butter', '1'),
    ('Salato', 'Pasta z tuńczykiem', '4'),
    ('Auchan', 'Peanut Paste Crunchy', '1'),
    ('I love vege', 'Paprykarz warzywny', '4'),
    ('Go on', 'Protein white cream and peanut butter', '4'),
    ('Społem Kielce', 'Chrzan luksusowy', '4'),
    ('CD miody & kremy', 'Kokosowe Love', '4'),
    ('Prymat', 'Chrzan tarty', '4'),
    ('Lumiko', 'Butter with 3/4 fat content', '2')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Breakfast & Grain-Based', 100, 'PL');
