-- PIPELINE (Dairy): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-04

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Milsani', 'Frischkäse natur', 'Aldi'),
    ('Gervais', 'Hüttenkäse Original', 'Edeka'),
    ('Gervais', 'Hüttenkäse Original', 'REWE'),
    ('Gervais', 'Hüttenkäse Original', 'Tegut'),
    ('Milsani', 'Körniger Frischkäse, Halbfettstufe', 'Aldi'),
    ('Almette', 'Almette Kräuter', 'Edeka'),
    ('Almette', 'Almette Kräuter', 'REWE'),
    ('Almette', 'Almette Kräuter', 'Netto'),
    ('Almette', 'Almette Kräuter', 'Tegut'),
    ('Bergader', 'Bergbauern mild nussig Käse', 'REWE'),
    ('Bergader', 'Bergbauern mild nussig Käse', 'Penny'),
    ('Bergader', 'Bergbauern mild nussig Käse', 'Real'),
    ('Bergader', 'Bergbauern mild nussig Käse', 'Norma'),
    ('DOVGAN Family', 'Körniger Frischkäse 33 % Fett', 'Lidl'),
    ('BMI Biobauern', 'Bio-Landkäse mild-nussig', 'Lidl'),
    ('Dr. Oetker', 'High Protein Pudding Grieß', 'Lidl'),
    ('Milsan', 'Grießpudding High-Protein - Zimt', 'Aldi'),
    ('Milram', 'Frühlingsquark Original', 'Aldi'),
    ('Milram', 'Frühlingsquark Original', 'Lidl'),
    ('Milram', 'Frühlingsquark Original', 'Edeka'),
    ('Milram', 'Frühlingsquark Original', 'REWE'),
    ('Milram', 'Frühlingsquark Original', 'Netto'),
    ('Milram', 'Frühlingsquark Original', 'Kaufland'),
    ('DMK', 'Müritzer original', 'REWE'),
    ('DMK', 'Müritzer original', 'Netto'),
    ('Milsani', 'Körniger Frischkäse mit fettarmem Joghurt - leicht', 'Aldi'),
    ('AF Deutschland', 'Hirtenkäse', 'Aldi'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'Aldi'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'Edeka'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'REWE'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'Netto'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'Kaufland'),
    ('Grünländer', 'Grünländer Leicht', 'Aldi'),
    ('Grünländer', 'Grünländer Leicht', 'Edeka'),
    ('Grünländer', 'Grünländer Leicht', 'REWE'),
    ('Grünländer', 'Grünländer Leicht', 'Kaufland'),
    ('Gazi', 'Grill- und Pfannenkäse', 'Edeka'),
    ('Gazi', 'Grill- und Pfannenkäse', 'Kaufland'),
    ('Bio', 'ALDI GUT BIO Milch Frische Bio-Milch 1.5 % Fett Aus der Kühlung 1l 1.15€ Fettarme Milch', 'Aldi'),
    ('Milsani', 'ALDI MILSANI Skyr Nach isländischer Art mit viel Eiweiß und wenig Fett Aus der Kühlung 1.49€ 500g Becher 1kg 2.98€', 'Aldi'),
    ('Miree', 'Frischkäse Französische Kräuter', 'Kaufland'),
    ('Milram', 'Müritzer herzhaft', 'REWE'),
    ('Milram', 'Müritzer herzhaft', 'Kaufland'),
    ('Milbona', 'Frischkäse becher', 'Lidl'),
    ('Gut Bio', 'ALDI BIO Frische Bio-Vollmilch 3,8 % Fett; kontrolliert ökologische Erzeugung Aus der Kühlung 1.35€ 1-L-Packung Liter 1.35€', 'Aldi'),
    ('Exquisa', 'Körniger Frischkäse', 'REWE'),
    ('Milbona', 'Käse Aufschnitt Leicht', 'Lidl'),
    ('Milram', 'Frühlingsquark Leicht', 'Aldi'),
    ('Milram', 'Frühlingsquark Leicht', 'Lidl'),
    ('Milram', 'Frühlingsquark Leicht', 'Edeka'),
    ('Milram', 'Frühlingsquark Leicht', 'REWE'),
    ('Milram', 'Frühlingsquark Leicht', 'Netto'),
    ('Milram', 'Frühlingsquark Leicht', 'Kaufland'),
    ('Aldi', 'Bio-Bergbauernkäse nussig', 'Aldi'),
    ('Milsani', 'Kräuterquark', 'Aldi'),
    ('Milram', 'Sylter Käse, Milram', 'REWE'),
    ('Aldi', 'Grießpudding High-Protein - Pur/Classic', 'Aldi'),
    ('Aldi', 'Fraîcho - Kräuter der Provence', 'Aldi'),
    ('Milsani', 'Joghurt nach türkischer Art, 3,5 % Fett', 'Aldi'),
    ('Hofburger', 'Butterkäse in Scheiben', 'Aldi'),
    ('Milbona', 'Bio Hirtenkäse', 'Lidl'),
    ('Weihenstephan', 'H-Milch 3,5%', 'Aldi'),
    ('Weihenstephan', 'H-Milch 3,5%', 'Lidl'),
    ('Weihenstephan', 'H-Milch 3,5%', 'Edeka'),
    ('Milbona', 'Skyr', 'Lidl'),
    ('Arla', 'Skyr Natur', 'Aldi'),
    ('Arla', 'Skyr Natur', 'Kaufland'),
    ('Milsani', 'H-Vollmilch 3,5 % Fett', 'Aldi'),
    ('Elinas', 'Joghurt Griechischer Art', 'Edeka'),
    ('Elinas', 'Joghurt Griechischer Art', 'REWE'),
    ('Ehrmann', 'High Protein Chocolate Pudding', 'Aldi'),
    ('Ehrmann', 'High Protein Chocolate Pudding', 'Edeka'),
    ('Ehrmann', 'High Protein Chocolate Pudding', 'REWE'),
    ('Ehrmann', 'High Protein Chocolate Pudding', 'Netto'),
    ('Bio', 'Frische Bio-Vollmilch 3,8 % Fett', 'Aldi'),
    ('Milsani', 'Haltbare Fettarme Milch', 'Aldi'),
    ('Arla', 'Skyr Bourbon Vanille', 'Edeka'),
    ('Milbona', 'High Protein Chocolate Flavour Pudding', 'Lidl'),
    ('Milsani', 'Joghurt mild 3,5 % Fett', 'Aldi'),
    ('Schwarzwaldmilch', 'Protein Milch', 'Edeka'),
    ('Schwarzwaldmilch', 'Protein Milch', 'Kaufland'),
    ('Bresso', 'Bresso', 'Netto'),
    ('Milsani', 'Milch', 'Aldi'),
    ('Bergader', 'Bavaria Blu', 'REWE'),
    ('Aldi', 'Milch, haltbar, 1,5 %, Bio', 'Lidl'),
    ('Aldi', 'A/Joghurt mild 3,5% Fett', 'Aldi'),
    ('Patros', 'Patros Natur', 'REWE'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', 'Aldi'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', 'Edeka'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', 'REWE'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', 'Netto'),
    ('Patros', 'Feta (Schaf- & Ziegenmilch)', 'REWE'),
    ('Patros', 'Feta (Schaf- & Ziegenmilch)', 'Kaufland'),
    ('Patros', 'Feta (Schaf- & Ziegenmilch)', 'Tegut'),
    ('Milsani', 'Frische Vollmilch 3,5%', 'Aldi'),
    ('Milram', 'Benjamin', 'Kaufland'),
    ('Milbona', 'Bio Fettarmer Joghurt mild', 'Edeka'),
    ('Bauer', 'Kirsche', 'Edeka'),
    ('Milbona', 'Skyr Vanilla', 'Lidl'),
    ('Weihenstephan', 'Joghurt Natur 3,5 % Fett', 'Netto'),
    ('Weihenstephan', 'Joghurt Natur 3,5 % Fett', 'Kaufland'),
    ('Cucina Nobile', 'Mozzarella', 'Aldi'),
    ('Bio', 'Bio-Feta', 'Aldi'),
    ('Ein gutes Stück Bayern', 'Haltbare Bio Vollmilch', 'Lidl'),
    ('Lyttos', 'Griechischer Joghurt', 'Aldi'),
    ('AF Deutschland', 'Fettarme Milch (laktosefrei; 1,5% Fett)', 'Aldi'),
    ('Lyttos', 'ALDI LYTTOS YOGRI nach griechischer Art 1kg 2.19€', 'Aldi'),
    ('Milbona', 'Bio Organic Cremiger Joghurt Mild (3,8% Fett)', 'Lidl'),
    ('Milsani', 'Gouda jung in Scheiben', 'Aldi'),
    ('Milbona', 'Bio Speisequark Magerstufe', 'Lidl'),
    ('Hofburger', 'Gouda in Scheiben', 'Aldi'),
    ('Milbona', 'Skyr Erdbeere', 'Lidl'),
    ('Milbona', 'Bio Vollmilch', 'Lidl'),
    ('Ehrmann', 'Chocolate & Topping with Protein', 'Aldi'),
    ('Ehrmann', 'Chocolate & Topping with Protein', 'Lidl'),
    ('Goldsteig', 'Emmentaler in Scheiben', 'Aldi'),
    ('Milbona', 'Joghurt 1,5%', 'Aldi'),
    ('Milbona', 'Joghurt 1,5%', 'Lidl'),
    ('Milsani', 'Speisequark Magerstufe 0,3 % Fett', 'Aldi'),
    ('Aldi', 'Joghurt mild 3,5% / 0x 500 gr / 3x 150 gr (Gebinde= 4x je 150 gr)', 'Aldi'),
    ('Elinas', 'Joghurt, Natur', 'Edeka'),
    ('Elinas', 'Joghurt, Natur', 'Kaufland'),
    ('Ehrmann', 'High Protein Chocolate Mousse', 'Edeka'),
    ('Ehrmann', 'High Protein Chocolate Mousse', 'REWE'),
    ('Ehrmann', 'High Protein Chocolate Mousse', 'Kaufland'),
    ('DMK', 'Haltbare Schlagsahne', 'Aldi'),
    ('Ehrmann', 'Grand Dessert - Vanille', 'REWE'),
    ('Karwendel', 'Miree - Paprika-Chili', 'Edeka'),
    ('Karwendel', 'Miree - Paprika-Chili', 'REWE'),
    ('Der grüne Altenburger', 'Ziegencreme', 'REWE'),
    ('Aldi', 'Bio-Magerquark', 'Aldi'),
    ('Weihenstephan', 'Sahne zum Kochen (Weihenstephan)', 'Edeka'),
    ('Milbona', 'Skyr Blueberry', 'Lidl'),
    ('Milbona', 'Kefir', 'Lidl'),
    ('Zott', 'Monte MAXI', 'REWE'),
    ('Milsani', 'Crème fraîche, 30 % Fett', 'Aldi'),
    ('Milsani', 'High-Protein-Pudding - Schoko', 'Aldi')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Dairy' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
