-- PIPELINE (Dairy): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Milsani', 'Frischkäse', 'D'),
    ('Almette', 'Almette Kräuter', 'D'),
    ('Bergader', 'Bergbauern mild nussig Käse', 'D'),
    ('DOVGAN Family', 'Körniger Frischkäse 33 % Fett', 'B'),
    ('BMI Biobauern', 'Bio-Landkäse mild-nussig', 'E'),
    ('Milram', 'Frühlingsquark Original', 'D'),
    ('Milram', 'Müritzer original', 'D'),
    ('AF Deutschland', 'Hirtenkäse', 'D'),
    ('Grünländer', 'Grünländer Mild & Nussig', 'C'),
    ('Grünländer', 'Grünländer Leicht', 'C'),
    ('GAZi', 'Grill- und Pfannenkäse', 'D'),
    ('Bio', 'ALDI GUT BIO Milch Frische Bio-Milch 1.5 % Fett Aus der Kühlung 1l 1.15€ Fettarme Milch', 'B'),
    ('Miree', 'Frischkäse Französische Kräuter', 'D'),
    ('Milram', 'Müritzer herzhaft', 'E'),
    ('Milbona', 'Frischkäse becher', 'D'),
    ('Gut Bio', 'ALDI BIO Frische Bio-Vollmilch 3,8 % Fett; kontrolliert ökologische Erzeugung Aus der Kühlung 1.35€ 1-L-Packung Liter 1.35€', 'C'),
    ('Exquisa', 'Körniger Frischkäse', 'A'),
    ('Milbona', 'Käse Aufschnitt Leicht', 'D'),
    ('Milram', 'Frühlingsquark Leicht', 'B'),
    ('Aldi', 'Bio-Bergbauernkäse nussig', 'D'),
    ('Milram', 'Sylter Käse, Milram', 'D'),
    ('Aldi', 'Fraîcho - Kräuter der Provence', 'D'),
    ('Hofburger', 'Butterkäse in Scheiben', 'D'),
    ('Milbona', 'Bio Hirtenkäse', 'UNKNOWN'),
    ('Landliebe Landkäse', 'Sahnig-Mild Butterkäse', 'D'),
    ('Bergader', 'Käse würzig-nussig', 'D'),
    ('HW Foods', 'Griechischer Feta / Schafskäse', 'E'),
    ('Schwälbchen Molkerei AG', 'Ayran (original türkische Art)', 'C'),
    ('Aldi', 'Käse-Aufschnitt', 'D'),
    ('Hofburger', 'Harzer Käse', 'C'),
    ('Bresso', 'ALDI BRESSO Frischkäse-Spezialität mit Meersalz verfeinert Aus der Kühlung 150g Becher 1.11€ 1kg 7.40€', 'C'),
    ('Gazi', 'Grill- und Pfannenkäse Natur', 'D'),
    ('Bergader', 'Almzeit (cremig-würzig)', 'D'),
    ('Milbona', 'Käse Mozzarella gerieben 45 %', 'C'),
    ('Bonifaz Kohler', 'Frischkäse-Fass - Natur', 'D'),
    ('Aldi', 'Kräftiger Bio-Bergkäse', 'D'),
    ('Aldi', 'ALDI ROI DE TREFLE Käse Französischer Weichkäse', 'D'),
    ('Milram', 'Frühlings Quark', 'C'),
    ('Agrial', 'Ziegenrahm Kräuter', 'D'),
    ('Quäse', 'Quäse Mild', 'C'),
    ('Der Grüne Altenburger', 'Ziegen-Rolle (Weichkäse) natur 45 %', 'D'),
    ('Bonifaz Kohler', 'Frischkäse-Fass - Kräuter', 'D'),
    ('Aldi', 'Geriebener Hartkäse', 'E'),
    ('Milbona', 'Käse in Salzlake', 'E'),
    ('Agrial', 'Ziegenfrischkäse', 'D'),
    ('Baackes & Heimes', 'Ziegenkäse in Scheiben - Bockshornklee', 'D'),
    ('Lidl', 'Ziegenkäse Classic', 'E'),
    ('Loose', 'Quäse Aromatisch', 'C'),
    ('Aldi', 'Gouda Jung am Stück', 'D'),
    ('Milbona', 'Crefee Kräuter', 'D'),
    ('Rougette', 'Ofenkäse', 'D'),
    ('Aldi', 'Käse Gouda // Emmentaler', 'D'),
    ('Dovgan', 'Gezuckerte Kondensmilch, wärmebehandelt', 'E'),
    ('Karwendel', 'Frischkäse Gorgonzola', 'D'),
    ('Milram', 'Rahmkäse', 'D'),
    ('Patros', 'Hirtenkäse Kräuter', 'E'),
    ('Roi de Trefle', 'Ziegen-Weichkäse 45 % Fett', 'D'),
    ('Milbona', 'Frischkäse Becher Meerrettich', 'D'),
    ('Aldi', 'Frischkäse-Fass - Meerrettich', 'D'),
    ('Rücker', 'Grill- & Pfannenkäse Kräuter', 'D'),
    ('Hofburger', 'Käsesnack in Würfeln - Maasdamer & Butterkäse', 'D'),
    ('Baackes & Heimes', 'Ziegenkäse 50 %', 'E'),
    ('Kerrygold', 'Kerrygold Butterkäse', 'D'),
    ('Baackes & Heimes', 'Emmentaler am Stück', 'C'),
    ('Roi De Triple', 'Original Französischer Weichkäse', 'D'),
    ('Karwendel', 'Miree Pikante Kräuter', 'C'),
    ('Aldi', 'Der französische Camembert', 'D'),
    ('Milbona', 'Hirtenkäse', 'E'),
    ('Milbona', 'Butterkäse', 'D'),
    ('Harzbube', 'Handkäse Kümmel', 'C'),
    ('Hofburger', 'Hofburger Schmelzscheiben &quot;Allgäuer Art&quot;', 'E'),
    ('Bergader', 'Almzeit Pfefferkäse', 'C'),
    ('Lidl', 'Ziegenkäse Schnittkäse mit Bockshornklee', 'D'),
    ('Körtez', 'Ayran (original türkische Art)', 'C'),
    ('Bio', 'Französischer Bio-Landkäse Cremig', 'D'),
    ('Exquisa', 'Exquisa Balance Frischkäse', 'B'),
    ('Grünländer', 'Grünländer würzig länger gereift', 'D'),
    ('Aldi', 'ALDI LYTTOS Weißkäse in Salzlake', 'E'),
    ('Baackes & Heimes', 'Ziegenkäse in Scheiben - Natur', 'D'),
    ('Almette', 'Almette - Kräuter Leicht', 'C'),
    ('Milsani', 'Kaffeeweißer', 'UNKNOWN'),
    ('Milram', 'Milram 3-Zwiebel Quark rote Zwiebeln, Frühlingszwiebeln, Schalotten 40466101 Speisequarkzubereitung', 'D'),
    ('Dovgan Family', 'Groß-Körniger Frischkäse Tworog', 'B'),
    ('Gervais', 'Hüttenkäse', 'B'),
    ('Landliebe', 'Frische Landmilch, länger haltbar, 3,8% Fett', 'C'),
    ('Bresso', 'Bresso feine Kräuter leichtgenuss 150g 0.99€ 1kg 6.60€', 'C'),
    ('Milbona (Lidl)', 'Bio Gouda Käse in Scheiben', 'D'),
    ('Nestlé', 'Milchmädchen', 'E'),
    ('Roi de Trefle', 'Ziegenfrischkäse Schnittlauch', 'D'),
    ('Milkana', 'Käse Vielfalt', 'D'),
    ('Milbona', 'Maasdamer Käse Scheiben', 'D'),
    ('Milbona', 'Bio Butterkäse', 'D'),
    ('Exquisa', 'Körnige Frischkäsezubereitung', 'A'),
    ('Karwendel', 'Miree - Frühlingskräuter', 'E'),
    ('Rougette', 'Ofenkäse cremig-mild', 'D'),
    ('Gervais', 'Hüttenkäse aktiv', 'A'),
    ('Gazi', 'Ziegenkäse in Salzlake, 50 % Fett', 'E'),
    ('Aldi', 'Fraicho Käse', 'D'),
    ('Dennree', 'Frischkäse', 'D'),
    ('Rougette', 'Marinierter Grillkäse Paprika', 'C'),
    ('Alpenmark', 'Hochland Käse Aldi', 'D'),
    ('Alpenhain', 'Obatzter - Röstzwiebel', 'D'),
    ('Aldi', 'Österreichischer Bergkäse', 'D'),
    ('Müller', 'Kefir', 'B'),
    ('Weihenstephan', 'H-Milch 3,5%', 'C'),
    ('Milsani', 'H-Vollmilch 3,5 % Fett', 'C'),
    ('Alpenhain', 'Obazda klassisch', 'D'),
    ('Bio', 'Frische Bio-Vollmilch 3,8 % Fett', 'C'),
    ('Aldi', 'Haltbare Fettarme Milch', 'B'),
    ('Schwarzwaldmilch', 'Protein Milch', 'B'),
    ('Bresso', 'Bresso', 'D'),
    ('Milsani', 'Milch', 'B'),
    ('Bergader', 'Bavaria Blu', 'D'),
    ('Aldi', 'Milch, haltbar, 1,5 %, Bio', 'B'),
    ('Patros', 'Patros Natur', 'E'),
    ('Patros', 'Feta (Schaf- & Ziegenmilch)', 'D'),
    ('Milsani', 'Frische Vollmilch 3,5%', 'C'),
    ('Milram', 'Benjamin', 'D'),
    ('Cucina Nobile', 'Mozzarella', 'C'),
    ('Bio', 'Bio-Feta', 'E'),
    ('Ein gutes Stück Bayern', 'Haltbare Bio Vollmilch', 'C'),
    ('AF Deutschland', 'Fettarme Milch (laktosefrei; 1,5% Fett)', 'B'),
    ('Milsani', 'Gouda jung in Scheiben', 'D'),
    ('Hofburger', 'Gouda in Scheiben', 'D'),
    ('Milbona', 'Bio Vollmilch', 'C'),
    ('Goldsteig', 'Emmentaler in Scheiben', 'C'),
    ('Milsani', 'Speisequark Magerstufe 0,3 % Fett', 'A'),
    ('DMK', 'Haltbare Schlagsahne', 'D'),
    ('Karwendel', 'Miree - Paprika-Chili', 'D'),
    ('Der grüne Altenburger', 'Ziegencreme', 'D'),
    ('Weihenstephan', 'Sahne zum Kochen (Weihenstephan)', 'D'),
    ('Milsani', 'Crème fraîche, 30 % Fett', 'D'),
    ('Nur Nur Natur', 'Mild-aromatischer Bio-Emmentaler', 'C'),
    ('Aldi', 'Bio-Gouda in Scheiben', 'D'),
    ('Almette', 'Almette - Tomaten-Pesto', 'D'),
    ('Fair&Gut', 'Weidemilch', 'C'),
    ('DMK', 'Nordlicht', 'D'),
    ('Gut Bio', 'Bio-Mozzarella', 'C'),
    ('Bergader', 'Almzeit', 'D'),
    ('Milbona', 'Reine Buttermilch', 'B'),
    ('Hofburger', 'Fettreduzierter Gouda - cremig-mild', 'C'),
    ('Lidl', 'Cheddar', 'D'),
    ('Milbona', 'Haltbare Vollmilch 3,5% Fett', 'C'),
    ('Milsani', 'Schmand, 24 % Fett', 'D'),
    ('Aldi', 'Kondensmilch 4% Fett', 'C'),
    ('Patros', 'Feta Leicht', 'D'),
    ('Milbona', 'Mozzarella leicht', 'C'),
    ('Bergader Bavaria blu', 'Bavaria Blu', 'D'),
    ('La Farm SA', 'Griechischer Feta (70 % Schafs- & 30 % Ziegenmilch) 43 % (Bio)', 'D'),
    ('Milsani', 'Speisequark 40 % Fett', 'C'),
    ('Milsani', 'Schlagsahne 30 % Fett', 'D'),
    ('Milbona', 'Milbona bio frische vollmilch 3,8%', 'C'),
    ('Hofburger', 'Gouda', 'D'),
    ('Dr. Oetker', 'Creme fraiche Classic', 'D'),
    ('Bio', 'Frische Bergbauern Heumilch', 'C'),
    ('Schwarzwaldmilch', 'BIO Frische Vollmilch', 'C'),
    ('Milram', 'Burlander Herzhaft', 'D'),
    ('Milbona', 'Haltbare Schlagsahne', 'D'),
    ('Bio Bauern', 'Bio Gouda', 'D'),
    ('Bärenmarke', 'Haltbare Milch', 'B'),
    ('Bioland Kaufland', 'H - Vollmilch 3,8% haltb./ Bio Kcl', 'C'),
    ('Cucina', 'Mozarella - Light 27 % Fett', 'B'),
    ('Milbona', 'Gouda jung', 'D'),
    ('Vemondo', 'Vegan plátkový sýr', 'E'),
    ('Aldi', 'Ayran', 'C'),
    ('Aldi', 'Cremia - Natur', 'D'),
    ('Aldi', 'Kondensmilch 10% Fett', 'E'),
    ('ALDI Kerrygold', 'ALDI KERRYGOLD Frisch & Cremig - Kirschpaprika 150g 0.99€ 1kg 6.60€', 'D'),
    ('Lidl', 'Gouda Holland mittelalt', 'D'),
    ('Milbona', 'Burrata', 'C'),
    ('Aldi bio', 'Schmand 24%', 'D'),
    ('AF Deutschland', 'Speisequark Magerstufe', 'A'),
    ('Milbona', 'Gouda', 'UNKNOWN'),
    ('Hofburger', 'Maasdamer mild-nussig', 'D'),
    ('Aldi', 'Zarte Scheiben - cremig-fein', 'D'),
    ('Aldi', 'Reine Buttermilch', 'B'),
    ('Lidl', 'Mozzarella', 'C'),
    ('Aldi', 'Parmigiano', 'D'),
    ('Milram', 'Kefir-Drink - Brombeere', 'D'),
    ('Milbona', 'Yogur High Protein Coco', 'A'),
    ('Gazi', 'Fromage de brebis - koyun peyniri', 'D'),
    ('Milbona', 'Cheddar', 'D'),
    ('Cocina', 'Mozzarella Minis', 'C'),
    ('Weihenstephan', 'Schlagrahm', 'D'),
    ('Milram', 'Gurken Quark', 'C'),
    ('Milsani', 'Creme à la Cuisine zum Kochen, 7 % Fett', 'C'),
    ('Milsani', 'Laktosefreie H-Vollmilch 3,5 % Fett', 'C'),
    ('Milbona', 'Goldessa Balance', 'D'),
    ('Aldi', 'Cremia - Laktosefrei', 'D'),
    ('Nur Nur Natur', 'Frische traditionelle Biomilch', 'C'),
    ('Elsdorfer Molkerei und Feinkost', 'Zazikiquark', 'C'),
    ('Patros', 'Original Feta (Bio)', 'D'),
    ('1001 delights', 'Ayran', 'C'),
    ('Hofburger', 'Mozzarella - Der Milde, gerieben', 'D'),
    ('Arla', 'Weidemilch (Vollmilch), frisch, 3,8% (Bio)', 'C'),
    ('Lidl', 'Milbona Bio frische fettarme Milch', 'B'),
    ('Bergader', 'Bavaria blu - der Milde', 'D'),
    ('Hofburger', 'Edamer in Scheiben, 40% Fett', 'D'),
    ('Bresso', 'Bresso - Kirschtomaten & Chili', 'D'),
    ('Hofburger', 'Fettreduzierter Maasdamer - zart-nussig', 'D'),
    ('Milsani', 'Crème Leicht', 'D'),
    ('Milbona - LIDL', 'Tilsiter', 'D'),
    ('Milbona', 'Schlagsahne ultrahocherhitzt', 'D'),
    ('Food in a bottle', 'Food in a Bottle - Berry Island', 'E'),
    ('DMK', 'Pizza-Liebe', 'D'),
    ('Almette', 'Almette Natur', 'D'),
    ('Géramont', 'Käse Géramont', 'D'),
    ('REWE Bio', 'Frischkäse', 'D'),
    ('Salakis', 'Schafskäse', 'E'),
    ('Müller', 'Ayran', 'C'),
    ('Bärenmarke', 'Haltbare Milch 3,8% Fett', 'C'),
    ('Géramont', 'Camembert Cremig-Würzig', 'D'),
    ('Bären Marke', 'Haltbare Milch 3,8% Fett', 'C'),
    ('Bio', 'Haltbare fettarme Bio-Milch 1,5 % Fett', 'B'),
    ('Bärenmarke', 'Vollmilch', 'C'),
    ('Weihenstephan', 'Milch', 'B'),
    ('Karwendel', 'Miree - Meerrettich', 'D'),
    ('Alnatura', 'Frischkäse Natur', 'D'),
    ('Milsani', 'Kefir', 'B'),
    ('Gut & Günstig', 'Körniger Frischkäse', 'B'),
    ('Chavroux', 'Frischkäse aus 100% Ziegenmilch', 'C'),
    ('Ja', 'Frischkäse', 'D'),
    ('Aldi', 'Frischkäse Pur', 'D'),
    ('Kerrygold', 'Original Irischer Cheddar Herzhaft', 'C'),
    ('Alpenhain', 'Camembert-Creme Natur', 'D'),
    ('Milbona', 'Alpenmilch', 'C'),
    ('Gut & Günstig', 'Frischkäse Natur', 'D'),
    ('Gut & Günstig', 'Käse Frischkäse Pur', 'D'),
    ('Fol Epi', 'Caractere würzig&intensiv', 'A'),
    ('Milbona', 'Kashkaval', 'D'),
    ('EDEKA Bio', 'Frischkäse - Bio', 'D'),
    ('Salakis', 'Schafsmilchkäse Light', 'D'),
    ('Milbona', 'Fettarme Milch', 'B'),
    ('Landliebe', 'Vollmilch 3,8 % Fett', 'C'),
    ('Aldi', 'Almost Hafer', 'A'),
    ('AF Deutschland', 'Speisequark 20 % Fett', 'A'),
    ('Ja!', 'Körniger Frischkäse', 'B'),
    ('Müller', 'Fruchtbuttermilch Multivitamin', 'C'),
    ('REWE Bio', 'Kräuterquark', 'D'),
    ('Landliebe', 'Milch 1.5% Fett', 'B'),
    ('Lidl', 'Hirtenkäse', 'E'),
    ('Cucina Nobile (Aldi)', 'Parmesan Grana Padano, gerieben', 'D'),
    ('Milbona', 'Food in a bottle', 'NOT-APPLICABLE'),
    ('Rewe', 'Gratinkäse Leicht', 'E'),
    ('Milram', 'Frischer Schmand', 'D'),
    ('Milram', 'Leuchtfeuer', 'D'),
    ('Ja!', 'Käseaufschnitt leicht', 'D'),
    ('REWE Bio', 'Ziegenfrischkäse', 'C'),
    ('Milram', 'Kefir Pur', 'B'),
    ('Almette', 'Almette Meerrettich', 'D'),
    ('Gutes Land', 'Frischkäse Balance 30% weniger fett', 'D'),
    ('Lidl', 'Vollmilch', 'UNKNOWN'),
    ('Milbona', 'Haltbare fettarme MILCH', 'UNKNOWN'),
    ('Saint Albray', 'Käse - Saint Albray', 'D'),
    ('Edeka - Gut & Günstig', 'Körnige Frischkäsezubereitung', 'B'),
    ('Lidl', 'Harzer Käse', 'C'),
    ('K-Classic', 'Körniger Frischkäse', 'B'),
    ('Ja!', 'Entrahmte H-MILCH höchstens 0,3% FETT', 'B'),
    ('Rewe', 'Frischkäse laktosefrei', 'D'),
    ('Rewe', 'Hirtenkäse 45 % Fett', 'E'),
    ('K-Clasic', 'Vollmilch 3.5%', 'C'),
    ('Kerrygold', 'Kerrygold Original Irischer Cheddar würzig Der würzige Käse in Scheiben', 'D'),
    ('Goldessa', 'Käse Frischkäse Kräuter', 'D'),
    ('Roi de Trefle', 'Brie-Spitze', 'D'),
    ('Esko', 'Kochkäse mit Kümmel', 'C'),
    ('Milbona', 'Frische Weidemilch', 'C'),
    ('Bären Marke', 'Frische Milch Fettarm 1,8% Fett', 'D'),
    ('Cucina', 'Gouda gerieben', 'D'),
    ('Ehrmann', 'Chocolate Drink - High Protein', 'C'),
    ('Bresso', 'Frischkäse Feine Kräuter', 'D'),
    ('Arla', 'Buko - Verfeinert mit mildem Ziegenkäse', 'D'),
    ('Gutes Land', 'Frischkäse', 'D'),
    ('Aldi', 'Kondensmilch 7,5% Fett', 'C'),
    ('Aldi', 'Irischer traditioneller Cheddar in Scheiben', 'D'),
    ('Almette', 'Almette Steinpilz', 'D'),
    ('Schwarzwaldmilch', 'Schwarzwald BIO Frische Vollmilch', 'C'),
    ('Lidl', 'Butterkäse', 'D'),
    ('Edeka', 'Käse', 'D'),
    ('Ja!', 'Harzer Käse', 'C'),
    ('Almette', 'Almette - Balance', 'D'),
    ('Nierstaler', 'Schafmilch 1,5% Fett', 'B'),
    ('Ja!', 'Hirtenkäse', 'E'),
    ('Mang', 'Original Allgäuer Limburger', 'D'),
    ('Petrella', 'Petrella mit Schnittlauch', 'D'),
    ('Gut & Günstig', 'Kaffeeweißer', 'E'),
    ('Steinhauer', 'Kondensmilch gezuckert', 'E'),
    ('Aldi', 'Creme à la Cuisine 15 % Fett zum Kochen', 'UNKNOWN'),
    ('K-Classic', 'Fettarme Milch', 'B'),
    ('LAC', 'Schlagsahne', 'D'),
    ('Gut & Günstig', 'Ziegen-Frischkäse', 'C'),
    ('Bärenmarke', 'H-Milch', 'B'),
    ('Goldsteig Käsereien', 'Käse - Mozzarella', 'C'),
    ('Bärenmarke', 'Schlagsahne', 'D'),
    ('Zott', 'Zottarella', 'C'),
    ('Alpenhain', 'Mozzarella Sticks', 'D'),
    ('Rewe Bio', 'Bergkäse (Heumilch)', 'D'),
    ('Arla', 'Frühlingszwiebel', 'D'),
    ('Aldi', 'Tilsiter', 'C'),
    ('Saint Agur', 'Edler Blauschimmelkäse aus Frankreich', 'D'),
    ('Milbona', 'Ayran', 'C')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Milsani', 'Frischkäse', '3'),
    ('Almette', 'Almette Kräuter', '4'),
    ('Bergader', 'Bergbauern mild nussig Käse', '3'),
    ('DOVGAN Family', 'Körniger Frischkäse 33 % Fett', '3'),
    ('BMI Biobauern', 'Bio-Landkäse mild-nussig', '3'),
    ('Milram', 'Frühlingsquark Original', '3'),
    ('Milram', 'Müritzer original', '4'),
    ('AF Deutschland', 'Hirtenkäse', '3'),
    ('Grünländer', 'Grünländer Mild & Nussig', '3'),
    ('Grünländer', 'Grünländer Leicht', '3'),
    ('GAZi', 'Grill- und Pfannenkäse', '3'),
    ('Bio', 'ALDI GUT BIO Milch Frische Bio-Milch 1.5 % Fett Aus der Kühlung 1l 1.15€ Fettarme Milch', '1'),
    ('Miree', 'Frischkäse Französische Kräuter', '4'),
    ('Milram', 'Müritzer herzhaft', '4'),
    ('Milbona', 'Frischkäse becher', '3'),
    ('Gut Bio', 'ALDI BIO Frische Bio-Vollmilch 3,8 % Fett; kontrolliert ökologische Erzeugung Aus der Kühlung 1.35€ 1-L-Packung Liter 1.35€', '1'),
    ('Exquisa', 'Körniger Frischkäse', '3'),
    ('Milbona', 'Käse Aufschnitt Leicht', '3'),
    ('Milram', 'Frühlingsquark Leicht', '3'),
    ('Aldi', 'Bio-Bergbauernkäse nussig', '3'),
    ('Milram', 'Sylter Käse, Milram', '4'),
    ('Aldi', 'Fraîcho - Kräuter der Provence', '4'),
    ('Hofburger', 'Butterkäse in Scheiben', '3'),
    ('Milbona', 'Bio Hirtenkäse', '3'),
    ('Landliebe Landkäse', 'Sahnig-Mild Butterkäse', '3'),
    ('Bergader', 'Käse würzig-nussig', '3'),
    ('HW Foods', 'Griechischer Feta / Schafskäse', '3'),
    ('Schwälbchen Molkerei AG', 'Ayran (original türkische Art)', '4'),
    ('Aldi', 'Käse-Aufschnitt', '3'),
    ('Hofburger', 'Harzer Käse', '3'),
    ('Bresso', 'ALDI BRESSO Frischkäse-Spezialität mit Meersalz verfeinert Aus der Kühlung 150g Becher 1.11€ 1kg 7.40€', '4'),
    ('Gazi', 'Grill- und Pfannenkäse Natur', '3'),
    ('Bergader', 'Almzeit (cremig-würzig)', '4'),
    ('Milbona', 'Käse Mozzarella gerieben 45 %', '3'),
    ('Bonifaz Kohler', 'Frischkäse-Fass - Natur', '3'),
    ('Aldi', 'Kräftiger Bio-Bergkäse', '3'),
    ('Aldi', 'ALDI ROI DE TREFLE Käse Französischer Weichkäse', '3'),
    ('Milram', 'Frühlings Quark', '3'),
    ('Agrial', 'Ziegenrahm Kräuter', '4'),
    ('Quäse', 'Quäse Mild', '4'),
    ('Der Grüne Altenburger', 'Ziegen-Rolle (Weichkäse) natur 45 %', '3'),
    ('Bonifaz Kohler', 'Frischkäse-Fass - Kräuter', '3'),
    ('Aldi', 'Geriebener Hartkäse', '4'),
    ('Milbona', 'Käse in Salzlake', '3'),
    ('Agrial', 'Ziegenfrischkäse', '3'),
    ('Baackes & Heimes', 'Ziegenkäse in Scheiben - Bockshornklee', '3'),
    ('Lidl', 'Ziegenkäse Classic', '3'),
    ('Loose', 'Quäse Aromatisch', '4'),
    ('Aldi', 'Gouda Jung am Stück', '3'),
    ('Milbona', 'Crefee Kräuter', '4'),
    ('Rougette', 'Ofenkäse', '4'),
    ('Aldi', 'Käse Gouda // Emmentaler', '3'),
    ('Dovgan', 'Gezuckerte Kondensmilch, wärmebehandelt', '4'),
    ('Karwendel', 'Frischkäse Gorgonzola', '4'),
    ('Milram', 'Rahmkäse', '4'),
    ('Patros', 'Hirtenkäse Kräuter', '3'),
    ('Roi de Trefle', 'Ziegen-Weichkäse 45 % Fett', '3'),
    ('Milbona', 'Frischkäse Becher Meerrettich', '3'),
    ('Aldi', 'Frischkäse-Fass - Meerrettich', '3'),
    ('Rücker', 'Grill- & Pfannenkäse Kräuter', '3'),
    ('Hofburger', 'Käsesnack in Würfeln - Maasdamer & Butterkäse', '3'),
    ('Baackes & Heimes', 'Ziegenkäse 50 %', '3'),
    ('Kerrygold', 'Kerrygold Butterkäse', '4'),
    ('Baackes & Heimes', 'Emmentaler am Stück', '3'),
    ('Roi De Triple', 'Original Französischer Weichkäse', '3'),
    ('Karwendel', 'Miree Pikante Kräuter', '4'),
    ('Aldi', 'Der französische Camembert', '4'),
    ('Milbona', 'Hirtenkäse', '3'),
    ('Milbona', 'Butterkäse', '3'),
    ('Harzbube', 'Handkäse Kümmel', '4'),
    ('Hofburger', 'Hofburger Schmelzscheiben &quot;Allgäuer Art&quot;', '4'),
    ('Bergader', 'Almzeit Pfefferkäse', '3'),
    ('Lidl', 'Ziegenkäse Schnittkäse mit Bockshornklee', '3'),
    ('Körtez', 'Ayran (original türkische Art)', '4'),
    ('Bio', 'Französischer Bio-Landkäse Cremig', '3'),
    ('Exquisa', 'Exquisa Balance Frischkäse', '4'),
    ('Grünländer', 'Grünländer würzig länger gereift', '3'),
    ('Aldi', 'ALDI LYTTOS Weißkäse in Salzlake', '4'),
    ('Baackes & Heimes', 'Ziegenkäse in Scheiben - Natur', '3'),
    ('Almette', 'Almette - Kräuter Leicht', '4'),
    ('Milsani', 'Kaffeeweißer', '4'),
    ('Milram', 'Milram 3-Zwiebel Quark rote Zwiebeln, Frühlingszwiebeln, Schalotten 40466101 Speisequarkzubereitung', '4'),
    ('Dovgan Family', 'Groß-Körniger Frischkäse Tworog', '3'),
    ('Gervais', 'Hüttenkäse', '3'),
    ('Landliebe', 'Frische Landmilch, länger haltbar, 3,8% Fett', '1'),
    ('Bresso', 'Bresso feine Kräuter leichtgenuss 150g 0.99€ 1kg 6.60€', '4'),
    ('Milbona (Lidl)', 'Bio Gouda Käse in Scheiben', '4'),
    ('Nestlé', 'Milchmädchen', '3'),
    ('Roi de Trefle', 'Ziegenfrischkäse Schnittlauch', '4'),
    ('Milkana', 'Käse Vielfalt', '4'),
    ('Milbona', 'Maasdamer Käse Scheiben', '3'),
    ('Milbona', 'Bio Butterkäse', '4'),
    ('Exquisa', 'Körnige Frischkäsezubereitung', '3'),
    ('Karwendel', 'Miree - Frühlingskräuter', '4'),
    ('Rougette', 'Ofenkäse cremig-mild', '3'),
    ('Gervais', 'Hüttenkäse aktiv', '3'),
    ('Gazi', 'Ziegenkäse in Salzlake, 50 % Fett', '3'),
    ('Aldi', 'Fraicho Käse', '4'),
    ('Dennree', 'Frischkäse', '3'),
    ('Rougette', 'Marinierter Grillkäse Paprika', '3'),
    ('Alpenmark', 'Hochland Käse Aldi', '3'),
    ('Alpenhain', 'Obatzter - Röstzwiebel', '3'),
    ('Aldi', 'Österreichischer Bergkäse', '4'),
    ('Müller', 'Kefir', '4'),
    ('Weihenstephan', 'H-Milch 3,5%', '1'),
    ('Milsani', 'H-Vollmilch 3,5 % Fett', '4'),
    ('Alpenhain', 'Obazda klassisch', '3'),
    ('Bio', 'Frische Bio-Vollmilch 3,8 % Fett', '1'),
    ('Aldi', 'Haltbare Fettarme Milch', '4'),
    ('Schwarzwaldmilch', 'Protein Milch', '4'),
    ('Bresso', 'Bresso', '4'),
    ('Milsani', 'Milch', '1'),
    ('Bergader', 'Bavaria Blu', '3'),
    ('Aldi', 'Milch, haltbar, 1,5 %, Bio', '1'),
    ('Patros', 'Patros Natur', '3'),
    ('Patros', 'Feta (Schaf- & Ziegenmilch)', '3'),
    ('Milsani', 'Frische Vollmilch 3,5%', '1'),
    ('Milram', 'Benjamin', '4'),
    ('Cucina Nobile', 'Mozzarella', '3'),
    ('Bio', 'Bio-Feta', '3'),
    ('Ein gutes Stück Bayern', 'Haltbare Bio Vollmilch', '1'),
    ('AF Deutschland', 'Fettarme Milch (laktosefrei; 1,5% Fett)', '1'),
    ('Milsani', 'Gouda jung in Scheiben', '3'),
    ('Hofburger', 'Gouda in Scheiben', '3'),
    ('Milbona', 'Bio Vollmilch', '4'),
    ('Goldsteig', 'Emmentaler in Scheiben', '3'),
    ('Milsani', 'Speisequark Magerstufe 0,3 % Fett', '3'),
    ('DMK', 'Haltbare Schlagsahne', '4'),
    ('Karwendel', 'Miree - Paprika-Chili', '4'),
    ('Der grüne Altenburger', 'Ziegencreme', '4'),
    ('Weihenstephan', 'Sahne zum Kochen (Weihenstephan)', '4'),
    ('Milsani', 'Crème fraîche, 30 % Fett', '1'),
    ('Nur Nur Natur', 'Mild-aromatischer Bio-Emmentaler', '3'),
    ('Aldi', 'Bio-Gouda in Scheiben', '3'),
    ('Almette', 'Almette - Tomaten-Pesto', '4'),
    ('Fair&Gut', 'Weidemilch', '1'),
    ('DMK', 'Nordlicht', '4'),
    ('Gut Bio', 'Bio-Mozzarella', '3'),
    ('Bergader', 'Almzeit', '4'),
    ('Milbona', 'Reine Buttermilch', '1'),
    ('Hofburger', 'Fettreduzierter Gouda - cremig-mild', '3'),
    ('Lidl', 'Cheddar', '4'),
    ('Milbona', 'Haltbare Vollmilch 3,5% Fett', '1'),
    ('Milsani', 'Schmand, 24 % Fett', '1'),
    ('Aldi', 'Kondensmilch 4% Fett', '4'),
    ('Patros', 'Feta Leicht', '3'),
    ('Milbona', 'Mozzarella leicht', '3'),
    ('Bergader Bavaria blu', 'Bavaria Blu', '3'),
    ('La Farm SA', 'Griechischer Feta (70 % Schafs- & 30 % Ziegenmilch) 43 % (Bio)', '3'),
    ('Milsani', 'Speisequark 40 % Fett', '1'),
    ('Milsani', 'Schlagsahne 30 % Fett', '4'),
    ('Milbona', 'Milbona bio frische vollmilch 3,8%', '4'),
    ('Hofburger', 'Gouda', '3'),
    ('Dr. Oetker', 'Creme fraiche Classic', '4'),
    ('Bio', 'Frische Bergbauern Heumilch', '1'),
    ('Schwarzwaldmilch', 'BIO Frische Vollmilch', '1'),
    ('Milram', 'Burlander Herzhaft', '4'),
    ('Milbona', 'Haltbare Schlagsahne', '4'),
    ('Bio Bauern', 'Bio Gouda', '3'),
    ('Bärenmarke', 'Haltbare Milch', '4'),
    ('Bioland Kaufland', 'H - Vollmilch 3,8% haltb./ Bio Kcl', '4'),
    ('Cucina', 'Mozarella - Light 27 % Fett', '3'),
    ('Milbona', 'Gouda jung', '4'),
    ('Vemondo', 'Vegan plátkový sýr', '4'),
    ('Aldi', 'Ayran', '4'),
    ('Aldi', 'Cremia - Natur', '4'),
    ('Aldi', 'Kondensmilch 10% Fett', '4'),
    ('ALDI Kerrygold', 'ALDI KERRYGOLD Frisch & Cremig - Kirschpaprika 150g 0.99€ 1kg 6.60€', '3'),
    ('Lidl', 'Gouda Holland mittelalt', '4'),
    ('Milbona', 'Burrata', '3'),
    ('Aldi bio', 'Schmand 24%', '1'),
    ('AF Deutschland', 'Speisequark Magerstufe', '1'),
    ('Milbona', 'Gouda', '3'),
    ('Hofburger', 'Maasdamer mild-nussig', '3'),
    ('Aldi', 'Zarte Scheiben - cremig-fein', '3'),
    ('Aldi', 'Reine Buttermilch', '1'),
    ('Lidl', 'Mozzarella', '3'),
    ('Aldi', 'Parmigiano', '3'),
    ('Milram', 'Kefir-Drink - Brombeere', '4'),
    ('Milbona', 'Yogur High Protein Coco', '4'),
    ('Gazi', 'Fromage de brebis - koyun peyniri', '3'),
    ('Milbona', 'Cheddar', '3'),
    ('Cocina', 'Mozzarella Minis', '3'),
    ('Weihenstephan', 'Schlagrahm', '4'),
    ('Milram', 'Gurken Quark', '4'),
    ('Milsani', 'Creme à la Cuisine zum Kochen, 7 % Fett', '4'),
    ('Milsani', 'Laktosefreie H-Vollmilch 3,5 % Fett', '1'),
    ('Milbona', 'Goldessa Balance', '4'),
    ('Aldi', 'Cremia - Laktosefrei', '4'),
    ('Nur Nur Natur', 'Frische traditionelle Biomilch', '1'),
    ('Elsdorfer Molkerei und Feinkost', 'Zazikiquark', '4'),
    ('Patros', 'Original Feta (Bio)', '3'),
    ('1001 delights', 'Ayran', '3'),
    ('Hofburger', 'Mozzarella - Der Milde, gerieben', '3'),
    ('Arla', 'Weidemilch (Vollmilch), frisch, 3,8% (Bio)', '1'),
    ('Lidl', 'Milbona Bio frische fettarme Milch', '1'),
    ('Bergader', 'Bavaria blu - der Milde', '4'),
    ('Hofburger', 'Edamer in Scheiben, 40% Fett', '3'),
    ('Bresso', 'Bresso - Kirschtomaten & Chili', '4'),
    ('Hofburger', 'Fettreduzierter Maasdamer - zart-nussig', '3'),
    ('Milsani', 'Crème Leicht', '3'),
    ('Milbona - LIDL', 'Tilsiter', '3'),
    ('Milbona', 'Schlagsahne ultrahocherhitzt', '4'),
    ('Food in a bottle', 'Food in a Bottle - Berry Island', '4'),
    ('DMK', 'Pizza-Liebe', '4'),
    ('Almette', 'Almette Natur', '4'),
    ('Géramont', 'Käse Géramont', '3'),
    ('REWE Bio', 'Frischkäse', '3'),
    ('Salakis', 'Schafskäse', '3'),
    ('Müller', 'Ayran', '3'),
    ('Bärenmarke', 'Haltbare Milch 3,8% Fett', '1'),
    ('Géramont', 'Camembert Cremig-Würzig', '3'),
    ('Bären Marke', 'Haltbare Milch 3,8% Fett', '4'),
    ('Bio', 'Haltbare fettarme Bio-Milch 1,5 % Fett', '4'),
    ('Bärenmarke', 'Vollmilch', '1'),
    ('Weihenstephan', 'Milch', '1'),
    ('Karwendel', 'Miree - Meerrettich', '4'),
    ('Alnatura', 'Frischkäse Natur', '3'),
    ('Milsani', 'Kefir', '1'),
    ('Gut & Günstig', 'Körniger Frischkäse', '3'),
    ('Chavroux', 'Frischkäse aus 100% Ziegenmilch', '3'),
    ('Ja', 'Frischkäse', '3'),
    ('Aldi', 'Frischkäse Pur', '3'),
    ('Kerrygold', 'Original Irischer Cheddar Herzhaft', '4'),
    ('Alpenhain', 'Camembert-Creme Natur', '3'),
    ('Milbona', 'Alpenmilch', '4'),
    ('Gut & Günstig', 'Frischkäse Natur', '3'),
    ('Gut & Günstig', 'Käse Frischkäse Pur', '3'),
    ('Fol Epi', 'Caractere würzig&intensiv', '4'),
    ('Milbona', 'Kashkaval', '3'),
    ('EDEKA Bio', 'Frischkäse - Bio', '3'),
    ('Salakis', 'Schafsmilchkäse Light', '4'),
    ('Milbona', 'Fettarme Milch', '4'),
    ('Landliebe', 'Vollmilch 3,8 % Fett', '1'),
    ('Aldi', 'Almost Hafer', '4'),
    ('AF Deutschland', 'Speisequark 20 % Fett', '1'),
    ('Ja!', 'Körniger Frischkäse', '3'),
    ('Müller', 'Fruchtbuttermilch Multivitamin', '4'),
    ('REWE Bio', 'Kräuterquark', '4'),
    ('Landliebe', 'Milch 1.5% Fett', '4'),
    ('Lidl', 'Hirtenkäse', '3'),
    ('Cucina Nobile (Aldi)', 'Parmesan Grana Padano, gerieben', '3'),
    ('Milbona', 'Food in a bottle', '4'),
    ('Rewe', 'Gratinkäse Leicht', '3'),
    ('Milram', 'Frischer Schmand', '1'),
    ('Milram', 'Leuchtfeuer', '4'),
    ('Ja!', 'Käseaufschnitt leicht', '3'),
    ('REWE Bio', 'Ziegenfrischkäse', '3'),
    ('Milram', 'Kefir Pur', '4'),
    ('Almette', 'Almette Meerrettich', '4'),
    ('Gutes Land', 'Frischkäse Balance 30% weniger fett', '3'),
    ('Lidl', 'Vollmilch', '1'),
    ('Milbona', 'Haltbare fettarme MILCH', '1'),
    ('Saint Albray', 'Käse - Saint Albray', '4'),
    ('Edeka - Gut & Günstig', 'Körnige Frischkäsezubereitung', '3'),
    ('Lidl', 'Harzer Käse', '3'),
    ('K-Classic', 'Körniger Frischkäse', '3'),
    ('Ja!', 'Entrahmte H-MILCH höchstens 0,3% FETT', '4'),
    ('Rewe', 'Frischkäse laktosefrei', '3'),
    ('Rewe', 'Hirtenkäse 45 % Fett', '3'),
    ('K-Clasic', 'Vollmilch 3.5%', '4'),
    ('Kerrygold', 'Kerrygold Original Irischer Cheddar würzig Der würzige Käse in Scheiben', '4'),
    ('Goldessa', 'Käse Frischkäse Kräuter', '4'),
    ('Roi de Trefle', 'Brie-Spitze', '3'),
    ('Esko', 'Kochkäse mit Kümmel', '4'),
    ('Milbona', 'Frische Weidemilch', '1'),
    ('Bären Marke', 'Frische Milch Fettarm 1,8% Fett', '4'),
    ('Cucina', 'Gouda gerieben', '3'),
    ('Ehrmann', 'Chocolate Drink - High Protein', '4'),
    ('Bresso', 'Frischkäse Feine Kräuter', '3'),
    ('Arla', 'Buko - Verfeinert mit mildem Ziegenkäse', '4'),
    ('Gutes Land', 'Frischkäse', '3'),
    ('Aldi', 'Kondensmilch 7,5% Fett', '4'),
    ('Aldi', 'Irischer traditioneller Cheddar in Scheiben', '4'),
    ('Almette', 'Almette Steinpilz', '4'),
    ('Schwarzwaldmilch', 'Schwarzwald BIO Frische Vollmilch', '1'),
    ('Lidl', 'Butterkäse', '3'),
    ('Edeka', 'Käse', '4'),
    ('Ja!', 'Harzer Käse', '4'),
    ('Almette', 'Almette - Balance', '4'),
    ('Nierstaler', 'Schafmilch 1,5% Fett', '1'),
    ('Ja!', 'Hirtenkäse', '3'),
    ('Mang', 'Original Allgäuer Limburger', '3'),
    ('Petrella', 'Petrella mit Schnittlauch', '4'),
    ('Gut & Günstig', 'Kaffeeweißer', '4'),
    ('Steinhauer', 'Kondensmilch gezuckert', '3'),
    ('Aldi', 'Creme à la Cuisine 15 % Fett zum Kochen', '4'),
    ('K-Classic', 'Fettarme Milch', '1'),
    ('LAC', 'Schlagsahne', '4'),
    ('Gut & Günstig', 'Ziegen-Frischkäse', '3'),
    ('Bärenmarke', 'H-Milch', '4'),
    ('Goldsteig Käsereien', 'Käse - Mozzarella', '3'),
    ('Bärenmarke', 'Schlagsahne', '4'),
    ('Zott', 'Zottarella', '3'),
    ('Alpenhain', 'Mozzarella Sticks', '4'),
    ('Rewe Bio', 'Bergkäse (Heumilch)', '3'),
    ('Arla', 'Frühlingszwiebel', '3'),
    ('Aldi', 'Tilsiter', '3'),
    ('Saint Agur', 'Edler Blauschimmelkäse aus Frankreich', '3'),
    ('Milbona', 'Ayran', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Dairy', 100, 'DE');
