-- PIPELINE (Canned Goods): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Nixe - LIDL', 'Thunfisch Filets in Sonnenblumenöl', 'A'),
    ('Hengstenberg', 'KNAX Gewürzgurken', 'C'),
    ('Aldi', 'Bio-Gewürzgurken', 'C'),
    ('Wonnemeyer', 'Mediterrane Antipasti - Kirschpaprika mit Frischkäsecreme Senf-Honig', 'D'),
    ('Spreewaldhof', 'Spreewälder Saure Gurken', 'C'),
    ('King''s Crown', 'Gurkenfässchen', 'B'),
    ('King''s Crown', 'Paprika geröstet, mild, süß-sauer', 'A'),
    ('Aldi', 'ALDI KING''S CROWN Schältomaten ATG 240g', 'A'),
    ('Specht', 'Bayerische Gewürzgurken', 'C'),
    ('Almare', 'Geräucherte Sprotten in Rapsöl', 'D'),
    ('Aldi', 'Genießer-Fässchen mit weißem Balsamico', 'C'),
    ('Freshona', 'Ananas. Stücke', 'A'),
    ('Aldi', 'Erbsen mit Möhren, klei', 'A'),
    ('Kaufland', 'Thunfischfilets in Sonnenblumenöl', 'B'),
    ('Kings Crown', 'Gewürzgurken', 'A'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Chili', 'B'),
    ('Bautz''ner', 'Gewürzgurken', 'C'),
    ('Aldi', 'Champignons ganze Köpfe', 'A'),
    ('Larsen', 'Wildlachs Gartenkräuter', 'C'),
    ('Appel', 'Herings-Filets -Tataren-Sauce- in kräftiger Sauce mit Tomaten nach ungarischer Art', 'C'),
    ('Aldi', 'Genießer-Fässchen mit Kräutern', 'C'),
    ('Kaufland', 'Gewürzgurken', 'UNKNOWN'),
    ('King''s Crown', 'Genießer-Fässchen mit Honig', 'C'),
    ('Gourmet Finest Cuisine', 'Thunfisch in Olivenöl Mini-Pack', 'C'),
    ('Spreewaldhof', 'Spreelinge Gewürzgurken von Spreewaldhof', 'C'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Zitrone', 'C'),
    ('Freshona', 'Bunter Gemüsemix Mexico Style', 'C'),
    ('Kühne', 'Gewürzgurken', 'C'),
    ('Spreewaldhof', 'Spreelinge Gewürzgurken', 'C'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Klassik', 'B'),
    ('King''s Crown', 'Erbsen und Möhren sehr fein', 'A'),
    ('Kühne', 'Gurken Sauer Honig Schlemmertöpfchen', 'C'),
    ('Lysell', 'Hanseatenröllchen', 'D'),
    ('Kühne', 'Gurken Schlemmertöpfchen, Mild Würzige Gürkchen', 'C'),
    ('Gourmet Finest Cuisine', 'Gegrillte Thunfischfilets in Olivenöl', 'A'),
    ('Kühne', 'Kühne Glas Apfelrotkohl der Klassiker 680g 2,19€ 1kg 3,22€', 'C'),
    ('Kühne', 'Schlemmer Töpfchen chili Gurken', 'C'),
    ('Appel', 'Appel Heringsfilets in Dill-Kräuter-Creme 4020500922035', 'D'),
    ('Kaufland', 'Knackige Gewürzgurken', 'A'),
    ('Almara', 'Thunfisch-Filets in nativen Olivenöl extra', 'B'),
    ('La Perla', 'Sardinen in Sonnenblumenöl', 'B'),
    ('RügenFisch', 'Heringsfilets in Tomaten-Creme von Rügenfisch', 'C'),
    ('King''S Crown', 'Gemüse Grünkohl 660 g', 'A'),
    ('Denn''s', 'Tomaten stückig - Bio', 'A'),
    ('Dovgan', 'Riga Sprotten in Rapsöl', 'D'),
    ('Deutsche see', 'Thunfisch in Olivenöl', 'A'),
    ('La Miranda', 'Sardinen in Sonnenblumenöl', 'C'),
    ('K-Classic', 'Ananasstücke', 'A'),
    ('Raabe Spreewalder Konserven', 'Gewürzgurken nach original DDR-Rezeptur', 'C'),
    ('K Classic', 'Gewürzgurken', 'C'),
    ('Dittmann', 'Konserve - Gemüse - Pfefferonen scharf', 'D'),
    ('Hengstenberg', 'Gurken Sticksi süß-würzig', 'C'),
    ('Hengstenberg', 'Cornichons kräuter-würzig', 'C'),
    ('Thüringer Landgarten', 'Gewürzgurken', 'C'),
    ('Larsen', 'Feine Kieler Sprotten in Rapsöl und eigenem Saft', 'D'),
    ('Nixe', 'Thunfisch', 'A'),
    ('Appel', 'Zarte Filets vom Hering in Tomaten-Creme', 'C'),
    ('KING''S CROWN (Aldi)', 'Tomatenmark', 'A'),
    ('Almare', 'Thunfisch Filets in eigenen Saft', 'A'),
    ('Aldi', 'Tomatenmark', 'A'),
    ('Oro di Parma', 'Famila Oro di Parma Tomatenmark mit Knoblauch 200g 1.29€ 1kg 6.45', 'B'),
    ('Aldi', 'Tomaten gehackt', 'A'),
    ('Oro Di Parma', 'Tomaten', 'A'),
    ('Hawesta', 'Heringsfilets - Tomaten-Creme', 'B'),
    ('Aldi', 'Cornichons', 'B'),
    ('DmBio', 'Tomatenmark', 'A'),
    ('Hawesta', 'Heringsfilets - Pfeffercreme', 'B'),
    ('Hengstenberg', 'Mildes Weinsauerkraut', 'C'),
    ('Bio Organic', 'Rote Beete', 'A'),
    ('Appel', 'Zarte Filets vom Hering in Eier-Senf-Creme', 'C'),
    ('Appel', 'Zarte Filets vom Hering Tomate-Mozzarella', 'D'),
    ('Aldi', 'Mais', 'B'),
    ('Hengstenberg', 'Tomaten - Passiert', 'A'),
    ('Sweet Valley', 'Pfirsiche halbe Frucht, leicht gezuckert', 'B'),
    ('Deutsche See', 'Thunfisch im Aufguss', 'A'),
    ('King''S Crown', 'Rote Beete in Kugeln', 'B'),
    ('Kühne', 'Cornichons', 'C'),
    ('Otto Franck Import', 'Mandarin-Orangen', 'C'),
    ('Lidl', 'Zarte Hertingsfilets in Tomatensauce', 'C'),
    ('7 Schwaben Konserven', 'Rote Beete in Scheiben', 'A'),
    ('Rügen Fisch', 'Scomber Mix Classic', 'C'),
    ('Feinkost Dittmann', 'Pfefferonen', 'E'),
    ('Appel', 'Zarte Filets', 'C'),
    ('Aldi', 'Mungobohnenkeime', 'A'),
    ('Appel', 'Fisch - Zarte Filets vom Hering in Pfeffer Creme', 'C'),
    ('Dittmann', 'Pfefferonen', 'E'),
    ('Kühne', 'Apfel-Rotkohl', 'B'),
    ('Hawesta', 'Heringsfilet - Paprika-Creme', 'C'),
    ('Clama', 'Kichererbsen mit Oliven & Karotten in Tomatensauce', 'B'),
    ('Lidl', 'Thunfisch Filets', 'A'),
    ('Bio', 'Passierte Tomaten', 'B'),
    ('Aldi', 'Thunfisch-Filets in eigenem Saft', 'D'),
    ('Hengstenberg', 'Rotkohl', 'C'),
    ('Kühne', 'Salz-Dill Gurken', 'C'),
    ('Spreewaldhof', 'Cornichons von Spreewaldhof', 'C'),
    ('Almare Seafood', 'Heringsfilets in Pfeffer-Creme', 'C'),
    ('Appel', 'Zarte Filets vom Hering Salsa-Picante', 'D'),
    ('Alpenschmaus', 'Gurkentopf', 'C'),
    ('DmBio', 'Sauerkraut', 'A'),
    ('Appel', 'Heringsfilet in Merettich Creme', 'D'),
    ('King''s Crown', 'Feine Cornichons mit Honig', 'C'),
    ('Hawesta', 'Heringsfilets Balkan-Sauce', 'C'),
    ('Hengstenberg', 'Sandwich Gurken/Glas', 'C'),
    ('K-Classic', 'Gehackte Tomaten in Tomatensaft', 'UNKNOWN'),
    ('Almare Seafood', 'Fischkonserve', 'C'),
    ('K-Classic', 'Champignons in Scheiben', 'A'),
    ('K-Classic', 'Tomaten', 'A'),
    ('Freshona', 'Sonnenmais natursüß', 'B'),
    ('REWE Bio', 'Tomaten in Stücken', 'A'),
    ('Aldi', 'Gehackte Tomaten', 'A'),
    ('K-Classic', 'Thunfisch Filets I.E.S', 'A'),
    ('Edeka', 'Delikatess Gewürzgurken', 'A'),
    ('Mutti', 'Geschälte Italienische Tomaten', 'A'),
    ('Sweet Valley', 'ALDI SWEET VALLEY OBST Ananas in Scheiben ohne Zuckerzusatz', 'A'),
    ('EnerBio', 'Kimchi', 'A'),
    ('Edeka Gut & Günstig', 'Obst: Ananas in Stücke', 'A'),
    ('Rewe', 'Tomaten stückig', 'A'),
    ('Saupiquet', 'Fisch Thunfisch Naturale ohne Öl', 'A'),
    ('Edeka', 'Tomaten in Stücken', 'A'),
    ('Gut & Günstig', 'Thunfisch in Sonnenblumenöl', 'UNKNOWN'),
    ('Gut & Günstig', 'Thunfisch in Öl', 'UNKNOWN'),
    ('Hengstenberg', 'Essiggurken', 'C'),
    ('Gut & Günstig', 'Sardinen in Sonnenblumenöl', 'A'),
    ('Freshona', 'Tomaten gewürfelt', 'UNKNOWN'),
    ('DmBio', 'Kimchi', 'C'),
    ('Rügen Fisch', 'Kieler Sprotten', 'D'),
    ('Penny', 'Junge Erbsen mit Möhren, sehr fein', 'A'),
    ('Almare', 'Heringsfilet Tomate', 'C'),
    ('Edeka', 'Thunfisch Stücke mit Gemüse', 'C'),
    ('Edeka', 'Tomaten geschält', 'A'),
    ('Hengstenberg', 'Cornichons', 'C'),
    ('K-Classic', 'Cornichons', 'A'),
    ('K Classic', 'Gehackte Tomaten', 'A'),
    ('Kühne', 'Rote Bete', 'C'),
    ('Kühne', 'SilberZwiebeln 40804477 Silberzwiebeln', 'C'),
    ('Aldi', 'Ananas', 'A'),
    ('Bibigo', 'Kimchi', 'C'),
    ('Ja!', 'Sardinen in Sonnenblumenöl', 'A'),
    ('Dreimaster', 'Thunfischfilets geschnitten in Sonnenblumenöl', 'A'),
    ('REWE Beste Wahl', 'Gegrillte Artischockenviertel in Sonnenblumenöl mit Kräutern', 'C'),
    ('Feinkost Dittmann', 'Pfefferonen mild-pikant', 'E'),
    ('Appel Appel Fisch', 'Zarte Filets vom Hering Tomate & Curry', 'D'),
    ('King''s Crown', 'Peperoni mild', 'D'),
    ('Hengstenberg', 'Burger Gurken', 'C'),
    ('Rügen Fisch', 'Heringsfilets Feinschmeckerplatte', 'C'),
    ('King''s Crown', 'Tomaten passiert klein', 'A'),
    ('Hengstenberg', 'Knax - Die Riesen', 'C'),
    ('Harvesta', 'Heringsfilet Mexico-Sauce', 'B'),
    ('K-Classic', 'Thunfisch in eigenem Saft', 'A'),
    ('Feinkost Dittmann', 'Peperoni', 'D'),
    ('Appel', 'Zarte Filets vom Hering Tomate-Barbecue', 'D'),
    ('Saupiquet', 'Sardinen - in Öl', 'D'),
    ('Cornichons', 'Gurken', 'B'),
    ('Gut & Günstig', 'Makrelenfilets in Sonnenblumenöl', 'B'),
    ('King Crown', 'Gurken', 'C'),
    ('Ja!', 'Tomaten geschält', 'A'),
    ('King''s Crown', 'Datterini Tomaten', 'A'),
    ('Baresa', 'Passierte Tomaten', 'A'),
    ('Greenyard Prepared Belgium', 'Erbsen mit Möhren', 'B'),
    ('Rügen Fisch', 'Brathering', 'C'),
    ('GutBio', 'Tomaten gehackt', 'A'),
    ('Kühne', 'Rotkohl', 'C'),
    ('Appel', 'Sardinen', 'C'),
    ('Kühne', 'Getrocknete Tomaten', 'C'),
    ('Gut & Günstig', 'Gurken Topf Gewürzgurken', 'C'),
    ('Kühne', 'Cocktail Cornichons', 'C'),
    ('Spreewaldhof', 'Cornichons', 'C'),
    ('Sol & Mar', 'Spanische grüne Oliven mit Stein', 'E'),
    ('Kühne', 'Gurken Moskauer Art', 'C'),
    ('RügenFisch', 'Heringsfilet in Senf-Creme', 'C'),
    ('BioBio', 'Tomaten stückig', 'A'),
    ('K-Classic', 'Champignons Scheiben - Pilze', 'A'),
    ('Appel', 'Sardinen Piri-Piri', 'D'),
    ('Armada', 'Heringsfilets', 'C'),
    ('K-bio', 'Rote Beete Bio/ Kcl', 'C'),
    ('Rewe', 'Gemüse - Mais Super-Sweet Gemüsemais', 'B'),
    ('Demeter', 'Rote Bete', 'UNKNOWN'),
    ('K-Classic', 'Ananas-Scheiben von K-Classic', 'C'),
    ('Dittmann', 'Sardinen', 'B'),
    ('K-Favourites', 'Premium Cornichons', 'C'),
    ('K-Classic', 'Sardinen in Tomatensauce', 'B'),
    ('Hawesta', 'HeringsFilets Zwiebel Sauce', 'C'),
    ('K Classic', 'Sandwichgurken', 'C'),
    ('Rewe Bio', 'Tomaten geschält', 'UNKNOWN'),
    ('Almare Seafood', 'Thunfisch filet', 'D'),
    ('Fontaine', 'Wildlachsfilet im eigenen Saft', 'A'),
    ('DmBio', 'Filetto Du Pomodoro', 'A'),
    ('King''s crown', 'Mais', 'B'),
    ('ALDI King''s Crown', 'Tomaten -gehackte 400g', 'A'),
    ('Hawesta', 'Heringsfilets', 'B'),
    ('Pomito', 'Tomatenfruchtfleisch in Stücken', 'A'),
    ('Edeka', 'Thunfisch Filets in Olivenöl', 'A'),
    ('Followfood', 'Thunfisch Filets in Bio-Sonnenblumenöl', 'A'),
    ('Kühne', 'Gurkenhappen Schlesischer Art', 'C'),
    ('Saupiquet', 'Thunfisch für Pasta - Knoblauch & Peperoncino', 'D'),
    ('Gut & Günstig', 'Champignons ganze Köpfe', 'A'),
    ('Hawesta', 'Heringsfilet in Honig-Senf Sauce', 'D'),
    ('Rewe', 'Delikatess Gewürzgurken Süss-Sauer', 'B'),
    ('Ömur', 'Omur', 'E'),
    ('DREIMASTER (Netto)', 'Bücklings Filets (mit Rapsöl)', 'B')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Nixe - LIDL', 'Thunfisch Filets in Sonnenblumenöl', '3'),
    ('Hengstenberg', 'KNAX Gewürzgurken', '3'),
    ('Aldi', 'Bio-Gewürzgurken', '3'),
    ('Wonnemeyer', 'Mediterrane Antipasti - Kirschpaprika mit Frischkäsecreme Senf-Honig', '4'),
    ('Spreewaldhof', 'Spreewälder Saure Gurken', '3'),
    ('King''s Crown', 'Gurkenfässchen', '3'),
    ('King''s Crown', 'Paprika geröstet, mild, süß-sauer', '3'),
    ('Aldi', 'ALDI KING''S CROWN Schältomaten ATG 240g', '1'),
    ('Specht', 'Bayerische Gewürzgurken', '3'),
    ('Almare', 'Geräucherte Sprotten in Rapsöl', '3'),
    ('Aldi', 'Genießer-Fässchen mit weißem Balsamico', '4'),
    ('Freshona', 'Ananas. Stücke', '1'),
    ('Aldi', 'Erbsen mit Möhren, klei', '3'),
    ('Kaufland', 'Thunfischfilets in Sonnenblumenöl', '3'),
    ('Kings Crown', 'Gewürzgurken', '3'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Chili', '3'),
    ('Bautz''ner', 'Gewürzgurken', '4'),
    ('Aldi', 'Champignons ganze Köpfe', '3'),
    ('Larsen', 'Wildlachs Gartenkräuter', '4'),
    ('Appel', 'Herings-Filets -Tataren-Sauce- in kräftiger Sauce mit Tomaten nach ungarischer Art', '4'),
    ('Aldi', 'Genießer-Fässchen mit Kräutern', '4'),
    ('Kaufland', 'Gewürzgurken', '3'),
    ('King''s Crown', 'Genießer-Fässchen mit Honig', '4'),
    ('Gourmet Finest Cuisine', 'Thunfisch in Olivenöl Mini-Pack', '4'),
    ('Spreewaldhof', 'Spreelinge Gewürzgurken von Spreewaldhof', '3'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Zitrone', '3'),
    ('Freshona', 'Bunter Gemüsemix Mexico Style', '4'),
    ('Kühne', 'Gewürzgurken', '4'),
    ('Spreewaldhof', 'Spreelinge Gewürzgurken', '3'),
    ('Aldi', 'Sardinen in Sonnenblumenöl - Klassik', '3'),
    ('King''s Crown', 'Erbsen und Möhren sehr fein', '3'),
    ('Kühne', 'Gurken Sauer Honig Schlemmertöpfchen', '4'),
    ('Lysell', 'Hanseatenröllchen', '4'),
    ('Kühne', 'Gurken Schlemmertöpfchen, Mild Würzige Gürkchen', '4'),
    ('Gourmet Finest Cuisine', 'Gegrillte Thunfischfilets in Olivenöl', '4'),
    ('Kühne', 'Kühne Glas Apfelrotkohl der Klassiker 680g 2,19€ 1kg 3,22€', '4'),
    ('Kühne', 'Schlemmer Töpfchen chili Gurken', '4'),
    ('Appel', 'Appel Heringsfilets in Dill-Kräuter-Creme 4020500922035', '4'),
    ('Kaufland', 'Knackige Gewürzgurken', '4'),
    ('Almara', 'Thunfisch-Filets in nativen Olivenöl extra', '3'),
    ('La Perla', 'Sardinen in Sonnenblumenöl', '3'),
    ('RügenFisch', 'Heringsfilets in Tomaten-Creme von Rügenfisch', '4'),
    ('King''S Crown', 'Gemüse Grünkohl 660 g', '3'),
    ('Denn''s', 'Tomaten stückig - Bio', '1'),
    ('Dovgan', 'Riga Sprotten in Rapsöl', '4'),
    ('Deutsche see', 'Thunfisch in Olivenöl', '3'),
    ('La Miranda', 'Sardinen in Sonnenblumenöl', '3'),
    ('K-Classic', 'Ananasstücke', '1'),
    ('Raabe Spreewalder Konserven', 'Gewürzgurken nach original DDR-Rezeptur', '4'),
    ('K Classic', 'Gewürzgurken', '4'),
    ('Dittmann', 'Konserve - Gemüse - Pfefferonen scharf', '3'),
    ('Hengstenberg', 'Gurken Sticksi süß-würzig', '4'),
    ('Hengstenberg', 'Cornichons kräuter-würzig', '4'),
    ('Thüringer Landgarten', 'Gewürzgurken', '4'),
    ('Larsen', 'Feine Kieler Sprotten in Rapsöl und eigenem Saft', '4'),
    ('Nixe', 'Thunfisch', '3'),
    ('Appel', 'Zarte Filets vom Hering in Tomaten-Creme', '4'),
    ('KING''S CROWN (Aldi)', 'Tomatenmark', '1'),
    ('Almare', 'Thunfisch Filets in eigenen Saft', '3'),
    ('Aldi', 'Tomatenmark', '1'),
    ('Oro di Parma', 'Famila Oro di Parma Tomatenmark mit Knoblauch 200g 1.29€ 1kg 6.45', '3'),
    ('Aldi', 'Tomaten gehackt', '1'),
    ('Oro Di Parma', 'Tomaten', '3'),
    ('Hawesta', 'Heringsfilets - Tomaten-Creme', '4'),
    ('Aldi', 'Cornichons', '3'),
    ('DmBio', 'Tomatenmark', '1'),
    ('Hawesta', 'Heringsfilets - Pfeffercreme', '4'),
    ('Hengstenberg', 'Mildes Weinsauerkraut', '3'),
    ('Bio Organic', 'Rote Beete', '1'),
    ('Appel', 'Zarte Filets vom Hering in Eier-Senf-Creme', '4'),
    ('Appel', 'Zarte Filets vom Hering Tomate-Mozzarella', '4'),
    ('Aldi', 'Mais', '3'),
    ('Hengstenberg', 'Tomaten - Passiert', '3'),
    ('Sweet Valley', 'Pfirsiche halbe Frucht, leicht gezuckert', '3'),
    ('Deutsche See', 'Thunfisch im Aufguss', '4'),
    ('King''S Crown', 'Rote Beete in Kugeln', '3'),
    ('Kühne', 'Cornichons', '4'),
    ('Otto Franck Import', 'Mandarin-Orangen', '3'),
    ('Lidl', 'Zarte Hertingsfilets in Tomatensauce', '4'),
    ('7 Schwaben Konserven', 'Rote Beete in Scheiben', '3'),
    ('Rügen Fisch', 'Scomber Mix Classic', '4'),
    ('Feinkost Dittmann', 'Pfefferonen', '4'),
    ('Appel', 'Zarte Filets', '4'),
    ('Aldi', 'Mungobohnenkeime', '4'),
    ('Appel', 'Fisch - Zarte Filets vom Hering in Pfeffer Creme', '4'),
    ('Dittmann', 'Pfefferonen', '4'),
    ('Kühne', 'Apfel-Rotkohl', '4'),
    ('Hawesta', 'Heringsfilet - Paprika-Creme', '4'),
    ('Clama', 'Kichererbsen mit Oliven & Karotten in Tomatensauce', '3'),
    ('Lidl', 'Thunfisch Filets', '4'),
    ('Bio', 'Passierte Tomaten', '4'),
    ('Aldi', 'Thunfisch-Filets in eigenem Saft', '3'),
    ('Hengstenberg', 'Rotkohl', '3'),
    ('Kühne', 'Salz-Dill Gurken', '3'),
    ('Spreewaldhof', 'Cornichons von Spreewaldhof', '3'),
    ('Almare Seafood', 'Heringsfilets in Pfeffer-Creme', '4'),
    ('Appel', 'Zarte Filets vom Hering Salsa-Picante', '4'),
    ('Alpenschmaus', 'Gurkentopf', '3'),
    ('DmBio', 'Sauerkraut', '3'),
    ('Appel', 'Heringsfilet in Merettich Creme', '4'),
    ('King''s Crown', 'Feine Cornichons mit Honig', '4'),
    ('Hawesta', 'Heringsfilets Balkan-Sauce', '4'),
    ('Hengstenberg', 'Sandwich Gurken/Glas', '4'),
    ('K-Classic', 'Gehackte Tomaten in Tomatensaft', '1'),
    ('Almare Seafood', 'Fischkonserve', '4'),
    ('K-Classic', 'Champignons in Scheiben', '3'),
    ('K-Classic', 'Tomaten', '1'),
    ('Freshona', 'Sonnenmais natursüß', '3'),
    ('REWE Bio', 'Tomaten in Stücken', '1'),
    ('Aldi', 'Gehackte Tomaten', '1'),
    ('K-Classic', 'Thunfisch Filets I.E.S', '3'),
    ('Edeka', 'Delikatess Gewürzgurken', '3'),
    ('Mutti', 'Geschälte Italienische Tomaten', '1'),
    ('Sweet Valley', 'ALDI SWEET VALLEY OBST Ananas in Scheiben ohne Zuckerzusatz', '1'),
    ('EnerBio', 'Kimchi', '3'),
    ('Edeka Gut & Günstig', 'Obst: Ananas in Stücke', '1'),
    ('Rewe', 'Tomaten stückig', '1'),
    ('Saupiquet', 'Fisch Thunfisch Naturale ohne Öl', '3'),
    ('Edeka', 'Tomaten in Stücken', '1'),
    ('Gut & Günstig', 'Thunfisch in Sonnenblumenöl', '3'),
    ('Gut & Günstig', 'Thunfisch in Öl', '3'),
    ('Hengstenberg', 'Essiggurken', '3'),
    ('Gut & Günstig', 'Sardinen in Sonnenblumenöl', '3'),
    ('Freshona', 'Tomaten gewürfelt', '1'),
    ('DmBio', 'Kimchi', '3'),
    ('Rügen Fisch', 'Kieler Sprotten', '3'),
    ('Penny', 'Junge Erbsen mit Möhren, sehr fein', '3'),
    ('Almare', 'Heringsfilet Tomate', '4'),
    ('Edeka', 'Thunfisch Stücke mit Gemüse', '4'),
    ('Edeka', 'Tomaten geschält', '1'),
    ('Hengstenberg', 'Cornichons', '3'),
    ('K-Classic', 'Cornichons', '3'),
    ('K Classic', 'Gehackte Tomaten', '1'),
    ('Kühne', 'Rote Bete', '4'),
    ('Kühne', 'SilberZwiebeln 40804477 Silberzwiebeln', '4'),
    ('Aldi', 'Ananas', '1'),
    ('Bibigo', 'Kimchi', '4'),
    ('Ja!', 'Sardinen in Sonnenblumenöl', '3'),
    ('Dreimaster', 'Thunfischfilets geschnitten in Sonnenblumenöl', '3'),
    ('REWE Beste Wahl', 'Gegrillte Artischockenviertel in Sonnenblumenöl mit Kräutern', '3'),
    ('Feinkost Dittmann', 'Pfefferonen mild-pikant', '4'),
    ('Appel Appel Fisch', 'Zarte Filets vom Hering Tomate & Curry', '4'),
    ('King''s Crown', 'Peperoni mild', '4'),
    ('Hengstenberg', 'Burger Gurken', '4'),
    ('Rügen Fisch', 'Heringsfilets Feinschmeckerplatte', '4'),
    ('King''s Crown', 'Tomaten passiert klein', '3'),
    ('Hengstenberg', 'Knax - Die Riesen', '3'),
    ('Harvesta', 'Heringsfilet Mexico-Sauce', '4'),
    ('K-Classic', 'Thunfisch in eigenem Saft', '3'),
    ('Feinkost Dittmann', 'Peperoni', '3'),
    ('Appel', 'Zarte Filets vom Hering Tomate-Barbecue', '4'),
    ('Saupiquet', 'Sardinen - in Öl', '3'),
    ('Cornichons', 'Gurken', '4'),
    ('Gut & Günstig', 'Makrelenfilets in Sonnenblumenöl', '3'),
    ('King Crown', 'Gurken', '4'),
    ('Ja!', 'Tomaten geschält', '1'),
    ('King''s Crown', 'Datterini Tomaten', '4'),
    ('Baresa', 'Passierte Tomaten', '1'),
    ('Greenyard Prepared Belgium', 'Erbsen mit Möhren', '1'),
    ('Rügen Fisch', 'Brathering', '4'),
    ('GutBio', 'Tomaten gehackt', '3'),
    ('Kühne', 'Rotkohl', '4'),
    ('Appel', 'Sardinen', '3'),
    ('Kühne', 'Getrocknete Tomaten', '4'),
    ('Gut & Günstig', 'Gurken Topf Gewürzgurken', '3'),
    ('Kühne', 'Cocktail Cornichons', '4'),
    ('Spreewaldhof', 'Cornichons', '3'),
    ('Sol & Mar', 'Spanische grüne Oliven mit Stein', '3'),
    ('Kühne', 'Gurken Moskauer Art', '4'),
    ('RügenFisch', 'Heringsfilet in Senf-Creme', '4'),
    ('BioBio', 'Tomaten stückig', '1'),
    ('K-Classic', 'Champignons Scheiben - Pilze', '3'),
    ('Appel', 'Sardinen Piri-Piri', '4'),
    ('Armada', 'Heringsfilets', '4'),
    ('K-bio', 'Rote Beete Bio/ Kcl', '3'),
    ('Rewe', 'Gemüse - Mais Super-Sweet Gemüsemais', '4'),
    ('Demeter', 'Rote Bete', '4'),
    ('K-Classic', 'Ananas-Scheiben von K-Classic', '4'),
    ('Dittmann', 'Sardinen', '4'),
    ('K-Favourites', 'Premium Cornichons', '3'),
    ('K-Classic', 'Sardinen in Tomatensauce', '4'),
    ('Hawesta', 'HeringsFilets Zwiebel Sauce', '4'),
    ('K Classic', 'Sandwichgurken', '4'),
    ('Rewe Bio', 'Tomaten geschält', '4'),
    ('Almare Seafood', 'Thunfisch filet', '4'),
    ('Fontaine', 'Wildlachsfilet im eigenen Saft', '3'),
    ('DmBio', 'Filetto Du Pomodoro', '1'),
    ('King''s crown', 'Mais', '3'),
    ('ALDI King''s Crown', 'Tomaten -gehackte 400g', '1'),
    ('Hawesta', 'Heringsfilets', '4'),
    ('Pomito', 'Tomatenfruchtfleisch in Stücken', '1'),
    ('Edeka', 'Thunfisch Filets in Olivenöl', '3'),
    ('Followfood', 'Thunfisch Filets in Bio-Sonnenblumenöl', '3'),
    ('Kühne', 'Gurkenhappen Schlesischer Art', '4'),
    ('Saupiquet', 'Thunfisch für Pasta - Knoblauch & Peperoncino', '4'),
    ('Gut & Günstig', 'Champignons ganze Köpfe', '4'),
    ('Hawesta', 'Heringsfilet in Honig-Senf Sauce', '4'),
    ('Rewe', 'Delikatess Gewürzgurken Süss-Sauer', '3'),
    ('Ömur', 'Omur', '3'),
    ('DREIMASTER (Netto)', 'Bücklings Filets (mit Rapsöl)', '3')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Canned Goods', 100, 'DE');
