-- PIPELINE (Condiments): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Kotlin', 'Ketchup Łagodny', 'D'),
    ('Heinz', 'Ketchup łagodny', 'D'),
    ('Tomatini', 'Ketchup łagodny', 'D'),
    ('Roleski', 'Ketchup łagodny markowy', 'D'),
    ('Pudliszki', 'Ketchup łagodny - Najsmaczniejszy', 'C'),
    ('Pudliszki', 'Ketchup łagodny Pudliszek', 'E'),
    ('Agro Nova Food', 'Ketchup pikantny z pomidorów z Kujaw', 'D'),
    ('Kotliński specjał', 'Ketchup łagodny', 'D'),
    ('Pudliszki', 'Ketchup Łagodny Premium', 'D'),
    ('Dawtona', 'Ketchup łagodny', 'E'),
    ('Unknown', 'Ketchup łagodny', 'D'),
    ('Kamis', 'Ketchup włoski', 'D'),
    ('Roleski', 'Ketchup markowy łagodny', 'D'),
    ('Develey', 'Musztarda Stołowa', 'D'),
    ('Pegaz', 'Musztarda stołowa', 'D'),
    ('Develey', 'Musztarda grillowa łagodna', 'C'),
    ('Auchan', 'Musztarda Słodko-Ostra', 'UNKNOWN'),
    ('Ocetix', 'Majonez pomorski stołowy', 'D'),
    ('Motyl', 'Majonez stołowy', 'D'),
    ('Fanex', 'Majonez sałatkowy', 'D'),
    ('Madero', 'Majonez wyborny z żółtkiem z jaja kurzego z chowu z wolnego wybiegu', 'D'),
    ('Piątnica', 'Skyr Jogurt Pitny Typu Islandzkiego - Limonka & Nuta Mięty', 'UNKNOWN'),
    ('Pudliszki', 'Ketchup łagodny', 'D'),
    ('Madero', 'Ketchup Łagodny', 'D'),
    ('Roleski', 'Ketchup Premium Łagodny', 'C'),
    ('Roleski', 'Ketchup premium meksykański KETO', 'C'),
    ('Lewiatan', 'Ketchup Łagodny', 'C'),
    ('Dawtona', 'Lagodny Bez Konserwantów Ketchup', 'D'),
    ('Kotliński', 'Ketchup łagodny', 'D'),
    ('Na Szlaku Smaku', 'Ketchup łagodny', 'E'),
    ('Międzychód', 'Ketchup łagodny', 'C'),
    ('Roleski', 'Ketchup łagodny', 'D'),
    ('Kotlin', 'Ketchup z truskawką', 'D'),
    ('Polskie przetwory', 'Ketchup łagodny', 'D'),
    ('Reypol', 'Ketchup Ziołowy Premium z Nasionami Konopi', 'D'),
    ('Reypol', 'Ketchup premium łagodny', 'D'),
    ('Roleski', 'Musztarda Stołowa', 'D'),
    ('Prymat', 'Musztarda stołowa łagodna', 'D'),
    ('Merkury S.A.', 'Bio Musztarda Łagodna', 'D'),
    ('Grewling', 'Musztarda kcyńska pełnoziarnista', 'D'),
    ('Octim', 'Musztarda o smaku wędzonej papryki i rozmarynu', 'D'),
    ('Mosso', 'Musztarda stołowa', 'D'),
    ('Unknown', 'Richtig Ślonski Zymft', 'C'),
    ('Mosso', 'Majonez Napoleoński', 'D'),
    ('Roleski', 'Majonez stołowy', 'D'),
    ('Pegaz', 'Majonez delikatesowy stołowy', 'D'),
    ('Roleski', 'Majonez wegański', 'D'),
    ('Pudliszki', 'Majonez gęsty kremowy', 'E'),
    ('Pudliszki', 'Majonez gęsty i kremowy', 'E'),
    ('Społem Kielce', 'Majonez kielecki z papryką chipotle', 'D'),
    ('Motyl', 'Majonez napoleoński', 'D'),
    ('Owolovo', 'Mus Jabłko Gruszka Ananas', 'UNKNOWN'),
    ('Kotlin', 'Ketchup hot', 'D'),
    ('Madero', 'Ketchup junior', 'D'),
    ('Roleski', 'Ketchup Premium', 'D'),
    ('Madero', 'Ketchup pikantny', 'E'),
    ('Kotlin', 'Ketchup Łagodny Mnie Kalorii', 'UNKNOWN'),
    ('Develey', 'Ketchup z dodatkiem miodu, czosnku i tymianku.', 'D'),
    ('Roleski', 'Ketchup premium Pikantny', 'D'),
    ('Madero', 'Premium ketchup pikantny', 'D'),
    ('Dawtona', 'Ketchup pikantny', 'D'),
    ('Pudliszki', 'Ketchup Super Pikantny', 'E'),
    ('Kotlin', 'Ketchup pikantny', 'D'),
    ('Madero', 'Ketchup classic', 'D'),
    ('Roleski', 'Ketchup premium jalapeño KETO', 'C'),
    ('Włocławek', 'Ketchup pikantny', 'D'),
    ('Włocławek', 'Ketchup', 'D'),
    ('Fenex', 'Ketchup nr. VII', 'E'),
    ('Krajowa Spółka Cukrowa', 'Ketchup lagoduy', 'UNKNOWN'),
    ('Kotlin sp. z o. o.', 'Ketchup kotliński', 'D'),
    ('Fenex', 'Ketchup nr VII', 'E'),
    ('Develey', 'Ketchup Pikantny', 'D'),
    ('Kotlin', 'Kotlin Ketchup Premium', 'D'),
    ('Kamis', 'Musztarda sarepska ostra', 'D'),
    ('Madero', 'Musztarda sarepska', 'D'),
    ('Prymat', 'Musztarda miodowa', 'D'),
    ('Społem Kielce', 'Moutarde Kielecka Forte', 'D'),
    ('Pegaz', 'Musztarda sarepska', 'C'),
    ('Roleski', 'Musztarda sarepska', 'D'),
    ('Unknown', 'Musztarda stołowa', 'E'),
    ('Carrefour classic', 'Moutarde', 'D'),
    ('Develey', 'Musztarda sarepska', 'C'),
    ('Madero', 'Musztarda Dijon', 'E'),
    ('Develey', 'Musztarda francuska', 'D'),
    ('Firma Roleski', 'Mutarde', 'D'),
    ('Develey', 'Musztarda Bawarska', 'E'),
    ('Roleski', 'Musztarda delikatesowa jerozolimska', 'D'),
    ('Develey', 'Musztarda gastronomiczna', 'D'),
    ('Develey', 'Horcice. Musztarda kremska', 'D'),
    ('Czas na Grill', 'Musztarda Jalapeño', 'D'),
    ('Roleski', 'Musztarda delikatesowa', 'D'),
    ('Roleski', 'Musztarda delikatesowa kozaka', 'D'),
    ('Rikka', 'Musztarda kremska', 'D'),
    ('Roleski', 'Moutarde Dijon', 'E'),
    ('Spolem', 'Spo?e Musztarda Delikatesowa 190Ml', 'D'),
    ('Develey', 'Musztarda Rosyjska', 'D'),
    ('Roleski', 'Musztarda delikatesowa angielska.', 'E'),
    ('Winiary', 'Majonez Dekoracyjny', 'D'),
    ('Winiary', 'Mayonnaise Decorative', 'D'),
    ('Polnisch', 'Majonez Kielecki', 'D'),
    ('Madero', 'Majonez delikatesowy', 'D'),
    ('Społem Kielce', 'Majonez Kielecki', 'D'),
    ('Madero', 'Majonez', 'D'),
    ('Wielkopolski', 'Majonez wielkopolski', 'D'),
    ('Roleski', 'Majonez', 'D'),
    ('Biedronka', 'Majonez z Truflami', 'D'),
    ('Auchan', 'Majonez', 'D'),
    ('Pudliszki', 'Majonez', 'E'),
    ('Quallio', 'Majonez', 'D'),
    ('Roleski', 'Majonez roleskiego.', 'D'),
    ('Agrovita', 'Majonez wyborowy', 'D'),
    ('Pano', 'Tost Maślany', 'C'),
    ('Delikate', 'Serek biały puszysty', 'UNKNOWN'),
    ('Pani', 'Tortilla', 'B'),
    ('Kraina wędlin', 'Głodniaki szyneczka z fileta kurczaka', 'UNKNOWN'),
    ('Pudliszki', 'Ketchup pikantny', 'E'),
    ('Pudliszki', 'Ketchup Lagodny', 'D'),
    ('Pudliszki', 'Ketchup Pudliszki 0%', 'C'),
    ('Roleski', 'Ketchup premium sycylijski KETO do pizzy', 'C'),
    ('Heinz', 'Ketchup pikantny', 'UNKNOWN'),
    ('Kotlin', 'Ketchup Pikantny Hot', 'D'),
    ('Wloclawek', 'Wloclawek Mild Tomato Ketchup', 'D'),
    ('Pudliszki', 'Ketchup 0', 'A'),
    ('Błonie', 'Ketchup pikantny', 'D'),
    ('Międzychód', 'Ketchup pikantny', 'D'),
    ('Maspex', 'Ketchup Pikantny', 'D'),
    ('Białuty', 'Ketchup pikantny', 'D'),
    ('Roleski', 'Ketchup bio ekologiczny Roleski', 'D'),
    ('Pudliszki', 'Ketchup czosnkowy', 'E'),
    ('Lidl', 'Ketchup łagodny', 'E'),
    ('Roleski', 'Firma Roleski Hot Ketchup 450 G', 'D'),
    ('Roleski', 'Ketchup Premium Jalapeño', 'E'),
    ('KFD', 'Premium sauce XXL - sos o smaku ketchupu', 'C'),
    ('Kotliński', 'Ketchup pikantny', 'D'),
    ('Roleski', 'Ketchup pikantny gastronomiczny', 'C'),
    ('Roleski', 'Ketchup pikantny', 'D'),
    ('Kamis', 'Ketchup pikatny', 'D'),
    ('Reypol', 'Ketchup premium pikantny', 'D'),
    ('Heinz', 'Heinz Zero Sel Ajoute', 'A'),
    ('Heinz', 'Zerp', 'A'),
    ('Kamis', 'Musztarda delikatesowa', 'D'),
    ('Roleski', 'Musztarda delikatesowa sarepska', 'D'),
    ('Prymat', 'Musztarda sarepska ostra', 'D'),
    ('Develey', 'Mustard Horcice kremzska', 'D'),
    ('Madero', 'Musztarda Sarepska ostra', 'D'),
    ('Develey', 'Musztarda Dijon premium', 'E'),
    ('Prymat', 'Musztarda francuska', 'D'),
    ('Lidl', 'Musztarda stołowa łagodna', 'D'),
    ('Prymat', 'Musztarda Jalapeño', 'D'),
    ('Kamis', 'Musztarda czeska', 'D'),
    ('Kamis', 'Musztarda Sarepska', 'D'),
    ('Kamis', 'Musztarda rosyjska', 'E'),
    ('Prymat', 'Musztarda Delikatesowa', 'C'),
    ('Pegaz', 'Musztarda piekielna', 'D'),
    ('Develey', 'Musztarda Sarepska premium', 'C'),
    ('Naura', 'Bio Musztarda Ostra', 'D'),
    ('Kamis', 'Musztarda francuska', 'E'),
    ('Mosso', 'Musztarda czeska', 'D'),
    ('Nestlé', 'Winiary Mayonnaise Decorative', 'D'),
    ('Kielecki', 'Mayonnaise Kielecki', 'D'),
    ('Kielecki', 'Majonez Kielecki lekki', 'D'),
    ('Madero', 'Majonez Wyborny', 'D'),
    ('Winiary', 'Majonez sałatkowy', 'D'),
    ('Develey', 'Majonez z chilli jalapeño', 'D'),
    ('Kętrzyński', 'Majonez klasyczny', 'D'),
    ('Roleski', 'Majonez Roleskiego Premium', 'D'),
    ('Społem', 'Mayonnaise Kielecki', 'E'),
    ('Tarczyński', 'Parowki Z Fileta Z Indyka', 'E'),
    ('Danone', 'Danio serek waniliowy', 'UNKNOWN'),
    ('Tymbark', 'Jago Da', 'A'),
    ('Unknown', 'Wloclawek Hot Tomato Ketchup', 'D'),
    ('Roleski', 'Ketchup Roleski', 'UNKNOWN'),
    ('Tortex', 'Łagodny', 'D'),
    ('Unknown', 'Ketchup premium sycylijski do pizzy', 'E'),
    ('Unknown', 'Spicy ketchup', 'UNKNOWN'),
    ('Tortex', 'Ketchup łagodny', 'D'),
    ('Winiary', 'Ketchup łagodny', 'D'),
    ('Unknown', 'Medero Premium ketchup classic', 'UNKNOWN'),
    ('Kotlin', 'Ketchup z pomidorami malinowymi', 'D'),
    ('Fanex Sp. z o.o.', 'Ketchup nr VII', 'E'),
    ('Dzik', 'Ketchup', 'C'),
    ('Madero', 'Musztarda miodowa', 'UNKNOWN'),
    ('Kamis', 'Musztarda chrzanowa', 'D'),
    ('Devely', 'Musztarda Miodowa', 'UNKNOWN'),
    ('Kaufland', 'Majonez z żółtkiem z jaj od kur na wolnym wybiegu', 'D'),
    ('Wild Bean Cafe', 'Majonez stołowy', 'D'),
    ('Top Chips', 'Chipsy Solone', 'UNKNOWN'),
    ('Łaciate', 'Czokomleko', 'UNKNOWN'),
    ('Unknown', 'Waterr', 'UNKNOWN'),
    ('Oshee', 'Oshee', 'UNKNOWN'),
    ('Lipton', 'Lipton brzoskwiniowy', 'UNKNOWN'),
    ('Tarczyński', 'Kabanos exclusive chilli', 'UNKNOWN'),
    ('Kania', 'Ketchup pikantny', 'E'),
    ('Heinz', 'Tomato edchup', 'D'),
    ('K-Classic', 'Ketchup Hot', 'D'),
    ('Chestfords', 'Ketchup', 'D'),
    ('Hellman''s', 'Ketchup Hot Pikantny', 'D'),
    ('Heinz', 'Tomato Ketchup', 'D'),
    ('Kania', 'Musztarda Dijon', 'E'),
    ('Kania', 'Musztarda francuska premium', 'D'),
    ('Heinz', 'Heinz Mayonesa', 'D'),
    ('Winiary', 'Majonez z olejem z awokado', 'D'),
    ('Kaufland', 'Mayonnaise sauce', 'D'),
    ('Lidl', 'Gelierzucker 2:1', 'A'),
    ('Tortex', 'Pikantny Ketchup z charakterem', 'D'),
    ('Winiary', 'Ketchup pikantny', 'D'),
    ('Winiary', 'Ketchup super hot', 'D'),
    ('Tortex', 'Tagodny ketchup', 'D'),
    ('K-Classic (Dawtona)', 'Ketchup pomidorowy pikantny', 'D'),
    ('McDonald''s', 'Tomato Ketchup', 'D'),
    ('Ikea', 'Sås Senap & Dill - Sauce à la moutarde et à l''aneth', 'D'),
    ('Roleski', 'Kuchnia Smaku Musztarda Sarepska', 'D'),
    ('BBQ', 'Musztarda miodowa', 'D'),
    ('Winiary', 'Majonez lekki', 'D'),
    ('Hellmann''s', 'Babuni Majonez Mayonnaise', 'D'),
    ('Winiary', 'Majonez delikatny', 'D'),
    ('Winiary', 'Majonez OMEGA 3:6', 'D'),
    ('Babcia Magdalena', 'Mayonnaise', 'D'),
    ('Tortex', 'Ketchup Pikantny', 'D'),
    ('Unknown', 'Tomato ketchup spicy curry', 'E'),
    ('Hellmann''s', 'Original Mayonnaise', 'D'),
    ('Pilos', 'Food In A Bottle', 'UNKNOWN')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Kotlin', 'Ketchup Łagodny', '4'),
    ('Heinz', 'Ketchup łagodny', '3'),
    ('Tomatini', 'Ketchup łagodny', '4'),
    ('Roleski', 'Ketchup łagodny markowy', '3'),
    ('Pudliszki', 'Ketchup łagodny - Najsmaczniejszy', '4'),
    ('Pudliszki', 'Ketchup łagodny Pudliszek', '4'),
    ('Agro Nova Food', 'Ketchup pikantny z pomidorów z Kujaw', '4'),
    ('Kotliński specjał', 'Ketchup łagodny', '4'),
    ('Pudliszki', 'Ketchup Łagodny Premium', '4'),
    ('Dawtona', 'Ketchup łagodny', '4'),
    ('Unknown', 'Ketchup łagodny', '4'),
    ('Kamis', 'Ketchup włoski', '4'),
    ('Roleski', 'Ketchup markowy łagodny', '3'),
    ('Develey', 'Musztarda Stołowa', '3'),
    ('Pegaz', 'Musztarda stołowa', '3'),
    ('Develey', 'Musztarda grillowa łagodna', '4'),
    ('Auchan', 'Musztarda Słodko-Ostra', '4'),
    ('Ocetix', 'Majonez pomorski stołowy', '4'),
    ('Motyl', 'Majonez stołowy', '4'),
    ('Fanex', 'Majonez sałatkowy', '4'),
    ('Madero', 'Majonez wyborny z żółtkiem z jaja kurzego z chowu z wolnego wybiegu', '3'),
    ('Piątnica', 'Skyr Jogurt Pitny Typu Islandzkiego - Limonka & Nuta Mięty', '4'),
    ('Pudliszki', 'Ketchup łagodny', '4'),
    ('Madero', 'Ketchup Łagodny', '4'),
    ('Roleski', 'Ketchup Premium Łagodny', '4'),
    ('Roleski', 'Ketchup premium meksykański KETO', '4'),
    ('Lewiatan', 'Ketchup Łagodny', '4'),
    ('Dawtona', 'Lagodny Bez Konserwantów Ketchup', '3'),
    ('Kotliński', 'Ketchup łagodny', '4'),
    ('Na Szlaku Smaku', 'Ketchup łagodny', '4'),
    ('Międzychód', 'Ketchup łagodny', '3'),
    ('Roleski', 'Ketchup łagodny', '4'),
    ('Kotlin', 'Ketchup z truskawką', '4'),
    ('Polskie przetwory', 'Ketchup łagodny', '4'),
    ('Reypol', 'Ketchup Ziołowy Premium z Nasionami Konopi', '3'),
    ('Reypol', 'Ketchup premium łagodny', '4'),
    ('Roleski', 'Musztarda Stołowa', '3'),
    ('Prymat', 'Musztarda stołowa łagodna', '4'),
    ('Merkury S.A.', 'Bio Musztarda Łagodna', '3'),
    ('Grewling', 'Musztarda kcyńska pełnoziarnista', '3'),
    ('Octim', 'Musztarda o smaku wędzonej papryki i rozmarynu', '4'),
    ('Mosso', 'Musztarda stołowa', '4'),
    ('Unknown', 'Richtig Ślonski Zymft', '3'),
    ('Mosso', 'Majonez Napoleoński', '4'),
    ('Roleski', 'Majonez stołowy', '4'),
    ('Pegaz', 'Majonez delikatesowy stołowy', '3'),
    ('Roleski', 'Majonez wegański', '4'),
    ('Pudliszki', 'Majonez gęsty kremowy', '3'),
    ('Pudliszki', 'Majonez gęsty i kremowy', '3'),
    ('Społem Kielce', 'Majonez kielecki z papryką chipotle', '4'),
    ('Motyl', 'Majonez napoleoński', '3'),
    ('Owolovo', 'Mus Jabłko Gruszka Ananas', '4'),
    ('Kotlin', 'Ketchup hot', '4'),
    ('Madero', 'Ketchup junior', '3'),
    ('Roleski', 'Ketchup Premium', '3'),
    ('Madero', 'Ketchup pikantny', '4'),
    ('Kotlin', 'Ketchup Łagodny Mnie Kalorii', '4'),
    ('Develey', 'Ketchup z dodatkiem miodu, czosnku i tymianku.', '3'),
    ('Roleski', 'Ketchup premium Pikantny', '3'),
    ('Madero', 'Premium ketchup pikantny', '4'),
    ('Dawtona', 'Ketchup pikantny', '4'),
    ('Pudliszki', 'Ketchup Super Pikantny', '4'),
    ('Kotlin', 'Ketchup pikantny', '4'),
    ('Madero', 'Ketchup classic', '4'),
    ('Roleski', 'Ketchup premium jalapeño KETO', '4'),
    ('Włocławek', 'Ketchup pikantny', '4'),
    ('Włocławek', 'Ketchup', '4'),
    ('Fenex', 'Ketchup nr. VII', '4'),
    ('Krajowa Spółka Cukrowa', 'Ketchup lagoduy', '4'),
    ('Kotlin sp. z o. o.', 'Ketchup kotliński', '4'),
    ('Fenex', 'Ketchup nr VII', '4'),
    ('Develey', 'Ketchup Pikantny', '4'),
    ('Kotlin', 'Kotlin Ketchup Premium', '4'),
    ('Kamis', 'Musztarda sarepska ostra', '4'),
    ('Madero', 'Musztarda sarepska', '3'),
    ('Prymat', 'Musztarda miodowa', '4'),
    ('Społem Kielce', 'Moutarde Kielecka Forte', '4'),
    ('Pegaz', 'Musztarda sarepska', '3'),
    ('Roleski', 'Musztarda sarepska', '4'),
    ('Unknown', 'Musztarda stołowa', '4'),
    ('Carrefour classic', 'Moutarde', '4'),
    ('Develey', 'Musztarda sarepska', '4'),
    ('Madero', 'Musztarda Dijon', '3'),
    ('Develey', 'Musztarda francuska', '3'),
    ('Firma Roleski', 'Mutarde', '3'),
    ('Develey', 'Musztarda Bawarska', '3'),
    ('Roleski', 'Musztarda delikatesowa jerozolimska', '4'),
    ('Develey', 'Musztarda gastronomiczna', '3'),
    ('Develey', 'Horcice. Musztarda kremska', '4'),
    ('Czas na Grill', 'Musztarda Jalapeño', '4'),
    ('Roleski', 'Musztarda delikatesowa', '4'),
    ('Roleski', 'Musztarda delikatesowa kozaka', '4'),
    ('Rikka', 'Musztarda kremska', '3'),
    ('Roleski', 'Moutarde Dijon', '3'),
    ('Spolem', 'Spo?e Musztarda Delikatesowa 190Ml', '4'),
    ('Develey', 'Musztarda Rosyjska', '3'),
    ('Roleski', 'Musztarda delikatesowa angielska.', '4'),
    ('Winiary', 'Majonez Dekoracyjny', '4'),
    ('Winiary', 'Mayonnaise Decorative', '4'),
    ('Polnisch', 'Majonez Kielecki', '3'),
    ('Madero', 'Majonez delikatesowy', '3'),
    ('Społem Kielce', 'Majonez Kielecki', '3'),
    ('Madero', 'Majonez', '3'),
    ('Wielkopolski', 'Majonez wielkopolski', '4'),
    ('Roleski', 'Majonez', '4'),
    ('Biedronka', 'Majonez z Truflami', '4'),
    ('Auchan', 'Majonez', '4'),
    ('Pudliszki', 'Majonez', '3'),
    ('Quallio', 'Majonez', '4'),
    ('Roleski', 'Majonez roleskiego.', '4'),
    ('Agrovita', 'Majonez wyborowy', '3'),
    ('Pano', 'Tost Maślany', '4'),
    ('Delikate', 'Serek biały puszysty', '4'),
    ('Pani', 'Tortilla', '4'),
    ('Kraina wędlin', 'Głodniaki szyneczka z fileta kurczaka', '4'),
    ('Pudliszki', 'Ketchup pikantny', '4'),
    ('Pudliszki', 'Ketchup Lagodny', '4'),
    ('Pudliszki', 'Ketchup Pudliszki 0%', '4'),
    ('Roleski', 'Ketchup premium sycylijski KETO do pizzy', '4'),
    ('Heinz', 'Ketchup pikantny', '4'),
    ('Kotlin', 'Ketchup Pikantny Hot', '4'),
    ('Wloclawek', 'Wloclawek Mild Tomato Ketchup', '4'),
    ('Pudliszki', 'Ketchup 0', '4'),
    ('Błonie', 'Ketchup pikantny', '4'),
    ('Międzychód', 'Ketchup pikantny', '4'),
    ('Maspex', 'Ketchup Pikantny', '4'),
    ('Białuty', 'Ketchup pikantny', '4'),
    ('Roleski', 'Ketchup bio ekologiczny Roleski', '3'),
    ('Pudliszki', 'Ketchup czosnkowy', '4'),
    ('Lidl', 'Ketchup łagodny', '4'),
    ('Roleski', 'Firma Roleski Hot Ketchup 450 G', '3'),
    ('Roleski', 'Ketchup Premium Jalapeño', '4'),
    ('KFD', 'Premium sauce XXL - sos o smaku ketchupu', '4'),
    ('Kotliński', 'Ketchup pikantny', '4'),
    ('Roleski', 'Ketchup pikantny gastronomiczny', '4'),
    ('Roleski', 'Ketchup pikantny', '4'),
    ('Kamis', 'Ketchup pikatny', '4'),
    ('Reypol', 'Ketchup premium pikantny', '4'),
    ('Heinz', 'Heinz Zero Sel Ajoute', '4'),
    ('Heinz', 'Zerp', '4'),
    ('Kamis', 'Musztarda delikatesowa', '4'),
    ('Roleski', 'Musztarda delikatesowa sarepska', '4'),
    ('Prymat', 'Musztarda sarepska ostra', '4'),
    ('Develey', 'Mustard Horcice kremzska', '4'),
    ('Madero', 'Musztarda Sarepska ostra', '3'),
    ('Develey', 'Musztarda Dijon premium', '3'),
    ('Prymat', 'Musztarda francuska', '4'),
    ('Lidl', 'Musztarda stołowa łagodna', '4'),
    ('Prymat', 'Musztarda Jalapeño', '4'),
    ('Kamis', 'Musztarda czeska', '3'),
    ('Kamis', 'Musztarda Sarepska', '4'),
    ('Kamis', 'Musztarda rosyjska', '4'),
    ('Prymat', 'Musztarda Delikatesowa', '4'),
    ('Pegaz', 'Musztarda piekielna', '3'),
    ('Develey', 'Musztarda Sarepska premium', '4'),
    ('Naura', 'Bio Musztarda Ostra', '3'),
    ('Kamis', 'Musztarda francuska', '4'),
    ('Mosso', 'Musztarda czeska', '3'),
    ('Nestlé', 'Winiary Mayonnaise Decorative', '4'),
    ('Kielecki', 'Mayonnaise Kielecki', '3'),
    ('Kielecki', 'Majonez Kielecki lekki', '4'),
    ('Madero', 'Majonez Wyborny', '3'),
    ('Winiary', 'Majonez sałatkowy', '4'),
    ('Develey', 'Majonez z chilli jalapeño', '4'),
    ('Kętrzyński', 'Majonez klasyczny', '4'),
    ('Roleski', 'Majonez Roleskiego Premium', '4'),
    ('Społem', 'Mayonnaise Kielecki', '4'),
    ('Tarczyński', 'Parowki Z Fileta Z Indyka', '3'),
    ('Danone', 'Danio serek waniliowy', '4'),
    ('Tymbark', 'Jago Da', '1'),
    ('Unknown', 'Wloclawek Hot Tomato Ketchup', '4'),
    ('Roleski', 'Ketchup Roleski', '4'),
    ('Tortex', 'Łagodny', '4'),
    ('Unknown', 'Ketchup premium sycylijski do pizzy', '4'),
    ('Unknown', 'Spicy ketchup', '4'),
    ('Tortex', 'Ketchup łagodny', '4'),
    ('Winiary', 'Ketchup łagodny', '4'),
    ('Unknown', 'Medero Premium ketchup classic', '4'),
    ('Kotlin', 'Ketchup z pomidorami malinowymi', '4'),
    ('Fanex Sp. z o.o.', 'Ketchup nr VII', '4'),
    ('Dzik', 'Ketchup', '4'),
    ('Madero', 'Musztarda miodowa', '4'),
    ('Kamis', 'Musztarda chrzanowa', '4'),
    ('Devely', 'Musztarda Miodowa', '4'),
    ('Kaufland', 'Majonez z żółtkiem z jaj od kur na wolnym wybiegu', '3'),
    ('Wild Bean Cafe', 'Majonez stołowy', '4'),
    ('Top Chips', 'Chipsy Solone', '4'),
    ('Łaciate', 'Czokomleko', '4'),
    ('Unknown', 'Waterr', '4'),
    ('Oshee', 'Oshee', '4'),
    ('Lipton', 'Lipton brzoskwiniowy', '4'),
    ('Tarczyński', 'Kabanos exclusive chilli', '4'),
    ('Kania', 'Ketchup pikantny', '4'),
    ('Heinz', 'Tomato edchup', '3'),
    ('K-Classic', 'Ketchup Hot', '3'),
    ('Chestfords', 'Ketchup', '4'),
    ('Hellman''s', 'Ketchup Hot Pikantny', '3'),
    ('Heinz', 'Tomato Ketchup', '3'),
    ('Kania', 'Musztarda Dijon', '3'),
    ('Kania', 'Musztarda francuska premium', '3'),
    ('Heinz', 'Heinz Mayonesa', '3'),
    ('Winiary', 'Majonez z olejem z awokado', '4'),
    ('Kaufland', 'Mayonnaise sauce', '3'),
    ('Lidl', 'Gelierzucker 2:1', '2'),
    ('Tortex', 'Pikantny Ketchup z charakterem', '4'),
    ('Winiary', 'Ketchup pikantny', '3'),
    ('Winiary', 'Ketchup super hot', '3'),
    ('Tortex', 'Tagodny ketchup', '4'),
    ('K-Classic (Dawtona)', 'Ketchup pomidorowy pikantny', '3'),
    ('McDonald''s', 'Tomato Ketchup', '4'),
    ('Ikea', 'Sås Senap & Dill - Sauce à la moutarde et à l''aneth', '4'),
    ('Roleski', 'Kuchnia Smaku Musztarda Sarepska', '4'),
    ('BBQ', 'Musztarda miodowa', '3'),
    ('Winiary', 'Majonez lekki', '4'),
    ('Hellmann''s', 'Babuni Majonez Mayonnaise', '4'),
    ('Winiary', 'Majonez delikatny', '4'),
    ('Winiary', 'Majonez OMEGA 3:6', '4'),
    ('Babcia Magdalena', 'Mayonnaise', '4'),
    ('Tortex', 'Ketchup Pikantny', '4'),
    ('Unknown', 'Tomato ketchup spicy curry', '4'),
    ('Hellmann''s', 'Original Mayonnaise', '4'),
    ('Pilos', 'Food In A Bottle', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Condiments', 100, 'PL');
