-- PIPELINE (Bread): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-04

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Gräfschafter', 'Eiweißreiches Weizenvollkornbrot', 'Lidl'),
    ('Harry', 'Körner Balance Sandwich', 'Lidl'),
    ('Harry', 'Körner Balance Sandwich', 'Kaufland'),
    ('Golden Toast', 'Sandwich Körner-Harmonie', 'Edeka'),
    ('Lieken Urkorn', 'Fitnessbrot mit 5 % Ölsaaten', 'Edeka'),
    ('Lieken Urkorn', 'Fitnessbrot mit 5 % Ölsaaten', 'REWE'),
    ('Lieken Urkorn', 'Fitnessbrot mit 5 % Ölsaaten', 'Netto'),
    ('Harry', 'Eiweißbrot', 'REWE'),
    ('Harry', 'Harry Dinkel Krüstchen 4071800057637', 'Kaufland'),
    ('Aldi', 'Das Pure - Bio-Haferbrot mit 29% Ölsaaten', 'Aldi'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'Aldi'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'Lidl'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'Edeka'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'REWE'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'Penny'),
    ('Conditorei Coppenrath & Wiese', 'Weizenbrötchen', 'Netto'),
    ('Lieken', 'Roggenbäcker', 'Netto'),
    ('Goldähren', 'Französisches Steinofen-Baguette', 'Aldi'),
    ('Goldähren', 'Laugen-Brioche vorgeschnitten, 6 Stück', 'Aldi'),
    ('Mestemacher', 'Westfälischen Pumpernickel', 'Edeka'),
    ('Goldähren', 'Toast-Brötchen Protein', 'Aldi'),
    ('Goldähren', 'Proteinbrötchen zum Fertigbacken', 'Aldi'),
    ('Grafschafter', 'Mehrkorn-Toastbrötchen', 'Lidl'),
    ('Conditorei Coppenrath & Wiese', 'Baguette-Brötchen', 'Edeka'),
    ('Conditorei Coppenrath & Wiese', 'Baguette-Brötchen', 'REWE'),
    ('Cucina', 'Grissotti - Olivenöl und Meersalz', 'Aldi'),
    ('K-Classic', 'Toastbrötchen Mehrkorn', 'Kaufland'),
    ('Golden Toast', 'Körnerharmonie-Toast', 'Edeka'),
    ('Golden Toast', 'Körnerharmonie-Toast', 'REWE'),
    ('Golden Toast', 'Körnerharmonie-Toast', 'Penny'),
    ('Mestemacher', 'High Protein Eiweißbrot', 'Edeka'),
    ('Mestemacher', 'High Protein Eiweißbrot', 'REWE'),
    ('EDEKA Harry', 'EDEKA Harry Harry XXL Burger Brötchen 4 Stück 300g 1.79€ 1kg 5.97€', 'Edeka'),
    ('EDEKA Harry', 'EDEKA Harry Harry XXL Burger Brötchen 4 Stück 300g 1.79€ 1kg 5.97€', 'Netto'),
    ('EDEKA Harry', 'EDEKA Harry Harry XXL Burger Brötchen 4 Stück 300g 1.79€ 1kg 5.97€', 'Kaufland'),
    ('Golden Toast', 'Körner Toasties (2x 3 Stück, 300 g; pro 3 Stück aufgeführt)', 'Edeka'),
    ('Grafschafter', 'Pure Kornkraft Haferbrot', 'Lidl'),
    ('Goldähren', 'Vollkorn-Sandwich', 'Aldi'),
    ('Golden Toast', 'Vollkorn-Toast', 'Aldi'),
    ('Golden Toast', 'Vollkorn-Toast', 'Lidl'),
    ('Golden Toast', 'Vollkorn-Toast', 'Edeka'),
    ('Golden Toast', 'Vollkorn-Toast', 'REWE'),
    ('Golden Toast', 'Vollkorn-Toast', 'Penny'),
    ('Golden Toast', 'Vollkorn-Toast', 'Netto'),
    ('Harry', 'Harry Brot Vital + Fit', 'Edeka'),
    ('Harry', 'Harry Brot Vital + Fit', 'Norma'),
    ('Goldähren', 'Vollkorntoast', 'Aldi'),
    ('Meierbaer & Albro', 'Das Pure - Bio-Haferbrot', 'Aldi'),
    ('Goldähren', 'Mehrkorn Wraps', 'Aldi'),
    ('Goldähren', 'Protein-Wraps', 'Aldi'),
    ('Nur Nur Natur', 'Bio-Roggenvollkornbrot', 'Aldi'),
    ('DmBio', 'Das Pure Hafer - und Saatenbrot', 'dm'),
    ('Goldähren', 'American Sandwich - Weizen', 'Aldi'),
    ('Harry', 'Vollkorn Toast', 'Edeka'),
    ('Brandt', 'Brandt Markenzwieback', 'Edeka'),
    ('Brandt', 'Brandt Markenzwieback', 'REWE'),
    ('Harry', 'Unser Mildes (Weizenmischbrot)', 'REWE'),
    ('Harry', 'Unser Mildes (Weizenmischbrot)', 'Netto'),
    ('Harry', 'Unser Mildes (Weizenmischbrot)', 'Norma'),
    ('Lieken', 'Bauernmild Brot', 'Lidl'),
    ('Lieken', 'Bauernmild Brot', 'Edeka'),
    ('Lieken', 'Bauernmild Brot', 'REWE'),
    ('Lieken', 'Bauernmild Brot', 'Netto'),
    ('Lieken', 'Bauernmild Brot', 'Norma'),
    ('Lieken Urkorn', 'Vollkornsaftiges fein', 'Edeka'),
    ('Lieken Urkorn', 'Vollkornsaftiges fein', 'REWE'),
    ('Lieken Urkorn', 'Vollkornsaftiges fein', 'Netto'),
    ('Goldähren', 'Mehrkornschnitten', 'Aldi'),
    ('Mestemacher', 'Dinkel Wraps', 'REWE'),
    ('Harry', 'Toastbrot', 'REWE'),
    ('Harry', 'Toastbrot', 'Kaufland'),
    ('Harry', 'Vollkorn Urtyp', 'REWE'),
    ('Golden Toast', 'Vollkorn Toast', 'Edeka'),
    ('Golden Toast', 'Vollkorn Toast', 'Netto'),
    ('Harry', 'Harry 1688 Korn an Korn', 'Norma'),
    ('Golden Toast', 'Buttertoast', 'Aldi'),
    ('Golden Toast', 'Buttertoast', 'Lidl'),
    ('Golden Toast', 'Buttertoast', 'Netto'),
    ('Golden Toast', 'Buttertoast', 'Tegut'),
    ('Brandt', 'Der Markenzwieback', 'Netto'),
    ('Gutes aus der Bäckerei', 'Weissbrot', 'REWE'),
    ('Gutes aus der Bäckerei', 'Weissbrot', 'Kaufland'),
    ('Harry', 'Mischbrot Anno 1688 Klassisch, Harry', 'Edeka'),
    ('Goldähren', 'Dreisaatbrot - Roggenvollkornbrot', 'Aldi'),
    ('Golden Toast', 'Dinkel-Harmonie Sandwich', 'Edeka'),
    ('Golden Toast', 'Dinkel-Harmonie Sandwich', 'REWE'),
    ('Filinchen', 'Das Knusperbrot Original', 'REWE'),
    ('Filinchen', 'Das Knusperbrot Original', 'Netto'),
    ('Goldähren', 'Saaten-Sandwich', 'Aldi'),
    ('Cucina', 'Pinsa', 'Aldi'),
    ('Nur Nur Natur', 'Das Pure Bio', 'Aldi'),
    ('Harry', '1688 Mehrkorn', 'REWE'),
    ('Harry', '1688 Mehrkorn', 'Norma'),
    ('Goldähren', 'Wraps - Weizen', 'Aldi'),
    ('Harry', 'Vital & pur', 'REWE'),
    ('Harry', 'Vollkorn mit Sonnenblumenkernen', 'REWE'),
    ('Harry', 'Vollkorn mit Sonnenblumenkernen', 'Kaufland'),
    ('Golden Toast', 'Vollkorn-Harmonie Sandwich', 'Edeka'),
    ('Harry', 'Roggenvollkornbrot Sonnenkern', 'Edeka'),
    ('Harry', 'Roggenvollkornbrot Sonnenkern', 'REWE'),
    ('Goldähren', 'Bauernschnitten', 'Aldi'),
    ('Harry', 'Voll:Korn - Katen - Harry 1688', 'Edeka'),
    ('Grafschafter', 'Bauernmildes Weizenmischbrot', 'Lidl'),
    ('Harry', 'Eiweiss Sandwich', 'REWE'),
    ('Aldi', 'Volles Korn dunkel - Roggenvollkornbrot', 'Aldi'),
    ('Grafschafter', 'American Style Sandwich Weizen', 'Lidl'),
    ('Grafschafter', 'Pfundsschnitten Roggenmischbrot', 'Lidl'),
    ('Goldähren', 'Das Rustikale - Dinkel', 'Aldi'),
    ('Brandt', 'Mini-Zwieback', 'Aldi'),
    ('Brandt', 'Mini-Zwieback', 'Edeka'),
    ('Brandt', 'Mini-Zwieback', 'REWE'),
    ('Kronenbrot', 'Rustikales Dinkel', 'Netto'),
    ('Grafschafter', 'Balance Brot', 'Lidl'),
    ('Goldähren', 'Dinkel-Sandwich', 'Aldi'),
    ('Golden Toast', 'American Sandwich', 'Edeka'),
    ('Golden Toast', 'American Sandwich', 'REWE'),
    ('Golden Toast', 'American Sandwich', 'Netto'),
    ('Harry', 'Krustenbrot', 'REWE'),
    ('Grafschafter', 'American Style Sandwich Vollkorn', 'Lidl'),
    ('Harry', 'Weltmeister Mehrkornbrot', 'REWE'),
    ('Cucina', 'Grissotti - Sesam', 'Aldi'),
    ('Grafschafter', 'Laugen-Brezeln', 'Lidl'),
    ('Backländer GmbH', 'Mehrkorn-Schnitten', 'Lidl')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Bread' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
