-- PIPELINE (Desserts & Ice Cream): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Fruvita', 'Jogurt typu islandzkiego SKYR Naturalny 0% tłuszczu', 'A'),
    ('Piątnica', 'Skyr z mango i marakują', 'A'),
    ('Piatnica', 'Skyr jogurt pitny typu islandzkiego Wiśnia', 'E'),
    ('OwoLovo', 'OwoLowo Jabłkowo', 'A'),
    ('Tutti', 'Tutti - serek o smaku waniliowym z pokruszoną laską wanilii', 'C'),
    ('Jovi', 'Napój jogurtowy Duet Banan-Truskawka', 'B'),
    ('Piątnica', 'Serek Wiejski Z Malinami I Żurawiną', 'C'),
    ('Zott', 'Jogurt jabłko i gruszka', 'A'),
    ('Amelia', 'Waniliowy 3 składniki', 'C'),
    ('Vital Fresh', 'Mus Jabłko Banan Marakuja', 'A'),
    ('Fruvita', 'Mixo Jabłko-Gruszka', 'C'),
    ('Łaciaty', 'Łaciaty SEREK WIEJSKI', 'B'),
    ('Bakoma', 'Maxi Meal o smaku słonego karmelu', 'A'),
    ('Maluta', 'Maluta Jogurt Bałkański', 'C'),
    ('Piątnica', 'Koktajl spożywczy', 'A'),
    ('Bakoma', 'Jogurt naturalny gęsty', 'B'),
    ('Bakoma', 'Bakoma 30 MILIARDOW jogurt Naturalny Gęsty RZADKI', 'B'),
    ('Fantasia', 'Fantasia z płatkami w czekoladzie', 'C'),
    ('Fruvita (Bakoma)', 'Jogurt Wiśniowy', 'C'),
    ('Piątnica', 'Koktail Białkowy malina & granat', 'D'),
    ('Bakoma', 'Jogurt kremowy z malinami i granolą', 'C'),
    ('Tutti', 'Serek Tutti Prosty Skład', 'C'),
    ('Ovolove', 'Mus Jabłko Rabarbar', 'UNKNOWN'),
    ('Bakoma', 'Bakoma Ave Vege (Czekolada z Wiśniami)', 'C'),
    ('Fruvita', 'Jogurt wysokobiałkowy low carb waniliowy', 'A'),
    ('Pilos Pure', 'Jogurt - truskawka, jabłko, banan, owies', 'C'),
    ('7zbóż men', 'Jogurt z jagodą, czarną porzeczką i ziarnami zbóż', 'C'),
    ('Bakoma', '7 zbóż MEN jogurt z brzoskwinią, gruszką i ziarnami zbóż', 'A'),
    ('Danone', 'Yopro jogurt o smaku banan-krem z orzeszków ziemnych z magnezem i witaminą b9', 'A'),
    ('Łaciaty', 'Łaciaty jogurt pitny równowaga i regeneracja z magnezem i biotyną', 'D'),
    ('Helcom', 'Mix owoców w lekkim syropie', 'B'),
    ('Jogobella', 'Jogurt wiśniowy', 'C'),
    ('Fruvita', 'Jogurt o smaku pieczonego jabłka', 'C'),
    ('Bakoma', 'Skyr Malina-truskawka Wysoka Zawartość Białka', 'UNKNOWN'),
    ('Dessella', 'Deser mleczny czekoladowy z bitą śmietana o smaku czekoladowym', 'D'),
    ('Piątnica', 'Skyr czekoladowy z wiśnią', 'B'),
    ('Danone', 'Ale pitny malina Borówka', 'E'),
    ('Rolmlecz', 'Serek poznański naturalny', 'C'),
    ('Wieluń', 'Mój Ulubiony', 'D'),
    ('Fruvita pure', 'Jogurt + owoce borówka banan', 'B'),
    ('Piątnica', 'Skyr jogurt pitny typu islandzkiego mango & marakuja', 'E'),
    ('Piątnica', 'Skyr Wanilia', 'D'),
    ('Piątnica', 'Skyr jogurt pitny typu islandzkiego Jagoda', 'B'),
    ('Piątnica', 'Icelandic type yoghurt natural', 'A'),
    ('Piątnica', 'Skyr jogurt typu islandzkiego waniliowy', 'B'),
    ('Mlekovita', 'Jogurt Grecki naturalny', 'C'),
    ('Zott', 'Jogurt naturalny', 'B'),
    ('Piątnica', 'Serek homogenizowany truskawkowy', 'C'),
    ('Piątnica', 'Skyr Naturalny', 'A'),
    ('Fruvita', 'Jogurt jagodowy', 'C'),
    ('Fruvita', 'Skyr Pitny Wanilia', 'A'),
    ('Pilos', 'Serek Wiejski Lekki', 'B'),
    ('Président', 'Twarog sernikowy', 'A'),
    ('Jovi', 'Duet jogurt pitny Truskawka-Kiwi', 'UNKNOWN'),
    ('Piątnica', 'Serek wiejski z jagodami', 'C'),
    ('Bakoma', 'Bakoma Ave Vege czekolada', 'C'),
    ('Vemondo', 'Kokos naturalny', 'A'),
    ('Delikate', 'Serek Wiejski', 'C'),
    ('Tutti', 'Serek homogenizowany brzoskwiniowy Tutti', 'C'),
    ('Président', 'Serek waniliowy', 'C'),
    ('Piatnica', 'Serek homogenizowany brzoskwiniowy', 'C'),
    ('Bakoma', 'Jogurt Bio naturalny', 'B'),
    ('Rolmlecz', 'Serek truskawkowy', 'C'),
    ('Go Active', 'Serek proteinowy ze skyrem', 'A'),
    ('Łowicz', 'Sernik z brzoskwiniami', 'C'),
    ('Danone', 'Fantasia ar ķiršiem', 'UNKNOWN'),
    ('Danone', 'Actimel o smaku wieloowocowym', 'E'),
    ('Activia', 'Activia pitna owoce leśne', 'B'),
    ('Go Active', 'Protein Jogurt Truskawkowy', 'A'),
    ('Fruvita', 'Skyr blueberry', 'B'),
    ('Fruivita', 'Skyr Słony Karmel', 'B'),
    ('Mlekowita', 'Jogurt Polski truskawka z kawałkami owoców', 'C'),
    ('Jogobella', 'Jogurt brzoskwiniowy', 'C'),
    ('Bakoma', 'Jogurt Bio z Truskawkami', 'C'),
    ('Unknown', 'Fruvita z granolą i truskawkami', 'C'),
    ('Fruvita', 'Jogurt Grecki', 'C'),
    ('Rolmlecz', 'Serek Homo Wanil 200G Rolmlecz', 'C'),
    ('Piątnica', 'Serek homogenizowany stracciatella', 'C'),
    ('Fruvita', 'Jogurt naturalny kremowy', 'B'),
    ('Piątnica', 'Skyr jogurt pitny Naturalny', 'A'),
    ('Zott Primo', 'Jogurt Naturalny', 'B'),
    ('Piątnica', 'Serek homogenizowany waniliowy', 'C'),
    ('Danone', 'YoPRO (Smak Truskawka Malina)', 'A'),
    ('Piątnica', 'Skyr - jogurt typu islandzkiego z truskawkami', 'A'),
    ('Piątnica', 'Skyr Joghurt', 'A'),
    ('Activia', 'Jogurt z probiotykami truskawka kiwi', 'B'),
    ('Piątnica', 'Skyr jogurt pitny', 'B'),
    ('Danone', 'Activia', 'B'),
    ('YoPRO', 'Jogurt pitny proteinowy o smaku mango', 'A'),
    ('Fruvita', 'Skyr naturalny', 'A'),
    ('Piątnica', 'Skyr Wanilia & Stracciatella', 'E'),
    ('Piątnica', 'Jogurt naturalny', 'A'),
    ('Delikate', 'Serek Wiejski Lekki', 'A'),
    ('Bakoma', 'Bakoma jogurt naturalny typ grecki', 'C'),
    ('Tolonis', 'Jogurt typu greckiego', 'C'),
    ('Pilos', 'Skyr', 'A'),
    ('Piątnica', 'Coconut homogenized cheese', 'C'),
    ('Fruvira', 'Skyr Naturalny Pitny', 'A'),
    ('Unknown', 'Fruvita low carb jogurt o smaku truskawkowym', 'A'),
    ('Owolovo', 'Brzoskwiniowo', 'A')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Fruvita', 'Jogurt typu islandzkiego SKYR Naturalny 0% tłuszczu', '1'),
    ('Piątnica', 'Skyr z mango i marakują', '4'),
    ('Piatnica', 'Skyr jogurt pitny typu islandzkiego Wiśnia', '4'),
    ('OwoLovo', 'OwoLowo Jabłkowo', '1'),
    ('Tutti', 'Tutti - serek o smaku waniliowym z pokruszoną laską wanilii', '4'),
    ('Jovi', 'Napój jogurtowy Duet Banan-Truskawka', '4'),
    ('Piątnica', 'Serek Wiejski Z Malinami I Żurawiną', '4'),
    ('Zott', 'Jogurt jabłko i gruszka', '4'),
    ('Amelia', 'Waniliowy 3 składniki', '4'),
    ('Vital Fresh', 'Mus Jabłko Banan Marakuja', '1'),
    ('Fruvita', 'Mixo Jabłko-Gruszka', '4'),
    ('Łaciaty', 'Łaciaty SEREK WIEJSKI', '3'),
    ('Bakoma', 'Maxi Meal o smaku słonego karmelu', '4'),
    ('Maluta', 'Maluta Jogurt Bałkański', '4'),
    ('Piątnica', 'Koktajl spożywczy', '4'),
    ('Bakoma', 'Jogurt naturalny gęsty', '1'),
    ('Bakoma', 'Bakoma 30 MILIARDOW jogurt Naturalny Gęsty RZADKI', '1'),
    ('Fantasia', 'Fantasia z płatkami w czekoladzie', '4'),
    ('Fruvita (Bakoma)', 'Jogurt Wiśniowy', '4'),
    ('Piątnica', 'Koktail Białkowy malina & granat', '4'),
    ('Bakoma', 'Jogurt kremowy z malinami i granolą', '4'),
    ('Tutti', 'Serek Tutti Prosty Skład', '4'),
    ('Ovolove', 'Mus Jabłko Rabarbar', '1'),
    ('Bakoma', 'Bakoma Ave Vege (Czekolada z Wiśniami)', '4'),
    ('Fruvita', 'Jogurt wysokobiałkowy low carb waniliowy', '4'),
    ('Pilos Pure', 'Jogurt - truskawka, jabłko, banan, owies', '1'),
    ('7zbóż men', 'Jogurt z jagodą, czarną porzeczką i ziarnami zbóż', '3'),
    ('Bakoma', '7 zbóż MEN jogurt z brzoskwinią, gruszką i ziarnami zbóż', '3'),
    ('Danone', 'Yopro jogurt o smaku banan-krem z orzeszków ziemnych z magnezem i witaminą b9', '4'),
    ('Łaciaty', 'Łaciaty jogurt pitny równowaga i regeneracja z magnezem i biotyną', '4'),
    ('Helcom', 'Mix owoców w lekkim syropie', '3'),
    ('Jogobella', 'Jogurt wiśniowy', '4'),
    ('Fruvita', 'Jogurt o smaku pieczonego jabłka', '4'),
    ('Bakoma', 'Skyr Malina-truskawka Wysoka Zawartość Białka', '4'),
    ('Dessella', 'Deser mleczny czekoladowy z bitą śmietana o smaku czekoladowym', '4'),
    ('Piątnica', 'Skyr czekoladowy z wiśnią', '4'),
    ('Danone', 'Ale pitny malina Borówka', '4'),
    ('Rolmlecz', 'Serek poznański naturalny', '4'),
    ('Wieluń', 'Mój Ulubiony', '3'),
    ('Fruvita pure', 'Jogurt + owoce borówka banan', '1'),
    ('Piątnica', 'Skyr jogurt pitny typu islandzkiego mango & marakuja', '4'),
    ('Piątnica', 'Skyr Wanilia', '4'),
    ('Piątnica', 'Skyr jogurt pitny typu islandzkiego Jagoda', '4'),
    ('Piątnica', 'Icelandic type yoghurt natural', '1'),
    ('Piątnica', 'Skyr jogurt typu islandzkiego waniliowy', '4'),
    ('Mlekovita', 'Jogurt Grecki naturalny', '3'),
    ('Zott', 'Jogurt naturalny', '4'),
    ('Piątnica', 'Serek homogenizowany truskawkowy', '4'),
    ('Piątnica', 'Skyr Naturalny', '1'),
    ('Fruvita', 'Jogurt jagodowy', '4'),
    ('Fruvita', 'Skyr Pitny Wanilia', '4'),
    ('Pilos', 'Serek Wiejski Lekki', '3'),
    ('Président', 'Twarog sernikowy', '4'),
    ('Jovi', 'Duet jogurt pitny Truskawka-Kiwi', '4'),
    ('Piątnica', 'Serek wiejski z jagodami', '4'),
    ('Bakoma', 'Bakoma Ave Vege czekolada', '4'),
    ('Vemondo', 'Kokos naturalny', '4'),
    ('Delikate', 'Serek Wiejski', '3'),
    ('Tutti', 'Serek homogenizowany brzoskwiniowy Tutti', '4'),
    ('Président', 'Serek waniliowy', '4'),
    ('Piatnica', 'Serek homogenizowany brzoskwiniowy', '4'),
    ('Bakoma', 'Jogurt Bio naturalny', '1'),
    ('Rolmlecz', 'Serek truskawkowy', '4'),
    ('Go Active', 'Serek proteinowy ze skyrem', '4'),
    ('Łowicz', 'Sernik z brzoskwiniami', '4'),
    ('Danone', 'Fantasia ar ķiršiem', '4'),
    ('Danone', 'Actimel o smaku wieloowocowym', '4'),
    ('Activia', 'Activia pitna owoce leśne', '4'),
    ('Go Active', 'Protein Jogurt Truskawkowy', '4'),
    ('Fruvita', 'Skyr blueberry', '4'),
    ('Fruivita', 'Skyr Słony Karmel', '4'),
    ('Mlekowita', 'Jogurt Polski truskawka z kawałkami owoców', '4'),
    ('Jogobella', 'Jogurt brzoskwiniowy', '4'),
    ('Bakoma', 'Jogurt Bio z Truskawkami', '3'),
    ('Unknown', 'Fruvita z granolą i truskawkami', '4'),
    ('Fruvita', 'Jogurt Grecki', '4'),
    ('Rolmlecz', 'Serek Homo Wanil 200G Rolmlecz', '4'),
    ('Piątnica', 'Serek homogenizowany stracciatella', '4'),
    ('Fruvita', 'Jogurt naturalny kremowy', '1'),
    ('Piątnica', 'Skyr jogurt pitny Naturalny', '1'),
    ('Zott Primo', 'Jogurt Naturalny', '4'),
    ('Piątnica', 'Serek homogenizowany waniliowy', '4'),
    ('Danone', 'YoPRO (Smak Truskawka Malina)', '4'),
    ('Piątnica', 'Skyr - jogurt typu islandzkiego z truskawkami', '4'),
    ('Piątnica', 'Skyr Joghurt', '4'),
    ('Activia', 'Jogurt z probiotykami truskawka kiwi', '4'),
    ('Piątnica', 'Skyr jogurt pitny', '4'),
    ('Danone', 'Activia', '4'),
    ('YoPRO', 'Jogurt pitny proteinowy o smaku mango', '4'),
    ('Fruvita', 'Skyr naturalny', '4'),
    ('Piątnica', 'Skyr Wanilia & Stracciatella', '4'),
    ('Piątnica', 'Jogurt naturalny', '1'),
    ('Delikate', 'Serek Wiejski Lekki', '3'),
    ('Bakoma', 'Bakoma jogurt naturalny typ grecki', '1'),
    ('Tolonis', 'Jogurt typu greckiego', '4'),
    ('Pilos', 'Skyr', '4'),
    ('Piątnica', 'Coconut homogenized cheese', '4'),
    ('Fruvira', 'Skyr Naturalny Pitny', '4'),
    ('Unknown', 'Fruvita low carb jogurt o smaku truskawkowym', '4'),
    ('Owolovo', 'Brzoskwiniowo', '1')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Desserts & Ice Cream', 100, 'PL');
