-- PIPELINE (Seafood & Fish): scoring
-- Generated: 2026-03-04

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Marinero', 'Łosoś wędzony na zimno', 'D'),
    ('Marinero', 'Łosoś atlantycki marynowany plastry', 'D'),
    ('Marinero', 'Łosoś wędzony na gorąco dymem z drewna bukowego', 'D'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym', 'A'),
    ('Lisner', 'Szybki śledzik w sosie czosnkowym z ziołami prowansalskimi', 'E'),
    ('Lisner', 'Filety śledziowe w oleju a''la Matjas', 'E'),
    ('Jantar', 'Szprot wędzony na gorąco', 'D'),
    ('Lisner', 'Szybki Śledzik w sosie śmietankowym', 'E'),
    ('Fischer King', 'Stek z łososia', 'D'),
    ('Lisner', 'Marynowane, krojone filety bez skórki ze śledzia atlantyckiego z ogórkiem konserwowym i czosnkiem w oleju rzepakowym.', 'E'),
    ('Lisner', 'Śledzik na raz z suszonymi pomidorami', 'E'),
    ('Auchan', 'Łosoś Pacyficzny Dziki', 'D'),
    ('Marinero', 'Pstrąg Tęczowy Łososiowy Wędzony Na Zimno', 'UNKNOWN'),
    ('Komersmag', 'Filety śledziowe panierowane i smażone w zalewie octowej.', 'C'),
    ('Kong Oskar', 'Tuńczyk w kawałkach w oleju roślinnym', 'B'),
    ('Jantar', 'Filet z pstrąga wędzonego na gorąco z pieprzem', 'D'),
    ('Northlantica', 'Śledź filet (wędzony z przyprawami)', 'UNKNOWN'),
    ('Dega', 'Ryba śledź po grecku', 'C'),
    ('Graal', 'Tuńczyk Mexicans z warzywami', 'C'),
    ('Lisner', 'Śledzik na raz w sosie grzybowym kurki', 'D'),
    ('Marinero', 'Wiejskie filety śledziowe z cebulką', 'D'),
    ('Suempol Pan Łosoś', 'Łosoś Wędzony Plastrowany', 'D'),
    ('Marinero', 'Łosoś łagodny', 'D'),
    ('Marinero', 'Łosoś wędzony na gorąco dymem drewna bukowego', 'D'),
    ('Pescadero', 'Filety z pstrąga', 'C'),
    ('Orka', 'Filety śledziowe w sosie pomidorowym', 'C'),
    ('Homar', 'Filet śledziowy a''la matjas', 'E'),
    ('Lisner', 'Śledzik na raz z suszonymi pomidorami i ziołami włoskimi', 'E'),
    ('Suempol', 'Łosoś atlantycki, wędzony na zimno, plastrowany', 'D'),
    ('Marinero', 'Śledź filety z suszonymi pomidorami', 'D'),
    ('Fisher King', 'Pstrąg łososiowy wędzony w plastrach', 'E'),
    ('Śledzie od serca', 'Śledzie po żydowsku', 'D'),
    ('Lisner', 'Śledzik na raz Pikantny', 'E'),
    ('Mirko', 'Koreczki śledziowe z papryką chilli', 'D'),
    ('Lisner', 'Filety śledziowe a''la Matjas', 'E'),
    ('Marinero', 'Łosoś plastry, wędzony na zimno', 'D'),
    ('Auchan', 'Łosoś atlantycki wędzony na zimno plastry', 'D'),
    ('Suempol', 'Łosoś atlantycki marynowany', 'D'),
    ('Contimax', 'Wiejskie filety śledziowe marynowane z cebulą', 'D'),
    ('Lisner', 'Tuńczyk Stek Z Kropla Oliwy Z Oliwek', 'UNKNOWN'),
    ('Seko', 'Filety z makreli smażone w zalewie octowej', 'D'),
    ('Baltica', 'Filety śledziowe w sosie pomidorowym', 'C'),
    ('Lisner', 'Marinated Herring in mushroom sauce', 'C'),
    ('Marinero', 'Filety z makreli w sosie pomidorowym', 'C'),
    ('SuperFish', 'Smoked Salmon', 'D'),
    ('MegaRyba', 'Szprot w sosie pomidorowym', 'C'),
    ('Lisner', 'Herring single portion with onion', 'D'),
    ('Suempol', 'Gniazda z łososia', 'UNKNOWN'),
    ('Koryb', 'Łosoś atlantycki', 'A'),
    ('Port netto', 'Łosoś atlantycki wędzony na zimno', 'D'),
    ('Unknown', 'Łosoś wędzony na gorąco', 'D'),
    ('Vital Food', 'Chlorella', 'A'),
    ('Graal', 'Filety z makreli w sosie pomidorowym', 'C'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym', 'D'),
    ('Lisner', 'Herring Snack', 'D'),
    ('Nautica', 'Śledzie Wiejskie', 'E'),
    ('Marinero', 'Paluszki z fileta z dorsza', 'A'),
    ('Asia Flavours', 'Sushi Nori', 'C'),
    ('House Od Asia', 'Nori', 'UNKNOWN'),
    ('Marinero', 'Tuńczyk jednolity w sosie własnym', 'A'),
    ('Graal', 'Szprot w sosie pomidorowym', 'C'),
    ('Marinero', 'Tuńczyk kawałki w sosie własnym', 'A'),
    ('Well done', 'Łosoś atlantycki', 'E'),
    ('House of Asia', 'Wakame', 'E'),
    ('Purella', 'Chlorella detoks', 'A'),
    ('Marinero', 'Filety śledziowe a''la Matjas', 'E'),
    ('K-Classic', 'Pstrąg tęczowy, wędzony na zimno w plastrach', 'D'),
    ('Biedronka', 'Filet z makreli wędzony z posypką', 'D'),
    ('Marinero', 'Świeży pstrąg tęczowy łososiowy filet', 'A'),
    ('Nautica', 'Opiekane filety śledziowe w zalewie octowej', 'D'),
    ('Graal', 'Thon', 'E'),
    ('Nautica', 'Filety śledziowe w sosie śmietanowym', 'D'),
    ('Seko', 'Ryba po grecku', 'D'),
    ('Targroch', 'Agar-Agar proszek', 'NOT-APPLICABLE'),
    ('Asia Flavours', 'Dried wakame', 'D'),
    ('Lisner', 'Herring rolls with onion in rapeseed oil', 'D'),
    ('K classic', 'Filety Śledziowe w sosie koperkowym', 'D'),
    ('Baltica', 'Filety z makreli w oleju', 'D'),
    ('Nautica', 'Łosoś plastry', 'D'),
    ('Nautica', 'Koreczki Śledziowe Po Kaszubsku', 'E'),
    ('Nautica', 'Koreczki śledziowe po giżycku', 'C'),
    ('Nautica', 'Koreczki śledziowe w oleju', 'C'),
    ('Nautica', 'Filety śledziowe wiejskie', 'D'),
    ('Nautica', 'Krajanka śledziowa z żurawiną i brzoskwinią', 'D'),
    ('Nautica', 'Krajanka śledziowa z kolorowym piperzem', 'D'),
    ('Nautica', 'Krajanka śledziowa z suszonymi pomidorami', 'D'),
    ('Unknown', 'Kimbab surimi', 'UNKNOWN'),
    ('Fjord', 'Łosoś Pieczony', 'UNKNOWN'),
    ('SuperFish', 'Łosoś atlantycki pieczony', 'D'),
    ('Golden Seafood', 'Filety Z Tuńczyka W Oleju Słonecznikowym', 'A'),
    ('Blue bay', 'Łosoś Norweski', 'A'),
    ('Nautica', 'Filety śledziowe w sosie koperkowym', 'C'),
    ('Almare Seafood', 'Filet z tuńczyka w sosie własnym', 'A'),
    ('Marinero', 'Filety z pstrąga tęczowego wędzonego na gorąco', 'B'),
    ('Biedronka', 'Łosos pacyficzny filet ze skórą', 'A')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Marinero', 'Łosoś wędzony na zimno', '3'),
    ('Marinero', 'Łosoś atlantycki marynowany plastry', '3'),
    ('Marinero', 'Łosoś wędzony na gorąco dymem z drewna bukowego', '3'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym', '3'),
    ('Lisner', 'Szybki śledzik w sosie czosnkowym z ziołami prowansalskimi', '3'),
    ('Lisner', 'Filety śledziowe w oleju a''la Matjas', '4'),
    ('Jantar', 'Szprot wędzony na gorąco', '3'),
    ('Lisner', 'Szybki Śledzik w sosie śmietankowym', '3'),
    ('Fischer King', 'Stek z łososia', '3'),
    ('Lisner', 'Marynowane, krojone filety bez skórki ze śledzia atlantyckiego z ogórkiem konserwowym i czosnkiem w oleju rzepakowym.', '3'),
    ('Lisner', 'Śledzik na raz z suszonymi pomidorami', '3'),
    ('Auchan', 'Łosoś Pacyficzny Dziki', '3'),
    ('Marinero', 'Pstrąg Tęczowy Łososiowy Wędzony Na Zimno', '3'),
    ('Komersmag', 'Filety śledziowe panierowane i smażone w zalewie octowej.', '4'),
    ('Kong Oskar', 'Tuńczyk w kawałkach w oleju roślinnym', '3'),
    ('Jantar', 'Filet z pstrąga wędzonego na gorąco z pieprzem', '3'),
    ('Northlantica', 'Śledź filet (wędzony z przyprawami)', '3'),
    ('Dega', 'Ryba śledź po grecku', '4'),
    ('Graal', 'Tuńczyk Mexicans z warzywami', '4'),
    ('Lisner', 'Śledzik na raz w sosie grzybowym kurki', '4'),
    ('Marinero', 'Wiejskie filety śledziowe z cebulką', '3'),
    ('Suempol Pan Łosoś', 'Łosoś Wędzony Plastrowany', '4'),
    ('Marinero', 'Łosoś łagodny', '3'),
    ('Marinero', 'Łosoś wędzony na gorąco dymem drewna bukowego', '3'),
    ('Pescadero', 'Filety z pstrąga', '3'),
    ('Orka', 'Filety śledziowe w sosie pomidorowym', '4'),
    ('Homar', 'Filet śledziowy a''la matjas', '3'),
    ('Lisner', 'Śledzik na raz z suszonymi pomidorami i ziołami włoskimi', '3'),
    ('Suempol', 'Łosoś atlantycki, wędzony na zimno, plastrowany', '3'),
    ('Marinero', 'Śledź filety z suszonymi pomidorami', '4'),
    ('Fisher King', 'Pstrąg łososiowy wędzony w plastrach', '3'),
    ('Śledzie od serca', 'Śledzie po żydowsku', '4'),
    ('Lisner', 'Śledzik na raz Pikantny', '4'),
    ('Mirko', 'Koreczki śledziowe z papryką chilli', '4'),
    ('Lisner', 'Filety śledziowe a''la Matjas', '4'),
    ('Marinero', 'Łosoś plastry, wędzony na zimno', '3'),
    ('Auchan', 'Łosoś atlantycki wędzony na zimno plastry', '4'),
    ('Suempol', 'Łosoś atlantycki marynowany', '3'),
    ('Contimax', 'Wiejskie filety śledziowe marynowane z cebulą', '4'),
    ('Lisner', 'Tuńczyk Stek Z Kropla Oliwy Z Oliwek', '3'),
    ('Seko', 'Filety z makreli smażone w zalewie octowej', '4'),
    ('Baltica', 'Filety śledziowe w sosie pomidorowym', '4'),
    ('Lisner', 'Marinated Herring in mushroom sauce', '4'),
    ('Marinero', 'Filety z makreli w sosie pomidorowym', '4'),
    ('SuperFish', 'Smoked Salmon', '3'),
    ('MegaRyba', 'Szprot w sosie pomidorowym', '4'),
    ('Lisner', 'Herring single portion with onion', '3'),
    ('Suempol', 'Gniazda z łososia', '4'),
    ('Koryb', 'Łosoś atlantycki', '4'),
    ('Port netto', 'Łosoś atlantycki wędzony na zimno', '4'),
    ('Unknown', 'Łosoś wędzony na gorąco', '3'),
    ('Vital Food', 'Chlorella', '1'),
    ('Graal', 'Filety z makreli w sosie pomidorowym', '4'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym', '4'),
    ('Lisner', 'Herring Snack', '3'),
    ('Nautica', 'Śledzie Wiejskie', '3'),
    ('Marinero', 'Paluszki z fileta z dorsza', '4'),
    ('Asia Flavours', 'Sushi Nori', '1'),
    ('House Od Asia', 'Nori', '4'),
    ('Marinero', 'Tuńczyk jednolity w sosie własnym', '3'),
    ('Graal', 'Szprot w sosie pomidorowym', '4'),
    ('Marinero', 'Tuńczyk kawałki w sosie własnym', '3'),
    ('Well done', 'Łosoś atlantycki', '3'),
    ('House of Asia', 'Wakame', '4'),
    ('Purella', 'Chlorella detoks', '1'),
    ('Marinero', 'Filety śledziowe a''la Matjas', '4'),
    ('K-Classic', 'Pstrąg tęczowy, wędzony na zimno w plastrach', '3'),
    ('Biedronka', 'Filet z makreli wędzony z posypką', '3'),
    ('Marinero', 'Świeży pstrąg tęczowy łososiowy filet', '1'),
    ('Nautica', 'Opiekane filety śledziowe w zalewie octowej', '3'),
    ('Graal', 'Thon', '4'),
    ('Nautica', 'Filety śledziowe w sosie śmietanowym', '4'),
    ('Seko', 'Ryba po grecku', '4'),
    ('Targroch', 'Agar-Agar proszek', '4'),
    ('Asia Flavours', 'Dried wakame', '1'),
    ('Lisner', 'Herring rolls with onion in rapeseed oil', '4'),
    ('K classic', 'Filety Śledziowe w sosie koperkowym', '4'),
    ('Baltica', 'Filety z makreli w oleju', '3'),
    ('Nautica', 'Łosoś plastry', '4'),
    ('Nautica', 'Koreczki Śledziowe Po Kaszubsku', '4'),
    ('Nautica', 'Koreczki śledziowe po giżycku', '3'),
    ('Nautica', 'Koreczki śledziowe w oleju', '3'),
    ('Nautica', 'Filety śledziowe wiejskie', '3'),
    ('Nautica', 'Krajanka śledziowa z żurawiną i brzoskwinią', '3'),
    ('Nautica', 'Krajanka śledziowa z kolorowym piperzem', '3'),
    ('Nautica', 'Krajanka śledziowa z suszonymi pomidorami', '3'),
    ('Unknown', 'Kimbab surimi', '4'),
    ('Fjord', 'Łosoś Pieczony', '3'),
    ('SuperFish', 'Łosoś atlantycki pieczony', '3'),
    ('Golden Seafood', 'Filety Z Tuńczyka W Oleju Słonecznikowym', '4'),
    ('Blue bay', 'Łosoś Norweski', '1'),
    ('Nautica', 'Filety śledziowe w sosie koperkowym', '4'),
    ('Almare Seafood', 'Filet z tuńczyka w sosie własnym', '3'),
    ('Marinero', 'Filety z pstrąga tęczowego wędzonego na gorąco', '4'),
    ('Biedronka', 'Łosos pacyficzny filet ze skórą', '1')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Seafood & Fish', 100, 'PL');
