-- PIPELINE (Chips): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-04

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Funny Frisch', 'Pom-Bär Ketchup Style', 'Netto'),
    ('Bio-Zentrale', 'Gemüsechips – Pastinake, Rote Beete, Süßkartoffel, lila Süßkartoffel, Meersalz', 'Edeka'),
    ('Lorenz', 'Naturals Mediterranes Gemüse', 'Edeka'),
    ('Lorenz', 'Naturals Mediterranes Gemüse', 'REWE'),
    ('K-Classic', 'Knuspermäuse Salz', 'Kaufland'),
    ('Pom-Bär', 'Pom-Bär Crizzlies - Paprika-Style', 'Aldi'),
    ('Pom-Bär', 'Pom-Bär Crizzlies - Paprika-Style', 'Edeka'),
    ('Pom-Bär', 'Pom-Bär Crizzlies - Paprika-Style', 'REWE'),
    ('Lorenz', 'Crunchips Paprika', 'REWE'),
    ('Funny-frisch', 'Chipsfrisch Oriental', 'Edeka'),
    ('Funny-frisch', 'Chipsfrisch Oriental', 'REWE'),
    ('Funny-frisch', 'Chipsfrisch Sour Cream', 'REWE'),
    ('Funny-frisch', 'Chipsfrisch Sour Cream', 'Kaufland'),
    ('Funny Frisch', 'Chipsfrisch ungarisch', 'Edeka'),
    ('Funny Frisch', 'Chipsfrisch ungarisch', 'REWE'),
    ('Funny-frisch', 'Ofenchips paprika', 'Edeka'),
    ('Funny-frisch', 'Ofenchips paprika', 'REWE'),
    ('Lay''s', 'Lays Salted Chips', 'Edeka'),
    ('Lay''s', 'Lays Salted Chips', 'REWE'),
    ('Funny-frisch', 'Linsen Chips Sour Creme Style', 'Edeka'),
    ('Funny-frisch', 'Linsen Chips Sour Creme Style', 'REWE'),
    ('Funny-frisch', 'Linsen Chips Sour Creme Style', 'Rossmann'),
    ('Lay''s', 'Sour Cream & Onion', 'Netto'),
    ('Lorenz', 'Naturals - Rosmarin', 'Edeka'),
    ('Lorenz', 'Naturals - Rosmarin', 'REWE'),
    ('Lorenz', 'Naturals - Rosmarin', 'Kaufland'),
    ('Chio', 'Tortillas Nacho Cheese', 'Edeka'),
    ('Chio', 'Tortillas Nacho Cheese', 'REWE'),
    ('Lorenz', 'Crunchips Western Style', 'REWE'),
    ('Lorenz', 'Crunchips Western Style', 'Netto'),
    ('Chio', 'Tortillas - Wild Paprika', 'Edeka'),
    ('Chio', 'Tortillas - Wild Paprika', 'REWE'),
    ('Lay''s', 'Chips "Subway Terriyaki"', 'REWE'),
    ('Funny-frisch', 'Salziges, Riffels Naturell', 'Edeka'),
    ('LORENZ Crunchips', 'Crunchips Salted Gesalzene Kartoffel-Chips', 'Edeka'),
    ('LORENZ Crunchips', 'Crunchips Salted Gesalzene Kartoffel-Chips', 'REWE'),
    ('Lorenz', 'Erdnusslocken Jumbos', 'REWE'),
    ('Funny-frisch', 'Chipsfrisch Chili Cheese Fries Style', 'Edeka'),
    ('Doritos', 'Sweet-Chili-Peppergeschmack', 'Aldi'),
    ('Doritos', 'Sweet-Chili-Peppergeschmack', 'Edeka'),
    ('Doritos', 'Sweet-Chili-Peppergeschmack', 'REWE'),
    ('Aldi', 'Tortilla-Chips - Paprika', 'Aldi'),
    ('Funny-frisch', 'Frit-Sticks ungarisch', 'Penny'),
    ('Lorenz', 'Naturals Chips "fein gesalzen"', 'REWE'),
    ('Funny-frisch', 'Linsenchips Oriental', 'REWE'),
    ('Chio', 'Tortillas Hot Chili', 'REWE'),
    ('Lorenz', 'Naturals - Meersalz und Pfeffer', 'Edeka'),
    ('Funny-frisch', 'Kessel Chips sweet chili', 'Lidl'),
    ('Funny-frisch', 'Kessel Chips sweet chili', 'Kaufland'),
    ('Sun Snacks', 'Erdnussflips Classic', 'Aldi'),
    ('Lorenz', 'Crunchips Cheese & Onion 150g', 'REWE'),
    ('DmBio', 'Tortilla Chips', 'dm'),
    ('Snack Day', 'Chips Paprika', 'Lidl'),
    ('Aldi', 'Chips SALZ', 'Aldi'),
    ('Sun Snacks', 'Light-Chips - Classic', 'Aldi'),
    ('Snäcky Knabbergebäck', 'Light-Chips - Paprika-Style', 'Aldi'),
    ('Lorenz', 'Crunchips Hot Paprika', 'Edeka'),
    ('Lorenz', 'Crunchips Hot Paprika', 'REWE'),
    ('Lorenz', 'Crunchips Hot Paprika', 'Kaufland'),
    ('Sun Snacks', 'Kessel-Chips Sweet-Chili-Geschmack', 'Aldi'),
    ('Lorenz', 'Pommels Original', 'Edeka'),
    ('Lorenz', 'Pommels Original', 'REWE'),
    ('Funny-frisch', 'Linsen Chips Sweet Chili', 'Edeka'),
    ('Funny-frisch', 'Linsen Chips Sweet Chili', 'Kaufland'),
    ('Doritos', 'Nacho Cheese', 'Lidl'),
    ('Aldi', 'Linsen-Chips - Paprika-Style', 'Aldi'),
    ('Aldi', 'Linsen-Chips - Sour Cream Style', 'Aldi'),
    ('Funny-frisch', 'Zwiebli-Ringe', 'REWE'),
    ('K-Classic', 'Kartoffelchips Paprika', 'Kaufland'),
    ('Bio zentrale', 'Tortilla Chips Mais & Paprika', 'Edeka'),
    ('Funny-frisch', 'Chipsfrisch Zaziki Style', 'Edeka'),
    ('Aldi', 'Stapelchips - Original', 'Aldi'),
    ('Asia Green Garden', 'Krabbenchips - Classic', 'Aldi'),
    ('Sun Snacks', 'Kartoffelringe Paprikageschmack', 'Aldi'),
    ('Lidl', 'Salz Chips', 'Lidl'),
    ('Snack Day', 'Sour Cream & Onion Flavour', 'Lidl'),
    ('Ültje', 'Linsen Crackets Paprika', 'Edeka'),
    ('Ültje', 'Linsen Crackets Paprika', 'REWE'),
    ('Sun Snacks', 'Hurricorn', 'Aldi'),
    ('Snack Day', 'Snack Day Paprika Stapelchips', 'Lidl'),
    ('Chio', 'Tortillias Nacho Cheese', 'Lidl'),
    ('K-Classic', 'Geriffelte Paprika Chips', 'Kaufland'),
    ('Ültje', 'Fusion - Peanuts Paprika Flamed Style', 'Aldi'),
    ('Ültje', 'Fusion - Peanuts Paprika Flamed Style', 'Edeka'),
    ('Ültje', 'Fusion - Peanuts Paprika Flamed Style', 'REWE'),
    ('Ültje', 'Fusion - Peanuts Paprika Flamed Style', 'Netto'),
    ('Halloween', 'Gespenster - Ketchupgeschmack', 'Aldi'),
    ('Rewe', 'Kartoffel Chips mit Trüffel Geschmack', 'REWE')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Chips' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
