-- PIPELINE (Ready Meals): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Bürger', 'Vegane Maultaschen mit feinem Gemüse', 'D'),
    ('Frosta', 'Bratkartoffel Hähnchen Pfanne', 'C'),
    ('Rügenwalder Mühle', 'Fleischsalat (vegan) - Rügenwalder Mühle', 'C'),
    ('Bürger', 'Gemüse-Maultaschen', 'C'),
    ('FRoSTA', 'Hühnerfrikassee', 'C'),
    ('FRoSTA', 'Rahmgeschnetzeltes mit Hähnchen und Spätzle', 'C'),
    ('Kuehne', 'Schlemmertöpfchen gew. Gurken', 'D'),
    ('Golden Seafood', 'Fischstäbchen', 'A'),
    ('Frosta', 'Spätzle Pfanne', 'D'),
    ('Frosta', 'Hähnchen Curry', 'B'),
    ('Frosta', 'Rotes Curry mit Hähnchen und Reis', 'C'),
    ('Kühlmann', 'Klarer Weißkrautsalat', 'C'),
    ('Bürger', 'Freilandhähnchen-Maultaschen', 'C'),
    ('Bunte Küche', 'Pasta mit Hähnchen in fruchtiger Tomatensoße', 'C'),
    ('Daylicious', 'Salatcup - Hähnchen mit Senf-Dressing', 'C'),
    ('Original Wagner', 'Flammkuchen Elsässer Art', 'D'),
    ('Dr. Oetker', 'Die Ofenfrische Vier Käse', 'D'),
    ('Dilek', 'Gefüllte Weinblätter mit Reis', 'B'),
    ('Aldi', 'Hähnchen Mediterran', 'C'),
    ('Frosta', 'Wildlachs in Kräuterrahm', 'UNKNOWN'),
    ('FRoSTA', 'Paprika Sahne Hähnchen mit Bandnudeln', 'C'),
    ('Reis-fit', 'Linsen mit Reis & Gemüse - Fach 14', 'C'),
    ('FRoSTA', 'Thai Style Hähnchen mit Bandnudeln', 'C'),
    ('Bauck Hof', 'Grünkern Burger', 'UNKNOWN'),
    ('Bürger', 'Bio Gemüse Maultaschen', 'C'),
    ('FRoSTA', 'Gemüsebowl Cremiges Linsencurry mit Kürbis & Spinat', 'A'),
    ('FRoSTA', 'Hackbällchen Pfanne', 'C'),
    ('Pfanni', 'Kartoffelknödel halb & halb', 'UNKNOWN'),
    ('Erasco', 'Hühner Reis-Topf', 'C'),
    ('FRoSTA', 'Reis Hähnchen Pfanne', 'D'),
    ('Kühne', 'Grünkohl', 'A'),
    ('Frosta', 'Bami Goreng', 'C'),
    ('Frosta', 'Butter Chicken', 'C'),
    ('Original Wagner', 'Pizza Die Backfrische Mozzarella', 'C'),
    ('Frosta', 'Nice Rice - Korean Style', 'C'),
    ('Dr. Oetker Ristorante', 'Ristorante PIZZA TONNO', 'C'),
    ('FRoSTA', 'Paella', 'C'),
    ('Bauch Hof', 'Falafel', 'UNKNOWN'),
    ('Rügenwalder Mühle', 'Veganer Schinkenspicker Salat', 'C'),
    ('Dr. Oetker', 'Suprema Pizza Calabrese & ''Nduja', 'D'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', 'C'),
    ('Dr. Oetker', 'Die Ofenfrische Margherita', 'D'),
    ('Frosta', 'Fisch Schlemmerfilet Mediterraner Art', 'C'),
    ('Frosta', 'Fettuccine Wildlachs', 'C'),
    ('Dahlhoff Feinkost', 'Kartoffelsalat - Tegernseer Art', 'C'),
    ('Bio', 'Veganer Linseneintopf', 'B'),
    ('Dr. Oetker', 'Pizza Tradizionale Margherita', 'C'),
    ('Original Wagner', 'Steinofen-Pizza - Diavolo', 'C'),
    ('Dr. Oetker', 'Die Ofenfrische Speciale', 'D'),
    ('Dr. Oetker', 'Pizza Salame Ristorante', 'D'),
    ('Vemondo', 'Vegan pizza Verdura', 'B'),
    ('Dm Bio', 'Kichererbseneintopf mit Kokosmilch', 'D'),
    ('Dr. Oetker', 'Die Ofenfrische Salami', 'D'),
    ('Hengstenberg', 'Mildes Weinsauerkraut', 'C'),
    ('Frosta', 'Fisch Schlemmerfilet Brokkoli Mandel', 'C'),
    ('Omnimax Lebensmittel', 'Chili con Carne', 'UNKNOWN'),
    ('Cucina Nobile', 'Tortelloni - Spinat-Ricotta', 'C'),
    ('Dr. Oetker', 'La Mia Grande Rucola', 'D'),
    ('Bürger', 'Vegane Maultaschen 2.0', 'C'),
    ('Dr. Oetker', 'Ristorante Pizza Funghi', 'C'),
    ('GiaPizza', 'Bio-Dinkel-Steinofenpizza - Spinat', 'C'),
    ('Nestlé', 'Pizza Speciale', 'D'),
    ('Dr. Oetker', 'La Mia Grande Pizza Margherita', 'D'),
    ('Lidl', 'Vegane Kartoffel-Schupfnudeln', 'B'),
    ('Popp', 'Kartoffelsalat Gurke, Zwiebel & Ei', 'C'),
    ('Bon-ri', 'Express Reis Parboiled Mexikanische Art', 'C'),
    ('Frosta', 'Nom Nom Noodles', 'C'),
    ('Condeli', 'Lasagne Bolognese', 'C'),
    ('Dr. Oetker', 'Ristorante Pizza Pasta', 'C'),
    ('Nordsee', 'Fischfrikadellen', 'A'),
    ('Asia Green Garden', 'Samosas', 'C'),
    ('Nestlé', 'Steinofen-Pizza Thunfisch', 'C'),
    ('Vemondo', 'Pumpkin & quinoa', 'A'),
    ('Feinkost Popp', 'Krautsalat griechischer Art', 'C'),
    ('Bürger', 'Rindfleisch-Maultaschen', 'C'),
    ('GOOD Choice', 'Rosmarinkartoffeln // 2 kg Kart.frisch oben / 2,5 kg frisch Keller', 'C'),
    ('Steinhaus', 'Steinpilz-Champignon-Totelli', 'C'),
    ('Omnimax Lebensmittel', 'Chili sin Carne', 'A'),
    ('Dr. Oetker', 'Ristorante Pizza Margherita Pomodori', 'C'),
    ('Dr. Oetker', 'Pizza Tradizionale Speciale', 'C'),
    ('Speisezeit', 'Red Thai Curry', 'C'),
    ('FRoSTA', 'Tagliatelle Wildlachs', 'C'),
    ('FRoSTA', 'Veganes Bami Goreng', 'C'),
    ('FRoSTA', 'Bandnudeln Pilz', 'C'),
    ('Gustavo Gusto', 'Tiefkühler Pizza groß', 'D'),
    ('Gustavo Gusto', 'Vier Käse für ein Halleluja - Pizza Quattro Formaggi', 'D'),
    ('Dr. Oetker', 'Ristorante Pizza Vegetale', 'C'),
    ('Bürger', 'BIO Maultaschen', 'C'),
    ('Maggi', 'Ravioli in Tomatensauce', 'C'),
    ('Feinkost Popp', 'Feiner Coleslaw-Salat', 'C'),
    ('Gustavo Gusto', 'Gustavo Gusto Pizza Salame 4260414150470 Steinofenpizza nach italienischer Art mit Tomatensoße, laktosefreiem, schnittfestem Mozzarella und Rindersalami, teilweise vorgebacken und tiefgekühlt', 'D'),
    ('Alnatura', 'Kartoffel Püree', 'B'),
    ('Eridanous', 'Bohnen weiß eingelegt in Tomatensoße', 'C'),
    ('Dr. Oetker', 'Die Ofenfrische Thunfisch', 'C'),
    ('Speise Zeit', 'Linseneintopf', 'B'),
    ('REWE to go', 'Hähnchen Salat', 'B'),
    ('Iglo', '8 Lachs-Stäbchen', 'A'),
    ('Ocean Sea', 'Fischstäbchen', 'B'),
    ('Frosta', 'Mexican Style Chicken', 'C'),
    ('Original Wagner', 'Rustipani dunkles Ofenbrot geräucherter Käse', 'D')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Bürger', 'Vegane Maultaschen mit feinem Gemüse', '4'),
    ('Frosta', 'Bratkartoffel Hähnchen Pfanne', '4'),
    ('Rügenwalder Mühle', 'Fleischsalat (vegan) - Rügenwalder Mühle', '4'),
    ('Bürger', 'Gemüse-Maultaschen', '3'),
    ('FRoSTA', 'Hühnerfrikassee', '3'),
    ('FRoSTA', 'Rahmgeschnetzeltes mit Hähnchen und Spätzle', '4'),
    ('Kuehne', 'Schlemmertöpfchen gew. Gurken', '4'),
    ('Golden Seafood', 'Fischstäbchen', '3'),
    ('Frosta', 'Spätzle Pfanne', '4'),
    ('Frosta', 'Hähnchen Curry', '4'),
    ('Frosta', 'Rotes Curry mit Hähnchen und Reis', '4'),
    ('Kühlmann', 'Klarer Weißkrautsalat', '4'),
    ('Bürger', 'Freilandhähnchen-Maultaschen', '3'),
    ('Bunte Küche', 'Pasta mit Hähnchen in fruchtiger Tomatensoße', '4'),
    ('Daylicious', 'Salatcup - Hähnchen mit Senf-Dressing', '4'),
    ('Original Wagner', 'Flammkuchen Elsässer Art', '4'),
    ('Dr. Oetker', 'Die Ofenfrische Vier Käse', '4'),
    ('Dilek', 'Gefüllte Weinblätter mit Reis', '3'),
    ('Aldi', 'Hähnchen Mediterran', '4'),
    ('Frosta', 'Wildlachs in Kräuterrahm', '3'),
    ('FRoSTA', 'Paprika Sahne Hähnchen mit Bandnudeln', '3'),
    ('Reis-fit', 'Linsen mit Reis & Gemüse - Fach 14', '4'),
    ('FRoSTA', 'Thai Style Hähnchen mit Bandnudeln', '4'),
    ('Bauck Hof', 'Grünkern Burger', '3'),
    ('Bürger', 'Bio Gemüse Maultaschen', '4'),
    ('FRoSTA', 'Gemüsebowl Cremiges Linsencurry mit Kürbis & Spinat', '3'),
    ('FRoSTA', 'Hackbällchen Pfanne', '4'),
    ('Pfanni', 'Kartoffelknödel halb & halb', '4'),
    ('Erasco', 'Hühner Reis-Topf', '4'),
    ('FRoSTA', 'Reis Hähnchen Pfanne', '4'),
    ('Kühne', 'Grünkohl', '4'),
    ('Frosta', 'Bami Goreng', '4'),
    ('Frosta', 'Butter Chicken', '4'),
    ('Original Wagner', 'Pizza Die Backfrische Mozzarella', '4'),
    ('Frosta', 'Nice Rice - Korean Style', '3'),
    ('Dr. Oetker Ristorante', 'Ristorante PIZZA TONNO', '3'),
    ('FRoSTA', 'Paella', '4'),
    ('Bauch Hof', 'Falafel', '3'),
    ('Rügenwalder Mühle', 'Veganer Schinkenspicker Salat', '4'),
    ('Dr. Oetker', 'Suprema Pizza Calabrese & ''Nduja', '4'),
    ('Original Wagner', 'Steinofen-Pizza Mozzarella Vegetarisch', '3'),
    ('Dr. Oetker', 'Die Ofenfrische Margherita', '4'),
    ('Frosta', 'Fisch Schlemmerfilet Mediterraner Art', '3'),
    ('Frosta', 'Fettuccine Wildlachs', '3'),
    ('Dahlhoff Feinkost', 'Kartoffelsalat - Tegernseer Art', '4'),
    ('Bio', 'Veganer Linseneintopf', '4'),
    ('Dr. Oetker', 'Pizza Tradizionale Margherita', '3'),
    ('Original Wagner', 'Steinofen-Pizza - Diavolo', '4'),
    ('Dr. Oetker', 'Die Ofenfrische Speciale', '4'),
    ('Dr. Oetker', 'Pizza Salame Ristorante', '4'),
    ('Vemondo', 'Vegan pizza Verdura', '4'),
    ('Dm Bio', 'Kichererbseneintopf mit Kokosmilch', '3'),
    ('Dr. Oetker', 'Die Ofenfrische Salami', '4'),
    ('Hengstenberg', 'Mildes Weinsauerkraut', '3'),
    ('Frosta', 'Fisch Schlemmerfilet Brokkoli Mandel', '3'),
    ('Omnimax Lebensmittel', 'Chili con Carne', '4'),
    ('Cucina Nobile', 'Tortelloni - Spinat-Ricotta', '4'),
    ('Dr. Oetker', 'La Mia Grande Rucola', '3'),
    ('Bürger', 'Vegane Maultaschen 2.0', '4'),
    ('Dr. Oetker', 'Ristorante Pizza Funghi', '4'),
    ('GiaPizza', 'Bio-Dinkel-Steinofenpizza - Spinat', '3'),
    ('Nestlé', 'Pizza Speciale', '4'),
    ('Dr. Oetker', 'La Mia Grande Pizza Margherita', '3'),
    ('Lidl', 'Vegane Kartoffel-Schupfnudeln', '4'),
    ('Popp', 'Kartoffelsalat Gurke, Zwiebel & Ei', '4'),
    ('Bon-ri', 'Express Reis Parboiled Mexikanische Art', '4'),
    ('Frosta', 'Nom Nom Noodles', '3'),
    ('Condeli', 'Lasagne Bolognese', '4'),
    ('Dr. Oetker', 'Ristorante Pizza Pasta', '4'),
    ('Nordsee', 'Fischfrikadellen', '3'),
    ('Asia Green Garden', 'Samosas', '4'),
    ('Nestlé', 'Steinofen-Pizza Thunfisch', '3'),
    ('Vemondo', 'Pumpkin & quinoa', '4'),
    ('Feinkost Popp', 'Krautsalat griechischer Art', '4'),
    ('Bürger', 'Rindfleisch-Maultaschen', '4'),
    ('GOOD Choice', 'Rosmarinkartoffeln // 2 kg Kart.frisch oben / 2,5 kg frisch Keller', '4'),
    ('Steinhaus', 'Steinpilz-Champignon-Totelli', '4'),
    ('Omnimax Lebensmittel', 'Chili sin Carne', '4'),
    ('Dr. Oetker', 'Ristorante Pizza Margherita Pomodori', '4'),
    ('Dr. Oetker', 'Pizza Tradizionale Speciale', '4'),
    ('Speisezeit', 'Red Thai Curry', '4'),
    ('FRoSTA', 'Tagliatelle Wildlachs', '3'),
    ('FRoSTA', 'Veganes Bami Goreng', '4'),
    ('FRoSTA', 'Bandnudeln Pilz', '3'),
    ('Gustavo Gusto', 'Tiefkühler Pizza groß', '3'),
    ('Gustavo Gusto', 'Vier Käse für ein Halleluja - Pizza Quattro Formaggi', '4'),
    ('Dr. Oetker', 'Ristorante Pizza Vegetale', '3'),
    ('Bürger', 'BIO Maultaschen', '3'),
    ('Maggi', 'Ravioli in Tomatensauce', '4'),
    ('Feinkost Popp', 'Feiner Coleslaw-Salat', '4'),
    ('Gustavo Gusto', 'Gustavo Gusto Pizza Salame 4260414150470 Steinofenpizza nach italienischer Art mit Tomatensoße, laktosefreiem, schnittfestem Mozzarella und Rindersalami, teilweise vorgebacken und tiefgekühlt', '4'),
    ('Alnatura', 'Kartoffel Püree', '3'),
    ('Eridanous', 'Bohnen weiß eingelegt in Tomatensoße', '3'),
    ('Dr. Oetker', 'Die Ofenfrische Thunfisch', '4'),
    ('Speise Zeit', 'Linseneintopf', '4'),
    ('REWE to go', 'Hähnchen Salat', '4'),
    ('Iglo', '8 Lachs-Stäbchen', '3'),
    ('Ocean Sea', 'Fischstäbchen', '3'),
    ('Frosta', 'Mexican Style Chicken', '4'),
    ('Original Wagner', 'Rustipani dunkles Ofenbrot geräucherter Käse', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Ready Meals', 100, 'DE');
