-- PIPELINE (Desserts & Ice Cream): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Gervais', 'Hüttenkäse Original', 'B'),
    ('Milsani', 'Körniger Frischkäse, Halbfettstufe', 'B'),
    ('Dr. Oetker', 'High Protein Pudding Grieß', 'A'),
    ('Milsani', 'Grießpudding High-Protein - Zimt', 'A'),
    ('Milsani', 'Körniger Frischkäse mit fettarmem Joghurt - leicht', 'A'),
    ('Milsani', 'ALDI MILSANI Skyr Nach isländischer Art mit viel Eiweiß und wenig Fett Aus der Kühlung 1.49€ 500g Becher 1kg 2.98€', 'A'),
    ('Milsani', 'Kräuterquark', 'C'),
    ('Milsani', 'Grießpudding High-Protein - Pur/Classic', 'A'),
    ('Milsani', 'Joghurt nach türkischer Art, 3,5 % Fett', 'B'),
    ('Der Grosse Bauer', 'Der große Bauer Himbeere Joghurt mild', 'C'),
    ('Bauer', 'Der große Bauer Heidelbeer-Cassis', 'C'),
    ('Lidl', 'Kräuterquark', 'C'),
    ('Milram', 'Frühlings Quark 7 Kräuter', 'C'),
    ('Müller', 'Müller Joghurt mit der Ecke - Schoko-Flakes', 'C'),
    ('Milram', 'Frühlingsquark Family-Pack', 'D'),
    ('Milram', 'Körniger Frischkäse', 'B'),
    ('Dr. Oetker', 'Götterspeise Waldmeister-Geschmack', 'C'),
    ('Aldi', 'Mandeljoghurt Natur ungesüßt', 'A'),
    ('Landliebe', 'Grießpudding Zimt', 'UNKNOWN'),
    ('Milbona', 'Skyr', 'A'),
    ('Arla', 'Skyr Natur', 'A'),
    ('Elinas', 'Joghurt Griechischer Art', 'C'),
    ('Ehrmann', 'High Protein Chocolate Pudding', 'A'),
    ('Arla', 'Skyr Bourbon Vanille', 'A'),
    ('Milbona', 'High Protein Chocolate Flavour Pudding', 'A'),
    ('Milsani', 'Joghurt mild 3,5 % Fett', 'B'),
    ('Aldi', 'A/Joghurt mild 3,5% Fett', 'B'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', 'A'),
    ('Milbona', 'Bio Fettarmer Joghurt mild', 'B'),
    ('Bauer', 'Kirsche', 'C'),
    ('Milbona', 'Skyr Vanilla', 'A'),
    ('Weihenstephan', 'Joghurt Natur 3,5 % Fett', 'B'),
    ('Lyttos', 'Griechischer Joghurt', 'C'),
    ('Lyttos', 'ALDI LYTTOS YOGRI nach griechischer Art 1kg 2.19€', 'A'),
    ('Müller', 'Joghurt mit der Ecke - Schoko Balls', 'C'),
    ('Dr. Oetker', 'High Protein Pudding Schoko', 'A'),
    ('Milbona', 'Bio Organic Cremiger Joghurt Mild (3,8% Fett)', 'B'),
    ('Milbona', 'Bio Speisequark Magerstufe', 'A'),
    ('Milbona', 'Skyr Erdbeere', 'A'),
    ('Ehrmann', 'Chocolate & Topping with Protein', 'A'),
    ('Milbona', 'Joghurt 1,5%', 'A'),
    ('Milbona', 'Haselnuss Pudding', 'A'),
    ('Milsani', 'Joghurt mild 3,5% / 0x 500 gr / 3x 150 gr (Gebinde= 4x je 150 gr)', 'A'),
    ('Elinas', 'Joghurt, Natur', 'C'),
    ('Ehrmann', 'High Protein Chocolate Mousse', 'A'),
    ('Ehrmann', 'Grand Dessert - Vanille', 'C'),
    ('Aldi', 'Speisequark Magerstufe', 'A'),
    ('Milbona', 'Skyr Blueberry', 'A'),
    ('Milbona', 'Kefir', 'B'),
    ('Zott', 'Monte MAXI', 'D'),
    ('Milsani', 'High-Protein-Pudding - Schoko', 'A'),
    ('My Vay', 'Sojaghurt', 'A'),
    ('Molkerei Gropper', 'High-Protein-Pudding - Schoko', 'A'),
    ('Dr. Oetker', 'High Protein Pudding Bourbon-Vanille', 'A'),
    ('Almighurt', 'Joghurt mild, Stracciatella', 'C'),
    ('DMK', 'Speisequark Magerstufe', 'A'),
    ('Exquisa', 'Quark queso natural', 'A'),
    ('Ehrmann', 'Grand Dessert - Double Choc', 'C'),
    ('Ehrmann', 'High Protein Heidelbeere Joghurt-Erzeugnis', 'A'),
    ('Ehrmann', 'Almighurt - Kirsche', 'C'),
    ('Actimel', 'Danone Actimel® CLASSIC 8X100G', 'D'),
    ('Ehrmann', 'Almighurt - Ananas', 'C'),
    ('Milsani', 'High-Protein-Mousse Vanillegeschmack', 'A'),
    ('Ehrmann', 'High-Protein-Pudding - Caramel Style', 'A'),
    ('Vemondo', 'Coconut Classic', 'D'),
    ('Lyttos', 'Yogri - Joghurterzeugnis nach griechischer Art', 'A'),
    ('Danone', 'Fruchtzwerge', 'C'),
    ('Elinas', 'Joghurt nach griechischer Art - Honig', 'C'),
    ('Aldi', 'Speisequark 20% - Bio', 'A'),
    ('Milbona', 'Bio fruchtjoghurt', 'C'),
    ('Milchfrisch', 'High-Protein-Mousse - Schokolade', 'A'),
    ('Zott', 'Sahne-Joghurt mild Amarena-Kirsche', 'C'),
    ('Weideglück', 'Bio Joghurt Mild', 'B'),
    ('Müller', 'Milchreis Schoko', 'C'),
    ('Milbona', 'High Protein Joghurterzeugnis - Heidelbeere', 'A'),
    ('Dr. Oetker', 'Paula Pudding Vanille', 'C'),
    ('Landliebe', 'Joghurt mild 3,8%', 'B'),
    ('Landliebe', 'Schokolade Sahne Pudding', 'C'),
    ('Dogan', 'Ayran', 'C'),
    ('Weihenstephan', 'Joghurt mild 0,1% Fett', 'UNKNOWN'),
    ('Schwarzwaldmilch', 'BIO Joghurt', 'C'),
    ('Milsani', 'Sour Creme - cremig mild', 'C'),
    ('Seraphos', 'Joghurt Mild nach Griechischer ART', 'C'),
    ('Ehrmann', 'Almighurt - Pfirsich-Maracuja', 'C'),
    ('Milbona', 'Joghurt griechischer Art Natur', 'C'),
    ('Ehrmann', 'High Protein Mango', 'A'),
    ('Kaufland', 'Veganer cocogurt', 'C'),
    ('Aldi', 'Apfelmus', 'A'),
    ('Lidl', 'High protein vanilla pudding', 'A'),
    ('Gut & günstig', 'Joghurt Griechischer Art (pur)', 'C'),
    ('Zott', 'Zott Sahne Joghurt mild Erdbeere 4014500059617 Sahnejoghurt mild mit Erdbeeren. 10% Fett im Milchantei', 'C'),
    ('Ehrmann', 'Almighurt - Himbeere', 'C'),
    ('Elinas', 'Joghurt nach griechischer Art Kirsche', 'C'),
    ('Ehrmann', 'Almighurt - Zitrone', 'C'),
    ('Milbona', 'Joghurt Mild Vanille', 'C'),
    ('Milsani', 'Joghurt 3,5 %', 'B'),
    ('DMK', 'Speisequark', 'A'),
    ('Weideglück', 'Joghurt 3,5% Fett', 'B'),
    ('Milsani', 'Joghurt laktosefrei', 'B'),
    ('Weihenstephan', 'Rahmjoghurt Stracciatella', 'D')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Gervais', 'Hüttenkäse Original', '4'),
    ('Milsani', 'Körniger Frischkäse, Halbfettstufe', '3'),
    ('Dr. Oetker', 'High Protein Pudding Grieß', '4'),
    ('Milsani', 'Grießpudding High-Protein - Zimt', '4'),
    ('Milsani', 'Körniger Frischkäse mit fettarmem Joghurt - leicht', '3'),
    ('Milsani', 'ALDI MILSANI Skyr Nach isländischer Art mit viel Eiweiß und wenig Fett Aus der Kühlung 1.49€ 500g Becher 1kg 2.98€', '1'),
    ('Milsani', 'Kräuterquark', '3'),
    ('Milsani', 'Grießpudding High-Protein - Pur/Classic', '4'),
    ('Milsani', 'Joghurt nach türkischer Art, 3,5 % Fett', '1'),
    ('Der Grosse Bauer', 'Der große Bauer Himbeere Joghurt mild', '4'),
    ('Bauer', 'Der große Bauer Heidelbeer-Cassis', '4'),
    ('Lidl', 'Kräuterquark', '4'),
    ('Milram', 'Frühlings Quark 7 Kräuter', '3'),
    ('Müller', 'Müller Joghurt mit der Ecke - Schoko-Flakes', '4'),
    ('Milram', 'Frühlingsquark Family-Pack', '3'),
    ('Milram', 'Körniger Frischkäse', '3'),
    ('Dr. Oetker', 'Götterspeise Waldmeister-Geschmack', '4'),
    ('Aldi', 'Mandeljoghurt Natur ungesüßt', '3'),
    ('Landliebe', 'Grießpudding Zimt', '3'),
    ('Milbona', 'Skyr', '3'),
    ('Arla', 'Skyr Natur', '3'),
    ('Elinas', 'Joghurt Griechischer Art', '1'),
    ('Ehrmann', 'High Protein Chocolate Pudding', '4'),
    ('Arla', 'Skyr Bourbon Vanille', '4'),
    ('Milbona', 'High Protein Chocolate Flavour Pudding', '4'),
    ('Milsani', 'Joghurt mild 3,5 % Fett', '1'),
    ('Aldi', 'A/Joghurt mild 3,5% Fett', '1'),
    ('Ehrmann', 'High-Protein-Pudding - Vanilla', '4'),
    ('Milbona', 'Bio Fettarmer Joghurt mild', '1'),
    ('Bauer', 'Kirsche', '4'),
    ('Milbona', 'Skyr Vanilla', '4'),
    ('Weihenstephan', 'Joghurt Natur 3,5 % Fett', '1'),
    ('Lyttos', 'Griechischer Joghurt', '1'),
    ('Lyttos', 'ALDI LYTTOS YOGRI nach griechischer Art 1kg 2.19€', '1'),
    ('Müller', 'Joghurt mit der Ecke - Schoko Balls', '4'),
    ('Dr. Oetker', 'High Protein Pudding Schoko', '4'),
    ('Milbona', 'Bio Organic Cremiger Joghurt Mild (3,8% Fett)', '1'),
    ('Milbona', 'Bio Speisequark Magerstufe', '3'),
    ('Milbona', 'Skyr Erdbeere', '4'),
    ('Ehrmann', 'Chocolate & Topping with Protein', '4'),
    ('Milbona', 'Joghurt 1,5%', '1'),
    ('Milbona', 'Haselnuss Pudding', '4'),
    ('Milsani', 'Joghurt mild 3,5% / 0x 500 gr / 3x 150 gr (Gebinde= 4x je 150 gr)', '1'),
    ('Elinas', 'Joghurt, Natur', '1'),
    ('Ehrmann', 'High Protein Chocolate Mousse', '4'),
    ('Ehrmann', 'Grand Dessert - Vanille', '4'),
    ('Aldi', 'Speisequark Magerstufe', '3'),
    ('Milbona', 'Skyr Blueberry', '4'),
    ('Milbona', 'Kefir', '1'),
    ('Zott', 'Monte MAXI', '4'),
    ('Milsani', 'High-Protein-Pudding - Schoko', '4'),
    ('My Vay', 'Sojaghurt', '4'),
    ('Molkerei Gropper', 'High-Protein-Pudding - Schoko', '4'),
    ('Dr. Oetker', 'High Protein Pudding Bourbon-Vanille', '4'),
    ('Almighurt', 'Joghurt mild, Stracciatella', '4'),
    ('DMK', 'Speisequark Magerstufe', '4'),
    ('Exquisa', 'Quark queso natural', '4'),
    ('Ehrmann', 'Grand Dessert - Double Choc', '4'),
    ('Ehrmann', 'High Protein Heidelbeere Joghurt-Erzeugnis', '4'),
    ('Ehrmann', 'Almighurt - Kirsche', '4'),
    ('Actimel', 'Danone Actimel® CLASSIC 8X100G', '4'),
    ('Ehrmann', 'Almighurt - Ananas', '4'),
    ('Milsani', 'High-Protein-Mousse Vanillegeschmack', '4'),
    ('Ehrmann', 'High-Protein-Pudding - Caramel Style', '4'),
    ('Vemondo', 'Coconut Classic', '4'),
    ('Lyttos', 'Yogri - Joghurterzeugnis nach griechischer Art', '1'),
    ('Danone', 'Fruchtzwerge', '4'),
    ('Elinas', 'Joghurt nach griechischer Art - Honig', '4'),
    ('Aldi', 'Speisequark 20% - Bio', '3'),
    ('Milbona', 'Bio fruchtjoghurt', '4'),
    ('Milchfrisch', 'High-Protein-Mousse - Schokolade', '4'),
    ('Zott', 'Sahne-Joghurt mild Amarena-Kirsche', '4'),
    ('Weideglück', 'Bio Joghurt Mild', '1'),
    ('Müller', 'Milchreis Schoko', '4'),
    ('Milbona', 'High Protein Joghurterzeugnis - Heidelbeere', '4'),
    ('Dr. Oetker', 'Paula Pudding Vanille', '4'),
    ('Landliebe', 'Joghurt mild 3,8%', '1'),
    ('Landliebe', 'Schokolade Sahne Pudding', '4'),
    ('Dogan', 'Ayran', '4'),
    ('Weihenstephan', 'Joghurt mild 0,1% Fett', '1'),
    ('Schwarzwaldmilch', 'BIO Joghurt', '1'),
    ('Milsani', 'Sour Creme - cremig mild', '4'),
    ('Seraphos', 'Joghurt Mild nach Griechischer ART', '4'),
    ('Ehrmann', 'Almighurt - Pfirsich-Maracuja', '4'),
    ('Milbona', 'Joghurt griechischer Art Natur', '4'),
    ('Ehrmann', 'High Protein Mango', '4'),
    ('Kaufland', 'Veganer cocogurt', '4'),
    ('Aldi', 'Apfelmus', '1'),
    ('Lidl', 'High protein vanilla pudding', '4'),
    ('Gut & günstig', 'Joghurt Griechischer Art (pur)', '1'),
    ('Zott', 'Zott Sahne Joghurt mild Erdbeere 4014500059617 Sahnejoghurt mild mit Erdbeeren. 10% Fett im Milchantei', '4'),
    ('Ehrmann', 'Almighurt - Himbeere', '4'),
    ('Elinas', 'Joghurt nach griechischer Art Kirsche', '4'),
    ('Ehrmann', 'Almighurt - Zitrone', '4'),
    ('Milbona', 'Joghurt Mild Vanille', '4'),
    ('Milsani', 'Joghurt 3,5 %', '4'),
    ('DMK', 'Speisequark', '3'),
    ('Weideglück', 'Joghurt 3,5% Fett', '1'),
    ('Milsani', 'Joghurt laktosefrei', '4'),
    ('Weihenstephan', 'Rahmjoghurt Stracciatella', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Desserts & Ice Cream', 100, 'DE');
