-- PIPELINE (Plant-Based & Alternatives): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Rügenwalder Mühle', 'Veganer Schinken-Spicker Grillgemüse', 'Edeka'),
    ('Rügenwalder Mühle', 'Veganer Schinken-Spicker Grillgemüse', 'REWE'),
    ('Rügenwalder Mühle', 'Veganer Schinken-Spicker Grillgemüse', 'Kaufland'),
    ('Rügenwalder Mühle', 'Veganer Schinken-Spicker Grillgemüse', 'Tegut'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'Aldi'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'Lidl'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'Edeka'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'REWE'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'Netto'),
    ('Rügenwalder Mühle', 'Veganes Mühlen Cordon Bleu auf Basis von Soja', 'Kaufland'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Nuggets Klassisch', 'Edeka'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Nuggets Klassisch', 'REWE'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Nuggets Klassisch', 'Penny'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Nuggets Klassisch', 'Kaufland'),
    ('Mühlenbauer', 'Vegane Bratwürste', 'Edeka'),
    ('Mühlenbauer', 'Vegane Bratwürste', 'REWE'),
    ('Mühlenbauer', 'Vegane Bratwürste', 'Kaufland'),
    ('Eberswalder', 'Vegetarios Würstchen', 'Edeka'),
    ('Vemondo', 'Bio Tofu geräuchert', 'Lidl'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Crispies', 'REWE'),
    ('Gut Bio', 'Griechische Bio-Oliven, grün', 'Aldi'),
    ('Jerg', 'Vegane Genießerscheiben würzig', 'Lidl'),
    ('Rügenwalder Mühle', 'Vegane Mühlen Bratwurst', 'REWE'),
    ('DmBio', 'Maiswaffeln', 'dm'),
    ('Vemondo', 'Tofu Natur', 'Lidl'),
    ('Rügenwalder Mühle', 'Veganer Schinken Spicker Bunter Pfeffer', 'REWE'),
    ('DmBio', 'Mais Waffeln gesalzen', 'dm'),
    ('Rügenwalder Mühle', 'Vegan Curry aufschnitt', 'REWE'),
    ('Gut Bio', 'Bio-Linsenwaffeln - Meersalz', 'Aldi'),
    ('Kühne', 'Rotkohl', 'Lidl'),
    ('Kühne', 'Rotkohl', 'Edeka'),
    ('Kühne', 'Rotkohl', 'REWE'),
    ('Kühne', 'Rotkohl', 'Kaufland'),
    ('Harry', 'Steinofenbrot, Harry 1688', 'REWE'),
    ('Better Plant', 'Vegane Creme', 'Lidl'),
    ('REWE Bio +vegan', 'Räucher-Tofu', 'REWE'),
    ('Rewe', 'Falafel bällchen', 'REWE'),
    ('Rewe Beste Wahl', 'Milde Genießer Scheiben', 'REWE'),
    ('Simply V', 'Würzig verfeinert mit Mandelöl', 'Tegut'),
    ('Plant Republic', 'Räucher-Tofu', 'REWE'),
    ('K-take it veggie', 'Bio Tofu geräuchert', 'Kaufland'),
    ('No-Name', 'Bananen süß & samtig', 'REWE'),
    ('No-Name', 'Bananen süß & samtig', 'Penny'),
    ('EDEKA Bio', 'My Veggie Tofu geräuchert', 'Edeka'),
    ('Like Meat', 'Like Grilled Chicken', 'REWE'),
    ('Like Meat', 'Like Chicken', 'Edeka'),
    ('Like Meat', 'Like Chicken', 'REWE'),
    ('Baresa', 'Tomatenmark 2-Fach Konzentriert', 'Lidl'),
    ('Freshona', 'Cornichons Gurken', 'Lidl'),
    ('Freshona', 'Cornichons Gurken', 'Norma'),
    ('Rewe Bio', 'Tofu Natur', 'REWE'),
    ('Baresa', 'Tomaten passiert', 'Lidl'),
    ('Garden Gourmet', 'Sensational Burger aus Sojaprotein', 'REWE'),
    ('Sondey', 'Mais Waffeln mit Meersalz Bio', 'Lidl'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'Aldi'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'Lidl'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'Edeka'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'REWE'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'Netto'),
    ('Greenforce', 'Pflanzliche Mini-Frika', 'Kaufland'),
    ('Ja', 'Tomaten passiert', 'REWE'),
    ('REWE Bio', 'Sojasahne', 'REWE'),
    ('Simply V', 'Gerieben Pizza', 'REWE'),
    ('Ja!', 'Cherry-Roma Tomaten Klasse 1', 'REWE'),
    ('EDEKA Bio', 'My Veggie Tofu Natur', 'Edeka'),
    ('REWE Bio', 'Linsenwaffeln', 'REWE'),
    ('Nestlé', 'Vegane Filet-Streifen', 'REWE'),
    ('Greenforce', 'Pflanzliche Cevapcici', 'Edeka'),
    ('Greenforce', 'Pflanzliche Cevapcici', 'REWE'),
    ('Greenforce', 'Pflanzliche Cevapcici', 'Netto'),
    ('EnerBiO', 'Veggie Hack', 'Rossmann'),
    ('Edeka Bio', 'Tomatenmark 2-fach konzentriert', 'Edeka'),
    ('Rewe', 'Tofu Natur', 'REWE'),
    ('Like Meat', 'Like Beef Strips', 'REWE')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Plant-Based & Alternatives' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
