-- PIPELINE (Breakfast & Grain-Based): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Dr. Oetker', 'Vitalis Knuspermüsli Weniger Süß Knusper pur ohne Rosinen', 'C'),
    ('Kölln', 'Kölln Knusper Volkorn-Müsli mit Vanille-Note 500g', 'C'),
    ('Kölln', 'Knusper Honig-Nuss Müsli', 'D'),
    ('Dm', 'Bio Schokomüsli ohne Rosinen', 'C'),
    ('Kölln', 'Kellogs, Hafer-Müsli, Schoko und Keks', 'D'),
    ('Kölln', 'Zartes Bircher Müsli', 'A'),
    ('Seitenbacher', 'Kakao-Düsis', 'A'),
    ('Dr. Oetker Vitalis', 'Vitalis Weniger süß Knusper Himbeere', 'A'),
    ('Kölln', 'Crunchy Choc-Choc-Choc - Hafer-Müsli', 'D'),
    ('Kölln', 'Hafer Müsli Beere Apfel', 'A'),
    ('Dr. Oetker', 'Schoko Müsli klassisch', 'C'),
    ('Dr. Oetker', 'Vitalis Knusper Schoko Müsli', 'B'),
    ('Golden Bridge', 'Trauben-Nuss Müsli Vollkorn', 'A'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli PLUS Nussmischung', 'C'),
    ('Dr. Oetker', 'Vitalis Müsli Joghurt', 'C'),
    ('Kölln', 'Crunchy Berry Hafer-Müsli', 'C'),
    ('Kölln', 'Kölln Müsli Nuss & Krokant', 'A'),
    ('Seitenbacher', 'Müsli 205 Für Sportliche', 'A'),
    ('Dr. Oetker', 'Vitalis Knusper müsli Honeys', 'C'),
    ('Golden Bridge', 'Schoko-Müsli mit 30 % weniger Zucker', 'A'),
    ('Golden Bridge', 'Früchte-Müsli', 'C'),
    ('DmBio', 'Beeren Müsli', 'B'),
    ('Kölln', 'Schoko Müsli', 'D'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli klassisch', 'C'),
    ('Crownfield', 'Schoko Müsli', 'C'),
    ('Dr. Oetker', 'Knusper Schoko Müsli', 'C'),
    ('GUT Bio', 'Basis Müsli 5-Kornmix', 'A'),
    ('Kölln', 'Crunchy Mango-Maracuja Hafer-Müsli', 'D'),
    ('Aldi', 'Bio-Müsli - Urkorn-Früchte', 'A'),
    ('Dr. Oetker', 'Müsli Schoko weniger süss', 'C'),
    ('Kölln', 'EDEKA Müsli Kölln Müsli Knusper Schoko-Krokant 500g 2.49€ 1kg 4.98€', 'D'),
    ('GUT bio', 'Bio Knusper-Müsli Schoko-Amaranth', 'C'),
    ('Seitenbacher', 'Seitenbacher Müsli 479, Knackige Mischung Ohne Süß...', 'UNKNOWN'),
    ('Golden Bridge', 'Früchte-Müsli Vollkorn', 'B'),
    ('Kölln', 'Crunchy Hazel Hafer-Müsli', 'D'),
    ('Dr. Oetker', 'Vitalis Schokomüsli', 'C'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli feinherb', 'C'),
    ('Dr. Oetker', 'Knusper Schoko Weniger Süß', 'B'),
    ('Gut Bio', 'Bio Knusper-Müsli Schoko-Banane', 'D'),
    ('Dr. Oetker', 'Vitalis Müsli weniger süß - Knusper Früchte', 'C'),
    ('Kölln', 'Regenbogenmüsli', 'C'),
    ('DmBio', 'Schoko-Müsli glutenfrei', 'A'),
    ('Kaufland Bio', 'Beeren-Müsli', 'A'),
    ('Dr. Oetker', 'Vitalis Müsli Double Choc', 'D'),
    ('Dr. Oetker', 'Veganes Müsli Knusper Triple Chunks', 'C'),
    ('GUT bio', 'Bio Knusper-Müsli Mango', 'C'),
    ('Kölln', 'Hafer-Müsli - Crunchy Peanut Choc', 'D'),
    ('Dr. Oetker', 'Vitalis Knuspermüsli Plus', 'D'),
    ('Seitenbacher', 'Gebackenes Müsli', 'C'),
    ('Vitalis', 'Schoko Müsli Feinherb', 'C'),
    ('Gut Bio', 'Bio Knusper-Müsli Beere', 'C'),
    ('Dr. Oetker', 'Vitalis Weniger süß', 'C'),
    ('Seitenbacher', 'Düsis', 'A'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli klassisch', 'C'),
    ('Seitenbacher', 'Apfel-Zimt-Müsli', 'C'),
    ('Seitenbacher', 'Müsli 615 Natural-Body-Power', 'B'),
    ('Dr. Oetker', 'Roasted Müsli Schoko Nuss', 'C'),
    ('Dr. Oetker', 'Knusper Müsli Klassisch', 'C'),
    ('Bio Zentrale', 'Crunchy Müsli Amaranth', 'C'),
    ('Seitenbacher', 'Seitenbacher Müsli 477 die geröstete Eiweißquelle', 'B'),
    ('EnerBio', 'Müsli Bio Schoko Crunchy', 'D'),
    ('Dr. Oetker', 'Knusper Müsli Brownie Style', 'C'),
    ('Kölln', 'Knusper-Hafermüsli - Strawberry Yogurt', 'C'),
    ('Aldi', 'Bio-Müsli Klassik - Dinkel und Schoko', 'C'),
    ('Aldi', 'Bio-Müsli Klassik - Dinkel und Früchte', 'E'),
    ('Kölln Müsli', 'Kölln Knusper Schoko-Minze Hafer Müsli', 'E'),
    ('Kölln', 'Mühlenklassiker mit feinen roten Beeren', 'A'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Flakes & Mandeln', 'C'),
    ('Kölln', 'Mühlenklassiker mit vielen ganzen Nüssen', 'A'),
    ('Dr. Oetker', 'VITALIS Knusper Müsli Schoko feinherb', 'C'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Nougat-Schoko', 'C'),
    ('Aldi', 'Bio-Müsli - Apfel-Mandel-Urkorn', 'A'),
    ('Aldi', 'Bio-Müsli - Dinkel-Nuss-Crunchy', 'A'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli Duo', 'C'),
    ('Kölln', 'Hafen-Müsli banana bread style', 'A'),
    ('Dr. Oetker', 'Kokos Mandel Müsli', 'C'),
    ('Golden Bridge', 'Knusper Müsli mit 5% kakaofreier Schokoladenalternative', 'C'),
    ('Kölln', 'Schokomüsli', 'C'),
    ('Knusperone', 'Premium-Müsli - Honig-Nuss', 'D'),
    ('Crownfield', 'Bio Knusper Müsli Früchte', 'C'),
    ('Kölln', 'Knusper Klassik Hafer-Müsli Vorratspack', 'D'),
    ('Dr. Oetker', 'Vitalis Roasted Müsli Cranberry-kürbiskern', 'C'),
    ('Dr. Oetker', 'Vitalis Knuspermüsli Schoko', 'D'),
    ('Kölln', 'Schoko 2.0 Hafer-Müsli', 'D'),
    ('Golden Bridge', 'Knuspermüsli Klassik ohne Rosinen', 'D'),
    ('K Classic', 'Schoko Knuspermüsli', 'D'),
    ('K Classic', 'Schoko Müsli', 'C'),
    ('Bio Zentrale', 'Protein Müsli, Schoko', 'C'),
    ('Dr. Oetker', 'Vitalis Veganes Müsli Knusper Berry & White Chunks', 'C'),
    ('Aro', 'Früchte-Müsli', 'C'),
    ('Kölln', 'Knusper-Hafermüsli - Apple Crumble Style', 'C'),
    ('Minderleinsmühle', 'Bio Cranberry Johannisbeer Müsli', 'C'),
    ('Aldi', 'Premium-Müsli - Triple-Choc', 'D'),
    ('Aldi', 'Premium-Müsli - Früchte & Nüsse', 'C'),
    ('Kölln', 'Früchte Hafer Müsli', 'C'),
    ('Kölln', 'Das Original Joghurt Erdbeer Hafer-Müsli', 'D'),
    ('Schneekoppe', 'Basis Müsli 5-Korn-Mix', 'A'),
    ('Knusperone', 'Schoko Müsli', 'A'),
    ('Kölln', 'Früchte Hafer-Müsli', 'C'),
    ('Kölln kölln', 'Schoko Müsli', 'C'),
    ('Kölln', 'Knusper Müsli', 'D'),
    ('Kölln', 'Hafer Müsli', 'A'),
    ('Kölln', 'Früchte Müsli ohne Zuckerzusatz', 'C'),
    ('DmBio', 'Müsli Nuss', 'C'),
    ('DmBio', 'Paleo Müsli', 'A'),
    ('Golden Bridge', 'Premium Müsli', 'C'),
    ('Dr. Oetker', 'Vitalis Müsli Knusper Schoko ohne Zuckerzusatz', 'B'),
    ('DmBio', 'Basismüsli ohne Rosinen', 'A'),
    ('Kölln', 'Knusper Schoko & Keks Müsli', 'D'),
    ('Kölln', 'Knusper Joghurt Himbeer Müsli', 'D'),
    ('Seitenbacher', 'Müsli 508 Dinos Frühstück', 'D'),
    ('Dr. Oetker', 'Paula Müslispaß Schoko', 'C'),
    ('DmBio', 'Früchte müsli', 'C'),
    ('Bauck Mühle', 'Schoko+Flakes Hafer Müsli Bio', 'A'),
    ('Brüggen', 'Schoko-Müsli', 'C'),
    ('Seitenbacher', 'Bergsteiger Müsli', 'A'),
    ('Seitenbacher', 'Müsli zuckerarm', 'A'),
    ('Golden Bridge', 'Schoko Knusper Müsli', 'C'),
    ('Kölln', 'Schoko Hafer Müesli', 'C'),
    ('Aldi', 'Klassik Knusper Müsli', 'C'),
    ('Rapunzel', 'Mond & Sterne Müsli', 'B'),
    ('Kölln', 'Vollkorn Basis-Müsli', 'A'),
    ('Gut Bio', 'Basismüsli - Fach 7', 'A'),
    ('Bauck Mühle', 'Protein Hafer Müsli', 'A'),
    ('Dr. Oetker', 'Knuspermüsli Schoko', 'C'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli', 'C'),
    ('Aldi Bio', 'Klassik Müsli Dinkel & Schoko', 'C'),
    ('Seitenbacher', 'Energy-Müsli', 'A'),
    ('Seitenbacher', 'Protein Müsli 1', 'C'),
    ('Dr. Oetker', 'Vitalis Früchte Müsli', 'C'),
    ('Golden Bridge', 'Schoko Keks Knusper Müsli', 'D'),
    ('Bauck Mühle', 'Fertigmischung für warmen Haferbrei mit sieben verschiedenen Saaten7-Saaten', 'A'),
    ('Bauck Mühle', 'Beeren Hafer Müsli', 'A'),
    ('Peter Kölln', 'Schoko & Kekse Müsli', 'D'),
    ('Dr. Oetker', 'Vitalis Weniger süß Schoko Müsli', 'C'),
    ('Seitenbacher', 'Urkorn Müsli', 'C'),
    ('Seitenbacher', 'Protein Müsli', 'E'),
    ('Bauck Hof', 'Schoko Dinkel Müsli Bio', 'A'),
    ('Kölln', 'Crunchy Waffel Hafer-Müsli', 'D'),
    ('Dr. Oetker Vitalis', 'Vitalis Knuspermüsli zuckerfrei', 'A'),
    ('Seitenbacher', 'Sonnenmüsli', 'A'),
    ('Kaufland Bio', 'Müsli', 'A'),
    ('Seitenbacher', 'Frühstücks-Müsli', 'A'),
    ('Rossmann', 'Basis Müsli', 'A'),
    ('Bauckmühle', 'Schoko Hafer Müsli', 'A'),
    ('Kölln', 'Knusper Schoko-Krokant Hafer-Müsli', 'UNKNOWN'),
    ('Seitenbacher Naturkost', 'Seitenbacher Müsli 721 Verwöhner Mischung', 'A'),
    ('Seitenbacher', 'Müsli Extra für Kinder', 'C'),
    ('Kölln', 'Müsli Schokolade', 'C'),
    ('Seitenbacher', 'Manager Müsli', 'C'),
    ('Bio-Zentrale', 'Protein Müsli', 'A'),
    ('Rapunzel', 'Frühstücksbrei Basen Balance', 'A'),
    ('Allos', 'Das Ungesüßte Protein-Müsli', 'A'),
    ('Crownfield', 'Premium Müsli Früchte und Nüsse', 'D'),
    ('DmBio', 'Kindermüsli - ohne Rosinen', 'A'),
    ('DmBio', 'Bircher Müsli nach Schweizer Art ohne Zuckerzusatz', 'A'),
    ('K-Classic', 'Bircher Müsli', 'C'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Schoko + Banane', 'C'),
    ('Bio Aldi', 'Knusper Müsli Schoko Amaranth', 'C'),
    ('Aldi', 'Knüsper Müsli Berren', 'C'),
    ('Seitenbacher', 'Müsli 656 Dinkel-Mischung', 'A'),
    ('Gut bio', 'Müsli Klassik Dinkel und Früchte', 'C'),
    ('Kölln', 'Mühlenklassiker Früchte', 'B'),
    ('Kölln', 'Zartes Bircher Fruchtiges Hafer-Müsli', 'A'),
    ('Rapunzel', 'Basis Müsli', 'A'),
    ('Allos', 'Das ungesüßte Schoko-Müsli', 'A'),
    ('K Classic', 'Schoko Müsli Weniger Süß', 'A'),
    ('Kaufland', 'Bio Dinkel Früchte Müsli', 'C'),
    ('Bauck Mühle', 'Früchte + Flakes Hafer Müsli', 'A'),
    ('Rapunzel', 'Schmetterlings Müsli', 'A'),
    ('Dr. Oetker', 'Knusper Müsli Cinnamon Roll Style', 'C'),
    ('Seitenbacher', 'Müsli 054 Confiserie', 'C'),
    ('Seitenbacher', 'Seitenbacher Müsli 362, Ballaststoffe + Chia', 'A'),
    ('Kölln', 'Müsli Knusper Schoko-Krokant', 'D'),
    ('Kölln', 'Knusper Honig-Nuss Hafer-Müsli', 'D'),
    ('Allos', 'Das Ungesüßte Beeren-Müsli', 'A'),
    ('HiPP', 'Beeren Müesli', 'A'),
    ('Bauck Hof', 'Müzli Knusperzart Dinkel', 'A'),
    ('Dr. Oetker', 'High Protein - Müsli Schoko & Nuss', 'C'),
    ('Seitenbacher', 'Protein Müsli 2', 'C'),
    ('Barnhouse', 'Krunchy Erdbeere Hafer Müsli', 'C'),
    ('Rosengarten', 'Nuss Müsli, 3 Edle Nusssorten', 'A'),
    ('Barnhouse', 'Krunchy Very Berry Müsli', 'B'),
    ('Bauck Hof', 'Müzli Früchtezart', 'A'),
    ('Rapunzel', 'Frühstücksbrei Kakao Banane', 'A'),
    ('Dennree', 'Schokomüsli', 'D'),
    ('DmBio', 'Kinder Früchte Müsli', 'A'),
    ('Bioland', '5-Korn Aktiv Müsli feine Früchte', 'A'),
    ('Trek n eat', 'Vollkorn Früchtemüsli', 'UNKNOWN'),
    ('Bauck Mühle', 'Nussgenuss Hafer Müsli', 'A'),
    ('De-Vau-Ge', 'Knuspermüsli - Apfel-Zimt', 'C'),
    ('Dr. Oetker', 'Veganes Müsli Knusper Apple White Chunks', 'C'),
    ('Bio', 'Klassik Müsli', 'C'),
    ('Aldi', 'Knüsper Müsli Nüsse', 'C'),
    ('Dr. Oetker', 'Vitalis SuperMüsli', 'C'),
    ('Kölln', 'Müsli Knusper Schoko-Karamell', 'D'),
    ('Knusperone', 'Früchte Müsli Vollkorn', 'B'),
    ('Kölln', 'Schoko & Keks Müsli', 'D'),
    ('Hipp', 'Knusper Müsli', 'A'),
    ('Müsli', 'Knusper-Müsli mit Beeren', 'D')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Dr. Oetker', 'Vitalis Knuspermüsli Weniger Süß Knusper pur ohne Rosinen', '4'),
    ('Kölln', 'Kölln Knusper Volkorn-Müsli mit Vanille-Note 500g', '4'),
    ('Kölln', 'Knusper Honig-Nuss Müsli', '4'),
    ('Dm', 'Bio Schokomüsli ohne Rosinen', '4'),
    ('Kölln', 'Kellogs, Hafer-Müsli, Schoko und Keks', '4'),
    ('Kölln', 'Zartes Bircher Müsli', '3'),
    ('Seitenbacher', 'Kakao-Düsis', '4'),
    ('Dr. Oetker Vitalis', 'Vitalis Weniger süß Knusper Himbeere', '4'),
    ('Kölln', 'Crunchy Choc-Choc-Choc - Hafer-Müsli', '4'),
    ('Kölln', 'Hafer Müsli Beere Apfel', '1'),
    ('Dr. Oetker', 'Schoko Müsli klassisch', '4'),
    ('Dr. Oetker', 'Vitalis Knusper Schoko Müsli', '4'),
    ('Golden Bridge', 'Trauben-Nuss Müsli Vollkorn', '3'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli PLUS Nussmischung', '4'),
    ('Dr. Oetker', 'Vitalis Müsli Joghurt', '4'),
    ('Kölln', 'Crunchy Berry Hafer-Müsli', '4'),
    ('Kölln', 'Kölln Müsli Nuss & Krokant', '4'),
    ('Seitenbacher', 'Müsli 205 Für Sportliche', '3'),
    ('Dr. Oetker', 'Vitalis Knusper müsli Honeys', '4'),
    ('Golden Bridge', 'Schoko-Müsli mit 30 % weniger Zucker', '4'),
    ('Golden Bridge', 'Früchte-Müsli', '3'),
    ('DmBio', 'Beeren Müsli', '1'),
    ('Kölln', 'Schoko Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli klassisch', '4'),
    ('Crownfield', 'Schoko Müsli', '4'),
    ('Dr. Oetker', 'Knusper Schoko Müsli', '4'),
    ('GUT Bio', 'Basis Müsli 5-Kornmix', '4'),
    ('Kölln', 'Crunchy Mango-Maracuja Hafer-Müsli', '4'),
    ('Aldi', 'Bio-Müsli - Urkorn-Früchte', '1'),
    ('Dr. Oetker', 'Müsli Schoko weniger süss', '4'),
    ('Kölln', 'EDEKA Müsli Kölln Müsli Knusper Schoko-Krokant 500g 2.49€ 1kg 4.98€', '4'),
    ('GUT bio', 'Bio Knusper-Müsli Schoko-Amaranth', '3'),
    ('Seitenbacher', 'Seitenbacher Müsli 479, Knackige Mischung Ohne Süß...', '1'),
    ('Golden Bridge', 'Früchte-Müsli Vollkorn', '3'),
    ('Kölln', 'Crunchy Hazel Hafer-Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Schokomüsli', '4'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli feinherb', '4'),
    ('Dr. Oetker', 'Knusper Schoko Weniger Süß', '4'),
    ('Gut Bio', 'Bio Knusper-Müsli Schoko-Banane', '4'),
    ('Dr. Oetker', 'Vitalis Müsli weniger süß - Knusper Früchte', '4'),
    ('Kölln', 'Regenbogenmüsli', '4'),
    ('DmBio', 'Schoko-Müsli glutenfrei', '3'),
    ('Kaufland Bio', 'Beeren-Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Müsli Double Choc', '4'),
    ('Dr. Oetker', 'Veganes Müsli Knusper Triple Chunks', '4'),
    ('GUT bio', 'Bio Knusper-Müsli Mango', '3'),
    ('Kölln', 'Hafer-Müsli - Crunchy Peanut Choc', '4'),
    ('Dr. Oetker', 'Vitalis Knuspermüsli Plus', '4'),
    ('Seitenbacher', 'Gebackenes Müsli', '4'),
    ('Vitalis', 'Schoko Müsli Feinherb', '4'),
    ('Gut Bio', 'Bio Knusper-Müsli Beere', '3'),
    ('Dr. Oetker', 'Vitalis Weniger süß', '4'),
    ('Seitenbacher', 'Düsis', '4'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli klassisch', '4'),
    ('Seitenbacher', 'Apfel-Zimt-Müsli', '4'),
    ('Seitenbacher', 'Müsli 615 Natural-Body-Power', '1'),
    ('Dr. Oetker', 'Roasted Müsli Schoko Nuss', '4'),
    ('Dr. Oetker', 'Knusper Müsli Klassisch', '4'),
    ('Bio Zentrale', 'Crunchy Müsli Amaranth', '4'),
    ('Seitenbacher', 'Seitenbacher Müsli 477 die geröstete Eiweißquelle', '3'),
    ('EnerBio', 'Müsli Bio Schoko Crunchy', '4'),
    ('Dr. Oetker', 'Knusper Müsli Brownie Style', '4'),
    ('Kölln', 'Knusper-Hafermüsli - Strawberry Yogurt', '4'),
    ('Aldi', 'Bio-Müsli Klassik - Dinkel und Schoko', '4'),
    ('Aldi', 'Bio-Müsli Klassik - Dinkel und Früchte', '4'),
    ('Kölln Müsli', 'Kölln Knusper Schoko-Minze Hafer Müsli', '4'),
    ('Kölln', 'Mühlenklassiker mit feinen roten Beeren', '3'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Flakes & Mandeln', '4'),
    ('Kölln', 'Mühlenklassiker mit vielen ganzen Nüssen', '1'),
    ('Dr. Oetker', 'VITALIS Knusper Müsli Schoko feinherb', '4'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Nougat-Schoko', '4'),
    ('Aldi', 'Bio-Müsli - Apfel-Mandel-Urkorn', '3'),
    ('Aldi', 'Bio-Müsli - Dinkel-Nuss-Crunchy', '3'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli Duo', '4'),
    ('Kölln', 'Hafen-Müsli banana bread style', '3'),
    ('Dr. Oetker', 'Kokos Mandel Müsli', '4'),
    ('Golden Bridge', 'Knusper Müsli mit 5% kakaofreier Schokoladenalternative', '4'),
    ('Kölln', 'Schokomüsli', '4'),
    ('Knusperone', 'Premium-Müsli - Honig-Nuss', '3'),
    ('Crownfield', 'Bio Knusper Müsli Früchte', '4'),
    ('Kölln', 'Knusper Klassik Hafer-Müsli Vorratspack', '4'),
    ('Dr. Oetker', 'Vitalis Roasted Müsli Cranberry-kürbiskern', '4'),
    ('Dr. Oetker', 'Vitalis Knuspermüsli Schoko', '4'),
    ('Kölln', 'Schoko 2.0 Hafer-Müsli', '4'),
    ('Golden Bridge', 'Knuspermüsli Klassik ohne Rosinen', '3'),
    ('K Classic', 'Schoko Knuspermüsli', '4'),
    ('K Classic', 'Schoko Müsli', '4'),
    ('Bio Zentrale', 'Protein Müsli, Schoko', '3'),
    ('Dr. Oetker', 'Vitalis Veganes Müsli Knusper Berry & White Chunks', '4'),
    ('Aro', 'Früchte-Müsli', '3'),
    ('Kölln', 'Knusper-Hafermüsli - Apple Crumble Style', '4'),
    ('Minderleinsmühle', 'Bio Cranberry Johannisbeer Müsli', '4'),
    ('Aldi', 'Premium-Müsli - Triple-Choc', '4'),
    ('Aldi', 'Premium-Müsli - Früchte & Nüsse', '4'),
    ('Kölln', 'Früchte Hafer Müsli', '4'),
    ('Kölln', 'Das Original Joghurt Erdbeer Hafer-Müsli', '4'),
    ('Schneekoppe', 'Basis Müsli 5-Korn-Mix', '4'),
    ('Knusperone', 'Schoko Müsli', '4'),
    ('Kölln', 'Früchte Hafer-Müsli', '4'),
    ('Kölln kölln', 'Schoko Müsli', '4'),
    ('Kölln', 'Knusper Müsli', '4'),
    ('Kölln', 'Hafer Müsli', '4'),
    ('Kölln', 'Früchte Müsli ohne Zuckerzusatz', '4'),
    ('DmBio', 'Müsli Nuss', '3'),
    ('DmBio', 'Paleo Müsli', '1'),
    ('Golden Bridge', 'Premium Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Müsli Knusper Schoko ohne Zuckerzusatz', '4'),
    ('DmBio', 'Basismüsli ohne Rosinen', '1'),
    ('Kölln', 'Knusper Schoko & Keks Müsli', '4'),
    ('Kölln', 'Knusper Joghurt Himbeer Müsli', '4'),
    ('Seitenbacher', 'Müsli 508 Dinos Frühstück', '4'),
    ('Dr. Oetker', 'Paula Müslispaß Schoko', '4'),
    ('DmBio', 'Früchte müsli', '4'),
    ('Bauck Mühle', 'Schoko+Flakes Hafer Müsli Bio', '4'),
    ('Brüggen', 'Schoko-Müsli', '4'),
    ('Seitenbacher', 'Bergsteiger Müsli', '3'),
    ('Seitenbacher', 'Müsli zuckerarm', '3'),
    ('Golden Bridge', 'Schoko Knusper Müsli', '4'),
    ('Kölln', 'Schoko Hafer Müesli', '4'),
    ('Aldi', 'Klassik Knusper Müsli', '4'),
    ('Rapunzel', 'Mond & Sterne Müsli', '4'),
    ('Kölln', 'Vollkorn Basis-Müsli', '1'),
    ('Gut Bio', 'Basismüsli - Fach 7', '4'),
    ('Bauck Mühle', 'Protein Hafer Müsli', '1'),
    ('Dr. Oetker', 'Knuspermüsli Schoko', '4'),
    ('Dr. Oetker', 'Vitalis Schoko Müsli', '4'),
    ('Aldi Bio', 'Klassik Müsli Dinkel & Schoko', '4'),
    ('Seitenbacher', 'Energy-Müsli', '3'),
    ('Seitenbacher', 'Protein Müsli 1', '4'),
    ('Dr. Oetker', 'Vitalis Früchte Müsli', '3'),
    ('Golden Bridge', 'Schoko Keks Knusper Müsli', '4'),
    ('Bauck Mühle', 'Fertigmischung für warmen Haferbrei mit sieben verschiedenen Saaten7-Saaten', '1'),
    ('Bauck Mühle', 'Beeren Hafer Müsli', '3'),
    ('Peter Kölln', 'Schoko & Kekse Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Weniger süß Schoko Müsli', '4'),
    ('Seitenbacher', 'Urkorn Müsli', '4'),
    ('Seitenbacher', 'Protein Müsli', '3'),
    ('Bauck Hof', 'Schoko Dinkel Müsli Bio', '3'),
    ('Kölln', 'Crunchy Waffel Hafer-Müsli', '4'),
    ('Dr. Oetker Vitalis', 'Vitalis Knuspermüsli zuckerfrei', '4'),
    ('Seitenbacher', 'Sonnenmüsli', '1'),
    ('Kaufland Bio', 'Müsli', '1'),
    ('Seitenbacher', 'Frühstücks-Müsli', '4'),
    ('Rossmann', 'Basis Müsli', '1'),
    ('Bauckmühle', 'Schoko Hafer Müsli', '4'),
    ('Kölln', 'Knusper Schoko-Krokant Hafer-Müsli', '4'),
    ('Seitenbacher Naturkost', 'Seitenbacher Müsli 721 Verwöhner Mischung', '1'),
    ('Seitenbacher', 'Müsli Extra für Kinder', '4'),
    ('Kölln', 'Müsli Schokolade', '4'),
    ('Seitenbacher', 'Manager Müsli', '4'),
    ('Bio-Zentrale', 'Protein Müsli', '3'),
    ('Rapunzel', 'Frühstücksbrei Basen Balance', '1'),
    ('Allos', 'Das Ungesüßte Protein-Müsli', '3'),
    ('Crownfield', 'Premium Müsli Früchte und Nüsse', '4'),
    ('DmBio', 'Kindermüsli - ohne Rosinen', '4'),
    ('DmBio', 'Bircher Müsli nach Schweizer Art ohne Zuckerzusatz', '1'),
    ('K-Classic', 'Bircher Müsli', '4'),
    ('Dr. Oetker', 'Vitalis Knusper Müsli Schoko + Banane', '4'),
    ('Bio Aldi', 'Knusper Müsli Schoko Amaranth', '4'),
    ('Aldi', 'Knüsper Müsli Berren', '3'),
    ('Seitenbacher', 'Müsli 656 Dinkel-Mischung', '3'),
    ('Gut bio', 'Müsli Klassik Dinkel und Früchte', '4'),
    ('Kölln', 'Mühlenklassiker Früchte', '3'),
    ('Kölln', 'Zartes Bircher Fruchtiges Hafer-Müsli', '3'),
    ('Rapunzel', 'Basis Müsli', '1'),
    ('Allos', 'Das ungesüßte Schoko-Müsli', '1'),
    ('K Classic', 'Schoko Müsli Weniger Süß', '4'),
    ('Kaufland', 'Bio Dinkel Früchte Müsli', '3'),
    ('Bauck Mühle', 'Früchte + Flakes Hafer Müsli', '4'),
    ('Rapunzel', 'Schmetterlings Müsli', '3'),
    ('Dr. Oetker', 'Knusper Müsli Cinnamon Roll Style', '4'),
    ('Seitenbacher', 'Müsli 054 Confiserie', '3'),
    ('Seitenbacher', 'Seitenbacher Müsli 362, Ballaststoffe + Chia', '1'),
    ('Kölln', 'Müsli Knusper Schoko-Krokant', '4'),
    ('Kölln', 'Knusper Honig-Nuss Hafer-Müsli', '4'),
    ('Allos', 'Das Ungesüßte Beeren-Müsli', '3'),
    ('HiPP', 'Beeren Müesli', '1'),
    ('Bauck Hof', 'Müzli Knusperzart Dinkel', '3'),
    ('Dr. Oetker', 'High Protein - Müsli Schoko & Nuss', '4'),
    ('Seitenbacher', 'Protein Müsli 2', '4'),
    ('Barnhouse', 'Krunchy Erdbeere Hafer Müsli', '3'),
    ('Rosengarten', 'Nuss Müsli, 3 Edle Nusssorten', '3'),
    ('Barnhouse', 'Krunchy Very Berry Müsli', '4'),
    ('Bauck Hof', 'Müzli Früchtezart', '3'),
    ('Rapunzel', 'Frühstücksbrei Kakao Banane', '1'),
    ('Dennree', 'Schokomüsli', '4'),
    ('DmBio', 'Kinder Früchte Müsli', '1'),
    ('Bioland', '5-Korn Aktiv Müsli feine Früchte', '4'),
    ('Trek n eat', 'Vollkorn Früchtemüsli', '4'),
    ('Bauck Mühle', 'Nussgenuss Hafer Müsli', '4'),
    ('De-Vau-Ge', 'Knuspermüsli - Apfel-Zimt', '4'),
    ('Dr. Oetker', 'Veganes Müsli Knusper Apple White Chunks', '4'),
    ('Bio', 'Klassik Müsli', '4'),
    ('Aldi', 'Knüsper Müsli Nüsse', '4'),
    ('Dr. Oetker', 'Vitalis SuperMüsli', '4'),
    ('Kölln', 'Müsli Knusper Schoko-Karamell', '4'),
    ('Knusperone', 'Früchte Müsli Vollkorn', '3'),
    ('Kölln', 'Schoko & Keks Müsli', '4'),
    ('Hipp', 'Knusper Müsli', '1'),
    ('Müsli', 'Knusper-Müsli mit Beeren', '3')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Breakfast & Grain-Based', 100, 'DE');
