-- PIPELINE (Oils & Vinegars): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Bellasan', 'Natives Olivenöl Extra', 'B'),
    ('Primadonna', 'Natives Olivenöl extra', 'B'),
    ('DmBio', 'Natives Olivenöl extra', 'B'),
    ('Lyttos', 'Olivenöl', 'B'),
    ('DmBio', 'Bratolivenöl', 'B'),
    ('Camaletti', 'Camaletti Olivenöl', 'B'),
    ('Gut Bio', 'Natives Olivenöl Extra', 'B'),
    ('Lyttos', 'Griechisches natives Olivenöl extra', 'D'),
    ('Primadonna', 'Brat Olivenöl', 'B'),
    ('Primadonna', 'Olivenöl (nativ, extra)', 'B'),
    ('Aldi', 'Griechisches natives Olivenöl Extra', 'UNKNOWN'),
    ('Bellasan', 'Oliven Öl', 'B'),
    ('K-Classic', 'Natives Olivenöl extra', 'B'),
    ('Lidl', 'Natives Olivenöl extra aus Griechenland', 'B'),
    ('DmBio', 'Natives Olivenöl extra naturtrüb', 'B'),
    ('Cucina Nobile', 'Natives Olivenöl', 'B'),
    ('Aldi Bellasan', 'ALDI BELLASAN Natives Olivenöl extra für kalte Zubereitungen wie Salate und Vinaigretten geeignet, in PET-Flasche 1l 8.99€', 'B'),
    ('Bellasan', 'Olivenöl', 'B'),
    ('Aldi', 'Natives Olivenöl Extra', 'UNKNOWN'),
    ('Gourmet Finest Cuisine', 'Aromatisiertes Olivenöl mit Gewürzen - Rosmarin', 'B'),
    ('Cucina Nobile', 'Aromatisiertes Würzöl aus nativem Olivenöl Extra - Zitrone', 'B'),
    ('Aldi', 'Aromatisiertes Würzöl aus nativem Olivenöl Extra - Tomate', 'B'),
    ('Primadonna', 'Olivenöl', 'B'),
    ('Rapunzel', 'Ö-Kreta Olivenöl nativ extra-10,48€/29.6.22', 'B'),
    ('Ener Bio', 'Griechisches natives Olivenöl e', 'B'),
    ('Deluxe', 'Olivenöl', 'B'),
    ('K Favorites', 'Natives Olivenöl Extra', 'B'),
    ('Rapunzel', 'Olivenöl fruchtig', 'B'),
    ('Rapunzel', 'Olivenöl nativ extra mild', 'C'),
    ('Rapunzel', 'Ölivenöl Finca la Torre', 'B'),
    ('Biozentrsle', 'Olivenöl', 'B'),
    ('Deluxe', 'Öl - Olivenöl Extra G.G.A. Chania Kritis', 'B'),
    ('Dennree', 'Olivenöl nativ extra', 'B'),
    ('Aldi', 'Aromatisiertes Olivenöl mit Gewürzen - Chili', 'UNKNOWN'),
    ('Erfurter Ölmühle', 'Natives Olivenöl Extra', 'B'),
    ('Rapunzel', 'Sicilia Olivenöl nativ extra', 'B'),
    ('Lyttos', 'Olivenöl nativ extra', 'UNKNOWN'),
    ('Ölmühle Solling', 'Natives Olivenöl', 'B'),
    ('Falani', 'Olivenöl', 'B'),
    ('Cantinelle', 'Olivenöl', 'B'),
    ('Campo Verde', 'Olivenöl', 'B'),
    ('Cazorla', 'Natives Olivenöl extra', 'B'),
    ('Minos', 'Olivenöl extra nativ', 'B'),
    ('Brändle', 'Vita Olivenöl nativ extra', 'B'),
    ('Eridanous', 'Eridanus Olivenöl', 'B'),
    ('Kunella', 'Olivenöl', 'B'),
    ('Dennree', 'Bratöl Olive', 'B'),
    ('Rapunzel', 'Rapunzel Olivenöl Mild Nativ Extra, 250 ML Flasche', 'C'),
    ('Feines aus Spanien', 'Olivenöl Natives Olivenöl Extra', 'B'),
    ('Gourmet Finest Cuisine', 'Natives Olivenöl Extra - Italien', 'UNKNOWN'),
    ('Sovena Espana', 'Natives Olivenöl Extra', 'UNKNOWN'),
    ('Basic', 'Natives Olivenöl extra', 'B'),
    ('Bioladen', 'Natives Olivenöl Extra', 'B'),
    ('Primadonna', 'Extra Virgin Olive Oil', 'B'),
    ('Rapunzel', 'Rapunzel Olivenöl Fruchtig, Nativ Extra, 0,5 LTR Flasche', 'B'),
    ('Mamma Lucia', 'Natives Olivenöl Extra', 'B'),
    ('Rapunzel', 'Olivenöl nativ extra', 'B'),
    ('BioGourmet', 'Koronias Olivenöl nativ extra', 'B'),
    ('Unknown', 'Olivenöl griechisch', 'B'),
    ('Lidl', 'Huile d''olive vierge extra', 'B'),
    ('Unknown', 'Olivenöl', 'UNKNOWN'),
    ('Eridanous', 'Greek Extra Virgin Olive Oil Kalamata P.D.O.', 'B'),
    ('Rapunzel', 'Olivenöl', 'C'),
    ('Rapunzel', 'Polyphenolia Olivenöl nativ extra', 'B'),
    ('Dennree', 'Griechisches Olivenöl Nativ extra', 'B'),
    ('Bertolli', 'Natives Olivenöl Originale', 'B'),
    ('Rewe Bio', 'Natives Olivenöl Extra', 'B'),
    ('Edeka Bio', 'EDEKA Bio Natives Olivenöl extra 750ml 6.65€ 1l 9.27€', 'B'),
    ('Alnatura', 'Olivenöl', 'B'),
    ('Gut & Günstig', 'Olivenöl Extra Natives', 'B'),
    ('D.O.P. Terra Di Bari Castel Del Monte', 'Italienisches natives Olivenöl extra', 'UNKNOWN'),
    ('Bertolli', 'Olivenöl Natives Extra Gentile SANFT', 'B'),
    ('BioBio', 'Natives Bio-Olivenöl Extra', 'B'),
    ('EDEKA Bio', 'Natives Olivenöl extra', 'B'),
    ('Rewe beste Wahl', 'Olivenöl ideal für warme Speisen', 'B'),
    ('Ja!', 'Natives Olivenöl Extra', 'B'),
    ('La Espaniola', 'Natives Ölivenöl extra', 'B'),
    ('Las Cuarenta', 'Spanisches Natives Olivenöl extra', 'B'),
    ('Natur Gut', 'Natives Olivenöl Extra', 'B'),
    ('Bio', 'Bio natives Olivenöl', 'B'),
    ('Primadonna', 'Bio natives Olivenöl extra', 'B'),
    ('Vegola', 'Natives Olivenöl extra', 'B'),
    ('Fiore', 'Natives Olivenöl Extra', 'B'),
    ('REWE Feine Welt', 'Natives Olivenöl Extra Lesvos g.g.A.', 'B'),
    ('Edeka', 'Griechisches Natives Olivenöl Extra', 'B'),
    ('Carapelli', 'Bio Natives Olivenöl Extra', 'B'),
    ('De Cecco', 'Natives Olivenöl Extra', 'B'),
    ('Primadonna', 'Olivenöl Extra', 'B'),
    ('Ener Bio', 'Bratöl Olive mit Sonnenblumenöl', 'B'),
    ('Bertolli', 'Olivenöl Extra vergin', 'B'),
    ('Edeka', 'Natives Olivenöl extra angef.', 'B'),
    ('Eridanous', 'Olivenöl', 'B'),
    ('Eridanous', 'Eridanous', 'B'),
    ('Sol&mar', 'Natives Olivenöl extra', 'B'),
    ('Rewe', 'Natives Olivenöl Extra', 'B'),
    ('Tegut Bio', 'Olivenöl Bio', 'B'),
    ('Eridanous', 'Greek Olive Oil', 'B'),
    ('Byodo', 'Brat-Olive', 'B'),
    ('Rewe', 'Natives Olivenöl etra', 'B'),
    ('K Classic', 'Natives Olivenöl extra von K-Bio', 'B'),
    ('Bertolli', 'Olivenöl', 'B'),
    ('Kölln', 'Olivenöl', 'B'),
    ('Rewe Bio', 'Bio Natives Olivenöl Extra', 'B'),
    ('Bio', 'Natives Olivenöl extra', 'B'),
    ('Primadonna', 'Маслиново масло Extra Virgin', 'B'),
    ('Mylos', 'Bio Natives Olivenöl extra', 'B'),
    ('Bellucino', 'Olivenöl', 'C'),
    ('Rewe', 'Olivenöl', 'B'),
    ('Olivari', 'Olivari Bratöl', 'B'),
    ('Edeka', 'Griechisches Natives Olivenöl', 'B'),
    ('Kaufland', 'Natives Olivenöl extra', 'B'),
    ('Premieur', 'Natives Olivenöl Extra', 'B'),
    ('Giovanni Agnelli', 'Olivenöl nativ extra', 'B'),
    ('Aceites del Sur-Coosur', 'Natives Olivenöl Extra', 'B'),
    ('Bertolli', 'Natives Bio-Olivenöl Extra', 'B'),
    ('Bertolli', 'Brat Olivenöl von Bertolli', 'B'),
    ('Bertolli', 'Natives Olivenöl Extra Robusto', 'B'),
    ('Vegola', 'Olivenöl', 'B'),
    ('Alnatura', 'Griechisches natives Olivenöl extra', 'B'),
    ('Zeus', 'Griechisches natives Olivenöl extra', 'B'),
    ('Gut & Günstig', 'Natives Olivenöl Extra', 'B'),
    ('Alnatura', 'Italienisches Olivenöl', 'B'),
    ('Filippo Berio', 'Natives Olivenöl Extra , Classico', 'B'),
    ('Bertolli', 'Bratolivenöl', 'UNKNOWN'),
    ('Corovita', 'Olivenöl bio', 'UNKNOWN'),
    ('BioBio', 'Natives Olivenöl extra, kaltextrahiert', 'B'),
    ('Filippo Berio', 'Natives Olivenöl', 'B'),
    ('Edeka', 'Edeka Bio Rapskernöl', 'B'),
    ('Mitakos', 'Natives Olivenöl', 'UNKNOWN'),
    ('Chania Kritis', 'Griechisches Natives Olivenöl extra Chania Kritis G.G.A.', 'B'),
    ('Stern 1821', 'Olivenöl Extra', 'B'),
    ('Alnatura', 'Brat Olivenöl', 'B'),
    ('Gaea', 'Olivenöl', 'B'),
    ('Bio Planete', 'Olivenöl fruchtig', 'B'),
    ('Bio Planete', 'Öl Olivenöl Kaltgepresst', 'B'),
    ('La Espanola', 'Olivenöl', 'B'),
    ('Gaea', 'Natives Olivenöl extra', 'B'),
    ('Bertolli', 'Öl - Natives Olivenöl Extra', 'B'),
    ('Primadonna', 'Natives Olivenöl', 'B'),
    ('Latzimas', 'Natives Olivenöl', 'B'),
    ('La Espanola', 'Natives Olivenöl Extra', 'B'),
    ('Edeka', 'Natives Olivenöl Extra', 'B'),
    ('Bio Planete', 'Brat-Olivenöl', 'B'),
    ('Maria De La Vara', 'Premium Olivenöl Nativ Extra Spanien', 'B'),
    ('Gaea', 'Bio Natives Olivenöl Extra', 'B'),
    ('Jeden Tag', 'Natives Olivenöl extra', 'UNKNOWN'),
    ('Gaea', 'Fresh Olivenöl', 'B'),
    ('Olio & Pane', 'Bio Natives Olivenöl', 'B'),
    ('Penny', 'Olivenöl', 'B'),
    ('Mitos', 'Natives Olivenöl', 'B')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Bellasan', 'Natives Olivenöl Extra', '2'),
    ('Primadonna', 'Natives Olivenöl extra', '2'),
    ('DmBio', 'Natives Olivenöl extra', '2'),
    ('Lyttos', 'Olivenöl', '2'),
    ('DmBio', 'Bratolivenöl', '2'),
    ('Camaletti', 'Camaletti Olivenöl', '2'),
    ('Gut Bio', 'Natives Olivenöl Extra', '2'),
    ('Lyttos', 'Griechisches natives Olivenöl extra', '2'),
    ('Primadonna', 'Brat Olivenöl', '2'),
    ('Primadonna', 'Olivenöl (nativ, extra)', '2'),
    ('Aldi', 'Griechisches natives Olivenöl Extra', '2'),
    ('Bellasan', 'Oliven Öl', '2'),
    ('K-Classic', 'Natives Olivenöl extra', '2'),
    ('Lidl', 'Natives Olivenöl extra aus Griechenland', '2'),
    ('DmBio', 'Natives Olivenöl extra naturtrüb', '2'),
    ('Cucina Nobile', 'Natives Olivenöl', '2'),
    ('Aldi Bellasan', 'ALDI BELLASAN Natives Olivenöl extra für kalte Zubereitungen wie Salate und Vinaigretten geeignet, in PET-Flasche 1l 8.99€', '2'),
    ('Bellasan', 'Olivenöl', '2'),
    ('Aldi', 'Natives Olivenöl Extra', '2'),
    ('Gourmet Finest Cuisine', 'Aromatisiertes Olivenöl mit Gewürzen - Rosmarin', '4'),
    ('Cucina Nobile', 'Aromatisiertes Würzöl aus nativem Olivenöl Extra - Zitrone', '4'),
    ('Aldi', 'Aromatisiertes Würzöl aus nativem Olivenöl Extra - Tomate', '4'),
    ('Primadonna', 'Olivenöl', '2'),
    ('Rapunzel', 'Ö-Kreta Olivenöl nativ extra-10,48€/29.6.22', '2'),
    ('Ener Bio', 'Griechisches natives Olivenöl e', '2'),
    ('Deluxe', 'Olivenöl', '2'),
    ('K Favorites', 'Natives Olivenöl Extra', '4'),
    ('Rapunzel', 'Olivenöl fruchtig', '2'),
    ('Rapunzel', 'Olivenöl nativ extra mild', '2'),
    ('Rapunzel', 'Ölivenöl Finca la Torre', '2'),
    ('Biozentrsle', 'Olivenöl', '2'),
    ('Deluxe', 'Öl - Olivenöl Extra G.G.A. Chania Kritis', '2'),
    ('Dennree', 'Olivenöl nativ extra', '2'),
    ('Aldi', 'Aromatisiertes Olivenöl mit Gewürzen - Chili', '2'),
    ('Erfurter Ölmühle', 'Natives Olivenöl Extra', '2'),
    ('Rapunzel', 'Sicilia Olivenöl nativ extra', '2'),
    ('Lyttos', 'Olivenöl nativ extra', '2'),
    ('Ölmühle Solling', 'Natives Olivenöl', '4'),
    ('Falani', 'Olivenöl', '2'),
    ('Cantinelle', 'Olivenöl', '2'),
    ('Campo Verde', 'Olivenöl', '4'),
    ('Cazorla', 'Natives Olivenöl extra', '4'),
    ('Minos', 'Olivenöl extra nativ', '4'),
    ('Brändle', 'Vita Olivenöl nativ extra', '2'),
    ('Eridanous', 'Eridanus Olivenöl', '2'),
    ('Kunella', 'Olivenöl', '4'),
    ('Dennree', 'Bratöl Olive', '4'),
    ('Rapunzel', 'Rapunzel Olivenöl Mild Nativ Extra, 250 ML Flasche', '2'),
    ('Feines aus Spanien', 'Olivenöl Natives Olivenöl Extra', '2'),
    ('Gourmet Finest Cuisine', 'Natives Olivenöl Extra - Italien', '2'),
    ('Sovena Espana', 'Natives Olivenöl Extra', '2'),
    ('Basic', 'Natives Olivenöl extra', '2'),
    ('Bioladen', 'Natives Olivenöl Extra', '2'),
    ('Primadonna', 'Extra Virgin Olive Oil', '2'),
    ('Rapunzel', 'Rapunzel Olivenöl Fruchtig, Nativ Extra, 0,5 LTR Flasche', '2'),
    ('Mamma Lucia', 'Natives Olivenöl Extra', '2'),
    ('Rapunzel', 'Olivenöl nativ extra', '2'),
    ('BioGourmet', 'Koronias Olivenöl nativ extra', '2'),
    ('Unknown', 'Olivenöl griechisch', '2'),
    ('Lidl', 'Huile d''olive vierge extra', '2'),
    ('Unknown', 'Olivenöl', '2'),
    ('Eridanous', 'Greek Extra Virgin Olive Oil Kalamata P.D.O.', '2'),
    ('Rapunzel', 'Olivenöl', '2'),
    ('Rapunzel', 'Polyphenolia Olivenöl nativ extra', '2'),
    ('Dennree', 'Griechisches Olivenöl Nativ extra', '2'),
    ('Bertolli', 'Natives Olivenöl Originale', '4'),
    ('Rewe Bio', 'Natives Olivenöl Extra', '2'),
    ('Edeka Bio', 'EDEKA Bio Natives Olivenöl extra 750ml 6.65€ 1l 9.27€', '2'),
    ('Alnatura', 'Olivenöl', '2'),
    ('Gut & Günstig', 'Olivenöl Extra Natives', '4'),
    ('D.O.P. Terra Di Bari Castel Del Monte', 'Italienisches natives Olivenöl extra', '2'),
    ('Bertolli', 'Olivenöl Natives Extra Gentile SANFT', '4'),
    ('BioBio', 'Natives Bio-Olivenöl Extra', '2'),
    ('EDEKA Bio', 'Natives Olivenöl extra', '2'),
    ('Rewe beste Wahl', 'Olivenöl ideal für warme Speisen', '2'),
    ('Ja!', 'Natives Olivenöl Extra', '2'),
    ('La Espaniola', 'Natives Ölivenöl extra', '2'),
    ('Las Cuarenta', 'Spanisches Natives Olivenöl extra', '4'),
    ('Natur Gut', 'Natives Olivenöl Extra', '2'),
    ('Bio', 'Bio natives Olivenöl', '2'),
    ('Primadonna', 'Bio natives Olivenöl extra', '2'),
    ('Vegola', 'Natives Olivenöl extra', '2'),
    ('Fiore', 'Natives Olivenöl Extra', '2'),
    ('REWE Feine Welt', 'Natives Olivenöl Extra Lesvos g.g.A.', '2'),
    ('Edeka', 'Griechisches Natives Olivenöl Extra', '2'),
    ('Carapelli', 'Bio Natives Olivenöl Extra', '2'),
    ('De Cecco', 'Natives Olivenöl Extra', '2'),
    ('Primadonna', 'Olivenöl Extra', '2'),
    ('Ener Bio', 'Bratöl Olive mit Sonnenblumenöl', '2'),
    ('Bertolli', 'Olivenöl Extra vergin', '2'),
    ('Edeka', 'Natives Olivenöl extra angef.', '2'),
    ('Eridanous', 'Olivenöl', '2'),
    ('Eridanous', 'Eridanous', '2'),
    ('Sol&mar', 'Natives Olivenöl extra', '2'),
    ('Rewe', 'Natives Olivenöl Extra', '2'),
    ('Tegut Bio', 'Olivenöl Bio', '2'),
    ('Eridanous', 'Greek Olive Oil', '2'),
    ('Byodo', 'Brat-Olive', '2'),
    ('Rewe', 'Natives Olivenöl etra', '2'),
    ('K Classic', 'Natives Olivenöl extra von K-Bio', '2'),
    ('Bertolli', 'Olivenöl', '4'),
    ('Kölln', 'Olivenöl', '2'),
    ('Rewe Bio', 'Bio Natives Olivenöl Extra', '2'),
    ('Bio', 'Natives Olivenöl extra', '2'),
    ('Primadonna', 'Маслиново масло Extra Virgin', '2'),
    ('Mylos', 'Bio Natives Olivenöl extra', '2'),
    ('Bellucino', 'Olivenöl', '2'),
    ('Rewe', 'Olivenöl', '2'),
    ('Olivari', 'Olivari Bratöl', '2'),
    ('Edeka', 'Griechisches Natives Olivenöl', '2'),
    ('Kaufland', 'Natives Olivenöl extra', '2'),
    ('Premieur', 'Natives Olivenöl Extra', '2'),
    ('Giovanni Agnelli', 'Olivenöl nativ extra', '2'),
    ('Aceites del Sur-Coosur', 'Natives Olivenöl Extra', '2'),
    ('Bertolli', 'Natives Bio-Olivenöl Extra', '4'),
    ('Bertolli', 'Brat Olivenöl von Bertolli', '2'),
    ('Bertolli', 'Natives Olivenöl Extra Robusto', '4'),
    ('Vegola', 'Olivenöl', '2'),
    ('Alnatura', 'Griechisches natives Olivenöl extra', '2'),
    ('Zeus', 'Griechisches natives Olivenöl extra', '2'),
    ('Gut & Günstig', 'Natives Olivenöl Extra', '4'),
    ('Alnatura', 'Italienisches Olivenöl', '2'),
    ('Filippo Berio', 'Natives Olivenöl Extra , Classico', '2'),
    ('Bertolli', 'Bratolivenöl', '4'),
    ('Corovita', 'Olivenöl bio', '2'),
    ('BioBio', 'Natives Olivenöl extra, kaltextrahiert', '2'),
    ('Filippo Berio', 'Natives Olivenöl', '4'),
    ('Edeka', 'Edeka Bio Rapskernöl', '2'),
    ('Mitakos', 'Natives Olivenöl', '2'),
    ('Chania Kritis', 'Griechisches Natives Olivenöl extra Chania Kritis G.G.A.', '2'),
    ('Stern 1821', 'Olivenöl Extra', '2'),
    ('Alnatura', 'Brat Olivenöl', '2'),
    ('Gaea', 'Olivenöl', '2'),
    ('Bio Planete', 'Olivenöl fruchtig', '2'),
    ('Bio Planete', 'Öl Olivenöl Kaltgepresst', '2'),
    ('La Espanola', 'Olivenöl', '2'),
    ('Gaea', 'Natives Olivenöl extra', '2'),
    ('Bertolli', 'Öl - Natives Olivenöl Extra', '2'),
    ('Primadonna', 'Natives Olivenöl', '2'),
    ('Latzimas', 'Natives Olivenöl', '2'),
    ('La Espanola', 'Natives Olivenöl Extra', '2'),
    ('Edeka', 'Natives Olivenöl Extra', '2'),
    ('Bio Planete', 'Brat-Olivenöl', '4'),
    ('Maria De La Vara', 'Premium Olivenöl Nativ Extra Spanien', '2'),
    ('Gaea', 'Bio Natives Olivenöl Extra', '2'),
    ('Jeden Tag', 'Natives Olivenöl extra', '2'),
    ('Gaea', 'Fresh Olivenöl', '2'),
    ('Olio & Pane', 'Bio Natives Olivenöl', '2'),
    ('Penny', 'Olivenöl', '4'),
    ('Mitos', 'Natives Olivenöl', '2')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Oils & Vinegars', 100, 'DE');
