-- PIPELINE (Canned Goods): scoring
-- Generated: 2026-03-04

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Nasza Spiżarnia', 'Kukurydza słodka', 'B'),
    ('Marinero', 'Tuńczyk jednolity w oliwie z oliwek', 'B'),
    ('Marineo', 'Filety śledziowe w sosie pomidorowym', 'C'),
    ('Marinero', 'Łosoś Kawałki w sosie pomidorowym', 'A'),
    ('Graal', 'Tuńczyk kawałki w oleju roślinnym.', 'A'),
    ('Mariners', 'Paprykarz szczeciński z łososiem', 'C'),
    ('Marinero', 'Chili filety śledziowe', 'C'),
    ('Nasza Spiżarnia', 'Ogórki konserwowe', 'B'),
    ('Dawtona', 'Kukurydza słodka', 'B'),
    ('Marinero', 'Płaty śledziowe smażone w zalewie octowej', 'D'),
    ('Go Active', 'Proteinowa sałatka z łososiem pikantna', 'A'),
    ('Graal', 'Sałatka z makrelą pikantna', 'C'),
    ('Lisner', 'Śledź atlantycki opiekamy', 'A'),
    ('Carrefour Classic', 'Pomidory całe', 'A'),
    ('Krakus', 'Ćwikła z chrzanem', 'B'),
    ('Auchan', 'Kukurydza super słodka', 'B'),
    ('Nasza spiżarnia', 'Ogórki konserwowe', 'C'),
    ('Nasza spiżarnia', 'Mieszanka owoców w lekkim syropie', 'A'),
    ('Provitus', 'Ogórki konserwowe hot chili', 'C'),
    ('Mega ryba', 'Śledź w sosie pomidorowym.', 'C'),
    ('Łosoś Ustka', 'Śledź w sosie pomidorowym', 'B'),
    ('Biedronka', 'Ogórki ćwiartki', 'C'),
    ('Graal', 'Filety że śledzia w oleju', 'C'),
    ('Auchan', 'Kiszone ogórki', 'C'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym z papryką.', 'D'),
    ('Helcom', 'Tuńczyk kawałki w sosie własnym.', 'B'),
    ('EvraFish', 'Śledzie w sosie pomidorowym.', 'C'),
    ('Graal', 'Tuńczyk kawałki w bulionie warzywnym.', 'A'),
    ('Graal S.A.', 'Śledź w oleju po gdańsku', 'D'),
    ('Nasza spiżarnia', 'Ogórki kiszone', 'C'),
    ('Nasza Spiżarnia', 'Pomidory całe', 'A'),
    ('Lisner', 'Tuńczyk w sosie własnym', 'A'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym.', 'A'),
    ('Amerigo', 'Śledź w sosie pomidorowym', 'C'),
    ('Nasza Spiżarnia', 'Mieszanka warzywna z kukuyrdzą', 'B'),
    ('Dawtona', 'Pomidory skrojone z ziołami', 'A'),
    ('Helcom', 'Mix owoców w lekkim syropie', 'B'),
    ('Pudliszki', 'Fasolka po Bretońsku', 'C'),
    ('Lisner', 'Tuńczyk kawałki w oleju roślinnym', 'A'),
    ('Neptun', 'Tuńczyk W Wodzie', 'UNKNOWN'),
    ('Pudliszki', 'Pomidore krojone bez skórki w sosie pomidorowym.', 'A'),
    ('Asia Flavours', 'Jackfruit kawałki', 'A'),
    ('Nasza Spiżarnia', 'Ćwikła z chrzanem', 'A'),
    ('Graal', 'Śledź w sosie pomidorowym', 'C'),
    ('Smak', 'Konserwowe ogóreczki klasyczne', 'B'),
    ('MK', 'Szproty wędzone w sosie pomidorowym', 'E'),
    ('Helcom Premium', 'Brzoskwinie połówki', 'B'),
    ('Kuchnia STAROPOLSKA', 'Bigos z kiełbasą', 'C'),
    ('Łosoś', 'Paprykarz szczeciński', 'C'),
    ('Graal', 'Winter szprot podwędzany w oleju', 'C'),
    ('Provitus', 'Ogórki konserwowe kozackie', 'UNKNOWN'),
    ('Łowicz', 'Pomidory krojone bez skórki', 'A'),
    ('Ole!', 'Cebulka marynowana złota', 'C'),
    ('Łosoś Ustka', 'Śledź po gdańsku w oleju', 'D'),
    ('Unknown', 'Brzoskwinie połówki w lekkim syropie', 'B'),
    ('Królewska', 'Sardynka w sosie własnym z dodatkiem oleju', 'C'),
    ('Lisner', 'Śledź atlantycki w sosie grzybowym', 'D'),
    ('Jamar', 'Mieszanka warzywna meksykańska', 'B'),
    ('Krakus', 'Ogórki Korniszony', 'UNKNOWN'),
    ('Kuchnia Polska', 'Ogórki kiszone', 'C'),
    ('Magaw', 'Ogórki kiszone', 'C'),
    ('Dominik', 'Kapusta kiszona z marchewką', 'A'),
    ('Primavika', 'Gołąbki wegetariańskie z kaszą jaglaną', 'B'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', 'C'),
    ('Dobry wybór', 'Tuńczyk kawałki w zalewie z olejem roślinnym.', 'B'),
    ('Super Fish', 'Tuńczyk kawałki w oleju roślinnym', 'D'),
    ('Tradycyjny smak', 'Buraczki wiórki', 'B'),
    ('Pudliszki', 'Pomidory całe', 'A'),
    ('Victus', 'Ogórki Kiszone', 'B'),
    ('Kier', 'Szparagi białe', 'A'),
    ('Lisner', 'Śledź atlantycki filety a''la Matjas korzenne', 'E'),
    ('Nasza Spiżarnia', 'Pomidory Krojone', 'A'),
    ('Dega', 'Fish spread with rice', 'C'),
    ('Dawtona', 'Kukurydza gold', 'B'),
    ('Kwidzyn', 'Canned Corn', 'C'),
    ('Graal', 'Makrela w sosie pomidorowym', 'D'),
    ('Auchan', 'Tuńczyk w kawałkach w sosie własnym', 'A'),
    ('Nasza spiżarnia', 'Brzoskwinie w syropie', 'B'),
    ('Nasza Spiżarnia', 'Korniszony z chili', 'B'),
    ('Mega ryba', 'Filety z makreli w sosie pomidorowym.', 'B'),
    ('Unknown', 'Buraczki zasmażane z cebulą', 'C'),
    ('Łosoś ustka', 'Paprykarz szczeciński', 'C'),
    ('GustoBello', 'Carciofi', 'C'),
    ('Carrefour', 'Korniszony delitatesowe z przyprawami', 'C'),
    ('ZPH "Wojna"', 'Marchewka z groszkiem', 'A'),
    ('Graal', 'Filety z makreli w sosie pomidorowym z suszonymi pomidorami.', 'D'),
    ('Łosoś Ustka', 'Tinned Tomato Mackerel', 'D'),
    ('Greek Trade', 'Brzoskwinie w syropie', 'B'),
    ('EvraFish', 'Szprot w oleju roslinnym', 'UNKNOWN'),
    ('Provitus', 'Kapusta kwaszona duszona', 'C'),
    ('Biedronka', 'Maliny w lekkim syropie', 'C'),
    ('Farma-świętokrzyska', 'Bio kapusta z grochem', 'A'),
    ('Elios', 'Papryczki pikantne nadziewane serem', 'D'),
    ('Nautica', 'Makrélafilé bőrrel paradicsomos szószban', 'C'),
    ('Nasza Spiżarnia', 'Korniszony Delikatesowe', 'B')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Nasza Spiżarnia', 'Kukurydza słodka', '3'),
    ('Marinero', 'Tuńczyk jednolity w oliwie z oliwek', '3'),
    ('Marineo', 'Filety śledziowe w sosie pomidorowym', '4'),
    ('Marinero', 'Łosoś Kawałki w sosie pomidorowym', '4'),
    ('Graal', 'Tuńczyk kawałki w oleju roślinnym.', '3'),
    ('Mariners', 'Paprykarz szczeciński z łososiem', '4'),
    ('Marinero', 'Chili filety śledziowe', '3'),
    ('Nasza Spiżarnia', 'Ogórki konserwowe', '3'),
    ('Dawtona', 'Kukurydza słodka', '3'),
    ('Marinero', 'Płaty śledziowe smażone w zalewie octowej', '3'),
    ('Go Active', 'Proteinowa sałatka z łososiem pikantna', '4'),
    ('Graal', 'Sałatka z makrelą pikantna', '4'),
    ('Lisner', 'Śledź atlantycki opiekamy', '4'),
    ('Carrefour Classic', 'Pomidory całe', '3'),
    ('Krakus', 'Ćwikła z chrzanem', '3'),
    ('Auchan', 'Kukurydza super słodka', '3'),
    ('Nasza spiżarnia', 'Ogórki konserwowe', '3'),
    ('Nasza spiżarnia', 'Mieszanka owoców w lekkim syropie', '3'),
    ('Provitus', 'Ogórki konserwowe hot chili', '4'),
    ('Mega ryba', 'Śledź w sosie pomidorowym.', '4'),
    ('Łosoś Ustka', 'Śledź w sosie pomidorowym', '4'),
    ('Biedronka', 'Ogórki ćwiartki', '4'),
    ('Graal', 'Filety że śledzia w oleju', '3'),
    ('Auchan', 'Kiszone ogórki', '4'),
    ('King Oscar', 'Filety z makreli w sosie pomidorowym z papryką.', '4'),
    ('Helcom', 'Tuńczyk kawałki w sosie własnym.', '3'),
    ('EvraFish', 'Śledzie w sosie pomidorowym.', '4'),
    ('Graal', 'Tuńczyk kawałki w bulionie warzywnym.', '3'),
    ('Graal S.A.', 'Śledź w oleju po gdańsku', '3'),
    ('Nasza spiżarnia', 'Ogórki kiszone', '3'),
    ('Nasza Spiżarnia', 'Pomidory całe', '3'),
    ('Lisner', 'Tuńczyk w sosie własnym', '3'),
    ('Graal', 'Tuńczyk kawałki w sosie własnym.', '3'),
    ('Amerigo', 'Śledź w sosie pomidorowym', '4'),
    ('Nasza Spiżarnia', 'Mieszanka warzywna z kukuyrdzą', '3'),
    ('Dawtona', 'Pomidory skrojone z ziołami', '4'),
    ('Helcom', 'Mix owoców w lekkim syropie', '3'),
    ('Pudliszki', 'Fasolka po Bretońsku', '4'),
    ('Lisner', 'Tuńczyk kawałki w oleju roślinnym', '3'),
    ('Neptun', 'Tuńczyk W Wodzie', '3'),
    ('Pudliszki', 'Pomidore krojone bez skórki w sosie pomidorowym.', '1'),
    ('Asia Flavours', 'Jackfruit kawałki', '3'),
    ('Nasza Spiżarnia', 'Ćwikła z chrzanem', '3'),
    ('Graal', 'Śledź w sosie pomidorowym', '4'),
    ('Smak', 'Konserwowe ogóreczki klasyczne', '3'),
    ('MK', 'Szproty wędzone w sosie pomidorowym', '4'),
    ('Helcom Premium', 'Brzoskwinie połówki', '3'),
    ('Kuchnia STAROPOLSKA', 'Bigos z kiełbasą', '4'),
    ('Łosoś', 'Paprykarz szczeciński', '4'),
    ('Graal', 'Winter szprot podwędzany w oleju', '1'),
    ('Provitus', 'Ogórki konserwowe kozackie', '4'),
    ('Łowicz', 'Pomidory krojone bez skórki', '3'),
    ('Ole!', 'Cebulka marynowana złota', '4'),
    ('Łosoś Ustka', 'Śledź po gdańsku w oleju', '3'),
    ('Unknown', 'Brzoskwinie połówki w lekkim syropie', '4'),
    ('Królewska', 'Sardynka w sosie własnym z dodatkiem oleju', '3'),
    ('Lisner', 'Śledź atlantycki w sosie grzybowym', '4'),
    ('Jamar', 'Mieszanka warzywna meksykańska', '3'),
    ('Krakus', 'Ogórki Korniszony', '3'),
    ('Kuchnia Polska', 'Ogórki kiszone', '3'),
    ('Magaw', 'Ogórki kiszone', '3'),
    ('Dominik', 'Kapusta kiszona z marchewką', '3'),
    ('Primavika', 'Gołąbki wegetariańskie z kaszą jaglaną', '3'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', '4'),
    ('Dobry wybór', 'Tuńczyk kawałki w zalewie z olejem roślinnym.', '3'),
    ('Super Fish', 'Tuńczyk kawałki w oleju roślinnym', '3'),
    ('Tradycyjny smak', 'Buraczki wiórki', '3'),
    ('Pudliszki', 'Pomidory całe', '1'),
    ('Victus', 'Ogórki Kiszone', '3'),
    ('Kier', 'Szparagi białe', '3'),
    ('Lisner', 'Śledź atlantycki filety a''la Matjas korzenne', '4'),
    ('Nasza Spiżarnia', 'Pomidory Krojone', '3'),
    ('Dega', 'Fish spread with rice', '4'),
    ('Dawtona', 'Kukurydza gold', '4'),
    ('Kwidzyn', 'Canned Corn', '3'),
    ('Graal', 'Makrela w sosie pomidorowym', '4'),
    ('Auchan', 'Tuńczyk w kawałkach w sosie własnym', '4'),
    ('Nasza spiżarnia', 'Brzoskwinie w syropie', '3'),
    ('Nasza Spiżarnia', 'Korniszony z chili', '3'),
    ('Mega ryba', 'Filety z makreli w sosie pomidorowym.', '4'),
    ('Unknown', 'Buraczki zasmażane z cebulą', '4'),
    ('Łosoś ustka', 'Paprykarz szczeciński', '4'),
    ('GustoBello', 'Carciofi', '3'),
    ('Carrefour', 'Korniszony delitatesowe z przyprawami', '4'),
    ('ZPH "Wojna"', 'Marchewka z groszkiem', '3'),
    ('Graal', 'Filety z makreli w sosie pomidorowym z suszonymi pomidorami.', '4'),
    ('Łosoś Ustka', 'Tinned Tomato Mackerel', '4'),
    ('Greek Trade', 'Brzoskwinie w syropie', '3'),
    ('EvraFish', 'Szprot w oleju roslinnym', '3'),
    ('Provitus', 'Kapusta kwaszona duszona', '3'),
    ('Biedronka', 'Maliny w lekkim syropie', '3'),
    ('Farma-świętokrzyska', 'Bio kapusta z grochem', '3'),
    ('Elios', 'Papryczki pikantne nadziewane serem', '4'),
    ('Nautica', 'Makrélafilé bőrrel paradicsomos szószban', '4'),
    ('Nasza Spiżarnia', 'Korniszony Delikatesowe', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Canned Goods', 100, 'PL');
