-- PIPELINE (Soups): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Krakus', 'Zupa Żurek', 'C'),
    ('Auchan', 'Fasolka po bretońsku z kiełbasą i boczkiem.', 'C'),
    ('Łowicz', 'Kociołek węgierski', 'C'),
    ('Profi', 'Krupnik z mięsem wieprzowym', 'C'),
    ('Krakus', 'Barszcz biały koncentrat', 'E'),
    ('Profi', 'Zupa pomidorowa z mięsem wieprzowym', 'C'),
    ('Lewiatan', 'Fasolka po bretońsku', 'C'),
    ('Biedronka', 'Zupa kapuśniak z pomidorami', 'B'),
    ('Biedronka', 'Zupa kapuśniak', 'C'),
    ('Pudliszki', 'Fasolka po Bretońsku', 'C'),
    ('Pudliszki', 'Flaki wołowe w rosole', 'C'),
    ('Kuchnia Staropolska', 'Fasolka po bretońsku z kiełbasą', 'C'),
    ('Pudliszki', 'Flaki wołowe po zamojsku', 'C'),
    ('Unknown', 'Krem pomidorowo-paprykowy z ryżem', 'UNKNOWN'),
    ('Nasze Smaki', 'Żurek', 'A'),
    ('Pudliszki', 'Gulasz wieprzowo-wołowy', 'C'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', 'C'),
    ('Unknown', 'Flaczki królewskie wołowe', 'C'),
    ('Brzeziecki', 'Barszcz biały', 'C'),
    ('Brzeziecki', 'Żur Wiejski', 'C'),
    ('Rolnik', 'Żurek na zakwasie koncentrat', 'B'),
    ('Culineo', 'Flaki wołowe w rosole', 'C'),
    ('Pudliszki', 'Fasolka po bretońsku z kiełbasą', 'C'),
    ('M.E.A.L. Artea', 'Fasola po bretońsku', 'C'),
    ('Bobovita', 'Pomidorowa z kurczakiem i ryżem', 'NOT-APPLICABLE'),
    ('Unknown', 'Żurek Aliny', 'A'),
    ('Ten Smak', 'Żurek staropolski', 'A'),
    ('Łowicz', 'Kociołek Orientalny', 'C'),
    ('Stoczek', 'Mięso wołowe z makaronem i boczkiem wędzonym w sosie pomidorowym', 'C'),
    ('Kuchnia Staropolska', 'Krupnik z mięsem drobiowym', 'C'),
    ('Łowicz', 'Fasolka po bretońsku z boczkiem i kiełbasą', 'C'),
    ('Farma świętokrzyska', 'Kapuśniak świętokrzyski', 'B'),
    ('Delikatna', 'Fasolka po bretońsku z ziemniakami', 'A'),
    ('Pamapol', 'Fasolka po bretońsku z boczkiem', 'UNKNOWN'),
    ('Rolnik', 'Fasolka po bretońsku z kiełbasą', 'C'),
    ('Carrefour Classic', 'Fasolka po bretońsku', 'C'),
    ('Herby', 'Fasolka Po Bretońsku z Kiełbasą', 'C'),
    ('Szubryt', 'Fasolka po bretońsku', 'B'),
    ('Primavika', 'Fasola a''la po bretońsku', 'B'),
    ('EdRED', 'Grochówka generalska', 'C'),
    ('Nestlé', 'Barszcz czerwony', 'E'),
    ('Jemy Jemy', 'Zupa krem z pomidorow', 'C'),
    ('Biedronka', 'Zupa krem z dyni', 'C'),
    ('Biedronka', 'Zupa Fasolowa z Pomidorami i Szpinakiem', 'B'),
    ('Jemy Jemy', 'Zupa krem z zielonego groszku', 'C'),
    ('Biedronka', 'Zupa pomidorowa', 'UNKNOWN'),
    ('Biedronka', 'Zupa grochowa', 'C'),
    ('Biedronka', 'Zupa koperkowa', 'B'),
    ('Urbanek', 'Cucumber soup with dill', 'C'),
    ('Słoik konesera', 'Klopsy w sosie pomidorowym', 'C'),
    ('Auchan', 'Pulpety w sosie pomidorowym', 'C'),
    ('Yabra', 'Zupa gulaszowa', 'B'),
    ('Pan Pomidor Lidl', 'Zupa marokańska', 'C'),
    ('Yabra', 'Fasolka po bretońsku', 'C'),
    ('Pan Pomidor', 'Zupa indyjska z soczewicą i gram masala', 'C'),
    ('Pan Pomidor', 'Zupa szczawiowa z ziemniakami', 'C'),
    ('Biedronka', 'Zupa Minestrone', 'B'),
    ('Culineo', 'Bulion warzywny', 'E'),
    ('Chef select', 'Zupa krem z pomidorów z bazylią', 'C'),
    ('Jemy JEMY', 'ZUPA TAJSKA Zupy Swiata', 'UNKNOWN'),
    ('Krakus', 'Barszcz czerwony', 'C'),
    ('Vifon', 'Bo tieu', 'UNKNOWN'),
    ('M.E.A.L.', 'Gulasz wieprzowy', 'UNKNOWN'),
    ('Kotwica', 'Krupnik', 'D'),
    ('Biedronka', 'Zupa jarzynowa', 'B'),
    ('Łowicz', 'Flaki po zamojsku', 'C'),
    ('Biedronka', 'Zupa krem pomidorowy', 'C'),
    ('Go vege', 'Strogonow roslinny', 'A'),
    ('Sorella', 'Zupa krem z dyni i mango', 'C'),
    ('Eat me', 'Zupa krem z pieczonej papryki i mascarpone', 'C'),
    ('Hortex', 'Zupa pomidorowa z makaronem', 'C'),
    ('Kucharek', 'Bulion warzywny', 'UNKNOWN'),
    ('Pan pomidor', 'Pomidorowa', 'UNKNOWN'),
    ('Chef Select', 'Żurek z białą kiełbasą i boczkiem', 'C'),
    ('Nestlé', 'Rosół drobiowy królewski', 'UNKNOWN'),
    ('Knorr', 'Rosół z kury', 'C'),
    ('Podravka', 'Vegeta Natur Rosół Wołowy', 'UNKNOWN'),
    ('Samyang', 'Buldak HOT Chicken Flavour Ramen Cheese Flavour', 'E'),
    ('Italiamo', 'Paradizniki suseni lidl', 'UNKNOWN'),
    ('Amino', 'Hühnersuppe mit Petersillie', 'UNKNOWN'),
    ('Chef Select', 'Zupa Inspiracja Tajska', 'C'),
    ('Knorr', 'Borowikowa z grzankami', 'UNKNOWN'),
    ('Bonduelle', 'Haricots blancs', 'B'),
    ('Freshona', 'Zupa kalafiorowa z koperkiem', 'A'),
    ('Knorr', 'Grochowa z grzankami', 'UNKNOWN'),
    ('Lidl', 'Lentil Soup Indian Style', 'C'),
    ('Knorr', 'Borscht, Instant', 'E'),
    ('Nestlé', 'Bulion drobiowy', 'C'),
    ('Kania', 'Hühnerbrühe', 'C'),
    ('Knorr', 'Danie puree', 'UNKNOWN'),
    ('Chef Select Lidl', 'Zupa grochowa z boczkiem i tymiankiem', 'C'),
    ('Chef Select Lidl', 'Zupa Inspiracja Wietnamska', 'C'),
    ('Knorr', 'Kremowa zupa z kurek ze szczypiorkiem', 'UNKNOWN')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Krakus', 'Zupa Żurek', '4'),
    ('Auchan', 'Fasolka po bretońsku z kiełbasą i boczkiem.', '4'),
    ('Łowicz', 'Kociołek węgierski', '4'),
    ('Profi', 'Krupnik z mięsem wieprzowym', '4'),
    ('Krakus', 'Barszcz biały koncentrat', '4'),
    ('Profi', 'Zupa pomidorowa z mięsem wieprzowym', '4'),
    ('Lewiatan', 'Fasolka po bretońsku', '4'),
    ('Biedronka', 'Zupa kapuśniak z pomidorami', '3'),
    ('Biedronka', 'Zupa kapuśniak', '4'),
    ('Pudliszki', 'Fasolka po Bretońsku', '4'),
    ('Pudliszki', 'Flaki wołowe w rosole', '4'),
    ('Kuchnia Staropolska', 'Fasolka po bretońsku z kiełbasą', '4'),
    ('Pudliszki', 'Flaki wołowe po zamojsku', '4'),
    ('Unknown', 'Krem pomidorowo-paprykowy z ryżem', '3'),
    ('Nasze Smaki', 'Żurek', '3'),
    ('Pudliszki', 'Gulasz wieprzowo-wołowy', '4'),
    ('Stoczek', 'Fasolka po bretońsku z dodatkiem kiełbasy', '4'),
    ('Unknown', 'Flaczki królewskie wołowe', '4'),
    ('Brzeziecki', 'Barszcz biały', '3'),
    ('Brzeziecki', 'Żur Wiejski', '3'),
    ('Rolnik', 'Żurek na zakwasie koncentrat', '3'),
    ('Culineo', 'Flaki wołowe w rosole', '4'),
    ('Pudliszki', 'Fasolka po bretońsku z kiełbasą', '4'),
    ('M.E.A.L. Artea', 'Fasola po bretońsku', '4'),
    ('Bobovita', 'Pomidorowa z kurczakiem i ryżem', '3'),
    ('Unknown', 'Żurek Aliny', '3'),
    ('Ten Smak', 'Żurek staropolski', '3'),
    ('Łowicz', 'Kociołek Orientalny', '4'),
    ('Stoczek', 'Mięso wołowe z makaronem i boczkiem wędzonym w sosie pomidorowym', '4'),
    ('Kuchnia Staropolska', 'Krupnik z mięsem drobiowym', '4'),
    ('Łowicz', 'Fasolka po bretońsku z boczkiem i kiełbasą', '4'),
    ('Farma świętokrzyska', 'Kapuśniak świętokrzyski', '3'),
    ('Delikatna', 'Fasolka po bretońsku z ziemniakami', '3'),
    ('Pamapol', 'Fasolka po bretońsku z boczkiem', '4'),
    ('Rolnik', 'Fasolka po bretońsku z kiełbasą', '4'),
    ('Carrefour Classic', 'Fasolka po bretońsku', '4'),
    ('Herby', 'Fasolka Po Bretońsku z Kiełbasą', '4'),
    ('Szubryt', 'Fasolka po bretońsku', '4'),
    ('Primavika', 'Fasola a''la po bretońsku', '3'),
    ('EdRED', 'Grochówka generalska', '4'),
    ('Nestlé', 'Barszcz czerwony', '4'),
    ('Jemy Jemy', 'Zupa krem z pomidorow', '4'),
    ('Biedronka', 'Zupa krem z dyni', '4'),
    ('Biedronka', 'Zupa Fasolowa z Pomidorami i Szpinakiem', '3'),
    ('Jemy Jemy', 'Zupa krem z zielonego groszku', '3'),
    ('Biedronka', 'Zupa pomidorowa', '4'),
    ('Biedronka', 'Zupa grochowa', '3'),
    ('Biedronka', 'Zupa koperkowa', '4'),
    ('Urbanek', 'Cucumber soup with dill', '3'),
    ('Słoik konesera', 'Klopsy w sosie pomidorowym', '4'),
    ('Auchan', 'Pulpety w sosie pomidorowym', '4'),
    ('Yabra', 'Zupa gulaszowa', '4'),
    ('Pan Pomidor Lidl', 'Zupa marokańska', '4'),
    ('Yabra', 'Fasolka po bretońsku', '4'),
    ('Pan Pomidor', 'Zupa indyjska z soczewicą i gram masala', '4'),
    ('Pan Pomidor', 'Zupa szczawiowa z ziemniakami', '3'),
    ('Biedronka', 'Zupa Minestrone', '3'),
    ('Culineo', 'Bulion warzywny', '4'),
    ('Chef select', 'Zupa krem z pomidorów z bazylią', '4'),
    ('Jemy JEMY', 'ZUPA TAJSKA Zupy Swiata', '4'),
    ('Krakus', 'Barszcz czerwony', '4'),
    ('Vifon', 'Bo tieu', '4'),
    ('M.E.A.L.', 'Gulasz wieprzowy', '4'),
    ('Kotwica', 'Krupnik', '4'),
    ('Biedronka', 'Zupa jarzynowa', '4'),
    ('Łowicz', 'Flaki po zamojsku', '4'),
    ('Biedronka', 'Zupa krem pomidorowy', '3'),
    ('Go vege', 'Strogonow roslinny', '3'),
    ('Sorella', 'Zupa krem z dyni i mango', '3'),
    ('Eat me', 'Zupa krem z pieczonej papryki i mascarpone', '4'),
    ('Hortex', 'Zupa pomidorowa z makaronem', '4'),
    ('Kucharek', 'Bulion warzywny', '4'),
    ('Pan pomidor', 'Pomidorowa', '4'),
    ('Chef Select', 'Żurek z białą kiełbasą i boczkiem', '4'),
    ('Nestlé', 'Rosół drobiowy królewski', '4'),
    ('Knorr', 'Rosół z kury', '4'),
    ('Podravka', 'Vegeta Natur Rosół Wołowy', '4'),
    ('Samyang', 'Buldak HOT Chicken Flavour Ramen Cheese Flavour', '4'),
    ('Italiamo', 'Paradizniki suseni lidl', '3'),
    ('Amino', 'Hühnersuppe mit Petersillie', '4'),
    ('Chef Select', 'Zupa Inspiracja Tajska', '4'),
    ('Knorr', 'Borowikowa z grzankami', '4'),
    ('Bonduelle', 'Haricots blancs', '4'),
    ('Freshona', 'Zupa kalafiorowa z koperkiem', '3'),
    ('Knorr', 'Grochowa z grzankami', '4'),
    ('Lidl', 'Lentil Soup Indian Style', '4'),
    ('Knorr', 'Borscht, Instant', '4'),
    ('Nestlé', 'Bulion drobiowy', '4'),
    ('Kania', 'Hühnerbrühe', '4'),
    ('Knorr', 'Danie puree', '4'),
    ('Chef Select Lidl', 'Zupa grochowa z boczkiem i tymiankiem', '4'),
    ('Chef Select Lidl', 'Zupa Inspiracja Wietnamska', '4'),
    ('Knorr', 'Kremowa zupa z kurek ze szczypiorkiem', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Soups', 100, 'PL');
