-- PIPELINE (Spices & Seasonings): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Farmer''s Snack', 'Südsee-Ingwer', 'NOT-APPLICABLE'),
    ('Kania', 'Würzlinge Kräuter Italienische Art', 'NOT-APPLICABLE'),
    ('Nestlé', 'Würzmischung Nr. 1, Gebratenes Fleisch', 'NOT-APPLICABLE'),
    ('Ostmann', 'Kreuzkümmel (Cumin)', 'NOT-APPLICABLE'),
    ('Hügli Nahrungsmittel GmbH', 'Gewürzmischung Ofen-Gemüse (Bio)', 'NOT-APPLICABLE'),
    ('Ostmann', 'Paprika edelsüß', 'NOT-APPLICABLE'),
    ('Fuchs-Gruppe', 'Lebkuchengewürz', 'NOT-APPLICABLE'),
    ('Kania', 'Spice your Slice- würzmischung', 'NOT-APPLICABLE'),
    ('Dittmann', 'Pfeffer, Eingelegter Grüner Pfeffer', 'NOT-APPLICABLE'),
    ('Le Gusto', 'Pfeffermühle mit Keramikmahlwerk - Pariser Pfeffer', 'NOT-APPLICABLE'),
    ('Le Gusto', 'Pfeffermühle mit Keramikmahlwerk - Steakpfeffer', 'NOT-APPLICABLE'),
    ('Feinkost Dittmann', 'Grüne Jalapeño Pfefferonen', 'NOT-APPLICABLE'),
    ('Gewürze', 'Gewürzmischung 4', 'NOT-APPLICABLE'),
    ('Block House', 'Zauber Gewürz', 'NOT-APPLICABLE'),
    ('Kania', 'Pommes Würzsalz', 'NOT-APPLICABLE'),
    ('Lebensbaum', 'Gewürzmischung Thai-Curry', 'NOT-APPLICABLE'),
    ('Ostmann', 'Steak Gewürzsalz', 'NOT-APPLICABLE'),
    ('Ostmann', 'China Gewürz', 'NOT-APPLICABLE'),
    ('Grillmeister', 'Gewürzmischung BBQ Steakpfeffer', 'NOT-APPLICABLE'),
    ('Kluth', 'Ingwerstücke', 'NOT-APPLICABLE'),
    ('Fuego', 'EDEKA GEWÜRZE Fuchs-Gruppe Fuego Fajita Seasoning Mix Verbesserte Rezeptur Vegan ohne Geschmacksverstärker und ohne PalmölB. 1.79€ 0.03 kg Beutel. 59.67€ 1kg', 'NOT-APPLICABLE'),
    ('Ostmann', 'Zimt gemahlen', 'NOT-APPLICABLE'),
    ('Ostmann', 'Oregano', 'NOT-APPLICABLE'),
    ('Aldi', 'Vanilleextrakt-Zubereitung Bio-Bourbon', 'NOT-APPLICABLE'),
    ('Le Gusto', 'Curry Pulver', 'NOT-APPLICABLE'),
    ('Bionade', 'Ingwer-Orange', 'NOT-APPLICABLE'),
    ('Dr. Oetker', 'Zitronenschale', 'NOT-APPLICABLE'),
    ('Kühne', 'Jalapeños', 'NOT-APPLICABLE'),
    ('Just Spices', 'Hähnchen Allrounder', 'NOT-APPLICABLE'),
    ('Kania', 'Bio Curry', 'NOT-APPLICABLE'),
    ('Rio d''oro', 'Bio ingwer', 'NOT-APPLICABLE'),
    ('DmBio', 'Ingwersaft', 'NOT-APPLICABLE'),
    ('Gut&günstig', 'Grüne Peperoni', 'NOT-APPLICABLE'),
    ('BioWagner', 'Zimt gemahlen', 'NOT-APPLICABLE'),
    ('Block House', 'Steak Pfeffer', 'NOT-APPLICABLE'),
    ('Ostmann', 'Paprika Rosenscharf', 'NOT-APPLICABLE'),
    ('Feinkost Dittmann', 'Pfefferonen', 'NOT-APPLICABLE'),
    ('Just Spices', 'Gemüse Allrounder', 'NOT-APPLICABLE'),
    ('Aldi', 'Hi! Spice - Stullengenie', 'NOT-APPLICABLE'),
    ('Fuego', 'Fuego Taco Seasoning Mix', 'NOT-APPLICABLE'),
    ('Unknown', 'Vanille Extract', 'NOT-APPLICABLE'),
    ('Belbake', 'Bourbon-Vanillepaste', 'NOT-APPLICABLE'),
    ('Kania', 'Mélanges épices sandwich', 'NOT-APPLICABLE'),
    ('Kclassic', 'Sushi Ingwer', 'NOT-APPLICABLE'),
    ('Kühne', 'Peperoni mild', 'NOT-APPLICABLE'),
    ('Ankerkraut', 'Rührei Mix Gewürz', 'NOT-APPLICABLE'),
    ('Ruf', 'Gourmet Vanille-Extrakt', 'NOT-APPLICABLE'),
    ('1001 delights', 'Gewürz, Ras el Hanout', 'NOT-APPLICABLE'),
    ('Pickerd', 'Zimt Paste', 'NOT-APPLICABLE'),
    ('Kania', 'Knoblauch granuliert', 'NOT-APPLICABLE'),
    ('Aldi', 'Bio-Kurkumapulver', 'NOT-APPLICABLE'),
    ('Kania', 'Fix fur salatsauce', 'NOT-APPLICABLE'),
    ('Rewe Beste Wahl', 'Paprika geräuchert', 'NOT-APPLICABLE'),
    ('DmBio', 'Bourbon Vanille', 'NOT-APPLICABLE'),
    ('Just spices', 'Bratkartoffel Gewürz', 'NOT-APPLICABLE'),
    ('Sonnentor', 'Das Beste für Reste', 'NOT-APPLICABLE'),
    ('Kania', 'Kreuzkümmel', 'NOT-APPLICABLE'),
    ('Just Spices', 'Kräuter Quark Gewürz', 'NOT-APPLICABLE'),
    ('Maggi', 'Fix Jäger-Sahne Schnitzel', 'NOT-APPLICABLE'),
    ('Gefro', 'Gewürz-Pfeffer', 'NOT-APPLICABLE'),
    ('Sonnentor', 'Sonnentor Gewürzblüten', 'NOT-APPLICABLE'),
    ('Lee Kum Kee', 'Premium-Pilz-Würzpulver', 'NOT-APPLICABLE'),
    ('Rewe', 'Jalapenos', 'NOT-APPLICABLE'),
    ('Kania', 'Persillade provençale', 'NOT-APPLICABLE'),
    ('Edeka', 'Pfefferonen griechisch', 'NOT-APPLICABLE'),
    ('Taylor & Colledge', 'Bourbon Bio-Vanille extrakt', 'NOT-APPLICABLE'),
    ('Backfee', 'Vanillepaste', 'NOT-APPLICABLE'),
    ('Vitasia', 'Ingwer eingelegt', 'NOT-APPLICABLE'),
    ('Gut & Günstig', 'Pfeffer schwarz', 'NOT-APPLICABLE'),
    ('Kania', 'Oignons', 'NOT-APPLICABLE'),
    ('Unknown', 'Bolognese Gewürz', 'NOT-APPLICABLE'),
    ('Rewe Bio', 'Zitronenschale gerieben', 'NOT-APPLICABLE'),
    ('1001 delights', 'Gewürz, Couscous', 'NOT-APPLICABLE'),
    ('Beltane Naturkost GmbH', 'Biofix Gebratene Nudeln (Bami Goreng)', 'NOT-APPLICABLE'),
    ('Just Spices', 'Stullen Spice', 'NOT-APPLICABLE'),
    ('Vitasia Lidl', 'Sushi Ingwer', 'NOT-APPLICABLE'),
    ('Just Spices', 'Avocado Toppimg', 'NOT-APPLICABLE'),
    ('Lebepur', 'Kurkuma Shot', 'NOT-APPLICABLE'),
    ('The Coca-Cola Company', 'Cola Vanille', 'NOT-APPLICABLE'),
    ('Alnatura', 'Gelbe Linse Kurkuma Aufstrich', 'NOT-APPLICABLE'),
    ('Just Spices', 'Italian allrounder', 'NOT-APPLICABLE'),
    ('Suntat', 'Jalapeno Scharf', 'NOT-APPLICABLE'),
    ('Gefro', 'Bella italia', 'NOT-APPLICABLE'),
    ('Ducros', 'Curry Madras', 'NOT-APPLICABLE'),
    ('Gefro', 'Mexiko Chili', 'NOT-APPLICABLE'),
    ('Bissfest', 'Pasta Konfetti', 'NOT-APPLICABLE'),
    ('Beltane', 'Biofix Spaghetti Bolognese', 'NOT-APPLICABLE'),
    ('Batts', 'Chilimauste', 'NOT-APPLICABLE'),
    ('Knorr', 'Broccoli Gratin', 'NOT-APPLICABLE'),
    ('Gefro', 'Gefro Curry Indisch Bio', 'NOT-APPLICABLE'),
    ('Just Spices', 'Kartoffel Allrounder', 'NOT-APPLICABLE'),
    ('Vegeta', 'Vegeta', 'NOT-APPLICABLE'),
    ('Gefro', 'Gefro Bella Italia', 'NOT-APPLICABLE'),
    ('Beltane', 'Biofix', 'NOT-APPLICABLE'),
    ('Santa maria', 'Fajita', 'NOT-APPLICABLE'),
    ('Suntat', 'Scharfe Chiliflocken', 'NOT-APPLICABLE'),
    ('Ankerkraut', 'Chili con Carne Mild Ankerkraut', 'NOT-APPLICABLE'),
    ('Podravka', 'Vegeta', 'NOT-APPLICABLE')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Farmer''s Snack', 'Südsee-Ingwer', '3'),
    ('Kania', 'Würzlinge Kräuter Italienische Art', '4'),
    ('Nestlé', 'Würzmischung Nr. 1, Gebratenes Fleisch', '4'),
    ('Ostmann', 'Kreuzkümmel (Cumin)', '1'),
    ('Hügli Nahrungsmittel GmbH', 'Gewürzmischung Ofen-Gemüse (Bio)', '3'),
    ('Ostmann', 'Paprika edelsüß', '1'),
    ('Fuchs-Gruppe', 'Lebkuchengewürz', '1'),
    ('Kania', 'Spice your Slice- würzmischung', '4'),
    ('Dittmann', 'Pfeffer, Eingelegter Grüner Pfeffer', '4'),
    ('Le Gusto', 'Pfeffermühle mit Keramikmahlwerk - Pariser Pfeffer', '3'),
    ('Le Gusto', 'Pfeffermühle mit Keramikmahlwerk - Steakpfeffer', '3'),
    ('Feinkost Dittmann', 'Grüne Jalapeño Pfefferonen', '4'),
    ('Gewürze', 'Gewürzmischung 4', '4'),
    ('Block House', 'Zauber Gewürz', '4'),
    ('Kania', 'Pommes Würzsalz', '4'),
    ('Lebensbaum', 'Gewürzmischung Thai-Curry', '4'),
    ('Ostmann', 'Steak Gewürzsalz', '2'),
    ('Ostmann', 'China Gewürz', '4'),
    ('Grillmeister', 'Gewürzmischung BBQ Steakpfeffer', '4'),
    ('Kluth', 'Ingwerstücke', '3'),
    ('Fuego', 'EDEKA GEWÜRZE Fuchs-Gruppe Fuego Fajita Seasoning Mix Verbesserte Rezeptur Vegan ohne Geschmacksverstärker und ohne PalmölB. 1.79€ 0.03 kg Beutel. 59.67€ 1kg', '3'),
    ('Ostmann', 'Zimt gemahlen', '1'),
    ('Ostmann', 'Oregano', '1'),
    ('Aldi', 'Vanilleextrakt-Zubereitung Bio-Bourbon', '4'),
    ('Le Gusto', 'Curry Pulver', '4'),
    ('Bionade', 'Ingwer-Orange', '4'),
    ('Dr. Oetker', 'Zitronenschale', '4'),
    ('Kühne', 'Jalapeños', '3'),
    ('Just Spices', 'Hähnchen Allrounder', '3'),
    ('Kania', 'Bio Curry', '4'),
    ('Rio d''oro', 'Bio ingwer', '1'),
    ('DmBio', 'Ingwersaft', '4'),
    ('Gut&günstig', 'Grüne Peperoni', '3'),
    ('BioWagner', 'Zimt gemahlen', '1'),
    ('Block House', 'Steak Pfeffer', '4'),
    ('Ostmann', 'Paprika Rosenscharf', '4'),
    ('Feinkost Dittmann', 'Pfefferonen', '4'),
    ('Just Spices', 'Gemüse Allrounder', '3'),
    ('Aldi', 'Hi! Spice - Stullengenie', '3'),
    ('Fuego', 'Fuego Taco Seasoning Mix', '3'),
    ('Unknown', 'Vanille Extract', '4'),
    ('Belbake', 'Bourbon-Vanillepaste', '4'),
    ('Kania', 'Mélanges épices sandwich', '4'),
    ('Kclassic', 'Sushi Ingwer', '4'),
    ('Kühne', 'Peperoni mild', '3'),
    ('Ankerkraut', 'Rührei Mix Gewürz', '3'),
    ('Ruf', 'Gourmet Vanille-Extrakt', '4'),
    ('1001 delights', 'Gewürz, Ras el Hanout', '3'),
    ('Pickerd', 'Zimt Paste', '4'),
    ('Kania', 'Knoblauch granuliert', '4'),
    ('Aldi', 'Bio-Kurkumapulver', '1'),
    ('Kania', 'Fix fur salatsauce', '4'),
    ('Rewe Beste Wahl', 'Paprika geräuchert', '1'),
    ('DmBio', 'Bourbon Vanille', '1'),
    ('Just spices', 'Bratkartoffel Gewürz', '3'),
    ('Sonnentor', 'Das Beste für Reste', '3'),
    ('Kania', 'Kreuzkümmel', '4'),
    ('Just Spices', 'Kräuter Quark Gewürz', '3'),
    ('Maggi', 'Fix Jäger-Sahne Schnitzel', '4'),
    ('Gefro', 'Gewürz-Pfeffer', '3'),
    ('Sonnentor', 'Sonnentor Gewürzblüten', '3'),
    ('Lee Kum Kee', 'Premium-Pilz-Würzpulver', '4'),
    ('Rewe', 'Jalapenos', '3'),
    ('Kania', 'Persillade provençale', '1'),
    ('Edeka', 'Pfefferonen griechisch', '4'),
    ('Taylor & Colledge', 'Bourbon Bio-Vanille extrakt', '3'),
    ('Backfee', 'Vanillepaste', '4'),
    ('Vitasia', 'Ingwer eingelegt', '3'),
    ('Gut & Günstig', 'Pfeffer schwarz', '4'),
    ('Kania', 'Oignons', '1'),
    ('Unknown', 'Bolognese Gewürz', '4'),
    ('Rewe Bio', 'Zitronenschale gerieben', '1'),
    ('1001 delights', 'Gewürz, Couscous', '4'),
    ('Beltane Naturkost GmbH', 'Biofix Gebratene Nudeln (Bami Goreng)', '4'),
    ('Just Spices', 'Stullen Spice', '3'),
    ('Vitasia Lidl', 'Sushi Ingwer', '4'),
    ('Just Spices', 'Avocado Toppimg', '3'),
    ('Lebepur', 'Kurkuma Shot', '4'),
    ('The Coca-Cola Company', 'Cola Vanille', '4'),
    ('Alnatura', 'Gelbe Linse Kurkuma Aufstrich', '3'),
    ('Just Spices', 'Italian allrounder', '3'),
    ('Suntat', 'Jalapeno Scharf', '4'),
    ('Gefro', 'Bella italia', '3'),
    ('Ducros', 'Curry Madras', '3'),
    ('Gefro', 'Mexiko Chili', '4'),
    ('Bissfest', 'Pasta Konfetti', '3'),
    ('Beltane', 'Biofix Spaghetti Bolognese', '4'),
    ('Batts', 'Chilimauste', '4'),
    ('Knorr', 'Broccoli Gratin', '4'),
    ('Gefro', 'Gefro Curry Indisch Bio', '4'),
    ('Just Spices', 'Kartoffel Allrounder', '3'),
    ('Vegeta', 'Vegeta', '4'),
    ('Gefro', 'Gefro Bella Italia', '4'),
    ('Beltane', 'Biofix', '4'),
    ('Santa maria', 'Fajita', '4'),
    ('Suntat', 'Scharfe Chiliflocken', '3'),
    ('Ankerkraut', 'Chili con Carne Mild Ankerkraut', '3'),
    ('Podravka', 'Vegeta', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Spices & Seasonings', 100, 'DE');
