-- PIPELINE (Nuts, Seeds & Legumes): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-13

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Ültje', 'Ültje Erdnüsse geröstet & ungesalzen 180g 2,49€ 13,83€ 1kg', 'Aldi'),
    ('Ültje', 'Ültje Erdnüsse geröstet & ungesalzen 180g 2,49€ 13,83€ 1kg', 'Edeka'),
    ('Ültje', 'Erdnüsse', 'Norma'),
    ('Ültje', 'EXTRA ROAST Erdnüsse gesalzen', 'Edeka'),
    ('Farmer', 'Cashewkerne - geröstet & gesalzen', 'Aldi'),
    ('Maryland', 'Snack Nüsse pur', 'REWE'),
    ('Maryland', 'Snack Nüsse pur', 'Penny'),
    ('Maryland', 'Snack Nüsse pur', 'Netto'),
    ('K-Classic', 'Erdnüsse geröstet & gesalzen', 'Kaufland'),
    ('Ültje', 'Ofen Erdnüsse gesalzen', 'Kaufland'),
    ('Alesto', 'Erdnusskerne geröstet', 'Lidl'),
    ('Aldi', 'Pistazien - geröstet & gesalzen', 'Aldi'),
    ('Maryland', 'Nuss-Kern-Mischung geröstet & gesalzen', 'Penny'),
    ('Maryland', 'Nuss-Kern-Mischung geröstet & gesalzen', 'Netto'),
    ('Alesto', 'XXL Erdnüsse', 'Lidl'),
    ('Farmer', 'Macadamia geröstet & gesalzen', 'Aldi'),
    ('Aldi', 'Erdnüsse in der Schale, geröstet', 'Aldi'),
    ('Seeberger', 'Cashew Kerne Nüsse', 'dm'),
    ('August Töpfer', 'Nuss-Mix, geröstet & gesalzen', 'Aldi'),
    ('Maryland', 'Studentenfutter Berry mit Cranberries & Walnüssen', 'Edeka'),
    ('Maryland', 'Studentenfutter Berry mit Cranberries & Walnüssen', 'Penny'),
    ('Farmer', 'Cashewkerne - pikant gewürzt', 'Aldi'),
    ('XOX', 'Erdnüsse geröstet ohne Salz', 'Netto'),
    ('Farmer', 'Pistazien - geröstet & ungesalzen', 'Aldi'),
    ('K-Classic', 'Erdnüsse geröstet', 'Kaufland'),
    ('Maryland', 'Snack Nüsse Honig & Salz', 'Edeka'),
    ('Maryland', 'Snack Nüsse Honig & Salz', 'Netto'),
    ('Maryland', 'Snack Nüsse Provence', 'Netto'),
    ('Maryland', 'Snack Nüsse Ungarisch Style', 'Netto'),
    ('Trader Joe''s', 'Salat-Plus - Mischung aus Sonnenblumen-, Kürbis- & Pinienkerne', 'Aldi'),
    ('Trader Joe''s', 'Jumbo Erdnüsse in der Schale, geröstet', 'Aldi'),
    ('Aldi', 'Wasabi-Erdnüsse', 'Aldi'),
    ('Ültje', 'Erdnüsse - geröstet & gezalzen XXL Party Edition', 'REWE'),
    ('Traders Joe''s', 'Cashews, geröstet & gesalzen', 'Aldi'),
    ('Maryland', 'Snack Nüsse Salz & Pfeffer', 'Netto'),
    ('Trader Joe''s', 'Kalifornische Pistazien, geröstet & gesalzen', 'Aldi'),
    ('Trader Joe''s', 'Haselnusskerne geröstet, ungesalzen', 'Aldi'),
    ('Trader Joe''s', 'Erdnüsse mit Knusperhülle', 'Aldi'),
    ('Trader Joe''s', 'Cashews, geröstet & pikant gewürzt', 'Aldi'),
    ('K-Classic', 'Cashewkerne geröstet u. gesalzen', 'Kaufland'),
    ('Alesto', 'Californische Pistazienkerne geröstet & gesalzen', 'Lidl'),
    ('Aldi', 'Erdnüsse im Teigmantel - Paprika', 'Aldi'),
    ('Farmer''s Snack', 'Geröstete Mandel, ungesalzen', 'REWE'),
    ('Farmer''s Snack', 'Geröstete Mandel, ungesalzen', 'Netto'),
    ('Max', 'Jumbo Erdnüsse geröstet & gesalzen', 'Edeka'),
    ('Maryland', 'Snack Nüsse BBQ', 'Netto'),
    ('Alesto', 'Cashewkerne geröstet & ungesalzen', 'Lidl'),
    ('Kaufland Classic', 'Erdnüsse', 'Kaufland'),
    ('K-Bio', 'Erdnusskerne geröstet & gesalzen', 'Kaufland'),
    ('Maryland', 'Snack Nüsse Oriental Style', 'Netto'),
    ('Trader Joe''s', 'Pistazienkerne geröstet, ungesalzen', 'Aldi'),
    ('Lorenz', 'NicNacs', 'Edeka'),
    ('Lorenz', 'NicNacs', 'REWE'),
    ('Farmer Naturals', 'Walnusskerne naturbelassen', 'Aldi'),
    ('Seeberger', 'Nusskernmischung', 'Kaufland'),
    ('Fazer naturals', 'Feinste Nuss-Variation, naturbelassen', 'Aldi'),
    ('Alesto', 'Mix Proteína Frutos Secos Y Soja', 'Lidl'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen', 'Aldi'),
    ('Farmer naturals', 'Premium-Nussmix - Fein mit Pekannusskernen', 'Aldi'),
    ('Alesto Selection', 'Pecan Nuts natural', 'Lidl'),
    ('Trader Joe''s', 'Walnusskerne naturbelassen', 'Aldi'),
    ('Farmer Naturals', 'Simply Roasted - Cashewkerne', 'Aldi'),
    ('Trader Joe''s', 'Cashewkerne, naturbelassen', 'Aldi'),
    ('Farmer', 'Trail-Mix Kerne', 'Aldi'),
    ('DmBio', 'Mandeln ganze Kerne', 'dm'),
    ('Farmer Naturals', 'Simply Roasted - Nussmischung', 'Aldi'),
    ('Trader joes', 'Pistachio mix', 'Aldi'),
    ('Seeberger', 'Seeberger Walnusskerne 4008258130018 Walnusskerne', 'Edeka'),
    ('Alesto', 'Cashew Nuts XXL', 'Lidl'),
    ('Alesto', 'Mandeln Honig & Salz', 'Lidl'),
    ('Alesto', 'Noisettes grillées', 'Lidl'),
    ('Farmer', 'Nuss-Frucht-Mix 5er-Pack - Cranberry', 'Aldi'),
    ('K-Classic', 'Nuts royal', 'Kaufland'),
    ('Dm', 'Pistazien Creme', 'dm'),
    ('Maryland', 'Studentenfutter', 'REWE'),
    ('Farmer naturals', 'Premium-Nussmix - Extra mit Mandeln, Cashew-, Para-, Pekan-, Macadamia-Nusskernen', 'Aldi'),
    ('Trader Joe''s', 'Studentenfutter', 'Aldi'),
    ('Trader Joe''s', 'Knusperkracher', 'Aldi'),
    ('DmBio', 'Pistaziencreme', 'dm'),
    ('DmBio', 'Mandelmehl', 'dm'),
    ('Alesto', 'Cashews roasted & salted', 'Lidl'),
    ('Farmer''s Snack', 'Studentenfutter ohne Rosinen mit saftigen Cranberries', 'REWE'),
    ('Farmer''s Snack', 'Studentenfutter ohne Rosinen mit saftigen Cranberries', 'Netto'),
    ('Farmer naturals', 'Paranusskerne naturbelassen', 'Aldi'),
    ('Farmer Naturals', 'Simply Roasted - Mandeln', 'Aldi'),
    ('Farmer naturals', 'Pinienkerne', 'Aldi'),
    ('Farmer Naturals', 'Energieschub', 'Aldi'),
    ('Trader Joe''s', 'Mandelkerne naturbelassen', 'Aldi'),
    ('DmBio', 'Paranuss Kerne', 'dm'),
    ('Afrika', 'Bio Cashewkerne naturbelassen aus Westafrika', 'Aldi'),
    ('Trader Joe''s', 'Premiumnuss-Mix mit Mandel-, Cashew-, Pekan-, Macadamia- & Paranusskernen, ungesalzen', 'Aldi'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', 'Aldi'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', 'Edeka'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', 'REWE'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', 'Netto'),
    ('Ültje', 'Rauchmandeln', 'Edeka'),
    ('Ültje', 'Rauchmandeln', 'REWE'),
    ('Seeberger', 'Macadamia Nusskerne', 'Edeka'),
    ('Farmer''s Snack', 'Pinienkerne', 'REWE'),
    ('Trader Joe''s', 'Cashewkerne naturbelassen', 'Aldi'),
    ('Aldi', 'Mandeln blanchiert, gemahlen', 'Aldi'),
    ('Alesto', 'Pistazienkerne', 'Lidl'),
    ('Farmer', 'Trail mix Beeren', 'Aldi'),
    ('K-Bio', 'Cashew Cranberry mix', 'Kaufland'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen XXL', 'Aldi'),
    ('Gut bio', 'Kerne-Mix', 'Aldi'),
    ('Farmer''s Snack', 'Cashewkerne', 'REWE'),
    ('Trader Joe''s', 'Kalifornische Pistazien, ungesalzen', 'Aldi'),
    ('Gut Bio', 'Walnusskerne', 'Aldi'),
    ('Trader Joe''s', 'Paranusskerne', 'Aldi'),
    ('Alesto', 'Walnuts', 'Lidl'),
    ('Farmer naturals', 'Kernige Vielfalt', 'Aldi'),
    ('Alesto', 'Erdnüsse geröstet und gesalzen', 'Lidl'),
    ('Alesto', 'Cashewkerne geröstet & gesalzen', 'Lidl'),
    ('REWE Beste Wahl', 'Erdnüsse große Kerne geröstet ungesalzen', 'REWE'),
    ('Alesto', 'Erdnüsse, pikant gewürzt', 'Lidl'),
    ('Gut & Günstig', 'Erdnüsse geröstet & gesalzen', 'Edeka'),
    ('Edeka', 'Pistazien, geröstet & gesalzen', 'Edeka'),
    ('Alesto', 'Erdnüsse – geröstet & gesalzen', 'Lidl'),
    ('Clarkys', 'Erdnüsse im Teigmantel Paprika', 'Netto'),
    ('Ja!', 'Erdnüsse pikant gewürzt', 'REWE')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Nuts, Seeds & Legumes' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
