-- PIPELINE (Nuts, Seeds & Legumes): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Ültje', 'Erdnüsse geröstet & gesalzen', 'C'),
    ('Ültje', 'Ültje Erdnüsse geröstet & ungesalzen 180g 2,49€ 13,83€ 1kg', 'A'),
    ('Ültje', 'Erdnüsse', 'C'),
    ('Ültje', 'EXTRA ROAST Erdnüsse gesalzen', 'C'),
    ('Farmer', 'Cashewkerne - geröstet & gesalzen', 'C'),
    ('Maryland', 'Snack Nüsse pur', 'A'),
    ('K-Classic', 'Erdnüsse geröstet & gesalzen', 'C'),
    ('Ültje', 'Ofen Erdnüsse gesalzen', 'C'),
    ('Alesto', 'Erdnusskerne geröstet', 'A'),
    ('Aldi', 'Pistazien - geröstet & gesalzen', 'C'),
    ('Maryland', 'Nuss-Kern-Mischung geröstet & gesalzen', 'C'),
    ('Alesto', 'XXL Erdnüsse', 'C'),
    ('Farmer', 'Macadamia geröstet & gesalzen', 'D'),
    ('Aldi', 'Erdnüsse in der Schale, geröstet', 'UNKNOWN'),
    ('Seeberger', 'Cashew Kerne Nüsse', 'B'),
    ('August Töpfer', 'Nuss-Mix, geröstet & gesalzen', 'D'),
    ('Maryland', 'Studentenfutter Berry mit Cranberries & Walnüssen', 'D'),
    ('Farmer', 'Cashewkerne - pikant gewürzt', 'D'),
    ('XOX', 'Erdnüsse geröstet ohne Salz', 'B'),
    ('Farmer', 'Pistazien - geröstet & ungesalzen', 'A'),
    ('K-Classic', 'Erdnüsse geröstet', 'A'),
    ('Maryland', 'Snack Nüsse Honig & Salz', 'C'),
    ('Maryland', 'Snack Nüsse Provence', 'C'),
    ('Maryland', 'Snack Nüsse Ungarisch Style', 'B'),
    ('Trader Joe''s', 'Salat-Plus - Mischung aus Sonnenblumen-, Kürbis- & Pinienkerne', 'A'),
    ('Trader Joe''s', 'Jumbo Erdnüsse in der Schale, geröstet', 'B'),
    ('Aldi', 'Wasabi-Erdnüsse', 'D'),
    ('Ültje', 'Erdnüsse - geröstet & gezalzen XXL Party Edition', 'C'),
    ('Traders Joe''s', 'Cashews, geröstet & gesalzen', 'C'),
    ('Maryland', 'Snack Nüsse Salz & Pfeffer', 'C'),
    ('Trader Joe''s', 'Kalifornische Pistazien, geröstet & gesalzen', 'D'),
    ('Trader Joe''s', 'Haselnusskerne geröstet, ungesalzen', 'A'),
    ('Trader Joe''s', 'Erdnüsse mit Knusperhülle', 'E'),
    ('Trader Joe''s', 'Cashews, geröstet & pikant gewürzt', 'D'),
    ('K-Classic', 'Cashewkerne geröstet u. gesalzen', 'C'),
    ('Alesto', 'Californische Pistazienkerne geröstet & gesalzen', 'C'),
    ('Aldi', 'Erdnüsse im Teigmantel - Paprika', 'D'),
    ('Farmer''s Snack', 'Geröstete Mandel, ungesalzen', 'A'),
    ('Max', 'Jumbo Erdnüsse geröstet & gesalzen', 'C'),
    ('Maryland', 'Snack Nüsse BBQ', 'D'),
    ('Alesto', 'Cashewkerne geröstet & ungesalzen', 'B'),
    ('Kaufland Classic', 'Erdnüsse', 'A'),
    ('K-Bio', 'Erdnusskerne geröstet & gesalzen', 'C'),
    ('Maryland', 'Snack Nüsse Oriental Style', 'D'),
    ('Trader Joe''s', 'Pistazienkerne geröstet, ungesalzen', 'A'),
    ('Ültje', 'Erdnüsse pikant gewürzt', 'C'),
    ('Farmer', 'Erdnusskerne - geröstet und gesalzen', 'C'),
    ('Trader Joe''s', 'Erdnüsse geröstet und gesalzen', 'C'),
    ('Ültje', 'Kessel Nüsse Paprika', 'C'),
    ('Farmer', 'Erdnüsse', 'C'),
    ('Ültje', 'Erdnüsse, geröstet & gesalzen', 'C'),
    ('K Classic', 'Erdnüsse pikant', 'C'),
    ('Alesto', 'Spanische Mandeln blanchiert und geröstet', 'A'),
    ('Ültje', 'Erdnüsse ungesalzen', 'B'),
    ('Ültje', 'Mandeln & Erdnüsse Honig und Salz', 'D'),
    ('Kluth', 'Nuss-Mix geröstet und gesalzen', 'C'),
    ('Farmer', 'Geröstete Snackmandeln', 'D'),
    ('Kluth', 'Macadamias geröstet & ungesalzen', 'C'),
    ('Seeberger', 'Edel-Nuss-Mix geröstet & gesalzen', 'E'),
    ('Intersnack', 'Ültje Cashews, geröstet & gesalzen', 'C'),
    ('Maryland', 'Röst-Cashews', 'B'),
    ('Ültje', 'Erdnüsse - Cacahuètes grillées sans huile et salées, épicées', 'C'),
    ('Maryland', 'Snack Nüsse Salz XXL', 'E'),
    ('Trader Joe''s', 'Snackmandeln geröstet & gesalzen', 'B'),
    ('Bodeta', 'Gebrannte Erdnüsse', 'UNKNOWN'),
    ('DmBio', 'Erdnüsse ungesalzen', 'A'),
    ('Ültje', 'Fusion BBQ Erdnüsse', 'B'),
    ('Aldi', 'Erdnüsse geröstet & gesalzen', 'C'),
    ('K-Classic', 'Erdnüsse ger. & ges.', 'C'),
    ('Kaufland K-classic', 'Macadamia geröstet & gesalzen', 'D'),
    ('Max', 'Pistazien geröstet & gesalzen', 'C'),
    ('Seeberger', 'Geröstete Cashews ohne Salz', 'B'),
    ('Kaufland', 'Erdnüsse im Paprika-Knuspermantel', 'D'),
    ('Dennree', 'Mandelkerne, europäische', 'C'),
    ('Ültje', 'Erdnüsse geröstet und gesalzen', 'C'),
    ('Maryland', 'Nüsse Sportmix', 'D'),
    ('Kaufland K-classic', 'Mandeln unblanchiert geröstet & gesalzen', 'A'),
    ('Trader Joe''s', 'Walnüsse in der Schale', 'B'),
    ('Ültje', 'Ültje pur Erdnüsse, im Ofen gebacken & ungesalzen, 200g', 'A'),
    ('Seeberger', 'Cashewkerne geröstet & gesalzen', 'C'),
    ('Ültje', 'Nüsse Cashew geröstet', 'C'),
    ('Kaufland K-Classic', 'Erdnüsse mit schwarzem Pfeffer', 'C'),
    ('Lorenz', 'NicNacs', 'D'),
    ('Farmer Naturals', 'Walnusskerne naturbelassen', 'A'),
    ('Seeberger', 'Nusskernmischung', 'D'),
    ('Fazer naturals', 'Feinste Nuss-Variation, naturbelassen', 'C'),
    ('Alesto', 'Mix Proteína Frutos Secos Y Soja', 'D'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen', 'B'),
    ('Farmer naturals', 'Premium-Nussmix - Fein mit Pekannusskernen', 'A'),
    ('Alesto Selection', 'Pecan Nuts natural', 'A'),
    ('Trader Joe''s', 'Walnusskerne naturbelassen', 'A'),
    ('Farmer Naturals', 'Simply Roasted - Cashewkerne', 'C'),
    ('Trader Joe''s', 'Cashewkerne, naturbelassen', 'B'),
    ('Farmer', 'Trail-Mix Kerne', 'A'),
    ('DmBio', 'Mandeln ganze Kerne', 'A'),
    ('Farmer Naturals', 'Simply Roasted - Nussmischung', 'D'),
    ('Trader joes', 'Pistachio mix', 'B'),
    ('Seeberger', 'Seeberger Walnusskerne 4008258130018 Walnusskerne', 'A'),
    ('Alesto', 'Cashew Nuts XXL', 'B'),
    ('Alesto', 'Mandeln Honig & Salz', 'E'),
    ('Alesto', 'Noisettes grillées', 'A'),
    ('Farmer', 'Nuss-Frucht-Mix 5er-Pack - Cranberry', 'D'),
    ('K-Classic', 'Nuts royal', 'C'),
    ('Dm', 'Pistazien Creme', 'D'),
    ('Maryland', 'Studentenfutter', 'D'),
    ('Farmer naturals', 'Premium-Nussmix - Extra mit Mandeln, Cashew-, Para-, Pekan-, Macadamia-Nusskernen', 'D'),
    ('Trader Joe''s', 'Studentenfutter', 'D'),
    ('Trader Joe''s', 'Knusperkracher', 'D'),
    ('DmBio', 'Pistaziencreme', 'D'),
    ('DmBio', 'Mandelmehl', 'A'),
    ('Alesto', 'Cashews roasted & salted', 'C'),
    ('Farmer''s Snack', 'Studentenfutter ohne Rosinen mit saftigen Cranberries', 'D'),
    ('Farmer naturals', 'Paranusskerne naturbelassen', 'C'),
    ('Farmer Naturals', 'Simply Roasted - Mandeln', 'B'),
    ('Farmer naturals', 'Pinienkerne', 'A'),
    ('Farmer Naturals', 'Energieschub', 'D'),
    ('Trader Joe''s', 'Mandelkerne naturbelassen', 'A'),
    ('DmBio', 'Paranuss Kerne', 'C'),
    ('Afrika', 'Bio Cashewkerne naturbelassen aus Westafrika', 'B'),
    ('Trader Joe''s', 'Premiumnuss-Mix mit Mandel-, Cashew-, Pekan-, Macadamia- & Paranusskernen, ungesalzen', 'D'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', 'B'),
    ('Ültje', 'Rauchmandeln', 'B'),
    ('Seeberger', 'Macadamia Nusskerne', 'E'),
    ('Farmer''s Snack', 'Pinienkerne', 'A'),
    ('Trader Joe''s', 'Cashewkerne naturbelassen', 'B'),
    ('Aldi', 'Mandeln blanchiert, gemahlen', 'UNKNOWN'),
    ('Alesto', 'Pistazienkerne', 'A'),
    ('Farmer', 'Trail mix Beeren', 'E'),
    ('Unknown', 'Erdnüsse Wasabi Style', 'E'),
    ('K-Bio', 'Cashew Cranberry mix', 'C'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen XXL', 'B'),
    ('Gut bio', 'Kerne-Mix', 'A'),
    ('Farmer''s Snack', 'Cashewkerne', 'B'),
    ('Trader Joe''s', 'Kalifornische Pistazien, ungesalzen', 'B'),
    ('Gut Bio', 'Walnusskerne', 'B'),
    ('Trader Joe''s', 'Paranusskerne', 'C'),
    ('Alesto', 'Walnuts', 'A'),
    ('Farmer naturals', 'Kernige Vielfalt', 'C'),
    ('K-Classic', 'Walnuss-Kerne', 'A'),
    ('Alesto', 'Erdnüsse geröstet und gesalzen', 'C'),
    ('Alesto', 'Cashewkerne geröstet & gesalzen', 'C'),
    ('REWE Beste Wahl', 'Erdnüsse große Kerne geröstet ungesalzen', 'A'),
    ('Seeberger', 'Crunchy Fava-Snack salted', 'C'),
    ('Alesto', 'Erdnüsse, pikant gewürzt', 'UNKNOWN'),
    ('Gut & Günstig', 'Erdnüsse geröstet & gesalzen', 'C'),
    ('Edeka', 'Pistazien, geröstet & gesalzen', 'C'),
    ('Alesto', 'Erdnüsse – geröstet & gesalzen', 'A'),
    ('K-Bio', 'Walnusskerne', 'A'),
    ('Clarkys', 'Erdnüsse im Teigmantel Paprika', 'D'),
    ('Ja!', 'Erdnüsse pikant gewürzt', 'D')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Ültje', 'Erdnüsse geröstet & gesalzen', '3'),
    ('Ültje', 'Ültje Erdnüsse geröstet & ungesalzen 180g 2,49€ 13,83€ 1kg', '3'),
    ('Ültje', 'Erdnüsse', '3'),
    ('Ültje', 'EXTRA ROAST Erdnüsse gesalzen', '4'),
    ('Farmer', 'Cashewkerne - geröstet & gesalzen', '3'),
    ('Maryland', 'Snack Nüsse pur', '1'),
    ('K-Classic', 'Erdnüsse geröstet & gesalzen', '3'),
    ('Ültje', 'Ofen Erdnüsse gesalzen', '4'),
    ('Alesto', 'Erdnusskerne geröstet', '3'),
    ('Aldi', 'Pistazien - geröstet & gesalzen', '3'),
    ('Maryland', 'Nuss-Kern-Mischung geröstet & gesalzen', '3'),
    ('Alesto', 'XXL Erdnüsse', '3'),
    ('Farmer', 'Macadamia geröstet & gesalzen', '3'),
    ('Aldi', 'Erdnüsse in der Schale, geröstet', '1'),
    ('Seeberger', 'Cashew Kerne Nüsse', '1'),
    ('August Töpfer', 'Nuss-Mix, geröstet & gesalzen', '3'),
    ('Maryland', 'Studentenfutter Berry mit Cranberries & Walnüssen', '3'),
    ('Farmer', 'Cashewkerne - pikant gewürzt', '4'),
    ('XOX', 'Erdnüsse geröstet ohne Salz', '3'),
    ('Farmer', 'Pistazien - geröstet & ungesalzen', '1'),
    ('K-Classic', 'Erdnüsse geröstet', '3'),
    ('Maryland', 'Snack Nüsse Honig & Salz', '4'),
    ('Maryland', 'Snack Nüsse Provence', '3'),
    ('Maryland', 'Snack Nüsse Ungarisch Style', '4'),
    ('Trader Joe''s', 'Salat-Plus - Mischung aus Sonnenblumen-, Kürbis- & Pinienkerne', '1'),
    ('Trader Joe''s', 'Jumbo Erdnüsse in der Schale, geröstet', '1'),
    ('Aldi', 'Wasabi-Erdnüsse', '4'),
    ('Ültje', 'Erdnüsse - geröstet & gezalzen XXL Party Edition', '3'),
    ('Traders Joe''s', 'Cashews, geröstet & gesalzen', '3'),
    ('Maryland', 'Snack Nüsse Salz & Pfeffer', '3'),
    ('Trader Joe''s', 'Kalifornische Pistazien, geröstet & gesalzen', '3'),
    ('Trader Joe''s', 'Haselnusskerne geröstet, ungesalzen', '1'),
    ('Trader Joe''s', 'Erdnüsse mit Knusperhülle', '4'),
    ('Trader Joe''s', 'Cashews, geröstet & pikant gewürzt', '4'),
    ('K-Classic', 'Cashewkerne geröstet u. gesalzen', '3'),
    ('Alesto', 'Californische Pistazienkerne geröstet & gesalzen', '3'),
    ('Aldi', 'Erdnüsse im Teigmantel - Paprika', '4'),
    ('Farmer''s Snack', 'Geröstete Mandel, ungesalzen', '1'),
    ('Max', 'Jumbo Erdnüsse geröstet & gesalzen', '3'),
    ('Maryland', 'Snack Nüsse BBQ', '4'),
    ('Alesto', 'Cashewkerne geröstet & ungesalzen', '3'),
    ('Kaufland Classic', 'Erdnüsse', '1'),
    ('K-Bio', 'Erdnusskerne geröstet & gesalzen', '3'),
    ('Maryland', 'Snack Nüsse Oriental Style', '4'),
    ('Trader Joe''s', 'Pistazienkerne geröstet, ungesalzen', '1'),
    ('Ültje', 'Erdnüsse pikant gewürzt', '4'),
    ('Farmer', 'Erdnusskerne - geröstet und gesalzen', '3'),
    ('Trader Joe''s', 'Erdnüsse geröstet und gesalzen', '3'),
    ('Ültje', 'Kessel Nüsse Paprika', '4'),
    ('Farmer', 'Erdnüsse', '3'),
    ('Ültje', 'Erdnüsse, geröstet & gesalzen', '3'),
    ('K Classic', 'Erdnüsse pikant', '4'),
    ('Alesto', 'Spanische Mandeln blanchiert und geröstet', '1'),
    ('Ültje', 'Erdnüsse ungesalzen', '3'),
    ('Ültje', 'Mandeln & Erdnüsse Honig und Salz', '4'),
    ('Kluth', 'Nuss-Mix geröstet und gesalzen', '3'),
    ('Farmer', 'Geröstete Snackmandeln', '3'),
    ('Kluth', 'Macadamias geröstet & ungesalzen', '4'),
    ('Seeberger', 'Edel-Nuss-Mix geröstet & gesalzen', '4'),
    ('Intersnack', 'Ültje Cashews, geröstet & gesalzen', '3'),
    ('Maryland', 'Röst-Cashews', '1'),
    ('Ültje', 'Erdnüsse - Cacahuètes grillées sans huile et salées, épicées', '4'),
    ('Maryland', 'Snack Nüsse Salz XXL', '3'),
    ('Trader Joe''s', 'Snackmandeln geröstet & gesalzen', '3'),
    ('Bodeta', 'Gebrannte Erdnüsse', '4'),
    ('DmBio', 'Erdnüsse ungesalzen', '1'),
    ('Ültje', 'Fusion BBQ Erdnüsse', '4'),
    ('Aldi', 'Erdnüsse geröstet & gesalzen', '3'),
    ('K-Classic', 'Erdnüsse ger. & ges.', '4'),
    ('Kaufland K-classic', 'Macadamia geröstet & gesalzen', '3'),
    ('Max', 'Pistazien geröstet & gesalzen', '3'),
    ('Seeberger', 'Geröstete Cashews ohne Salz', '1'),
    ('Kaufland', 'Erdnüsse im Paprika-Knuspermantel', '4'),
    ('Dennree', 'Mandelkerne, europäische', '1'),
    ('Ültje', 'Erdnüsse geröstet und gesalzen', '3'),
    ('Maryland', 'Nüsse Sportmix', '4'),
    ('Kaufland K-classic', 'Mandeln unblanchiert geröstet & gesalzen', '3'),
    ('Trader Joe''s', 'Walnüsse in der Schale', '1'),
    ('Ültje', 'Ültje pur Erdnüsse, im Ofen gebacken & ungesalzen, 200g', '1'),
    ('Seeberger', 'Cashewkerne geröstet & gesalzen', '3'),
    ('Ültje', 'Nüsse Cashew geröstet', '3'),
    ('Kaufland K-Classic', 'Erdnüsse mit schwarzem Pfeffer', '4'),
    ('Lorenz', 'NicNacs', '4'),
    ('Farmer Naturals', 'Walnusskerne naturbelassen', '1'),
    ('Seeberger', 'Nusskernmischung', '1'),
    ('Fazer naturals', 'Feinste Nuss-Variation, naturbelassen', '1'),
    ('Alesto', 'Mix Proteína Frutos Secos Y Soja', '3'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen', '1'),
    ('Farmer naturals', 'Premium-Nussmix - Fein mit Pekannusskernen', '1'),
    ('Alesto Selection', 'Pecan Nuts natural', '1'),
    ('Trader Joe''s', 'Walnusskerne naturbelassen', '1'),
    ('Farmer Naturals', 'Simply Roasted - Cashewkerne', '1'),
    ('Trader Joe''s', 'Cashewkerne, naturbelassen', '3'),
    ('Farmer', 'Trail-Mix Kerne', '3'),
    ('DmBio', 'Mandeln ganze Kerne', '1'),
    ('Farmer Naturals', 'Simply Roasted - Nussmischung', '1'),
    ('Trader joes', 'Pistachio mix', '4'),
    ('Seeberger', 'Seeberger Walnusskerne 4008258130018 Walnusskerne', '1'),
    ('Alesto', 'Cashew Nuts XXL', '1'),
    ('Alesto', 'Mandeln Honig & Salz', '4'),
    ('Alesto', 'Noisettes grillées', '1'),
    ('Farmer', 'Nuss-Frucht-Mix 5er-Pack - Cranberry', '3'),
    ('K-Classic', 'Nuts royal', '4'),
    ('Dm', 'Pistazien Creme', '3'),
    ('Maryland', 'Studentenfutter', '3'),
    ('Farmer naturals', 'Premium-Nussmix - Extra mit Mandeln, Cashew-, Para-, Pekan-, Macadamia-Nusskernen', '4'),
    ('Trader Joe''s', 'Studentenfutter', '3'),
    ('Trader Joe''s', 'Knusperkracher', '4'),
    ('DmBio', 'Pistaziencreme', '4'),
    ('DmBio', 'Mandelmehl', '1'),
    ('Alesto', 'Cashews roasted & salted', '3'),
    ('Farmer''s Snack', 'Studentenfutter ohne Rosinen mit saftigen Cranberries', '3'),
    ('Farmer naturals', 'Paranusskerne naturbelassen', '1'),
    ('Farmer Naturals', 'Simply Roasted - Mandeln', '1'),
    ('Farmer naturals', 'Pinienkerne', '1'),
    ('Farmer Naturals', 'Energieschub', '1'),
    ('Trader Joe''s', 'Mandelkerne naturbelassen', '1'),
    ('DmBio', 'Paranuss Kerne', '1'),
    ('Afrika', 'Bio Cashewkerne naturbelassen aus Westafrika', '1'),
    ('Trader Joe''s', 'Premiumnuss-Mix mit Mandel-, Cashew-, Pekan-, Macadamia- & Paranusskernen, ungesalzen', '1'),
    ('Ültje', 'Fusion - Peanuts Curry Orient Style', '4'),
    ('Ültje', 'Rauchmandeln', '4'),
    ('Seeberger', 'Macadamia Nusskerne', '3'),
    ('Farmer''s Snack', 'Pinienkerne', '1'),
    ('Trader Joe''s', 'Cashewkerne naturbelassen', '1'),
    ('Aldi', 'Mandeln blanchiert, gemahlen', '4'),
    ('Alesto', 'Pistazienkerne', '1'),
    ('Farmer', 'Trail mix Beeren', '4'),
    ('Unknown', 'Erdnüsse Wasabi Style', '4'),
    ('K-Bio', 'Cashew Cranberry mix', '4'),
    ('Farmer Naturals', 'Cashewkerne naturbelassen XXL', '1'),
    ('Gut bio', 'Kerne-Mix', '1'),
    ('Farmer''s Snack', 'Cashewkerne', '1'),
    ('Trader Joe''s', 'Kalifornische Pistazien, ungesalzen', '1'),
    ('Gut Bio', 'Walnusskerne', '1'),
    ('Trader Joe''s', 'Paranusskerne', '1'),
    ('Alesto', 'Walnuts', '1'),
    ('Farmer naturals', 'Kernige Vielfalt', '1'),
    ('K-Classic', 'Walnuss-Kerne', '1'),
    ('Alesto', 'Erdnüsse geröstet und gesalzen', '3'),
    ('Alesto', 'Cashewkerne geröstet & gesalzen', '3'),
    ('REWE Beste Wahl', 'Erdnüsse große Kerne geröstet ungesalzen', '3'),
    ('Seeberger', 'Crunchy Fava-Snack salted', '3'),
    ('Alesto', 'Erdnüsse, pikant gewürzt', '4'),
    ('Gut & Günstig', 'Erdnüsse geröstet & gesalzen', '3'),
    ('Edeka', 'Pistazien, geröstet & gesalzen', '3'),
    ('Alesto', 'Erdnüsse – geröstet & gesalzen', '3'),
    ('K-Bio', 'Walnusskerne', '4'),
    ('Clarkys', 'Erdnüsse im Teigmantel Paprika', '4'),
    ('Ja!', 'Erdnüsse pikant gewürzt', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Nuts, Seeds & Legumes', 100, 'DE');
