-- PIPELINE (Drinks): scoring
-- Generated: 2026-03-04

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Hortex', 'Sok jabłkowy', 'C'),
    ('Riviva', 'Sok 100% pomarańcza z witaminą C', 'C'),
    ('Bracia Sadownicy', 'Sok 100% tłoczony tłoczone jabłko z marchewką', 'D'),
    ('Polaris', 'Napój gazowany Vital Red', 'C'),
    ('Polaris', 'Napój gazowany Vital Green', 'C'),
    ('Tymbark', 'Sok 100% Pomarańcza', 'C'),
    ('Tymbark', 'Sok 100% jabłko', 'C'),
    ('Riviva', 'Sok 100% jabłko', 'C'),
    ('Bracia Sadownicy', 'Tłoczone Jabłko słodkie odmiany', 'D'),
    ('Hellena', 'Oranżada czerwona', 'D'),
    ('Riviva', 'Napój Aloesowy z Cząstkami Aloesu', 'C'),
    ('Go Vege', 'Napój roślinny Owies Bio', 'C'),
    ('Tymbark', 'Tymbark Jabłko Wiśnia 2l', 'D'),
    ('Hortex', 'Sok 100% pomarańcza', 'C'),
    ('MWS', 'Kubuś Waterrr Truskawka', 'C'),
    ('Kubuš', '100% jabłko', 'UNKNOWN'),
    ('Tymbark', 'Vitamini JABŁKO MARCHEW MALINA', 'C'),
    ('Tymbark', 'Tymbark Jabłko-Wiśnia', 'D'),
    ('Piątnica', 'Napój owsiany z wapnem i witaminami', 'C'),
    ('Tymbark', 'Tymbark Sok pomarańczowy 100% 1l', 'E'),
    ('GoVege (Biedronka)', 'Napój Roślinny - Midgał', 'C'),
    ('Riviva', 'Napój o smaku Kaktus - Jabłko - Limonka', 'D'),
    ('Zatecky', 'Żatecky 0,0% nealko', 'B'),
    ('Tymbark', 'Sok pomarańczowy 100%', 'UNKNOWN'),
    ('Żywiec Zdrój', 'Z nutą truskawki', 'C'),
    ('Riviva', '100% Coconut Water', 'B'),
    ('Pepsico', 'Pepsi', 'E'),
    ('Pepsi', 'Pepsi Zero', 'C'),
    ('Riviva', 'Sok 100% multiwitamina', 'C'),
    ('Unknown', 'Żywiec Zdrój NGaz 1l', 'D'),
    ('Tymbark', 'Tymbark Jabłko Wiśnia', 'B'),
    ('Pepsi', 'Pepsi Max 0.5', 'B'),
    ('Tymbark', 'Multifruit mango flavoured still drink', 'E'),
    ('Fortuna', 'Sok 100% pomidor', 'B'),
    ('Unknown', 'Cola original zero', 'C'),
    ('Frugo', 'Ultra black', 'UNKNOWN'),
    ('Unknown', 'Zywiec zdróy z nuta cytryny', 'E'),
    ('Riviva', 'Jus d''orange 100%', 'C'),
    ('Unilever', '(3, 58eur / 100g) Schwarzer Tee Von Lipton - 25 Beutel', 'B'),
    ('Vemondo', 'Owsiane smoothie owoce lata', 'C'),
    ('Cola', 'Cola original intense zero', 'C'),
    ('Frugo', 'Frugo ultragreen', 'C'),
    ('Unknown', 'Żywiec Zdrój Minerals', 'A'),
    ('Tymbark', 'Sok pomidorowy pikantny', 'B'),
    ('Riviva', 'Sok 100% pomidorowo-warzywny', 'B'),
    ('Inka', 'Mleko owsiane', 'C'),
    ('Tymbark', 'Tymbark 100% jablko', 'C'),
    ('Grana', 'Owsiane', 'C'),
    ('Heineken', 'Heineken 0.0%', 'B'),
    ('WK Dzik', 'Dzik Energy Zero calorie', 'C'),
    ('Black', 'Black Energy', 'UNKNOWN'),
    ('Oshee', 'Oshee Vitamin Water', 'C'),
    ('Dawtona', 'Sok pomidorowy', 'B'),
    ('Tiger', 'TIGER Energy drink', 'D'),
    ('Oshee', 'Oshee Multifruit', 'D'),
    ('Pepsi', 'Pepsi puszka', 'E'),
    ('Oshee', 'Oshee Grapefruit', 'C'),
    ('Lipton', 'Lipton Green 1,5L', 'C'),
    ('Tymbark', 'Sok 100% Multiwitamina', 'D'),
    ('Pepsi', 'Pepsi 330ML Max Soft Drink', 'B'),
    ('Oshee', 'Vitamin Water', 'C'),
    ('Pepsico', 'Pepsi 1.5', 'E'),
    ('Pepsi', 'Pepsi 0.5', 'D'),
    ('Hellena', 'Helena zero', 'UNKNOWN'),
    ('Lipton', 'Ice Tea Peach', 'D'),
    ('Black', 'Black Zero Sugar', 'C'),
    ('Tymbark', 'Sok pomidorowy 100%', 'B'),
    ('Lidl', 'Sok 100% tłoczony z miąższem Pomarańcza Grejpfrut Pitaja', 'C'),
    ('Oshee', 'Vitamin Water zero', 'B'),
    ('Dawtona', 'Sok pomidorowy pikantny', 'B'),
    ('I♥Vege', 'Owsiane', 'C'),
    ('Schweppes', 'Indian Tonic', 'D'),
    ('Riviva', 'Sok Marchew Banan Jablko', 'C'),
    ('Pepsi', 'Pepsi 0.85', 'E'),
    ('Oshee', 'OSHEE Zero', 'C'),
    ('Cisowianka', 'Cisowianka gazowana', 'A'),
    ('Oshee', 'Vitamin Tea Zero Peach Flavour', 'C'),
    ('Tymbark', 'Apple watermelon', 'C'),
    ('Riviva', 'Sok Pomidor Pikantny', 'B'),
    ('4move', '4move sports wild cherry', 'C'),
    ('Tymbark', 'Just Plants Owies', 'C'),
    ('GoVege', 'Barista salted caramel', 'D'),
    ('4move', 'Activevitamin', 'C'),
    ('Hortex', 'Nektar z czarnych porzeczek', 'C'),
    ('Oshee', 'Oshee lemonade Malina-Grejpfrut', 'C'),
    ('Tymbark', 'Mousse', 'B'),
    ('Black', 'Black Energy - Mojito flavour', 'E'),
    ('Unknown', 'Dr witt multivitamin', 'C'),
    ('Alcalia', 'Alcalia Naturalna Woda Mineralna Naturalnie Alkaiczna', 'A'),
    ('Lipton', 'Green Ice Tea', 'D'),
    ('Lipton', 'Lipton green', 'C'),
    ('Wk Dzik', 'Dzik Vitamind Drink Cranberry', 'NOT-APPLICABLE'),
    ('Energy Drink', 'Dzik', 'C'),
    ('Swigo', 'Sok grejpfrutowy HPP', 'B'),
    ('Pepsi', 'Pepsi', 'E')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Hortex', 'Sok jabłkowy', '1'),
    ('Riviva', 'Sok 100% pomarańcza z witaminą C', '1'),
    ('Bracia Sadownicy', 'Sok 100% tłoczony tłoczone jabłko z marchewką', '1'),
    ('Polaris', 'Napój gazowany Vital Red', '4'),
    ('Polaris', 'Napój gazowany Vital Green', '4'),
    ('Tymbark', 'Sok 100% Pomarańcza', '1'),
    ('Tymbark', 'Sok 100% jabłko', '1'),
    ('Riviva', 'Sok 100% jabłko', '4'),
    ('Bracia Sadownicy', 'Tłoczone Jabłko słodkie odmiany', '1'),
    ('Hellena', 'Oranżada czerwona', '4'),
    ('Riviva', 'Napój Aloesowy z Cząstkami Aloesu', '3'),
    ('Go Vege', 'Napój roślinny Owies Bio', '3'),
    ('Tymbark', 'Tymbark Jabłko Wiśnia 2l', '4'),
    ('Hortex', 'Sok 100% pomarańcza', '4'),
    ('MWS', 'Kubuś Waterrr Truskawka', '4'),
    ('Kubuš', '100% jabłko', '4'),
    ('Tymbark', 'Vitamini JABŁKO MARCHEW MALINA', '4'),
    ('Tymbark', 'Tymbark Jabłko-Wiśnia', '4'),
    ('Piątnica', 'Napój owsiany z wapnem i witaminami', '3'),
    ('Tymbark', 'Tymbark Sok pomarańczowy 100% 1l', '1'),
    ('GoVege (Biedronka)', 'Napój Roślinny - Midgał', '4'),
    ('Riviva', 'Napój o smaku Kaktus - Jabłko - Limonka', '4'),
    ('Zatecky', 'Żatecky 0,0% nealko', '4'),
    ('Tymbark', 'Sok pomarańczowy 100%', '1'),
    ('Żywiec Zdrój', 'Z nutą truskawki', '4'),
    ('Riviva', '100% Coconut Water', '1'),
    ('Pepsico', 'Pepsi', '4'),
    ('Pepsi', 'Pepsi Zero', '4'),
    ('Riviva', 'Sok 100% multiwitamina', '4'),
    ('Unknown', 'Żywiec Zdrój NGaz 1l', '1'),
    ('Tymbark', 'Tymbark Jabłko Wiśnia', '4'),
    ('Pepsi', 'Pepsi Max 0.5', '4'),
    ('Tymbark', 'Multifruit mango flavoured still drink', '4'),
    ('Fortuna', 'Sok 100% pomidor', '3'),
    ('Unknown', 'Cola original zero', '4'),
    ('Frugo', 'Ultra black', '4'),
    ('Unknown', 'Zywiec zdróy z nuta cytryny', '4'),
    ('Riviva', 'Jus d''orange 100%', '1'),
    ('Unilever', '(3, 58eur / 100g) Schwarzer Tee Von Lipton - 25 Beutel', '4'),
    ('Vemondo', 'Owsiane smoothie owoce lata', '3'),
    ('Cola', 'Cola original intense zero', '4'),
    ('Frugo', 'Frugo ultragreen', '4'),
    ('Unknown', 'Żywiec Zdrój Minerals', '1'),
    ('Tymbark', 'Sok pomidorowy pikantny', '3'),
    ('Riviva', 'Sok 100% pomidorowo-warzywny', '3'),
    ('Inka', 'Mleko owsiane', '4'),
    ('Tymbark', 'Tymbark 100% jablko', '1'),
    ('Grana', 'Owsiane', '4'),
    ('Heineken', 'Heineken 0.0%', '4'),
    ('WK Dzik', 'Dzik Energy Zero calorie', '4'),
    ('Black', 'Black Energy', '4'),
    ('Oshee', 'Oshee Vitamin Water', '1'),
    ('Dawtona', 'Sok pomidorowy', '3'),
    ('Tiger', 'TIGER Energy drink', '4'),
    ('Oshee', 'Oshee Multifruit', '4'),
    ('Pepsi', 'Pepsi puszka', '4'),
    ('Oshee', 'Oshee Grapefruit', '4'),
    ('Lipton', 'Lipton Green 1,5L', '4'),
    ('Tymbark', 'Sok 100% Multiwitamina', '4'),
    ('Pepsi', 'Pepsi 330ML Max Soft Drink', '4'),
    ('Oshee', 'Vitamin Water', '4'),
    ('Pepsico', 'Pepsi 1.5', '4'),
    ('Pepsi', 'Pepsi 0.5', '4'),
    ('Hellena', 'Helena zero', '4'),
    ('Lipton', 'Ice Tea Peach', '4'),
    ('Black', 'Black Zero Sugar', '4'),
    ('Tymbark', 'Sok pomidorowy 100%', '3'),
    ('Lidl', 'Sok 100% tłoczony z miąższem Pomarańcza Grejpfrut Pitaja', '4'),
    ('Oshee', 'Vitamin Water zero', '4'),
    ('Dawtona', 'Sok pomidorowy pikantny', '3'),
    ('I♥Vege', 'Owsiane', '4'),
    ('Schweppes', 'Indian Tonic', '4'),
    ('Riviva', 'Sok Marchew Banan Jablko', '4'),
    ('Pepsi', 'Pepsi 0.85', '4'),
    ('Oshee', 'OSHEE Zero', '4'),
    ('Cisowianka', 'Cisowianka gazowana', '1'),
    ('Oshee', 'Vitamin Tea Zero Peach Flavour', '4'),
    ('Tymbark', 'Apple watermelon', '4'),
    ('Riviva', 'Sok Pomidor Pikantny', '3'),
    ('4move', '4move sports wild cherry', '4'),
    ('Tymbark', 'Just Plants Owies', '3'),
    ('GoVege', 'Barista salted caramel', '4'),
    ('4move', 'Activevitamin', '4'),
    ('Hortex', 'Nektar z czarnych porzeczek', '4'),
    ('Oshee', 'Oshee lemonade Malina-Grejpfrut', '4'),
    ('Tymbark', 'Mousse', '4'),
    ('Black', 'Black Energy - Mojito flavour', '4'),
    ('Unknown', 'Dr witt multivitamin', '4'),
    ('Alcalia', 'Alcalia Naturalna Woda Mineralna Naturalnie Alkaiczna', '1'),
    ('Lipton', 'Green Ice Tea', '4'),
    ('Lipton', 'Lipton green', '4'),
    ('Wk Dzik', 'Dzik Vitamind Drink Cranberry', '4'),
    ('Energy Drink', 'Dzik', '4'),
    ('Swigo', 'Sok grejpfrutowy HPP', '1'),
    ('Pepsi', 'Pepsi', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Drinks', 100, 'PL');
