-- PIPELINE (Plant-Based & Alternatives): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Pano', 'Wafle Ryżowe Wieloziarnisty', 'A'),
    ('Pri', 'Ziemniaczki Już Gotowe z papryką', 'C'),
    ('Go Vege', 'Parówki sojowe klasyczne', 'D'),
    ('Nasza Spiżarnia', 'Nasza Spiżarnia Korniszony z chilli', 'C'),
    ('Basia', 'Mąka Tortowa Extra typ 405 Basia', 'A'),
    ('Dobra-kaloria', 'Baton owocowy chrupiący orzech', 'D'),
    ('Tarczyński', 'Rośl-inne Kabanosy 3 Ziarna', 'E'),
    ('Złote Pola', 'Mąka tortowa pszenna. Typ 450', 'A'),
    ('Sante', 'Otręby owsiane', 'A'),
    ('Sonko', 'Kasza jęczmienna perłowa', 'A'),
    ('Pano', 'Wafle Kukurydziane sól morska', 'A'),
    ('Polskie Mlyny', 'Mąka pszenna Szymanowska 480', 'A'),
    ('Kupiec', 'Kasza manna błyskawiczna', 'B'),
    ('GustoBello', 'Mąka do pizzy neapolitańskiej typ 00', 'UNKNOWN'),
    ('PZZ Kraków', 'Mąka pszenna tortowa', 'A'),
    ('Uniflora', 'Kiełki rzodkiewki', 'A'),
    ('Szczepanki', 'Mąka pszenna wrocławska typ 500', 'UNKNOWN'),
    ('Unknown', 'Kasza gryczana prażona', 'UNKNOWN'),
    ('Pani', 'Wafle Prowansalskie', 'A'),
    ('Culineo', 'Koncentrat Pomidorowy 30%', 'B'),
    ('Madero', 'Chrzan tarty', 'C'),
    ('Dawtona', 'Sűrített paradicsom', 'C'),
    ('Melvit', 'Natural Mix', 'A'),
    ('Culineo', 'Koncentrat pomidorowy', 'A'),
    ('Wojan team', 'Wojanek', 'B'),
    ('Pudliszki', 'Koncentrat pomidorowy', 'A'),
    ('Nasza Spiżarnia', 'Fasola czerwona', 'UNKNOWN'),
    ('Dawtona', 'Koncentrat pomidorowy', 'A'),
    ('Culineo', 'Pasta z czosnkiem', 'A'),
    ('Biedronka', 'Borówka amerykańska odmiany Brightwell', 'A'),
    ('GustoBello', 'Gnocchi Di Patate', 'C'),
    ('Plony natury', 'Kasza manna', 'A'),
    ('Culineo', 'Passata klasyczna', 'B'),
    ('Anecoop', 'Włoszczyzna', 'A'),
    ('Vemondo', 'Tofu wędzone', 'C'),
    ('El Toro Rojo', 'Oliwki zielone nadziewane pastą paprykową', 'E'),
    ('Plony Natury', 'Kasza Gryczana Biała', 'UNKNOWN'),
    ('Janex', 'Kasza Gryczana', 'A'),
    ('Go Vege', 'Tofu Naturalne', 'A'),
    ('Go VEGE', 'Tofu sweet chili', 'C'),
    ('Lidl', 'Avocados', 'A'),
    ('Kania', 'Crispy Fried Onions', 'E'),
    ('Vemondo', 'Tofu plain', 'B'),
    ('Vemondo', 'Tofu naturalne', 'A'),
    ('K-take it veggie', 'Tofu natur eco', 'A'),
    ('GustoBello', 'Polpa di pomodoro', 'A'),
    ('Garden Gourmet', 'Veggie Balls', 'A'),
    ('Vemondo', 'Tofu', 'A'),
    ('Tastino', 'Wafle Kukurydziane', 'A'),
    ('Crownfield', 'Owsianka Truskawkowa', 'C'),
    ('Bakello', 'Ciasto francuskie', 'D'),
    ('Violife', 'Cheddar flavour slices', 'E'),
    ('Golden Sun Lidl', 'Kasza manna', 'B'),
    ('Nasza Spiżarnia', 'Ananas Plastry', 'UNKNOWN'),
    ('Unknown', 'Awokado hass', 'UNKNOWN')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Pano', 'Wafle Ryżowe Wieloziarnisty', '3'),
    ('Pri', 'Ziemniaczki Już Gotowe z papryką', '3'),
    ('Go Vege', 'Parówki sojowe klasyczne', '4'),
    ('Nasza Spiżarnia', 'Nasza Spiżarnia Korniszony z chilli', '4'),
    ('Basia', 'Mąka Tortowa Extra typ 405 Basia', '1'),
    ('Dobra-kaloria', 'Baton owocowy chrupiący orzech', '1'),
    ('Tarczyński', 'Rośl-inne Kabanosy 3 Ziarna', '4'),
    ('Złote Pola', 'Mąka tortowa pszenna. Typ 450', '1'),
    ('Sante', 'Otręby owsiane', '1'),
    ('Sonko', 'Kasza jęczmienna perłowa', '1'),
    ('Pano', 'Wafle Kukurydziane sól morska', '3'),
    ('Polskie Mlyny', 'Mąka pszenna Szymanowska 480', '1'),
    ('Kupiec', 'Kasza manna błyskawiczna', '4'),
    ('GustoBello', 'Mąka do pizzy neapolitańskiej typ 00', '4'),
    ('PZZ Kraków', 'Mąka pszenna tortowa', '4'),
    ('Uniflora', 'Kiełki rzodkiewki', '1'),
    ('Szczepanki', 'Mąka pszenna wrocławska typ 500', '1'),
    ('Unknown', 'Kasza gryczana prażona', '4'),
    ('Pani', 'Wafle Prowansalskie', '3'),
    ('Culineo', 'Koncentrat Pomidorowy 30%', '4'),
    ('Madero', 'Chrzan tarty', '3'),
    ('Dawtona', 'Sűrített paradicsom', '4'),
    ('Melvit', 'Natural Mix', '1'),
    ('Culineo', 'Koncentrat pomidorowy', '1'),
    ('Wojan team', 'Wojanek', '4'),
    ('Pudliszki', 'Koncentrat pomidorowy', '1'),
    ('Nasza Spiżarnia', 'Fasola czerwona', '4'),
    ('Dawtona', 'Koncentrat pomidorowy', '1'),
    ('Culineo', 'Pasta z czosnkiem', '3'),
    ('Biedronka', 'Borówka amerykańska odmiany Brightwell', '1'),
    ('GustoBello', 'Gnocchi Di Patate', '4'),
    ('Plony natury', 'Kasza manna', '4'),
    ('Culineo', 'Passata klasyczna', '4'),
    ('Anecoop', 'Włoszczyzna', '1'),
    ('Vemondo', 'Tofu wędzone', '4'),
    ('El Toro Rojo', 'Oliwki zielone nadziewane pastą paprykową', '4'),
    ('Plony Natury', 'Kasza Gryczana Biała', '4'),
    ('Janex', 'Kasza Gryczana', '4'),
    ('Go Vege', 'Tofu Naturalne', '4'),
    ('Go VEGE', 'Tofu sweet chili', '4'),
    ('Lidl', 'Avocados', '1'),
    ('Kania', 'Crispy Fried Onions', '3'),
    ('Vemondo', 'Tofu plain', '4'),
    ('Vemondo', 'Tofu naturalne', '4'),
    ('K-take it veggie', 'Tofu natur eco', '4'),
    ('GustoBello', 'Polpa di pomodoro', '3'),
    ('Garden Gourmet', 'Veggie Balls', '4'),
    ('Vemondo', 'Tofu', '4'),
    ('Tastino', 'Wafle Kukurydziane', '3'),
    ('Crownfield', 'Owsianka Truskawkowa', '4'),
    ('Bakello', 'Ciasto francuskie', '4'),
    ('Violife', 'Cheddar flavour slices', '4'),
    ('Golden Sun Lidl', 'Kasza manna', '1'),
    ('Nasza Spiżarnia', 'Ananas Plastry', '4'),
    ('Unknown', 'Awokado hass', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Plant-Based & Alternatives', 100, 'PL');
