-- PIPELINE (Snacks): scoring
-- Generated: 2026-03-04

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Top', 'Popcorn o smaku maślanym', 'D'),
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', 'D'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', 'E'),
    ('Kupiec', 'Wafle ryżowe naturalne', 'A'),
    ('Zdrowidło', 'Chipsy Loopea''s O Smaku Śmietanki Z Cebulką', 'C'),
    ('Lubella', 'Paluszki z solą', 'E'),
    ('Pano', 'Wafle mini, zbożowe', 'B'),
    ('Bakalland', 'Ba! żurawina', 'D'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', 'A'),
    ('Lajkonik', 'Paluszki o smaku waniliowym.', 'D'),
    ('Delicje', 'Szampariskie pomaranczowe', 'E'),
    ('Vitanella', 'Superballs Kokos i kakao', 'D'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Dobry chrup', 'D'),
    ('Lajkonik', 'Salted cracker', 'D'),
    ('Go On Nutrition', 'Protein 33% Caramel', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Krakersy mini', 'D'),
    ('Bakalland', 'Barre chocolat ba', 'D'),
    ('Go On', 'Go On Energy', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Prezel', 'B'),
    ('Lorenz', 'Chrupki Curly', 'D'),
    ('Beskidzkie', 'Beskidzkie paluchy z sezamem', 'D'),
    ('Purella superfoods', 'Purella ciasteczko', 'D'),
    ('Unknown', 'Vitanella raw', 'E'),
    ('Meltié Chocolatier', 'Dark Chocolate 64% Cocoa', 'E'),
    ('Lajkonik', 'Junior Safari', 'D'),
    ('Lorenz', 'Monster munch', 'E'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', 'E'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', 'B'),
    ('TOP', 'Paluszki solone', 'D'),
    ('Be raw', 'Energy Raspberry', 'NOT-APPLICABLE'),
    ('Top', 'Paluszki i precelki solone', 'E'),
    ('San', 'San bieszczadzkie suchary', 'C'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', 'C'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Krakersy mini ser i cebula', 'D'),
    ('Delicje', 'Delicje malinowe', 'E'),
    ('Go On', 'Vitamin Coconut & Milk Chocolate', 'NOT-APPLICABLE'),
    ('Góralki', 'Góralki mleczne', 'E'),
    ('Unknown', 'Popcorn solony', 'UNKNOWN'),
    ('7 Days', 'Croissant with Cocoa Filling', 'E'),
    ('Snack Day', 'Popcorn', 'D'),
    ('Lorenz', 'Monster Munch Crispy Potato-Snack Original', 'E'),
    ('Zott', 'Monte Snack', 'E'),
    ('Emco', 'Vitanella Bars', 'D'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', 'D'),
    ('7days', '7days', 'E'),
    ('Tastino', 'Wafle Kukurydziane', 'C'),
    ('Eti', 'Dare with MILK CHOCOLATE', 'E'),
    ('Belle France', 'Brioche Tressée', 'D'),
    ('Happy Creations', 'Cracker Mix Classic', 'E')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Top', 'Popcorn o smaku maślanym', '4'),
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', '4'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', '4'),
    ('Kupiec', 'Wafle ryżowe naturalne', '1'),
    ('Zdrowidło', 'Chipsy Loopea''s O Smaku Śmietanki Z Cebulką', '4'),
    ('Lubella', 'Paluszki z solą', '3'),
    ('Pano', 'Wafle mini, zbożowe', '3'),
    ('Bakalland', 'Ba! żurawina', '4'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', '4'),
    ('Lajkonik', 'Paluszki o smaku waniliowym.', '4'),
    ('Delicje', 'Szampariskie pomaranczowe', '4'),
    ('Vitanella', 'Superballs Kokos i kakao', '4'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', '4'),
    ('Lajkonik', 'Dobry chrup', '4'),
    ('Lajkonik', 'Salted cracker', '4'),
    ('Go On Nutrition', 'Protein 33% Caramel', '4'),
    ('Lajkonik', 'Krakersy mini', '4'),
    ('Bakalland', 'Barre chocolat ba', '4'),
    ('Go On', 'Go On Energy', '4'),
    ('Lajkonik', 'Prezel', '3'),
    ('Lorenz', 'Chrupki Curly', '4'),
    ('Beskidzkie', 'Beskidzkie paluchy z sezamem', '4'),
    ('Purella superfoods', 'Purella ciasteczko', '4'),
    ('Unknown', 'Vitanella raw', '4'),
    ('Meltié Chocolatier', 'Dark Chocolate 64% Cocoa', '4'),
    ('Lajkonik', 'Junior Safari', '4'),
    ('Lorenz', 'Monster munch', '4'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', '4'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', '4'),
    ('TOP', 'Paluszki solone', '4'),
    ('Be raw', 'Energy Raspberry', '4'),
    ('Top', 'Paluszki i precelki solone', '3'),
    ('San', 'San bieszczadzkie suchary', '4'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', '4'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', '4'),
    ('Lajkonik', 'Krakersy mini ser i cebula', '4'),
    ('Delicje', 'Delicje malinowe', '4'),
    ('Go On', 'Vitamin Coconut & Milk Chocolate', '4'),
    ('Góralki', 'Góralki mleczne', '4'),
    ('Unknown', 'Popcorn solony', '3'),
    ('7 Days', 'Croissant with Cocoa Filling', '4'),
    ('Snack Day', 'Popcorn', '4'),
    ('Lorenz', 'Monster Munch Crispy Potato-Snack Original', '4'),
    ('Zott', 'Monte Snack', '4'),
    ('Emco', 'Vitanella Bars', '4'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', '4'),
    ('7days', '7days', '4'),
    ('Tastino', 'Wafle Kukurydziane', '4'),
    ('Eti', 'Dare with MILK CHOCOLATE', '4'),
    ('Belle France', 'Brioche Tressée', '4'),
    ('Happy Creations', 'Cracker Mix Classic', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Snacks', 100, 'PL');
