-- PIPELINE (Snacks): scoring
-- Generated: 2026-03-12

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', 'D'),
    ('Top', 'Popcorn o smaku maślanym', 'D'),
    ('Kopernik', 'Pierniki nadziewane w białej czekoladzie.', 'E'),
    ('E. Wedel', 'Batonik z nadzieniem o smaku śmietankowym w mlecznej czekoladzie (z dodatkiem alkoholu).', 'E'),
    ('Maga', 'Surówka Colesław', 'B'),
    ('Pano', 'Wafle Kukurydziane z Kaszą jaglaną i Pieprzem', 'B'),
    ('Good-food', 'Wafle kukurydziane z ziołami prowansalskimi', 'A'),
    ('Lay''s Oven Baked', 'Oven Baked Krakersy wielozbożowe', 'D'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', 'E'),
    ('Kupiec', 'Wafle ryżowe naturalne', 'A'),
    ('Zdrowidło', 'Chipsy Loopea''s O Smaku Śmietanki Z Cebulką', 'C'),
    ('Lubella', 'Paluszki z solą', 'E'),
    ('Pano', 'Wafle mini, zbożowe', 'B'),
    ('Bakalland', 'Ba! żurawina', 'D'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', 'A'),
    ('Brześć', 'Słomka ptysiowa', 'D'),
    ('Helio', 'Popcorn solony do mikrofalówki', 'E'),
    ('Dobra Kaloria', 'Wysokobiałkowy Baton Krem Orzechowy Z Nutą Karmelu', 'C'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców à la latte waniliowe', 'D'),
    ('Goplana', 'Grześki w mlecznej czekoladzie', 'E'),
    ('Bakalland', 'Popcorn maślany', 'D'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców a la ciasto marchewkowe', 'D'),
    ('Unknown', 'Onigiri łosoś wędzony', 'C'),
    ('Delisana', 'Biszkopty z galaretką w polewie', 'E'),
    ('Good Food', 'Wafle ryżowe z kukurydzą o smaku pizzy- Jumbo Pizza', 'C'),
    ('Bakalland', 'Baton proteinowy o smaku słonego karmelu', 'NOT-APPLICABLE'),
    ('Dobra kaloria', 'Mini batoniki z nerkowców à la tarta malinowa', 'D'),
    ('Biedronka', 'Bonitki paryskie z galaretką pomarańczową bez cukru', 'C'),
    ('Lajkonik', 'Paluszki o smaku waniliowym.', 'D'),
    ('Delicje', 'Szampariskie pomaranczowe', 'E'),
    ('Vitanella', 'Superballs Kokos i kakao', 'D'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', 'NOT-APPLICABLE'),
    ('Pano', 'Pieczywo kukurydziane chrupkie', 'C'),
    ('Wafle Dzik', 'Kukurydziane - ser', 'D'),
    ('Vitanella', 'Protein 30% Nugat Karmel', 'NOT-APPLICABLE'),
    ('Nestlé', 'Nestle musli cherry', 'C'),
    ('Purella', 'Baton proteinowy - truskawkowa beza', 'NOT-APPLICABLE'),
    ('Purella', 'Baton proteinowy - Matcha & Yuzu', 'NOT-APPLICABLE'),
    ('Unknown', 'Ciasto francuskie', 'D'),
    ('Lajkonik', 'Paluszki extra cienkie', 'E'),
    ('Sante A. Kowalski sp. j.', 'Crunchy Cranberry & Raspberry - Santé', 'E'),
    ('Zmiany Zmiany', 'Sztanga', 'NOT-APPLICABLE'),
    ('Kopernik torun', 'Pierniki nadziewane', 'E'),
    ('Popcrop Pyramids', 'High Protein Tomato & Basil Chips', 'C'),
    ('Dan Cake', 'Sandkuchen', 'E'),
    ('Purella', 'Baton proteinowy - mango crispy rice', 'NOT-APPLICABLE'),
    ('Beskidzkie', 'Paluszki solone', 'E'),
    ('Miami', 'Paleczki', 'B'),
    ('Good-food', 'Wafle kukyrydziane', 'A'),
    ('Lajkonik', 'Dobry chrup', 'D'),
    ('Lajkonik', 'Salted cracker', 'D'),
    ('Go On Nutrition', 'Protein 33% Caramel', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Krakersy mini', 'D'),
    ('Bakalland', 'Barre chocolat ba', 'D'),
    ('Go On', 'Go On Energy', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Prezel', 'B'),
    ('Lorenz', 'Chrupki Curly', 'D'),
    ('Beskidzkie', 'Beskidzkie paluchy z sezamem', 'D'),
    ('SFD', 'Fking Protein', 'NOT-APPLICABLE'),
    ('Purella superfoods', 'Purella ciasteczko', 'D'),
    ('Unknown', 'Vitanella raw', 'E'),
    ('Meltié Chocolatier', 'Dark Chocolate 64% Cocoa', 'E'),
    ('Lajkonik', 'Junior Safari', 'D'),
    ('Lorenz', 'Monster munch', 'E'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', 'E'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', 'B'),
    ('TOP', 'Paluszki solone', 'D'),
    ('Be raw', 'Energy Raspberry', 'NOT-APPLICABLE'),
    ('Top', 'Paluszki i precelki solone', 'E'),
    ('San', 'San bieszczadzkie suchary', 'C'),
    ('Bakalland', 'Bakalland BA! Banan', 'D'),
    ('Nestlé', 'Musli', 'C'),
    ('Lajkonik', 'Lajkonik Salted Sticks', 'E'),
    ('Pawełek', 'E. Wedel Milk Chocolate Bar with Toffee Flavour Filling', 'UNKNOWN'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcami o smaku pina colada', 'D'),
    ('Popcrop', 'Chipsy proteinowe barbecue', 'D'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcami', 'D'),
    ('Zmiany Zmiany', 'Kompas', 'UNKNOWN'),
    ('Wawel', 'Croissant with cocoa cream filling', 'E'),
    ('Dan Cake', 'Muffinka Stracciatella', 'UNKNOWN'),
    ('Lidl', 'Chrupiący baton proteinowy o smaku malinowym', 'NOT-APPLICABLE'),
    ('Dobra Kaloria', 'Mini batonik z nerkowcem', 'D'),
    ('Kresto', 'Pop corn', 'A'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowcow', 'D'),
    ('AllNutrition', 'Sernik z kremem nutlove crunch', 'C'),
    ('Lajkonik', 'Precelki chrupkie', 'E'),
    ('Sante', 'Vitamin coconut bar', 'NOT-APPLICABLE'),
    ('Go Nutrition', 'Protein 33', 'NOT-APPLICABLE'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcow à la muffin jagodowy', 'D'),
    ('Oshee', 'Raspberry & Almond High Protein Bar PROMO', 'NOT-APPLICABLE'),
    ('Lay''s', 'Oven baked - ser cheddar', 'D'),
    ('Unknown', 'Graciella marmukowa', 'E'),
    ('Popcrop', 'Piramidki proteinowe Ser cebula', 'C'),
    ('Bakalland', 'Popcorn', 'E'),
    ('Mlekovita', 'SBA Quark Bar Coconut', 'D'),
    ('Unknown', 'Popcorn Ziarno', 'D'),
    ('Vemondo', 'Roślinny batonik z tofu o smaku słonego karmelu', 'E'),
    ('Pop''n Chrup', 'Wafle kukurydziane smak fromage', 'C'),
    ('Dobra Kaloria', 'Kokos & Orzech', 'D'),
    ('TOP', 'Krakersy solone', 'D'),
    ('GO ON Nutrition', 'Protein 33%', 'NOT-APPLICABLE'),
    ('Baron', 'Protein BarMax Caramel', 'NOT-APPLICABLE'),
    ('Łakomcia', 'Krem o smaku kakaowo-orzechowym', 'E'),
    ('Good Food', 'Jumbo Papryka', 'E'),
    ('Go On', 'Keto Bar', 'NOT-APPLICABLE'),
    ('Go active', 'Baton Proteinowy Smak Waniliowy 50%', 'NOT-APPLICABLE'),
    ('Nestlé', 'Musli Chocolate & Banana', 'D'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', 'C'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', 'NOT-APPLICABLE'),
    ('Lajkonik', 'Krakersy mini ser i cebula', 'D'),
    ('Delicje', 'Delicje malinowe', 'E'),
    ('Go On', 'Vitamin Coconut & Milk Chocolate', 'NOT-APPLICABLE'),
    ('Góralki', 'Góralki mleczne', 'E'),
    ('Unknown', 'Popcorn solony', 'UNKNOWN'),
    ('Good Food', 'Wafle good food ser', 'D'),
    ('Unknown', 'À la sernik waniliowy', 'NOT-APPLICABLE'),
    ('Unknown', 'Krakersy cebulowe', 'D'),
    ('Sante', 'Nuts and chia bar', 'UNKNOWN'),
    ('Snickers', 'Snickers', 'E'),
    ('Go Active', 'Baton wysokobiałkowy z migdałami i kokosem', 'NOT-APPLICABLE'),
    ('Unknown', 'BeRAW energy peanut butter raw snack', 'E'),
    ('Fit King Delicious', 'Protein Chips - Cheese And Onion', 'C'),
    ('Unknown', 'Coconut RAW snack', 'E'),
    ('Top', 'Top popcorn', 'UNKNOWN'),
    ('Lorenz', 'Curly Salted Caramel', 'D'),
    ('Unknown', 'Go On Protein Crisp Riegel - Go ON', 'UNKNOWN'),
    ('7 Days', 'Croissant with Cocoa Filling', 'E'),
    ('Snack Day', 'Popcorn', 'D'),
    ('Lorenz', 'Monster Munch Crispy Potato-Snack Original', 'E'),
    ('Zott', 'Monte Snack', 'E'),
    ('Emco', 'Vitanella Bars', 'D'),
    ('Monte snack', 'Monte Snack', 'E'),
    ('Tutti', 'Batonik twarogowy Tutti w polewie czekoladowej', 'E'),
    ('GustoBello', 'Bruschette con rosmarino', 'D'),
    ('Sen Soy', 'Nori chips kimchi', 'E'),
    ('Nakd', 'Blueberry Muffin Myrtilles', 'D'),
    ('Unknown', 'Baton Vitanella z migdałami, żurawiną i orzeszkami ziemnymi', 'D'),
    ('Vitanella', 'Barony', 'D'),
    ('Nestlé', 'Nestle Nesquik', 'E'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', 'D'),
    ('7days', '7days', 'E'),
    ('Tastino', 'Wafle Kukurydziane', 'C'),
    ('Eti', 'Dare with MILK CHOCOLATE', 'E'),
    ('Nestlé', 'Princessa longa kokosowa', 'E'),
    ('Belle France', 'Brioche Tressée', 'D'),
    ('Happy Creations', 'Cracker Mix Classic', 'E'),
    ('Milka', 'Czekolada mleczna z mleka alpejskiego z nadzieniem mlecznym o smaku waniliowym (35%) oraz pokruszone ciastka kakaowe (15%).', 'E'),
    ('Mister CHOC', 'Crunchy Protein', 'E'),
    ('Milka', 'Choco brownie', 'E'),
    ('7 Days', 'Jretin', 'E'),
    ('Ideal', 'Pieczywo chrupkie kukurydziane', 'C'),
    ('Lidl', 'Mini batoniki z nerkowcow', 'D'),
    ('Magija', 'Magija baton twarogowy czekoladowy', 'E'),
    ('Protein M', 'Baton Protein M Czekoladowy', 'D'),
    ('Unknown', 'Baton orzechowy', 'D'),
    ('Unknown', 'Popcorn', 'B'),
    ('Baitz', 'Cocoa croissant', 'E'),
    ('Wasa', 'Lekkie 7 Ziaren', 'B'),
    ('7 days', 'Croissant strawberry filling', 'E')
) as d(brand, product_name, ns)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Lay''s', 'Oven Baked Krakersy wielozbożowe', '4'),
    ('Top', 'Popcorn o smaku maślanym', '4'),
    ('Kopernik', 'Pierniki nadziewane w białej czekoladzie.', '4'),
    ('E. Wedel', 'Batonik z nadzieniem o smaku śmietankowym w mlecznej czekoladzie (z dodatkiem alkoholu).', '4'),
    ('Maga', 'Surówka Colesław', '4'),
    ('Pano', 'Wafle Kukurydziane z Kaszą jaglaną i Pieprzem', '3'),
    ('Good-food', 'Wafle kukurydziane z ziołami prowansalskimi', '3'),
    ('Lay''s Oven Baked', 'Oven Baked Krakersy wielozbożowe', '4'),
    ('Sonko', 'Wafle ryżowe w czekoladzie mlecznej', '4'),
    ('Kupiec', 'Wafle ryżowe naturalne', '1'),
    ('Zdrowidło', 'Chipsy Loopea''s O Smaku Śmietanki Z Cebulką', '4'),
    ('Lubella', 'Paluszki z solą', '3'),
    ('Pano', 'Wafle mini, zbożowe', '3'),
    ('Bakalland', 'Ba! żurawina', '4'),
    ('Vital Fresh', 'Surówka Colesław z białej kapusty', '4'),
    ('Brześć', 'Słomka ptysiowa', '3'),
    ('Helio', 'Popcorn solony do mikrofalówki', '4'),
    ('Dobra Kaloria', 'Wysokobiałkowy Baton Krem Orzechowy Z Nutą Karmelu', '4'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców à la latte waniliowe', '4'),
    ('Goplana', 'Grześki w mlecznej czekoladzie', '4'),
    ('Bakalland', 'Popcorn maślany', '4'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowców a la ciasto marchewkowe', '4'),
    ('Unknown', 'Onigiri łosoś wędzony', '4'),
    ('Delisana', 'Biszkopty z galaretką w polewie', '4'),
    ('Good Food', 'Wafle ryżowe z kukurydzą o smaku pizzy- Jumbo Pizza', '4'),
    ('Bakalland', 'Baton proteinowy o smaku słonego karmelu', '4'),
    ('Dobra kaloria', 'Mini batoniki z nerkowców à la tarta malinowa', '4'),
    ('Biedronka', 'Bonitki paryskie z galaretką pomarańczową bez cukru', '4'),
    ('Lajkonik', 'Paluszki o smaku waniliowym.', '4'),
    ('Delicje', 'Szampariskie pomaranczowe', '4'),
    ('Vitanella', 'Superballs Kokos i kakao', '4'),
    ('Go On', 'Sante Baton Proteinowy Go On Kakaowy', '4'),
    ('Pano', 'Pieczywo kukurydziane chrupkie', '3'),
    ('Wafle Dzik', 'Kukurydziane - ser', '4'),
    ('Vitanella', 'Protein 30% Nugat Karmel', '4'),
    ('Nestlé', 'Nestle musli cherry', '4'),
    ('Purella', 'Baton proteinowy - truskawkowa beza', '4'),
    ('Purella', 'Baton proteinowy - Matcha & Yuzu', '4'),
    ('Unknown', 'Ciasto francuskie', '3'),
    ('Lajkonik', 'Paluszki extra cienkie', '3'),
    ('Sante A. Kowalski sp. j.', 'Crunchy Cranberry & Raspberry - Santé', '4'),
    ('Zmiany Zmiany', 'Sztanga', '3'),
    ('Kopernik torun', 'Pierniki nadziewane', '4'),
    ('Popcrop Pyramids', 'High Protein Tomato & Basil Chips', '3'),
    ('Dan Cake', 'Sandkuchen', '4'),
    ('Purella', 'Baton proteinowy - mango crispy rice', '4'),
    ('Beskidzkie', 'Paluszki solone', '4'),
    ('Miami', 'Paleczki', '1'),
    ('Good-food', 'Wafle kukyrydziane', '3'),
    ('Lajkonik', 'Dobry chrup', '4'),
    ('Lajkonik', 'Salted cracker', '4'),
    ('Go On Nutrition', 'Protein 33% Caramel', '4'),
    ('Lajkonik', 'Krakersy mini', '4'),
    ('Bakalland', 'Barre chocolat ba', '4'),
    ('Go On', 'Go On Energy', '4'),
    ('Lajkonik', 'Prezel', '3'),
    ('Lorenz', 'Chrupki Curly', '4'),
    ('Beskidzkie', 'Beskidzkie paluchy z sezamem', '4'),
    ('SFD', 'Fking Protein', '4'),
    ('Purella superfoods', 'Purella ciasteczko', '4'),
    ('Unknown', 'Vitanella raw', '4'),
    ('Meltié Chocolatier', 'Dark Chocolate 64% Cocoa', '4'),
    ('Lajkonik', 'Junior Safari', '4'),
    ('Lorenz', 'Monster munch', '4'),
    ('Aksam', 'Beskidzkie paluszki o smaku sera i cebulki', '4'),
    ('Lajkonik', 'Drobne pieczywo o smaku waniliowym', '4'),
    ('TOP', 'Paluszki solone', '4'),
    ('Be raw', 'Energy Raspberry', '4'),
    ('Top', 'Paluszki i precelki solone', '3'),
    ('San', 'San bieszczadzkie suchary', '4'),
    ('Bakalland', 'Bakalland BA! Banan', '4'),
    ('Nestlé', 'Musli', '4'),
    ('Lajkonik', 'Lajkonik Salted Sticks', '3'),
    ('Pawełek', 'E. Wedel Milk Chocolate Bar with Toffee Flavour Filling', '4'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcami o smaku pina colada', '4'),
    ('Popcrop', 'Chipsy proteinowe barbecue', '3'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcami', '4'),
    ('Zmiany Zmiany', 'Kompas', '3'),
    ('Wawel', 'Croissant with cocoa cream filling', '4'),
    ('Dan Cake', 'Muffinka Stracciatella', '4'),
    ('Lidl', 'Chrupiący baton proteinowy o smaku malinowym', '4'),
    ('Dobra Kaloria', 'Mini batonik z nerkowcem', '4'),
    ('Kresto', 'Pop corn', '1'),
    ('Dobra Kaloria', 'Mini batoniki z nerkowcow', '4'),
    ('AllNutrition', 'Sernik z kremem nutlove crunch', '4'),
    ('Lajkonik', 'Precelki chrupkie', '3'),
    ('Sante', 'Vitamin coconut bar', '4'),
    ('Go Nutrition', 'Protein 33', '4'),
    ('Dobra kaloria', 'Mini batoniki z nerkowcow à la muffin jagodowy', '4'),
    ('Oshee', 'Raspberry & Almond High Protein Bar PROMO', '4'),
    ('Lay''s', 'Oven baked - ser cheddar', '4'),
    ('Unknown', 'Graciella marmukowa', '4'),
    ('Popcrop', 'Piramidki proteinowe Ser cebula', '3'),
    ('Bakalland', 'Popcorn', '4'),
    ('Mlekovita', 'SBA Quark Bar Coconut', '4'),
    ('Unknown', 'Popcorn Ziarno', '1'),
    ('Vemondo', 'Roślinny batonik z tofu o smaku słonego karmelu', '4'),
    ('Pop''n Chrup', 'Wafle kukurydziane smak fromage', '4'),
    ('Dobra Kaloria', 'Kokos & Orzech', '3'),
    ('TOP', 'Krakersy solone', '4'),
    ('GO ON Nutrition', 'Protein 33%', '4'),
    ('Baron', 'Protein BarMax Caramel', '4'),
    ('Łakomcia', 'Krem o smaku kakaowo-orzechowym', '4'),
    ('Good Food', 'Jumbo Papryka', '4'),
    ('Go On', 'Keto Bar', '4'),
    ('Go active', 'Baton Proteinowy Smak Waniliowy 50%', '4'),
    ('Nestlé', 'Musli Chocolate & Banana', '4'),
    ('Tastino', 'Małe Wafle Kukurydziane O Smaku Pizzy', '4'),
    ('Go Active', 'Baton wysokobiałkowy z pistacjami', '4'),
    ('Lajkonik', 'Krakersy mini ser i cebula', '4'),
    ('Delicje', 'Delicje malinowe', '4'),
    ('Go On', 'Vitamin Coconut & Milk Chocolate', '4'),
    ('Góralki', 'Góralki mleczne', '4'),
    ('Unknown', 'Popcorn solony', '3'),
    ('Good Food', 'Wafle good food ser', '4'),
    ('Unknown', 'À la sernik waniliowy', '4'),
    ('Unknown', 'Krakersy cebulowe', '4'),
    ('Sante', 'Nuts and chia bar', '4'),
    ('Snickers', 'Snickers', '4'),
    ('Go Active', 'Baton wysokobiałkowy z migdałami i kokosem', '4'),
    ('Unknown', 'BeRAW energy peanut butter raw snack', '4'),
    ('Fit King Delicious', 'Protein Chips - Cheese And Onion', '4'),
    ('Unknown', 'Coconut RAW snack', '4'),
    ('Top', 'Top popcorn', '4'),
    ('Lorenz', 'Curly Salted Caramel', '4'),
    ('Unknown', 'Go On Protein Crisp Riegel - Go ON', '4'),
    ('7 Days', 'Croissant with Cocoa Filling', '4'),
    ('Snack Day', 'Popcorn', '4'),
    ('Lorenz', 'Monster Munch Crispy Potato-Snack Original', '4'),
    ('Zott', 'Monte Snack', '4'),
    ('Emco', 'Vitanella Bars', '4'),
    ('Monte snack', 'Monte Snack', '4'),
    ('Tutti', 'Batonik twarogowy Tutti w polewie czekoladowej', '4'),
    ('GustoBello', 'Bruschette con rosmarino', '3'),
    ('Sen Soy', 'Nori chips kimchi', '3'),
    ('Nakd', 'Blueberry Muffin Myrtilles', '4'),
    ('Unknown', 'Baton Vitanella z migdałami, żurawiną i orzeszkami ziemnymi', '4'),
    ('Vitanella', 'Barony', '4'),
    ('Nestlé', 'Nestle Nesquik', '4'),
    ('Maretti', 'Bruschette Chips Pizza Flavour', '4'),
    ('7days', '7days', '4'),
    ('Tastino', 'Wafle Kukurydziane', '4'),
    ('Eti', 'Dare with MILK CHOCOLATE', '4'),
    ('Nestlé', 'Princessa longa kokosowa', '4'),
    ('Belle France', 'Brioche Tressée', '4'),
    ('Happy Creations', 'Cracker Mix Classic', '4'),
    ('Milka', 'Czekolada mleczna z mleka alpejskiego z nadzieniem mlecznym o smaku waniliowym (35%) oraz pokruszone ciastka kakaowe (15%).', '4'),
    ('Mister CHOC', 'Crunchy Protein', '4'),
    ('Milka', 'Choco brownie', '4'),
    ('7 Days', 'Jretin', '4'),
    ('Ideal', 'Pieczywo chrupkie kukurydziane', '3'),
    ('Lidl', 'Mini batoniki z nerkowcow', '4'),
    ('Magija', 'Magija baton twarogowy czekoladowy', '4'),
    ('Protein M', 'Baton Protein M Czekoladowy', '4'),
    ('Unknown', 'Baton orzechowy', '4'),
    ('Unknown', 'Popcorn', '4'),
    ('Baitz', 'Cocoa croissant', '4'),
    ('Wasa', 'Lekkie 7 Ziaren', '3'),
    ('7 days', 'Croissant strawberry filling', '4')
) as d(brand, product_name, nova)
where p.country = 'PL' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Snacks', 100, 'PL');
