-- PIPELINE (Spreads & Dips): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-12

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Aldi', 'Vegane Bio-Streichcreme - Kräuter-Tomate', 'Aldi'),
    ('Noa', 'Noa Brotaufstrich Hummus Kräuter', 'REWE'),
    ('Lyttos', 'Griechischer Pitabrot-Dip - Grüne Oliven, Aprikosen & Mandeln', 'Aldi'),
    ('Lyttos', 'Griechischer Pitabrot-Dip - Tomaten, Walnüsse & Basilikum', 'Aldi'),
    ('Unknown', 'Hummus Kürbis Kürbis Kichererbsenpüree mit Kürbis und Sesam', 'Aldi'),
    ('Lyttos', 'Griechischer Pitabrot-Dip - Rote Linsen, Tomaten & Kürbis', 'Aldi'),
    ('Menken Salades & Sauzen', 'Hummus - Kürbis', 'Aldi'),
    ('BioGourmet', 'Hummus mit Schwartzkümmel', 'REWE'),
    ('Cucina Nobile', 'Crema Deliziosa - Kürbis', 'Aldi'),
    ('Apostels', 'GemüseCreme Chili', 'Edeka'),
    ('Apostels', 'GemüseCreme Chili', 'REWE'),
    ('Apostels', 'GemüseCreme Chili', 'Kaufland'),
    ('WW', 'Hummus Natur', 'Aldi'),
    ('NOA', 'Hummus , Natur', 'Kaufland'),
    ('NOA', 'Hummus , Natur', 'Real'),
    ('Heinrich Kuhmann GmbH', 'Hummus - Pikant', 'Aldi'),
    ('K Bio (Kaufland)', 'Bio Hummus Classic', 'Kaufland'),
    ('Noa', 'Hummus Paprika-Chili', 'Lidl'),
    ('Noa', 'Hummus Paprika-Chili', 'Edeka'),
    ('Noa', 'Hummus Paprika-Chili', 'REWE'),
    ('Noa', 'Hummus Paprika-Chili', 'Netto'),
    ('Noa', 'Hummus Paprika-Chili', 'Kaufland'),
    ('My Vay', 'Bio Streichcreme', 'Aldi'),
    ('DmBio', 'Hummus Natur', 'dm'),
    ('Chef Select', 'Bio Hummus Natur', 'Lidl'),
    ('Kaufland', 'Veganer Hummus Classic', 'Kaufland'),
    ('Deluxe', 'Hummus und Guacamole', 'Lidl'),
    ('Apostels', 'ALDI Apostels Zaziki 500g', 'REWE'),
    ('Noa', 'Brotaufstrich Kichererbse Tomate-Basilikum', 'REWE'),
    ('Aldi', 'Vegane Bio-Streichcreme - Aubergine', 'Aldi'),
    ('Chef select', 'Bio organic humus', 'Lidl'),
    ('Milbona', 'Zaziki', 'Lidl'),
    ('Aldi', 'Bio-Hummus - Natur', 'Aldi'),
    ('Aldi', 'Vegane Bio-Streichcreme - Rote Bete-Meerrettich', 'Aldi'),
    ('Chef Select', 'Guacamole scharf', 'Lidl'),
    ('Nur Nur Natur', 'Bio Humus Paprika Kurkuma Chili', 'Aldi'),
    ('Nur Nur Natur', 'Bio-Hummus - Rote Bete, Meerrettich, Hibiskus', 'Aldi'),
    ('Nabio', 'Gegrillte Paprika Cashew', 'REWE'),
    ('Chef Select', 'Guacamole Avocado-Dip mild', 'Lidl'),
    ('Wonnemeyer', 'Antipasticreme - Feta', 'Aldi'),
    ('Nur Nur Natur', 'Bio-Hummus - Tomate', 'Aldi'),
    ('Popp', 'Brotaufstrich Bruschetta', 'REWE'),
    ('Kaufland', 'Guacamole', 'Kaufland'),
    ('Chef select', 'Hummus Nature', 'Lidl'),
    ('Kühlmann', 'Hummus Trio', 'Edeka'),
    ('Aldi', 'Bio-Hummus - Rote Beete', 'Aldi'),
    ('Chef Select', 'Hummus bruschetta', 'Lidl'),
    ('Aldi', 'Bio-Hummus - Paprika', 'Aldi'),
    ('Grossmann', 'Knoblauch-Dip', 'REWE'),
    ('Wonnemeyer', 'Antipasticreme - Dattel-Curry', 'Aldi'),
    ('Lyttos', 'Griechischer Pitabrot-Dip - Paprika, Feta & Tomaten', 'Aldi'),
    ('Chef Select', 'Kirschpaprika Antipasti-Creme', 'Lidl'),
    ('Drews', 'Aioli', 'REWE'),
    ('Aldi', 'Aioli klassisch', 'Aldi'),
    ('Aldi', 'Hummus - Ras El Hanout', 'Aldi'),
    ('Bio Zentrale', 'Aufstrich Hummus Chili', 'REWE'),
    ('Chef select', 'Humus und rotes Pesto', 'Lidl'),
    ('Aldi', 'Houmous tomate séché', 'Aldi'),
    ('Kaufland', 'Veganer Hummus', 'Kaufland'),
    ('The deli', 'Houmous', 'Aldi'),
    ('Piquaños', 'Sour Cream Dip', 'Edeka'),
    ('Nur Nur Natur', 'Vegane Bio-Aioli', 'Aldi'),
    ('Chio', 'Dip! Hot Cheese', 'REWE'),
    ('Chio', 'Dip! Hot Cheese', 'Kaufland'),
    ('Chef select', 'Hummus Karotte-Ingwer', 'Lidl'),
    ('Chio', 'Dip - Mild Salsa', 'REWE'),
    ('Chio', 'Dip - Mild Salsa', 'Netto'),
    ('Apostels', 'Apostels Sour Cream', 'REWE'),
    ('Chef Select', 'Hummus getrocknete Tomaten mit Sesam', 'Lidl'),
    ('Feinkost popp', 'Hummus & Pesto', 'Kaufland'),
    ('Mein Veggie Tag', 'Vegane Bio Pastete Hummus', 'Aldi'),
    ('Gutbio', 'Hummus Klassisch', 'Aldi'),
    ('Feinkost Popp', 'Hummus & Muhammara', 'REWE'),
    ('Chef Select', 'Hummus Pikant', 'Lidl'),
    ('Wonnemeyer', 'Guacamole Scharf', 'Aldi'),
    ('Kaufland', 'Hummus Classic', 'Kaufland'),
    ('Erhardt', 'Meerretich, ungeschwefelt (Bio)', 'Tegut'),
    ('Chef Select', 'Hummus Curry', 'Lidl'),
    ('CABA Fine-Food', 'Hummus Naturel', 'Aldi'),
    ('Lidl', 'Vegane Creme -Tofu & getrocknete Tomaten', 'Lidl'),
    ('Chef Select', 'Hummus Sonnengetrocknete Tomaten', 'Lidl'),
    ('Krini', 'Schwarze Olivencreme', 'REWE'),
    ('Block House', 'Guacamole mit Tomate', 'Edeka'),
    ('Merl', 'Bruschetta Pomodoro', 'Edeka'),
    ('Chef Select', 'Kakao Hummus', 'Lidl'),
    ('Chef Select', 'Guacamole', 'Lidl'),
    ('DmBio', 'Hummus gegrillte Paprika', 'dm'),
    ('Cucina Nobile', 'Crema Deliziosa - Cherrytomate', 'Aldi'),
    ('CABA Fine-Food', 'Hummus Lemon', 'Aldi'),
    ('Pepper-King', 'Habanero-Dip', 'Real'),
    ('Chef select', 'Hummus Karamell Art', 'Lidl'),
    ('Lidl', 'Hummus zongedroogde tomaten', 'Lidl'),
    ('Sun Snacks', 'Salsa Dip Scharf', 'Aldi'),
    ('Robin Schulz', 'Heatwave Sauce', 'Lidl'),
    ('Unknown', 'Hummus Rote Bete', 'Aldi'),
    ('Old Fashioned Cheese', 'Jalapeño Squeeze Cheese', 'REWE'),
    ('Alnatura', 'Hummus gegrilltes Gemüse Bio-Aufstrich', 'Rossmann'),
    ('REWE to go', 'Guacamole würzig', 'REWE'),
    ('Chef Select', 'Antipasti-Creme Bärlauch', 'Lidl'),
    ('Rewe', 'Hummus Kürbis', 'REWE'),
    ('Ja!', 'Bärlauch Antipasticreme', 'REWE'),
    ('Obela', 'Hummus Geröstete Pinienkerne', 'Edeka'),
    ('Obela', 'Hummus Geröstete Pinienkerne', 'Real'),
    ('Clarkys', 'Käse Dip', 'Netto'),
    ('REWE to go', 'Guacamole - würzig - mit Knoblauch', 'REWE'),
    ('Mama''s', 'Hausgemachter Grüner Ajvar', 'Tegut'),
    ('Edeka', 'American Dressing mit feinen Kräutern', 'Edeka')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Spreads & Dips' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
