-- PIPELINE (Sweets): store availability
-- Source: Open Food Facts API store field
-- Generated: 2026-03-04

INSERT INTO product_store_availability (product_id, store_id, verified_at, source)
SELECT
  p.product_id,
  sr.store_id,
  NOW(),
  'pipeline'
FROM (
  VALUES
    ('Ferrero', 'Ferrero Yogurette 40084060 Gefüllte Vollmilchschokolade mit Magermilchjoghurt-Erdbeer-Creme', 'Lidl'),
    ('Ferrero', 'Ferrero Yogurette 40084060 Gefüllte Vollmilchschokolade mit Magermilchjoghurt-Erdbeer-Creme', 'Netto'),
    ('Back Family', 'Schoko-Tröpfchen - Zartbitter', 'Aldi'),
    ('Ferrero', 'Kinder Überraschung Maxi', 'REWE'),
    ('Schogetten', 'Weiße Pistazie', 'Tegut'),
    ('Schogetten', 'Weiße Schokolade', 'REWE'),
    ('RUF', 'Schoko Tröpfchen', 'Norma'),
    ('Moser Roth', 'Edelbitter-Schokolade 85 % Cacao', 'Aldi'),
    ('Ritter Sport', 'Kakao Klasse die Starke - 81%', 'Aldi'),
    ('Ritter Sport', 'Kakao Klasse die Starke - 81%', 'Edeka'),
    ('Lidl', 'Lidl Organic Dark Chocolate', 'Lidl'),
    ('Aldi', 'Edelbitter-Schokolade 70% Cacao', 'Aldi'),
    ('Ritter Sport', 'Schokolade Halbbitter', 'REWE'),
    ('Ritter Sport', 'Marzipan', 'Lidl'),
    ('Ritter Sport', 'Marzipan', 'Edeka'),
    ('Ritter Sport', 'Marzipan', 'REWE'),
    ('Aldi', 'Edelbitter- Schokolade', 'Aldi'),
    ('Ritter Sport', 'Alpenmilch', 'REWE'),
    ('Ritter Sport', 'Alpenmilch', 'Netto'),
    ('Ritter Sport', 'Ritter Sport Nugat', 'REWE'),
    ('Ritter Sport', 'Ritter Sport Nugat', 'Netto'),
    ('Lindt', 'Lindt Dubai Style Chocolade', 'REWE'),
    ('Ritter Sport', 'Ritter Sport Voll-Nuss', 'Edeka'),
    ('Schogetten', 'Schogetten originals: Edel-Zartbitter', 'REWE'),
    ('Choceur', 'Aldi-Gipfel', 'Aldi'),
    ('Ritter Sport', 'Edel-Vollmilch', 'REWE'),
    ('Ritter Sport', 'Edel-Vollmilch', 'Kaufland'),
    ('Müller & Müller GmbH', 'Blockschokolade', 'Real'),
    ('Sarotti', 'Mild 85%', 'Tegut'),
    ('Aldi', 'Nussknacker - Vollmilchschokolade', 'Aldi'),
    ('Aldi', 'Nussknacker - Zartbitterschokolade', 'Aldi'),
    ('Back Family', 'Schoko-Chunks - Zartbitter', 'Aldi'),
    ('Ritter Sport', 'Pistachio', 'REWE'),
    ('Lindt', 'Excellence Mild 70%', 'REWE'),
    ('Fairglobe', 'Bio Vollmilch-Schokolade', 'Lidl'),
    ('Ritter Sport', 'Kakao-Mousse', 'REWE'),
    ('Ritter Sport', 'Kakao Klasse 61 die feine aus Nicaragua', 'Edeka'),
    ('Ritter Sport', 'Ritter Sport Honig Salz Mandel', 'Netto'),
    ('Lindt', 'Gold Bunny', 'REWE'),
    ('Lindt', 'Gold Bunny', 'Kaufland'),
    ('Schogetten', 'Schogetten - Edel-Alpenvollmilchschokolade', 'Edeka'),
    ('Schogetten', 'Schogetten - Edel-Alpenvollmilchschokolade', 'REWE'),
    ('Ferrero', 'Kinder Osterhase - Harry Hase', 'Netto'),
    ('Ritter Sport', 'Joghurt', 'REWE'),
    ('Ritter Sport', 'Joghurt', 'Netto'),
    ('Ritter Sport', 'Trauben Nuss', 'Netto'),
    ('Ritter Sport', 'Knusperkeks', 'REWE'),
    ('Milka', 'Schokolade Joghurt', 'REWE'),
    ('Ritter Sport', 'Rum Trauben Nuss Schokolade', 'REWE'),
    ('Aldi', 'Schokolade (Alpen-Sahne-)', 'Aldi'),
    ('Aldi', 'Erdbeer-Joghurt', 'Aldi'),
    ('Ritter Sport', 'Haselnuss', 'REWE'),
    ('Ritter Sport', 'Ritter Sport Erdbeer', 'REWE'),
    ('Schogetten', 'Schogetten Edel-Zartbitter-Haselnuss', 'Edeka'),
    ('Schogetten', 'Schogetten Edel-Zartbitter-Haselnuss', 'Penny'),
    ('Schogetten', 'Schogetten Edel-Zartbitter-Haselnuss', 'Kaufland'),
    ('Ritter Sport', 'Amicelli', 'REWE'),
    ('Ferrero', 'Kinder Weihnachtsmann', 'REWE'),
    ('Merci', 'Finest Selection Mandel Knusper Vielfalt', 'REWE'),
    ('Aldi', 'Rahm Mandel', 'Aldi'),
    ('Ritter Sport', 'Vegan Roasted Peanut', 'Edeka'),
    ('Ritter Sport', 'Nussklasse Ganze Mandel', 'Edeka'),
    ('Aldi', 'Feinherbe Schokolade', 'Aldi'),
    ('Ritter Sport', 'Ritter Sport White Lemon', 'REWE'),
    ('Choceur', 'Vollmilchschokolade Alpenmilch', 'Aldi'),
    ('Romy', 'Kokos-Schoko-Creme', 'Norma'),
    ('Ritter Sport', 'Gebrannte Mandel', 'REWE'),
    ('Ritter Sport', 'Gebrannte Mandel', 'Netto'),
    ('Ritter Sport', 'Gebrannte Mandel', 'Kaufland'),
    ('Aldi', 'Zartbitterschokolade - Chili', 'Aldi'),
    ('Gepa', 'Zartbitter Mild Pur 60%', 'Edeka'),
    ('Gepa', 'Zartbitter Mild Pur 60%', 'REWE'),
    ('Ritter Sport', 'Groovy ritter', 'Edeka'),
    ('Ritter Sport', 'Groovy ritter', 'REWE'),
    ('Belbake', 'Schokochunks Zartbitter', 'Lidl'),
    ('Gepa', 'Grand Chocolat Matcha Blanc', 'REWE'),
    ('Ritter Sport', 'Weisse Lakritz', 'REWE'),
    ('Lidl', 'Vegane helle Cookies', 'Lidl'),
    ('Ritter Sport', 'Pfefferminz', 'Netto'),
    ('Choceur', 'Feine Weisse', 'Aldi'),
    ('Ritter Sport', 'Salted Caramel Vegan', 'Edeka'),
    ('Eszet', 'Schnitten- Zartbitter Schokolade', 'Tegut'),
    ('Ritter Sport', 'Crunchy Mandel', 'Edeka'),
    ('Ritter Sport', 'Crunchy Mandel', 'REWE'),
    ('Alpia', 'Feine Zartbitter Schokolade', 'REWE'),
    ('Belbake', 'Dark Chocolate Drops', 'Lidl'),
    ('Choceur', 'Mandelknacker - Zartbitterschokolade', 'Aldi'),
    ('EnerBio', 'Feine Edelbitter Schokolade 70%', 'Rossmann'),
    ('Aldi', 'Edel-Vollmilch', 'Aldi'),
    ('Aldi', 'Zartbitter Schokolade 70%', 'Aldi'),
    ('GEPA Grand Noir', 'GEPA Grand Noir Zarte Bitter 70% 4013320066393 Bio Bitterschokolade', 'Edeka'),
    ('Gepa', 'Vollmilch Schokolade, Espresso & Karamell', 'Tegut'),
    ('Fin Carré', 'Vegane Helle mit Haselnuss', 'Lidl'),
    ('Aldi', 'Choco Changer Salted Caramel', 'Aldi'),
    ('Ferrero', 'Yogurette', 'Lidl'),
    ('Zetti', 'Edel Bitter 75% Kakao', 'Tegut'),
    ('Schogetten', 'Schokolade Caramel Brownie', 'Lidl'),
    ('Schogetten', 'Schokolade Caramel Brownie', 'REWE'),
    ('Dr. Oetker', 'Couverture fine gloss aigre-doux', 'REWE'),
    ('Fin CARRE', 'Mandel Kracher', 'Lidl'),
    ('Lindt', 'Excellence 50% cacao Zartbitter', 'REWE'),
    ('Ritter Sport', 'Schokolade Crunchy Creamy Winter', 'Edeka'),
    ('Ritter Sport', 'Schokolade Crunchy Creamy Winter', 'REWE'),
    ('Ritter Sport', 'Schokolade Crunchy Creamy Winter', 'Norma'),
    ('Rossmann', 'RAW Chocolate mit Dattelsüsse', 'Rossmann')
) AS d(brand, product_name, store_name)
JOIN products p ON p.country = 'DE' AND p.brand = d.brand AND p.product_name = d.product_name
  AND p.category = 'Sweets' AND p.is_deprecated IS NOT TRUE
JOIN store_ref sr ON sr.country = 'DE' AND sr.store_name = d.store_name AND sr.is_active = true
ON CONFLICT (product_id, store_id) DO NOTHING;
