-- PIPELINE (Coffee & Tea): scoring
-- Generated: 2026-03-13

-- 2. Nutri-Score
update products p set
  nutri_score_label = d.ns
from (
  values
    ('Nestlé', 'Caro Landkaffee extra kräftig', 'UNKNOWN'),
    ('Grana', 'Feiner Landkaffee Aus Vollem Korn Geröstet, Kaffee', 'UNKNOWN'),
    ('Amaroy', 'Entkoffeiniert Premium Löslicher Kaffee', 'UNKNOWN'),
    ('Dallmayr', 'Kaffee - GOLD - löslicher Kaffee', 'UNKNOWN'),
    ('Tchibo', 'Feine Milde Natur-mild lösl. Kaffee', 'UNKNOWN'),
    ('Jacobs', 'Krönung Classic ganze Bohnen', 'B'),
    ('Nestlé', 'Nescafé Classic', 'UNKNOWN'),
    ('Lemonaid Beverages GmbH', 'Café Intención eclógico', 'UNKNOWN'),
    ('Krüger', 'Cappuccino Schoko', 'UNKNOWN'),
    ('Tchibo', 'Barista Caffè Crema Bohnen', 'B'),
    ('Hearts', 'Cappuccino mit feiner Kakaonote', 'UNKNOWN'),
    ('Aldi', 'Cappuccino Schoko', 'UNKNOWN'),
    ('Aldi', 'Family cappuccino', 'UNKNOWN'),
    ('Ehrmann', 'Protein Caffe Latte', 'B'),
    ('DmBio', 'Kaffee Klassik Gemahlen', 'B'),
    ('DmBio', 'Espresso gemahlen', 'B'),
    ('J.J. Darboven GmbH & Co KG', 'Café intención ecológico', 'B'),
    ('Krüger', 'Cappuccino Stracciatella', 'UNKNOWN'),
    ('Ja!', 'Typ Cappuccino - weniger süß im Geschmack', 'UNKNOWN'),
    ('Dallmayr', 'Crema d''Oro Kaffee', 'UNKNOWN'),
    ('Nestlé', 'Eiskaffee', 'UNKNOWN'),
    ('Dallmayr', 'Dallmayr Kaffee Prodomo Naturmild', 'UNKNOWN'),
    ('Milbona', 'Latte macchiato lactose free', 'C'),
    ('Cafèt', 'Latte Macchiato weniger süß', 'C'),
    ('Rewe', 'Extra löslicher Kaffee', 'UNKNOWN'),
    ('Dr. Oetker', 'High Protein Coffee Drink - Latte Macchiato Style', 'C'),
    ('Gut & Günstig', 'Latte Macchiato - weniger süß', 'D'),
    ('Edeka', 'Getränkepulver Typ Cappuccino (weniger süß)', 'UNKNOWN'),
    ('K Classic to go', 'Latte Espresso', 'UNKNOWN'),
    ('Senseo', 'Senseo Kaffeepads Caffè Pads', 'D'),
    ('Melitta', 'Kaffee Harmonie entkoffeiniert', 'B'),
    ('Lidl Milbona', 'Latte Macchiato', 'E'),
    ('Naturata', 'Getreidekaffee Instant', 'E'),
    ('Dallmayr', 'Kaffee', 'B'),
    ('Bellarom', 'Kaffeebohnen', 'UNKNOWN'),
    ('Weihenstephan', 'Rahmjoghurt Eiskaffee', 'E'),
    ('Nestlé', 'Nescafé Cappuccino - weniger süß', 'UNKNOWN'),
    ('Cafèt', 'Löslicher Kaffee, kräftig', 'B'),
    ('Krüger', 'Cappuccino Fein & Cremig', 'UNKNOWN'),
    ('Moreno', 'Cappuccino Classico', 'UNKNOWN'),
    ('Coffee Pads', 'Senseo Pads Cappuccino Choco', 'D'),
    ('Krüger', 'Latte Macchiato', 'UNKNOWN'),
    ('Melitta', 'Barista Classic Crema', 'UNKNOWN'),
    ('Eduscho', 'Café Crema (Kaffee)', 'B'),
    ('Nescafé', 'Löslicher Kaffee entkof.- Fach 21', 'UNKNOWN'),
    ('Nescafé', 'Typ Cappuccino Weniger Süss', 'UNKNOWN'),
    ('Cafèt', 'Typ Cappuccino weniger süß', 'UNKNOWN'),
    ('Alnatura', 'Kaffee löslich', 'UNKNOWN'),
    ('Jacobs', 'Krönung', 'UNKNOWN'),
    ('Jacobs', 'Kaffee - Löslich', 'UNKNOWN'),
    ('Jacobs', 'Jacobs Kaffee-kapseln Lungo 6 Classico 20 Stück', 'B'),
    ('Nestlé', 'Nescafé Cappuccino Weniger Süß', 'UNKNOWN'),
    ('Unknown', 'Kaffee Classico Cappucino', 'D'),
    ('Cafèt', 'Latte Espresso', 'C'),
    ('Bellarom', 'Family Cappuccino Chocolate', 'UNKNOWN'),
    ('Illy', 'Illy Classico 100% Arabica, 250g', 'UNKNOWN'),
    ('Jacobs', 'Classic 3in1', 'UNKNOWN'),
    ('Fairglobe', 'Café bio fairglobe', 'UNKNOWN'),
    ('Cafèt', 'Latte Cappuccino', 'C'),
    ('Cafèt', 'Typ Cappuccino Classico', 'UNKNOWN'),
    ('Bellarom', 'Cappuccino Caramel', 'UNKNOWN'),
    ('Cafet', 'Family Cappucino Schoko', 'UNKNOWN'),
    ('Edeka', 'Cappuccino', 'UNKNOWN'),
    ('Lavazza', 'Café Bio-Organic', 'UNKNOWN'),
    ('Emmi', 'Caffè Latte', 'C'),
    ('Ja!', 'Cappuccino Family mit feiner Kakaonote', 'UNKNOWN'),
    ('Gut & Günstig', 'Latte espresso', 'C'),
    ('Edeka Bio', 'Edeka Bio Espresso', 'B'),
    ('Emmi', 'Caffè Latte High Protein', 'C'),
    ('Gut & Günstig', 'Cold Latte Espresso', 'UNKNOWN'),
    ('Edeka Bio', 'Caffe Crema Kaffeepads', 'UNKNOWN'),
    ('Milbona', 'Cappucino', 'C'),
    ('Edeka', 'Family Cappuccino Schoko', 'UNKNOWN'),
    ('Nescafe', 'Nescafé Classic Mild Instantkaffee', 'UNKNOWN'),
    ('Cafet', 'Typ Cappuccino Vanille', 'UNKNOWN'),
    ('Tassimo', 'Tassimo Morning Café Strong XL', 'UNKNOWN'),
    ('Emmi', 'Caffè Latte Double Zero Macchiato', 'C'),
    ('Penny', 'Caffé Latte Espresso', 'C'),
    ('K to go', 'Latte Macchiato', 'E'),
    ('Jacobs', 'Kaffeesticks Espresso', 'B'),
    ('Nescafé', 'Nescafé Gold - Original', 'UNKNOWN'),
    ('Emmi', 'Caffè Latte Cappuccino', 'D'),
    ('Jacobs', 'Classic 3:1', 'E'),
    ('Nescafe', 'Nescafé 3 en 1 classique', 'UNKNOWN'),
    ('Emmi', 'Emmi Caffè Latte Balance', 'C'),
    ('Tassimo', 'Jacobs Latte Macchiato Classico', 'C'),
    ('Nestlé', 'Nescafé Gold Bio', 'UNKNOWN'),
    ('Penny Ready', 'Café Latte Espresso', 'C'),
    ('Jacobs', 'Kaffee Espresso Kaffee', 'B'),
    ('Nescafé', 'Dolce Gusto Latte Macchiato Caramel', 'C'),
    ('Jacobs', '3 in 1 Coffee With Caramel', 'E'),
    ('Jacobs Douwe Egberts Norge As', 'Caffè in grani classico', 'UNKNOWN'),
    ('Illy', 'Tostato classico caffè macinato ideale per moka', 'B'),
    ('Dolce Gusto', 'Latte Macchiato', 'E'),
    ('Senseo', 'Kaffeepads Classic, XXL', 'B'),
    ('Emmi', 'Caffè Latte Expresso', 'C'),
    ('Jacobs', 'Tassimo Jacobs Latte Macchiato Caramel', 'C'),
    ('Nescafé Dolce Gusto', 'Nescafe Dolce Gusto Chococino 16cap', 'UNKNOWN'),
    ('Jacobs', 'Cappuccino von Jacobs', 'UNKNOWN'),
    ('Nescafe', '2 in 1', 'C')
) as d(brand, product_name, ns)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 3. NOVA classification
update products p set
  nova_classification = d.nova
from (
  values
    ('Nestlé', 'Caro Landkaffee extra kräftig', '1'),
    ('Grana', 'Feiner Landkaffee Aus Vollem Korn Geröstet, Kaffee', '1'),
    ('Amaroy', 'Entkoffeiniert Premium Löslicher Kaffee', '4'),
    ('Dallmayr', 'Kaffee - GOLD - löslicher Kaffee', '4'),
    ('Tchibo', 'Feine Milde Natur-mild lösl. Kaffee', '1'),
    ('Jacobs', 'Krönung Classic ganze Bohnen', '4'),
    ('Nestlé', 'Nescafé Classic', '4'),
    ('Lemonaid Beverages GmbH', 'Café Intención eclógico', '1'),
    ('Krüger', 'Cappuccino Schoko', '4'),
    ('Tchibo', 'Barista Caffè Crema Bohnen', '1'),
    ('Hearts', 'Cappuccino mit feiner Kakaonote', '4'),
    ('Aldi', 'Cappuccino Schoko', '4'),
    ('Aldi', 'Family cappuccino', '4'),
    ('Ehrmann', 'Protein Caffe Latte', '4'),
    ('DmBio', 'Kaffee Klassik Gemahlen', '4'),
    ('DmBio', 'Espresso gemahlen', '1'),
    ('J.J. Darboven GmbH & Co KG', 'Café intención ecológico', '4'),
    ('Krüger', 'Cappuccino Stracciatella', '4'),
    ('Ja!', 'Typ Cappuccino - weniger süß im Geschmack', '4'),
    ('Dallmayr', 'Crema d''Oro Kaffee', '1'),
    ('Nestlé', 'Eiskaffee', '4'),
    ('Dallmayr', 'Dallmayr Kaffee Prodomo Naturmild', '1'),
    ('Milbona', 'Latte macchiato lactose free', '4'),
    ('Cafèt', 'Latte Macchiato weniger süß', '4'),
    ('Rewe', 'Extra löslicher Kaffee', '4'),
    ('Dr. Oetker', 'High Protein Coffee Drink - Latte Macchiato Style', '4'),
    ('Gut & Günstig', 'Latte Macchiato - weniger süß', '4'),
    ('Edeka', 'Getränkepulver Typ Cappuccino (weniger süß)', '4'),
    ('K Classic to go', 'Latte Espresso', '4'),
    ('Senseo', 'Senseo Kaffeepads Caffè Pads', '4'),
    ('Melitta', 'Kaffee Harmonie entkoffeiniert', '4'),
    ('Lidl Milbona', 'Latte Macchiato', '4'),
    ('Naturata', 'Getreidekaffee Instant', '1'),
    ('Dallmayr', 'Kaffee', '4'),
    ('Bellarom', 'Kaffeebohnen', '4'),
    ('Weihenstephan', 'Rahmjoghurt Eiskaffee', '4'),
    ('Nestlé', 'Nescafé Cappuccino - weniger süß', '4'),
    ('Cafèt', 'Löslicher Kaffee, kräftig', '4'),
    ('Krüger', 'Cappuccino Fein & Cremig', '3'),
    ('Moreno', 'Cappuccino Classico', '4'),
    ('Coffee Pads', 'Senseo Pads Cappuccino Choco', '4'),
    ('Krüger', 'Latte Macchiato', '4'),
    ('Melitta', 'Barista Classic Crema', '4'),
    ('Eduscho', 'Café Crema (Kaffee)', '4'),
    ('Nescafé', 'Löslicher Kaffee entkof.- Fach 21', '4'),
    ('Nescafé', 'Typ Cappuccino Weniger Süss', '4'),
    ('Cafèt', 'Typ Cappuccino weniger süß', '4'),
    ('Alnatura', 'Kaffee löslich', '4'),
    ('Jacobs', 'Krönung', '1'),
    ('Jacobs', 'Kaffee - Löslich', '4'),
    ('Jacobs', 'Jacobs Kaffee-kapseln Lungo 6 Classico 20 Stück', '1'),
    ('Nestlé', 'Nescafé Cappuccino Weniger Süß', '4'),
    ('Unknown', 'Kaffee Classico Cappucino', '4'),
    ('Cafèt', 'Latte Espresso', '4'),
    ('Bellarom', 'Family Cappuccino Chocolate', '4'),
    ('Illy', 'Illy Classico 100% Arabica, 250g', '1'),
    ('Jacobs', 'Classic 3in1', '4'),
    ('Fairglobe', 'Café bio fairglobe', '1'),
    ('Cafèt', 'Latte Cappuccino', '4'),
    ('Cafèt', 'Typ Cappuccino Classico', '4'),
    ('Bellarom', 'Cappuccino Caramel', '4'),
    ('Cafet', 'Family Cappucino Schoko', '4'),
    ('Edeka', 'Cappuccino', '4'),
    ('Lavazza', 'Café Bio-Organic', '4'),
    ('Emmi', 'Caffè Latte', '4'),
    ('Ja!', 'Cappuccino Family mit feiner Kakaonote', '4'),
    ('Gut & Günstig', 'Latte espresso', '4'),
    ('Edeka Bio', 'Edeka Bio Espresso', '1'),
    ('Emmi', 'Caffè Latte High Protein', '4'),
    ('Gut & Günstig', 'Cold Latte Espresso', '4'),
    ('Edeka Bio', 'Caffe Crema Kaffeepads', '1'),
    ('Milbona', 'Cappucino', '4'),
    ('Edeka', 'Family Cappuccino Schoko', '4'),
    ('Nescafe', 'Nescafé Classic Mild Instantkaffee', '4'),
    ('Cafet', 'Typ Cappuccino Vanille', '4'),
    ('Tassimo', 'Tassimo Morning Café Strong XL', '1'),
    ('Emmi', 'Caffè Latte Double Zero Macchiato', '1'),
    ('Penny', 'Caffé Latte Espresso', '4'),
    ('K to go', 'Latte Macchiato', '4'),
    ('Jacobs', 'Kaffeesticks Espresso', '4'),
    ('Nescafé', 'Nescafé Gold - Original', '4'),
    ('Emmi', 'Caffè Latte Cappuccino', '3'),
    ('Jacobs', 'Classic 3:1', '4'),
    ('Nescafe', 'Nescafé 3 en 1 classique', '4'),
    ('Emmi', 'Emmi Caffè Latte Balance', '4'),
    ('Tassimo', 'Jacobs Latte Macchiato Classico', '4'),
    ('Nestlé', 'Nescafé Gold Bio', '4'),
    ('Penny Ready', 'Café Latte Espresso', '4'),
    ('Jacobs', 'Kaffee Espresso Kaffee', '4'),
    ('Nescafé', 'Dolce Gusto Latte Macchiato Caramel', '4'),
    ('Jacobs', '3 in 1 Coffee With Caramel', '4'),
    ('Jacobs Douwe Egberts Norge As', 'Caffè in grani classico', '4'),
    ('Illy', 'Tostato classico caffè macinato ideale per moka', '1'),
    ('Dolce Gusto', 'Latte Macchiato', '3'),
    ('Senseo', 'Kaffeepads Classic, XXL', '4'),
    ('Emmi', 'Caffè Latte Expresso', '3'),
    ('Jacobs', 'Tassimo Jacobs Latte Macchiato Caramel', '4'),
    ('Nescafé Dolce Gusto', 'Nescafe Dolce Gusto Chococino 16cap', '4'),
    ('Jacobs', 'Cappuccino von Jacobs', '4'),
    ('Nescafe', '2 in 1', '4')
) as d(brand, product_name, nova)
where p.country = 'DE' and p.brand = d.brand and p.product_name = d.product_name;

-- 0/1/4/5. Score category (concern defaults, unhealthiness, flags, confidence)
CALL score_category('Coffee & Tea', 100, 'DE');
